### ISSUE TITLE
【Bug Report】tabs组件的animated属性 

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#10]
不设置、设置为true 或者false，没看出来有啥区别，是我打开方式不对？
 ` <l-tabs animated="true" bind:linchange="changeTabs">
    <l-tabpanel tab="京东物流" key="one" slot="one">
      <view class="tab-content">京东物流</view>
    </l-tabpanel>
    <l-tabpanel tab="品牌" key="two" slot="two">
      <view class="tab-content">品牌</view>
    </l-tabpanel>
    <l-tabpanel tab="接口" key="three" slot="three">
      <view class="tab-content">接口</view>
    </l-tabpanel>
    <l-tabpanel tab="面板" key="four" slot="four">
      <view class="tab-content">面板</view>
    </l-tabpanel>
  </l-tabs>`

**Comment by uniquenaer** [comment]
animated接收的是一个布尔值，不加`{{}}`的话会被解析成字符串，值无法传进去。

可以直接传入 `animated `或者 `animated="{{true}}"`。如下：

`<l-tabs animated></l-tabs>` 或者 `<l-tabs animated="{{true}}"></l-tabs>`

**Comment by virtualChan** [comment]
> animated接收的是一个布尔值，不加`{{}}`的话会被解析成字符串，值无法传进去。
> 
> 可以直接传入 `animated `或者 `animated="{{true}}"`。如下：
> 
> `<l-tabs animated></l-tabs>` 或者 `<l-tabs animated="{{true}}"></l-tabs>`

可以直接传入 `animated `或者 `animated="{{true}}" 这个我试过了，还是没看出来有啥区别，已经拉取刚修复的分支，或者我发个小视频到群里

**Comment by uniquenaer** [comment]
谢谢反馈，我们马上修复，晚上统一更新。
