### ISSUE TITLE
l-tabpanel内部有什么方式可以加入自定义组件

### ISSUE THREAD

**Issue by mzhiya** [TaleLin/lin-ui#100]
如下面代码形式
    <l-tabs class="l-tabs-nav" animated="true" swipeable="true" bind:linchange="changeTabs">
        <l-tabpanel tab="问卷" key="one" slot="one">
	        <view class="appraisal-container">
	            <block wx:key="id" wx:for="{{appraisal}}">
	                <m-appraisal appraisal="{{item}}" />                            //自定义组件
	            </block>
	        </view>
        </l-tabpanel>
        <l-tabpanel tab="笔记" key="two" slot="two">
            <view class="tab-content">适用笔记</view>
        </l-tabpanel>
    </l-tabs>

**Comment by uniquenaer** [comment]
```html
<l-tabs bind:linchange="changeTabs" l-class-header-line="header-line">
      <l-tabpanel tab="客厅" key="one" slot="one">
          <view class="tab-content">
            <content-card name="Tabs" describe="标签页">hdjshdshdsjh</content-card>
          </view>
        </l-tabpanel>
</l-tabs>
```

如上所示，使用`view`包裹，加入自定义组件正常渲染

**Comment by mzhiya** [comment]
如果在l-tabs组件上添加 swipeable="true"属性， 自定义组件显示的内容会不全，自定义标签加载出来了，但页面不显示

**Comment by uniquenaer** [comment]
> 如果在l-tabs组件上添加 swipeable="true"属性， 自定义组件显示的内容会不全，自定义标签加载出来了，但页面不显示

这是因为设置`swipeable="true"`之后，内部实现是用`swiper`实现的,高度受微信限制默认高度为150rpx，超出后就不显示。这个问题暂时还没想到更好的方式解决，你可以先看下面这个链接，看看能否解决你的问题

**Comment by uniquenaer** [comment]
[微信小程序swiper高度自适应，swiper的子元素高度不固定](https://developers.weixin.qq.com/community/develop/doc/00026c2d424a78c7eb27249a25b004)

**Comment by YpchenLove** [comment]
如果问题已经解决，可以关闭此issue，如果还有疑问，请在这里回复，我们在下次审查issue区的时候，会手动关闭此issue~
