### ISSUE TITLE
数量选择器Counter组件，数字改变时触发的事件bind:lincahnge，触发不了

### ISSUE THREAD

**Issue by 0feng0** [TaleLin/lin-ui#1003]
**LinUI版本（必填）：0.8.7

**设备（必填）：*PC，移动端都无效*

**基础库版本（必填）：*2.12.1*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
<l-counter bind:lincahnge="onIncident" count="1" min="1" max="10"/>
onIncident (e) {
    console.log('eeee',e)
  }

**Comment by juzi214032** [comment]
您好，我这边测试可以正常触发。请贴一下您的wxml和js代码
```html
<l-counter bindlinchange='ttt' l-class="count" wx:for="{{item.config}}" wx:for-item="count" wx:key="count" min="{{count.min}}" count="{{count.count}}" max="{{count.max}}" step="{{count.step}}" disabled="{{count.disabled}}" bind:linout="onOut"/>
```
![image](https://user-images.githubusercontent.com/38206169/89516695-59bcb280-d80b-11ea-894b-fb5cf9a494d5.png)

**Comment by 0feng0** [comment]
<l-counter bind:lincahnge="onIncident" count="1" min="1" max="10"/>
onIncident (e) {
    console.log('eeee',e)
  }

**Comment by 0feng0** [comment]
<l-counter bind:lincahnge="onIncident" count="1" min="1" max="10"/>

**Comment by 0feng0** [comment]
`<l-counter bind:lincahnge="onIncident" count="1" min="1" max="10"/>`
`onIncident (e) {
    console.log('eeee',e)
  }`

**Comment by juzi214032** [comment]
change写错了

**Comment by 0feng0** [comment]
官方文档事件名称那个写错了

**Comment by juzi214032** [comment]
感谢反馈，稍后对文档进行修改
