### ISSUE TITLE
数量选择器组件Counter，数字改变时触发的事件bind:linchang希望可以修改成键盘输入是触发	

### ISSUE THREAD

**Issue by 0feng0** [TaleLin/lin-ui#1004]
**描述你希望的支持的新功能？**
Counter组件的bind:linchang事件希望可以修改成键盘输入是触发，现在的数字改变时触发的事件，本质上也要失去焦点时才会执行该事件，和本身的bind:lintap事件无太大区别，如果可以改成键盘输入，并且能获取键盘输入的内容，对后面有判断操作可能会更友好点
**你期望的 API 是怎样的？**

**Comment by juzi214032** [comment]
请问是什么场景必须在输入时触发而不能是blur时触发呢

**Comment by 0feng0** [comment]
在用户添加超过给定的最大值触发某些操作，例如给出提示，例子：京东在购物车添加商品数量超过库存的操作。
blur时触发的话，如果用户输入了超出的最大值，再点击其他按钮，会出现自己写超出数量的提示，和这个按钮的操作

**Comment by juzi214032** [comment]
感谢反馈，下个版本将增加 `lininput` 事件
