### ISSUE TITLE
在组件中使用form拿不到value的值

### ISSUE THREAD

**Issue by xlaoter** [TaleLin/lin-ui#1009]
**LinUI版本（必填）：0.8.7

**设备（必填）：Windows10  i7

**基础库版本（必填）：2.12.0

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

![image](https://user-images.githubusercontent.com/37621732/89803965-1beebf80-db66-11ea-91c4-a10073ccc561.png)
![image](https://user-images.githubusercontent.com/37621732/89803555-91a65b80-db65-11ea-9dd0-33bee01f2beb.png)
![image](https://user-images.githubusercontent.com/37621732/89804144-59ebe380-db66-11ea-8229-da104bf71368.png)
![image](https://user-images.githubusercontent.com/37621732/89803628-ab47a300-db65-11ea-8c5b-f1f77e86dc38.png)
![image](https://user-images.githubusercontent.com/37621732/89803673-bb5f8280-db65-11ea-9703-242cd894e6fc.png)
![image](https://user-images.githubusercontent.com/37621732/89803715-c7e3db00-db65-11ea-9dcb-b768bd7c6818.png)

**Comment by juzi214032** [comment]
您好，方便提供一个代码片段吗

**Comment by xlaoter** [comment]
我放了截图，如果需要代码我只能晚上才有空了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 桔子 <notifications@github.com&gt;
发送时间: 2020年8月11日 09:03
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com&gt;
抄送: xlaoter <272711295@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[TaleLin/lin-ui] 在组件中使用form拿不到value的值 (#1009)





 
您好，方便提供一个代码片段吗

**Comment by juzi214032** [comment]
嗯嗯，因为这个场景比较复杂，有了代码更方便复现问题，等您有空再放上代码片段就好

**Comment by nikkiing** [comment]
所以咋解决，我也有这个问题
