### ISSUE TITLE
全局样式修改 build报错

### ISSUE THREAD

**Issue by sunchangpu** [TaleLin/lin-ui#1010]
从github上下载了master分支源码，npm install，修改了几个全局样式后， build时报错。
（以前操作过一次，未报错，这次报错了）
![46DAF86A0F6C8917D0ACD96A6A763AC9](https://user-images.githubusercontent.com/25578290/89966997-eee3ff00-dc82-11ea-8de3-2209023d8700.jpg)

**Comment by juzi214032** [comment]
初步判断是依赖安装不完整的问题，请尝试删除`node_modules`文件见，并重新执行`cnpm install`命令安装依赖
