### ISSUE TITLE
Toast 在mask为false的情况下，背景会先显示，再隐藏

### ISSUE THREAD

**Issue by christan-duplicate** [TaleLin/lin-ui#1011]
**LinUI版本（必填）：**
v0.8.5
**设备（必填）：**
微信pc，微信开发者工具
**基础库版本（必填）：**
2.12.0
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
Toast 在mask为false的情况下，背景会先显示，再隐藏
导致的结果就是每次用 Toast 时候都会闪一下

**Comment by christan-duplicate** [comment]
我知道了，是在之前我有执行一个提示信息：mask设为的是true，后面我再提示一条信息：mask设为false，这样就会闪一下，不知是不是我执行太快了还是怎么样引起的。

**Comment by juzi214032** [comment]
> 我知道了，是在之前我有执行一个提示信息：mask设为的是true，后面我再提示一条信息：mask设为false，这样就会闪一下，不知是不是我执行太快了还是怎么样引起的。

没太明白您说的意思，方便的话可以提供一个代码片段供我们排查一下，我这边暂时无法复现这个问题

**Comment by christan-duplicate** [comment]
就是toast背景闪了下，应该是我连续执行了两次toast引起的，第一次 mask是true，第二次 mask为false

**Comment by juzi214032** [comment]
我试了下第一次 true，第二次 fasle 还是没有复现
