### ISSUE TITLE
选项卡Segment组件开启惯性滚动

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-ui#1012]
**描述你希望的支持的新功能？**
今晚用开发者工具在Audits测试了评分 发现如下图所示：
![image](https://user-images.githubusercontent.com/39727435/90137799-b3435500-dda8-11ea-85d0-5997acab00c4.png)

**你期望的 API 是怎样的？**
希望可以增加这个样式

**Comment by juzi214032** [comment]
感谢反馈，我测试一下

**Comment by juzi214032** [comment]
已开启惯性滚动支持，将在下个版本更新

**Comment by ElanYoung** [comment]
> 已开启惯性滚动支持，将在下个版本更新

好哒
