### ISSUE TITLE
按需引入是报错，提示：VM13:1 MiniProgramError module "miniprogram_npm/lin-ui/core/utils/event-bus.js" is not defined；查找问题是按需引入input时，没有event-bus.js

### ISSUE THREAD

**Issue by huachuan005** [TaleLin/lin-ui#1023]
**LinUI版本（必填）：0.8.7**

**设备（必填）：win10，微信开发工具**

**基础库版本（必填）：2.12.0 **

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/24216400/90417112-e443c280-e0e5-11ea-9e62-cd10b347dd9a.png)

**重现步骤，必要时请提供代码片段链接**
查看需要event-bus.js的代码部分：
![image](https://user-images.githubusercontent.com/24216400/90417172-fb82b000-e0e5-11ea-8990-069cf590f57d.png)
在查看utils文件夹：
![Uploading image.png…]()

**Comment by MuRongXiaoDouBi** [comment]
请问您使用的是什么版本的lin-ui

**Comment by huachuan005** [comment]
![image](https://user-images.githubusercontent.com/24216400/90462861-2c8dcf80-e13c-11ea-8997-a9e2e6abe564.png)
github，下载的最新代码。看文档版本号：0.8.7

**Comment by MuRongXiaoDouBi** [comment]
您构建后的 `miniprogram_npm/lin-ui/core/utils` 目录下没有 `event-util.js` 文件吗

**Comment by MuRongXiaoDouBi** [comment]
我这里测试没有问题，您可以试着重新安装 `lin-ui` 或者重新构建

**Comment by huachuan005** [comment]
是的，构建之后没有event-util.js；
好的，我再尝试一下；
