### ISSUE TITLE
是否考虑给表单加上双向绑定的功能，类似angular的 [(ngModel)]

### ISSUE THREAD

**Issue by lk123321** [TaleLin/lin-ui#1025]
是否考虑给输入框加上双向绑定的功能，类似angular的 [(ngModel)]

**Comment by MuRongXiaoDouBi** [comment]
您好，之前有考虑过为表单组件做上双向绑定，但是由于微信小程序双向绑定机制还没有特别完善，就暂时搁置了，您可以看一下微信小程序[双向绑定文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html)
