### ISSUE TITLE
typescript环境下 wx.lin会报错 Property 'lin' does not exist on type 'Wx'. 需要怎么配置

### ISSUE THREAD

**Issue by Michel111** [TaleLin/lin-ui#1026]
**LinUI版本（必填）：*0.8.7*

**设备（必填）：*无*

**基础库版本（必填）：*2.8.3*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

error TS2339: Property 'lin' does not exist on type 'Wx'.
    wx.lin.showMessage

**Comment by MuRongXiaoDouBi** [comment]
目前 lin-ui 的编写并没有使用 typescript，所以对 typescript 的支持并不是很好

**Comment by Onlylonger** [comment]
typings/index.d.ts

declare namespace WechatMiniprogram {
  export interface Wx { lin: any; }
}
