### ISSUE TITLE
使用标签页 Tabs，便签页内容显示不完整且页面无法滚动（上下）

### ISSUE THREAD

**Issue by 1447003232** [TaleLin/lin-ui#1030]
**LinUI版本（必填）：**

**设备（必填）：手机微信+微信开发工具

**基础库版本（必填）：2.11.3

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/60308755/90633215-3c023b00-e258-11ea-9b91-82bfc7e39fe8.png)

![image](https://user-images.githubusercontent.com/60308755/90633948-86d08280-e259-11ea-9717-3349aad05caf.png)
![image](https://user-images.githubusercontent.com/60308755/90634036-b2536d00-e259-11ea-894d-bf7d9c54d7ce.png)
![image](https://user-images.githubusercontent.com/60308755/90709171-2fb8c500-e2ce-11ea-835e-58112ca82fb5.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by 1447003232** [comment]
请问是需要设置什么参数还是需要改什么东西？

**Comment by MuRongXiaoDouBi** [comment]
> 请问是需要设置什么参数还是需要改什么东西？

抱歉，没有复现您说的问题，请问可以看一下您的css样式吗

**Comment by MuRongXiaoDouBi** [comment]
经再次测试复现了问题，当 `swipeable` 为 `true` 时，确实存在此问题

**Comment by 1447003232** [comment]
那请问需要怎么修改呢？

**Comment by MuRongXiaoDouBi** [comment]
@1447003232 由于微信小程序 `swiper` 的特性，`swiper` 内部元素在某些情况下无法滚动，如果您想修改，需要修改组件源码，我们会尽早修复此问题

**Comment by 1447003232** [comment]
刚才试了下把swipeable改为false和删除还是无法上下滑动，是我哪里没有配置好嘛？

**Comment by MuRongXiaoDouBi** [comment]
@1447003232 可以提供详细代码吗，包括css样式

**Comment by 1447003232** [comment]
![image](https://user-images.githubusercontent.com/60308755/90709102-0435da80-e2ce-11ea-8c31-2d0f6c25ded2.png)
![image](https://user-images.githubusercontent.com/60308755/90709129-16b01400-e2ce-11ea-8874-a770dd9d53e3.png)

**Comment by 1447003232** [comment]
这样可以嘛

**Comment by 1447003232** [comment]
`/* pages/ucenter/wxOrder/wxOrder.wxss */
page{ 
  height: 100%;
  width: 100%;
  background: #f4f4f4;
}

.order_card{
  background-color: white;
  margin: 10px 5px;
  border-radius: 20rpx 20rpx 20rpx 20rpx;
}`

**Comment by MuRongXiaoDouBi** [comment]
@1447003232 测试 `swipeable` 为 `false` 时可以滚动，您的 `lin-ui` 是什么版本

**Comment by 1447003232** [comment]
请问在哪里可以查看版本？

**Comment by MuRongXiaoDouBi** [comment]
@1447003232 您是使用 `npm` 安装的吗

**Comment by 1447003232** [comment]
我是下的源码，再复制到项目里的

**Comment by 1447003232** [comment]
是今年6月初下载的

**Comment by MuRongXiaoDouBi** [comment]
应该是0.8.2版本，今天发了0.8.8版本

**Comment by 1447003232** [comment]
又发现一个问题，swipeable设置为false无效，还是可以滑动，只有删除该属性滑动效果才消失，不过还是无法滚动

**Comment by MuRongXiaoDouBi** [comment]
更新版本试一下，新版本应该没有这种问题

**Comment by 1447003232** [comment]
全部替换了，swipeable=“false”还是无效，是我开发工具出现bug了？

**Comment by MuRongXiaoDouBi** [comment]
试试 swipeable=“{{false}}” ，swipeable=“false” 这个 false是字符串，这里的值为true

**Comment by 1447003232** [comment]
swipeable=“{{false}}” 可以，不过还是无法上下滑动

**Comment by MuRongXiaoDouBi** [comment]
![image](https://user-images.githubusercontent.com/38655613/90711355-11a19380-e2d3-11ea-91a0-5312ee76dfc1.png)
![image](https://user-images.githubusercontent.com/38655613/90711350-0f3f3980-e2d3-11ea-92c5-9c4090ee842a.png)
![image](https://user-images.githubusercontent.com/38655613/90711364-18c8a180-e2d3-11ea-9d43-02ec2462fd44.png)
您看一下我的dai代码

**Comment by 1447003232** [comment]
您好，按照您的代码完全重写了一个，还是不行
![111](https://user-images.githubusercontent.com/60308755/90712740-45ca8380-e2d6-11ea-8fe6-f518fef665aa.gif)

详细代码：
![image](https://user-images.githubusercontent.com/60308755/90712647-14ea4e80-e2d6-11ea-8bba-e3fa7f96a448.png)
![image](https://user-images.githubusercontent.com/60308755/90712664-216ea700-e2d6-11ea-9d28-3de9c4054d33.png)
![image](https://user-images.githubusercontent.com/60308755/90712749-4ebb5500-e2d6-11ea-9ea1-1eca98f429e5.png)
![image](https://user-images.githubusercontent.com/60308755/90712696-2fbcc300-e2d6-11ea-8c9f-9a51e715a772.png)

**Comment by MuRongXiaoDouBi** [comment]
可能是因为平台差异的原因

**Comment by 1447003232** [comment]
平台差异？

**Comment by MuRongXiaoDouBi** [comment]
您是使用的什么系统

**Comment by 1447003232** [comment]
win7，家里和公司的都是win7都不行

**Comment by 1447003232** [comment]
应该和操作系统没关系吧

**Comment by 1447003232** [comment]
在手机上也是不行的啊

**Comment by 1447003232** [comment]
刚才试了下新建项目的都可以，就是现在的这个项目中无法使用，是冲突了，还是怎么回事？

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/90732660-00ba4780-e2fe-11ea-97fc-23bdcdc5563e.png)

@1447003232 把 page 高度限制去掉试一下呢

**Comment by 1447003232** [comment]
去了之后显示的就更少了，一页都显示不全

**Comment by juzi214032** [comment]
如果您新建一个项目没有问题，而在您旧项目中有问题的话，应该是旧项目中有样式冲突导致组件无法正常显示。如果您的项目方便上传源码的话，我们可以帮您排查一下。如果不方便上传源码的话，我们这边也确实无法解决这种由项目引起的问题了，还请见谅
