### ISSUE TITLE
混合标签 Combined Tabs文档里面能给出示例代码吗

### ISSUE THREAD

**Issue by nine-city** [TaleLin/lin-ui#1032]
**描述你希望的支持的新功能？**
混合标签 Combined Tabs文档里面能给出示例代码吗，由于水平有限，琢磨了半天感觉自己的用法不太对。
**你期望的 API 是怎样的？**

**Comment by MuRongXiaoDouBi** [comment]
您好，您可以[点击这里](https://github.com/TaleLin/lin-ui/tree/master/examples/pages/components/nav/pages/combined-tabs/)查看详细源码

**Comment by nine-city** [comment]
感谢！
