### ISSUE TITLE
list组件怎么加入开发者能力open-type？

### ISSUE THREAD

**Issue by christan-duplicate** [TaleLin/lin-ui#1037]
**描述你希望的支持的新功能？**
list组件怎么加入开发者能力？
**你期望的 API 是怎样的？**
怎么做到绑定open-type?

**Comment by christan-duplicate** [comment]
`<l-list title="联系客服" icon="customer-service" l-class-icon="iconfont" iconSize="{{ iconSize }}" iconColor="{{ iconColor }}" l-content-class="l-content" open-type="contact" data-key="customer-service" />`
这样无效果

**Comment by MuRongXiaoDouBi** [comment]
微信的开放能力应该是只能绑定到按钮上

**Comment by christan-duplicate** [comment]
好的，那就不能统一样式了

**Comment by MuRongXiaoDouBi** [comment]
您只能使用按钮组件重写成您想要的样式

**Comment by MuRongXiaoDouBi** [comment]
您可以使用 list 组件的插槽，在插槽内放入button 组件 来实现

**Comment by christan-duplicate** [comment]
放到插槽中，只能点到按钮才能生效吧
