### ISSUE TITLE
在不指定grid-item高度下在inner-container里不能自适应

### ISSUE THREAD

**Issue by zhuoNy** [TaleLin/lin-ui#1038]
**LinUI版本（必填）：0.8.8

**设备（必填）：小程序开发工具/iphone8

**基础库版本（必填）：2.8.3

**UI问题，请附上截图**
**问题：在不指定grid-item高度下在inner-container里不能自适应（水平/垂直居中）**
<img width="1633" alt="截屏2020-08-22 11 26 21" src="https://user-images.githubusercontent.com/60495408/90956378-b03b1980-e4b8-11ea-85e9-9c384daccf9c.png">
当不设置grid-item的高度时，grid-item不会在inner-container的高度里自适应（水平/垂直居中），除非对grid-item指定heigh和ustify-content；
**重现步骤，必要时请提供代码片段链接**
wxss
```
.container {
    width: 100%;
    height: 320rpx;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
}

.inner-container {
    width: 730rpx;
    height: 300rpx;
    border: 1px dashed #DCEBE6;
}

.grid-item {
    width: 200rpx;
    /*height: 200rpx;*/
    display: flex;
    flex-direction: column;
    align-items: center;
    /*justify-content: center;*/
}

.img {
    width: 60rpx;
    height: 60rpx;
}

```
wxml
```
<view class="container">
    <l-grid l-class="inner-container">
        <block wx:for="{{grid}}">
            <l-grid-item key="{{index}}" slot="{{index}}">
                <view class="grid-item">
                    <image class="img" src="{{item.img}}"></image>
                    <text class="text">{{item.title}}</text>
                </view>
            </l-grid-item>
        </block>
    </l-grid>
</view>
```

**Comment by zhuoNy** [comment]
@MuRongXiaoDouBi 增加padding会超出外部容器，不完美！调试过了，应该在组件中
```
.l-grid .l-grid-item {
display: flex;
flex-direction: column;
text-align: center;
box-sizing: border-box;
border-style: solid;
border-color: #ededed;
border-width: 0;
justify-content: center;
}

```
新增justify-content: center;这个属性就可以完美解决了！

**Comment by MuRongXiaoDouBi** [comment]
@zhuoNy 您是否自己设置了高度

**Comment by zhuoNy** [comment]
> @zhuoNy 您是否自己设置了高度
只设置了Grid外部容器的高度300rpx；内部容器没有再设置高度了；
要的效果就是网格内的项目位于容器的中心。

**Comment by zhuoNy** [comment]
> @zhuoNy 您是否自己设置了高度，测试在用户未自定义高度的情况下，padding 的效果会好些

Grid的高度用户还是要自定义设置的，因为这个是页面的整体布局。

**Comment by MuRongXiaoDouBi** [comment]
上一版去除了 grid 组件中 .l-grid-item 样式中的 justify-content: center; align-items: center;  
是为了优化 grid 组件的体验，扩大 grid-item 组件的点击范围，当前 grid-item 组件已默认占满 grid 组件，所有的垂直居中操作已内置在 grid-item 组件中
