### ISSUE TITLE
l-segment可以对字体做大小设置么？

### ISSUE THREAD

**Issue by FrancisJen** [TaleLin/lin-ui#1041]
**描述你希望的支持的新功能？**
l-segment可以对字体做大小设置么？ 目前通过外部样式类，不能对item的字体做大小的设置
**你期望的 API 是怎样的？**

**Comment by MuRongXiaoDouBi** [comment]
您是希望提供一个改变字体大小的属性吗

**Comment by caicai0525** [comment]
请问怎么在外部设置l-segment-item的字体

**Comment by juzi214032** [comment]
> 请问怎么在外部设置l-segment-item的字体

请新开一个 issue 描述你的问题
