### ISSUE TITLE
瀑布流中如何嵌入视频

### ISSUE THREAD

**Issue by FrancisJen** [TaleLin/lin-ui#1042]
**描述你希望的支持的新功能？**
在瀑布流中嵌入视频

**你期望的 API 是怎样的？**
类似小红书那样
## 在瀑布流形态下
可以支持移动到视频位置的时候，自动播放
可以定义自动播放的时长
右上角有个小的播放按钮，提示这是个视频

## 点击进去之后
点击进去可以观看完整的视频。

**Comment by MuRongXiaoDouBi** [comment]
抱歉，对于个别案例我们暂时没有精力去支持，您可以自己开发。
