### ISSUE TITLE
吸顶容器真机调试的时候 为什么反应很迟钝呢 有时候需要好几秒

### ISSUE THREAD

**Issue by eaglemens** [TaleLin/lin-ui#1045]
lin-ui 版本是0.8.5

![QQ图片20200827104542](https://user-images.githubusercontent.com/19241562/91378306-af0c4280-e852-11ea-9925-7c8d9f85a277.gif)

**Comment by MuRongXiaoDouBi** [comment]
真机调试需要实时传输数据，有卡顿现象很正常，在预览模式下如果没有卡顿，那就是没问题

**Comment by eaglemens** [comment]
好的
