### ISSUE TITLE
dialog中加入自定义组件input，input内容上下浮动

### ISSUE THREAD

**Issue by beibeiaiwuhao** [TaleLin/lin-ui#1046]
**LinUI版本（必填）：0.8.8

**设备（必填）：所有设备

**基础库版本（必填）：2.12.1

**UI问题，请附上截图**
<img width="428" alt="截屏2020-08-2721 50 50" src="https://user-images.githubusercontent.com/15605907/91450899-6767d400-e8af-11ea-848e-7472f7d8bbc0.png">

**重现步骤，必要时请提供代码片段链接**
wxml

  <l-dialog
    show="{{currentConf.show}}"
    type="{{currentConf.type}}"
    show-close="{{currentConf.showClose}}"
    title="{{currentConf.title}}"
    show-title="{{currentConf.showTitle}}"
    content="{{currentConf.content}}"
    locked="{{currentConf.locked}}"
    cancel-text="{{currentConf.cancelText}}"
    cancel-color="{{currentConf.cancelColor}}"
    confirm-text="{{currentConf.confirmText}}"
    confirm-color="{{currentConf.confirmColor}}"
    bind:lintap="onDialogTap"
    bind:lincancel="onCancelTap"
    bind:linconfirm="onConfirmTap"
  >
    
     <input class="input-common" placeholder="请重新命名" />
 
  </l-dialog>

wxss
.input-common {
  height: 96rpx;
}

**Comment by MuRongXiaoDouBi** [comment]
是会跳一下是吧

**Comment by beibeiaiwuhao** [comment]
嗯嗯，对的

**Comment by MuRongXiaoDouBi** [comment]
您好，经测试发现，这是微信小程序官方bug， input 组件的 placeholder 属性在某些情况下会有闪动情况！

**Comment by beibeiaiwuhao** [comment]
但是当我赋值value 的时候也会跳动的

**Comment by MuRongXiaoDouBi** [comment]
将高度去掉即可，微信小程序的bug，可以去微信开发者社区去详细了解一下
