### ISSUE TITLE
wx.lin 系列方法的参数，覆盖顺序能否改成：默认参数 <- 传递到组件内的数据 <- 传递的实参

### ISSUE THREAD

**Issue by lostexin** [TaleLin/lin-ui#1048]
**描述你希望的支持的新功能？**

wx.lin 系列方法的参数，覆盖顺序能否改成：默认参数 <- 传递到组件内的数据 <- 传递的实参

**你期望的 API 是怎样的？**

![image](https://user-images.githubusercontent.com/20023814/91635864-73c66b00-ea2e-11ea-8447-1455cce99aeb.png)

不然使用 wx.lin.show${组件名称} 方法，不传递参数时，使用的是默认参数，在组件上添加的属性就没有效果了

**Comment by juzi214032** [comment]
不建议修改顺序。根据单一职责原则，页面 wxml 组件和 js 内的组件本应该互不影响，只是由于小程序的原因，无法做到完全隔离。在使用 wx.lin.showArcPopup 之类的方法时，wxml 的职责应该仅是引入组件实例，而不负责数据的传输，否则耦合性太高。如果想要达到参数复用的目的，完全可以在 js 中抽取出参数对象。
并且，**如果修改顺序，对之前版本影响太大**。
