### ISSUE TITLE
图片选择器组件  通过l-item-class外部样式类  怎么上传的图片展示样式没有变化  还是那么大

### ISSUE THREAD

**Issue by eaglemens** [TaleLin/lin-ui#1049]
ui版本0.8.7

![微信图片_20200830115215](https://user-images.githubusercontent.com/19241562/91650873-c7c96200-eab7-11ea-848b-41bfec7f108e.png)
是有其它样式吗 还是怎么搞

**Comment by MuRongXiaoDouBi** [comment]
请问 css  属性后有没有加 !important

**Comment by eaglemens** [comment]
是已经加了！important 的  现在是那个添加那个图片+号样式是生效的   但是上传的图片不生效  然后还可以看到上传的图片上面的关闭按钮位置好像也是生效的 就是图片样式不生效

**Comment by MuRongXiaoDouBi** [comment]
可否提供代码供我们测试

**Comment by eaglemens** [comment]
> 可否提供代码供我们测试

https://developers.weixin.qq.com/s/Ke8YP4mn7okS

**Comment by MuRongXiaoDouBi** [comment]
可以加入以下代码解决问题：
```css
.a5 image {
  width: 100%;
  height: 100%;
}
```
