### ISSUE TITLE
picker组件

### ISSUE THREAD

**Issue by robin-dongbin** [TaleLin/lin-ui#1051]
**描述你希望的支持的新功能？**
增加picker组件
**你期望的 API 是怎样的？**
官方的picker在样式上和lin-ui不统一, 且无法引用到form组件中

**Comment by MuRongXiaoDouBi** [comment]
您好，此组件已在开发计划中，您可以通过 Project 查看开发进度

**Comment by shilei0124** [comment]
> 您好，此组件已在开发计划中，您可以通过 Projects 查看开发进度

你好，问一下picker的组件开发完成了么？我再project里面也看不到进度

**Comment by niubx** [comment]
> 您好，此组件已在开发计划中，您可以通过 Projects 查看开发进度

你好，问一下picker的组件开发完成了么？我在project里面也看不到进度

**Comment by juzi214032** [comment]
@niubx  还没有完成 计划 0.10.0  版本上线

**Comment by echoshiki** [comment]
您好，想问一下picker组件的开发进度，或者是已经放弃了么
