### ISSUE TITLE
0.8.8版的 .l-grid .l-grid-item样式改动导致grid组件不能居中

### ISSUE THREAD

**Issue by xiantie** [TaleLin/lin-ui#1052]
**LinUI版本（必填）：0.8.8

**设备（必填）：win10上的小程序开发开发工具

**基础库版本（必填）：2.11.0

**UI问题，请附上截图
![image](https://user-images.githubusercontent.com/27875010/91787408-5f57bd80-ec3c-11ea-9aa1-29010e58c10c.png)

**重现步骤，必要时请提供代码片段链接**

0.8.8版的 node_modules/lin-ui/dist/grid/index.wxss里.l-grid .l-grid-item的css样式相比0.7.5版少了justify-content:center;align-items:center;
我不知道你们为什么要去掉这个样式。原本在grid-item里的元素都是自动居中的，现在都歪了。

**Comment by MuRongXiaoDouBi** [comment]
0.8.8 版本确实将该样式去掉了，但是 grid-item 组件已经默认占满整个 grid 组件，`justify-content:center;align-items:center; ` 内置到了 grid-item 组件中，是为了扩大 grid-item 组件的点击范围，测试未发现样式有问题，可以提供一下复现代码吗

**Comment by zhuoNy** [comment]
#1038 和这个一样的问题;
可以用外部样式对grid-item容器view这两个justify-content:center;align-items:center属性加上;

**Comment by MuRongXiaoDouBi** [comment]
@zhuoNy 您试一下只加入 justify-content:center; 属性会不会可以修复此问题

**Comment by xiantie** [comment]
可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "木荣"<notifications@github.com&gt;; 
发送时间: 2020年9月1日(星期二) 中午1:47
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "鐵哥们"<303291556@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] 0.8.8版的 .l-grid .l-grid-item样式改动导致grid组件不能居中 (#1052)





 
@zhuoNy 您试一下只加入 justify-content:center; 属性会不会可以修复此问题
 
&mdash;

**Comment by xiantie** [comment]
好的。
这是慕课网七月老师的课程代码片段。我把请求api接口部分改成直接返回json数据了，这样你打开不用修改就可以直接使用了。
下图是问题的截图





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TaleLin/lin-ui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 上午10:41
收件人:&nbsp;"TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;;
抄送:&nbsp;"鐵哥们"<303291556@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TaleLin/lin-ui] 0.8.8版的 .l-grid .l-grid-item样式改动导致grid组件不能居中 (#1052)





 
0.8.8 版本确实将该样式去掉了，但是 grid-item 组件已经默认占满整个 grid 组件，justify-content:center;align-items:center;  内置到了 grid-item 组件中，是为了扩大 grid-item 组件的点击范围，测试未发现样式有问题，可以提供一下复现代码吗

**Comment by zhuoNy** [comment]
> @zhuoNy 您试一下只加入 justify-content:center; 属性会不会可以修复此问题
是的，这样就可以做到想要的效果了，但这样会报选择器警告。
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute
```
.my-grid view {
    justify-content: center;
}
```

**Comment by MuRongXiaoDouBi** [comment]
> > @zhuoNy 您试一下只加入 justify-content:center; 属性会不会可以修复此问题
> > 是的，这样就可以做到想要的效果了，但这样会报选择器警告。
> > Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute
> 
> ```
> .my-grid view {
>     justify-content: center;
> }
> ```

已修复，在 l-grid-item 样式中加入 justify-content: center;
