### ISSUE TITLE
segment包裹在position：fixed，absolute样式下无法自动滚动

### ISSUE THREAD

**Issue by liyaolin** [TaleLin/lin-ui#1056]
**LinUI版本（必填）：*0.8.8*

**设备（必填）：*window*

**基础库版本（必填）：*2.11.0*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
`  <view style="position: absolute;;">
  <l-segment l-active-class="tab-bar-active" l-class="tab-bar" scrollable="{{true}}" has-line="{{false}}" bind:linchange="changeTabs" even="{{false}}">
    <l-segment-item tab="{{item.name}}" key="{{item.id}}" wx:for="{{tabBarData}}" wx:key="{{item.id}}"/>
  </l-segment>
  </view>`

**Comment by MuRongXiaoDouBi** [comment]
您好，我通过在最外层容器里加入 width:100vw; 使得此问题解决了
