### ISSUE TITLE
布局组件-宫格-整体Grid绑定点击事件 bind:lintap="clickGrids" not work

### ISSUE THREAD

**Issue by clownf** [TaleLin/lin-ui#1059]
**LinUI版本（必填）：0.8.8

**设备（必填）：macos 微信开发者工具 1.03.2008270

**基础库版本（必填）：2.12.2

**UI问题，请附上截图**

![QQ20200911-192809](https://user-images.githubusercontent.com/23180168/92920510-f99dd980-f464-11ea-9461-b04636ca1ed5.gif)

**重现步骤，必要时请提供代码片段链接**
直接下载LinUI 0.8.8 代码 通过自己电脑的微信开发者工具运行 examples 发现lintap点击事件无效

**Comment by MuRongXiaoDouBi** [comment]
您好，确实存在此问题
