### ISSUE TITLE
l-segment点中选项卡后，颜色改变后，其他选项卡颜色不变

### ISSUE THREAD

**Issue by hjlxy** [TaleLin/lin-ui#1061]
**LinUI版本（必填）：0.8.8

**设备（必填）：**

**基础库版本（必填）：2.12.2

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/17348119/93048463-862cdf80-f691-11ea-9ada-762821dbae7d.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by hjlxy** [comment]
**基础库版本（必填）：2.12.2

**Comment by hjlxy** [comment]
<l-segment  active-key="1" bind:linchange="changeTabs" 
      data-id="{{item.stepId}}"  has-line="{{false}}" wx:for="{{tabData}}" wx:key="index"  
      active-color="#f4516c" inactive-color="#333333" >
        <l-segment-item tab="{{item.stepName}}" key="{{item.stepId}}"  />
      </l-segment>
没有任何css

**Comment by MuRongXiaoDouBi** [comment]
测试并未复现该问题，可以提供完整代码进行测试吗

**Comment by MuRongXiaoDouBi** [comment]
将 wx:for="{{tabData}}" 循环代码放入 l-segment-item 组件试下，例如：
![image](https://user-images.githubusercontent.com/38655613/93178465-e0e43b00-f766-11ea-9a45-8655eb0ebbaa.png)

**Comment by hjlxy** [comment]
谢谢，已处理
