### ISSUE TITLE
tabs和segment设置非等宽和scrollable后不起作用

### ISSUE THREAD

**Issue by suxiaogang** [TaleLin/lin-ui#1062]
最新的lin-ui, 直接贴个图吧

![image](https://user-images.githubusercontent.com/1567518/93060290-7bc81100-f6a4-11ea-9cd2-90ca8175e14b.png)

根据文档 

> 选项卡位置在顶部和底部时的默认高度为80rpx，宽度等分，开启scrollable时，最小宽度为160rpx;

宽度明显不够

**Comment by suxiaogang** [comment]
segment同样的问题... 都是内容很多时, 不会滑动, 只在一屏内显示

**Comment by suxiaogang** [comment]
尝试用了l-segment, 设置 width="1400", 但是scrollable还是不起作用.

**Comment by suxiaogang** [comment]
更新: 是模拟器的锅, 真机调试时没有这个问题.

**Comment by zhc525349965** [comment]
首先，感谢您的使用反馈。模拟器的问题我们无法解决，建议在使用这部分组件时，使用真机调试。感谢使用Lin-ui组件。

**Comment by suxiaogang** [comment]
@zhc525349965 你好 只有segment的问题 模拟器会出问题, tabs的问题是模拟器和真机都存在, 无法设置宽度, 也不能scroll

**Comment by zhc525349965** [comment]
> @zhc525349965 你好 只有segment的问题 模拟器会出问题, tabs的问题是模拟器和真机都存在, 无法设置宽度, 也不能scroll

不好意思，没有看全面。tab的问题我查一下

**Comment by suxiaogang** [comment]
好的 微信基础库 我这里是2.12.2 尝试后退了几个版本, 还是会有这个问题.

**Comment by MuRongXiaoDouBi** [comment]
将 equal-width 设置为 equal-width="{{false}}" 试一下
