### ISSUE TITLE
希望能够及时更新Lin-UI的开发文档

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#1063]
圆型进度条 Circle
最近使用圆形进度条的时候
<l-circle percent='50' out-diameter='150'></l-circle>
写错了外圆直径的参数，导致怎么都是默认的直径，调试到怀疑人生，
对照文档看清楚原来是参数错误了out-diameter 应该改成 outer-diameter
![image](https://user-images.githubusercontent.com/30004721/93153811-a1046000-f734-11ea-9409-364251923633.png)

**Comment by MuRongXiaoDouBi** [comment]
感谢指出错误！以后有问题可以直接提交issue，我们会及时改正。
