### ISSUE TITLE
npm安装构建之后，现在组件未找到

### ISSUE THREAD

**Issue by csonchen** [TaleLin/lin-ui#1064]
如图：
![image](https://user-images.githubusercontent.com/5915045/93312629-0726db00-f83a-11ea-9b14-4ff3bf02b0b6.png)

**Comment by MuRongXiaoDouBi** [comment]
路径不正确，按照以下例子引入
```js

  "usingComponents": {
    "l-segment": "/miniprogram_npm/lin-ui/segment/index",
    "l-segment-item": "/miniprogram_npm/lin-ui/segment-item/index"
  }
}
```

**Comment by MuRongXiaoDouBi** [comment]
再次构建一下试试

**Comment by MuRongXiaoDouBi** [comment]
或者重新npm install

**Comment by csonchen** [comment]
![image](https://user-images.githubusercontent.com/5915045/93314369-3dfdf080-f83c-11ea-92f6-aa4f731d0162.png)
还是不行，不知道是不是跟相对路径有关系

**Comment by MuRongXiaoDouBi** [comment]
查看miniprogram_npm/lin-ui下是否有该组件

**Comment by csonchen** [comment]
有的
![image](https://user-images.githubusercontent.com/5915045/93314578-89b09a00-f83c-11ea-9347-a1674df76c51.png)

**Comment by MuRongXiaoDouBi** [comment]
文件夹下是否有文件

**Comment by csonchen** [comment]
![image](https://user-images.githubusercontent.com/5915045/93314687-b369c100-f83c-11ea-91be-d737bf444224.png)
有的呀

**Comment by MuRongXiaoDouBi** [comment]
那应该不会出问题呀

**Comment by MuRongXiaoDouBi** [comment]
多构建几次

**Comment by csonchen** [comment]
你这边可不可以提供一个可以用的例子看看，写一个代码片段

**Comment by MuRongXiaoDouBi** [comment]
这是构建的问题，没办法提供代码案例
