### ISSUE TITLE
输入框能不能禁止输入？

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1069]
我这边点击输入框会弹出时间日期选择器，但是因为又弹出了软键盘，键盘会遮住 时间日期选择器。
虽然有个disabled属性，但是开启以后，文字会变灰，
我通过l-class覆盖了文字颜色，但是要么require的那个星号没法覆盖成红色，要么label无法覆盖为黑色，不知道是不是bug
l-class="disabled-override"

```
.disabled-override input{
  color:#333
}
.disabled-override .form-label{
  color:#333
}
.disabled-override .text-require{
  color: #e23;
}
```

所以看能不能单独加个readonly属性，只是禁止用户输入，但是不会改变文字颜色为灰色？

**Comment by MuRongXiaoDouBi** [comment]
可否提供完整代码供我们测试，

**Comment by KuoKongQingYun** [comment]
> 可否提供完整代码供我们测试，


wxml:
`<l-input label="预约时间" l-class="disabled-override" placeholder="请点击选择预约时间" required disabled/>`

wxss:
```
.disabled-override text,input{
  color:#333
}
.disabled-override .text-require{
  color:#e23
}
```

我的目的是，点击这个输入框会弹出日期选择器，但是不能弹出软键盘，所以设置了disabled，但是我又不想让文字变灰色，
所以覆盖样式，但是覆盖以后，required的那个红色星号也变黑了。

问题在于，我通过审查元素，查看.text-require那个星号的样式，明明红色是生效的，但是界面上又是黑色。

**Comment by MuRongXiaoDouBi** [comment]
解决方法
```html
<l-input label="预约时间" l-class="disabled-override" l-label-class="l-label-class" placeholder="请点击选择预约时间" required disabled/>
```
```css
.l-label-class {
  color:#333 !important;
}
.disabled-override .text-require{
  color:#e24 !important;
}
```

不知道为什么  l-label-class 这个外部样式类文档里没有
