### ISSUE TITLE
标签页能否也支持徽标

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1070]
我看选项卡都支持徽标，按理标签页也应该能支持吧，
虽然可以用过 选项卡 代替 标签页，但标签页总归有方便的地方。

**Comment by MuRongXiaoDouBi** [comment]
我们内部讨论这个功能后回复您

**Comment by KuoKongQingYun** [comment]
目前徽标有个问题，如果tab的label比较长，徽标遮住了部分label，会导致label点击无效，只能点没有被遮住的部分才能有响应，是不是不合理？

**Comment by KuoKongQingYun** [comment]
https://s3.ax1x.com/2020/12/10/rP6Y5j.png
如图，那个徽标挡住了label，导致label只有很小的区域能响应点击，操作体验很不好。

**Comment by juzi214032** [comment]
> https://s3.ax1x.com/2020/12/10/rP6Y5j.png
> 如图，那个徽标挡住了label，虽然只遮住了 右上角一小部分，但实测会导致label只有很小的区域能响应点击，操作体验很不好。

`0.8.13` 已经解决了这个问题

**Comment by KuoKongQingYun** [comment]
@juzi214032 我用的就是0.8.13，还是有问题。

**Comment by juzi214032** [comment]
哪个组件 Segment 还是 Tabs

**Comment by KuoKongQingYun** [comment]
Tabs

**Comment by juzi214032** [comment]
不好意思 Tabs 的修复被漏掉了，会在0.9.0加上
