### ISSUE TITLE
头像的优先级是否应该修改一下？

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1071]
文档里说：
组件支持三种类型，Icon、图片以及open-data，三种类型的优先级依次是open-data、Icon和图片。

一般icon是没有头像的时候的默认图标，比如下面
`<l-avatar src="{{avatar_url}}" icon="user"/>`
逻辑上应该是avatar_url没有的时候，才显示user图标，现在却是优先显示user图标，即便avatar_url存在？

**Comment by KuoKongQingYun** [comment]
按照文档原文，图片的优先级顺序为：open-data、Icon和图片
但是实际使用中，通常用icon作为默认头像，在有图片的时候显示图片，没有的时候才显示一个默认的icon
所以我个人认为 优先级顺序为：图片、open-data、Icon 更合理才对
不知道开发组采用现在的优先级的意图？

**Comment by MuRongXiaoDouBi** [comment]
`open-data` 作为微信原生功能，给予最优先级别

**Comment by KuoKongQingYun** [comment]
> `open-data` 作为微信原生功能，给予最优先级别

那后面两个呢，应该是图片优先，icon最低吧。
现在是icon优先，图片最低

**Comment by juzi214032** [comment]
您好，您提到的默认头像的需求，推荐在`src`中使用三目运算符实现。
因为默认头像并不一定是简单的 icon，所以这里的 icon 并无默认头像的含义，icon 与 src 的优先级也并无特定关系，所以在设计时没有特殊考虑。
**此处是文档错误，我们将对文档进行修正。** 感谢您的反馈
