### ISSUE TITLE
tabs标签栏- 标签位置 left情况下

### ISSUE THREAD

**Issue by yemaoknb** [TaleLin/lin-ui#1072]
**LinUI版本（必填）：**0.8.9

**设备（必填）：**微信开发工具

**基础库版本（必填）：**2.12.2

**UI问题，请附上截图**

![Uploading 微信截图_20200923160934.png…]()

[**重现步骤，必要时请提供代码片段链接**]

**Comment by MuRongXiaoDouBi** [comment]
抱歉，你的图片有问题，显示不出来
