### ISSUE TITLE
数量选择器 

### ISSUE THREAD

**Issue by yemaoknb** [TaleLin/lin-ui#1073]
**LinUI版本（必填）：**0.8.9

**设备（必填）：**设备工具

**基础库版本（必填）：*2.12.2*

**UI问题，请附上截图**
电商专题的  数量选择器  observers 监听result 这块有问题 具体复现 直接打印就可以出来
**重现步骤，必要时请提供代码片段链接**

**Comment by yemaoknb** [comment]
缺少唯一标识  多个的时候  例如在购物车中无法使用

**Comment by yemaoknb** [comment]
初始化 无法使用

**Comment by MuRongXiaoDouBi** [comment]
请具体说明问题，不然我们没有办法复现

**Comment by yemaoknb** [comment]
counter组建中的 result参数默认为1  count传入参数默认唯一   我传给count 100参数  result还是1

**Comment by yemaoknb** [comment]
加油 ~

**Comment by MuRongXiaoDouBi** [comment]
抱歉，未能复现该问题，可否提供一下代码

**Comment by yemaoknb** [comment]
我这边也无法复现   应该是我个人原因     我当时读取linchange的时候   observers中无限去监察result

**Comment by MuRongXiaoDouBi** [comment]
那先暂时关闭此 issue，等你再次复现问题时打开
