### ISSUE TITLE
表单复选框

### ISSUE THREAD

**Issue by yemaoknb** [TaleLin/lin-ui#1074]
**LinUI版本（必填）：*0.8.9*

**设备（必填）：*微信开发工具*

**基础库版本（必填）：*2.12.2*

**UI问题，请附上截图**
表单复选框  具体操作 根据文档无法正常操作 例如 将复选框改成圆形  个人建议是直接加个type类型  
**重现步骤，必要时请提供代码片段链接**

**Comment by MuRongXiaoDouBi** [comment]
您好，复选框本质是个 iconfont ，暂时无法更改
