### ISSUE TITLE
ImagePicker的urls属性更新以后，图片不显示

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1075]
比如这样：

`<l-image-picker id="photos" urls="{{user.photos}}" size-type="compressed" />`

```
this.setData({
      user: {photos:['https://www.baidu.com/img/flexible/logo/pc/result.png']}
    });
```

然后l-image-picker会响应，但是显示不出来图片，第一张图一片空白

**Comment by MuRongXiaoDouBi** [comment]
抱歉，未能复现该问题，我这里测试一切正常

**Comment by KuoKongQingYun** [comment]
> 抱歉，未能复现该问题，我这里测试一切正常

等一下，我这边传一个demo给您看看

**Comment by KuoKongQingYun** [comment]
> 抱歉，未能复现该问题，我这里测试一切正常

[https://wwe.lanzous.com/ibp2ih047mf](https://wwe.lanzous.com/ibp2ih047mf)
我写了个demo项目，麻烦您试一下

**Comment by KuoKongQingYun** [comment]
我看了一下ImagePicker的源码，知道问题在哪了，
judgeNewOrOld函数只会在attached里调用一次，如果我初始urls是空数组，那么这个判断那会使得“newOrOld”为“new",也就是识别为对象数组模式，而不是字符串数组
然后image的src就是item.url而不是item本身了。
这个应该是之前加入cell留下的bug？

**Comment by KuoKongQingYun** [comment]
我建议直接把judgeNewOrOld函数
```
judgeNewOrOld: function () {
      const e = this.data.urls;
      return 0 !== e.length && "object" != typeof e[0] ? "old" : "new"
    }
```
改为
```
judgeNewOrOld: function () {
      return this.data.cells?'new':'old'
    }
```
如果cells存在，则认为urls用{url:'http://..."}这种对象数组形式，如果不存在就是字符串形式。

**Comment by MuRongXiaoDouBi** [comment]
> 我建议直接把judgeNewOrOld函数
> 
> ```
> judgeNewOrOld: function () {
>       const e = this.data.urls;
>       return 0 !== e.length && "object" != typeof e[0] ? "old" : "new"
>     }
> ```
> 
> 改为
> 
> ```
> judgeNewOrOld: function () {
>       return this.data.cells?'new':'old'
>     }
> ```
> 
> 如果cells存在，则认为urls用{url:'http://..."}这种对象数组形式，如果不存在就是字符串形式。

直接改可能会有问题，我看看怎么改比较合适
