### ISSUE TITLE
IndexList组件，点击了sidebar，然后滚动content，sidebar就不动了

### ISSUE THREAD

**Issue by luochenlin** [TaleLin/lin-ui#1078]
**LinUI版本（必填）：**
0.8.3
**设备（必填）：**
微信开发工具
**基础库版本（必填）：**
2.13.0
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
官方LinUI小程序也是一样的问题

**Comment by MuRongXiaoDouBi** [comment]
已确认此bug

**Comment by juzi214032** [comment]
该问题已修复，将在下个版本更新

**Comment by Zeffon** [comment]
今天在使用IndexList中也刚好遇到该bug
