### ISSUE TITLE
关于新增Tabs的外部样式l-tabpanel-class的建议

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1080]
我建议新增一个外部样式l-tabpanel-class，用于修改tabpanel的样式。

原因如下：
==========目的============
我的目的是实现一个能填充剩余高度，内容带滚动的Tabs。
我的思路是使用flex布局，content的flex设置为1填充剩余高度，然后设置overflow-y为scroll来实现垂直滚动。
=========思路1=========
由于组件之间的样式隔离，所以我使用了 l-content-class 来修改tabs的样式，
```
<l-tabs l-content-class="tab-content" animated="true" active-key="{{activeKey}}">
  <l-tabpanel wx:for="{{panels}}" wx:key="title" tab="{{item.title}}" key="{{index}}" slot="{{index}}">
    <view class="content">
       ...(很长的内容)
    </view>
  </l-tabpanel>
</l-tabs>
```

```
.tab-content {
  min-height: 0!important;
  flex: 1;
  overflow-y: scroll;
}
```
但出现了一个很诡异的效果，l-content-class所在的view高度正常，但是滚动条很长，已经超过内容的长度（滚动到下面是空内容），而且切换到第二个tabpanel无显示，遂换了个思路。

=========思路2=========
既然l-content-class所在的view高度正常，我就把它设置为position: relative;
然后实际内容用<view class="content">包起来，并且设置绝对定位：
```
.tab-content{
  min-height: 0!important;
  flex: 1;
  position: relative;
}
.content {
  box-sizing: border-box;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  overflow-y: scroll;
}
```
但还是行不通，因为多个tabpanel的内容全都相对l-content-class所在view定位了，切换标签就没用了。

=============不完美的方案================
l-content-class所在的view距离实际的content还隔了一层:
`<view class="l-tabpanel l-tabpanel-active"></view>`
实测，如果内容相对这个.l-tabpanel所在元素定位，就没问题，如下
```
.tab-content{
  min-height: 0!important;
  flex: 1;
}
.tab-content>view{
  position: relative;
}
.content {
  box-sizing: border-box;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  overflow-y: scroll;
}
```
**完美显示！**

但是微信小程序不建议使用标签名来作为选择器，所以不能使用view，有警告，所以我改成下面：
```
.tab-content>.l-tabpanel{
  position: relative;
}
```
但是因为样式隔离，上面的设置无效……所以我要么忽略微信小程序的警告使用view标签选择器，要么就只能修改Tabs的源码。

所以综上：
如果要实现我的需求，必须对tabpanel也能自定义样式，所以建议增加一个l-tabpanel-class来自定义tabpanel的样式。

**Comment by MuRongXiaoDouBi** [comment]
![image](https://user-images.githubusercontent.com/38655613/94631187-58cf6b00-02fa-11eb-909c-c748b97d0e81.png)
已在这两处加入 l-tabpanel-class
