### ISSUE TITLE
 选项卡 Segment添加dot-badge属性后点击失效

### ISSUE THREAD

**Issue by yiqia** [TaleLin/lin-ui#1082]
**LinUI版本（必填）：0.8.8

**设备（必填）：所有设备

**基础库版本（必填）：2.12.0

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

<l-segment bind:linchange="changeTabs">
        <l-segment-item dot-badge="true" tab="客厅" key="one" />
        <l-segment-item tab="卧室" key="two" />
        <l-segment-item tab="厨房" key="three" />
    </l-segment>

**Comment by MuRongXiaoDouBi** [comment]
未复现此bug，可否提供复现代码

**Comment by yiqia** [comment]
已解决
