### ISSUE TITLE
Counter组件的到达最大值+号，没有置灰

### ISSUE THREAD

**Issue by Dan-Zo** [TaleLin/lin-ui#1087]
**LinUI版本（必填）：0.8.9

**设备（必填）：all

**基础库版本（必填）：all

Counter组件的到达最大值 `+`号，没有置灰。
0.8.6和0.8.9都有这个问题

**Comment by MuRongXiaoDouBi** [comment]
您好，我没有复现此bug，可否提供一下复现代码
