### ISSUE TITLE
胶囊栏 CapsuleBar的disable-back和disable-home无效？

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1089]
**LinUI版本（必填）：0.8.8

**设备（必填）：Android

**基础库版本（必填）：2.12.2

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
按文档里说明，disable-back和disable-home可以关闭左侧按钮，但是实际我设置为true，还是显示了返回按钮和首页按钮？

**Comment by KuoKongQingYun** [comment]
我看了一下源码，这两个属性貌似只是控制那两个按钮有没有响应，但是不控制显不显示，比如我首页用了自定义胶囊栏，完全可以隐藏首页按钮和返回按钮，但现在始终显示，是否不太友好?

**Comment by KuoKongQingYun** [comment]
我看到另一个属性，hidden-capsule 应该是这个了，我之前以为这个是把右边的菜单一起隐藏了，实测只隐藏左边，暂时解决了我的需求。
但是 有一个场景，别人是通过分享页面进入的我的子页面，我想只显示“首页”按钮，而不显示“返回”按钮（因为无法返回），这种还是得两个按钮分开设置显示与隐藏

**Comment by murongg** [comment]
我们内部讨论此功能后回复您

**Comment by juzi214032** [comment]
`disable-back`和`disable-home`是禁用而并非隐藏两个按钮，文档有清楚说明。
`hidden-capsule`仅隐藏左侧按钮是因为小程序右侧按钮无法隐藏，这是小程序限制的原因。
您提到的分开隐藏显示没有设计的原因是因为胶囊按钮本身是左右对称的，如果仅隐藏返回，显示主页按钮，这样在 UI 上并不优雅（如果您有更好的想法欢迎提供给我们）。
不过我们计划提供 API 修改两个按钮的图标，这个功能可以一定程度上满足你的需求

**Comment by yuuki2017** [comment]
我也碰到这个需求，需要隐藏返回按钮，可以在linui提供的胶囊栏基础上自己封装下，从外部传值进来控制返回按钮的隐藏和显示，需要注意胶囊栏的中线也要同时隐藏，以及整个胶囊栏的宽度要减半。建议官方下个版本提供下这个功能。

**Comment by yuuki2017** [comment]
我也碰到这个需求，需要隐藏返回按钮，可以在linui提供的胶囊栏基础上自己封装下，从外部传值进来控制返回按钮的隐藏和显示，需要注意胶囊栏的中线也要同时隐藏，以及整个胶囊栏的宽度要减半。建议官方下个版本提供下这个功能。
