### ISSUE TITLE
关于自定义tabbar，按照之前的issues的说法，这个组件暂时没有维护了

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1090]
关于自定义tabbar，按照之前的issues的说法，这个组件暂时没有维护了，文档里也没有，但是我看组件里面还是有tabbar这个组件，我能不能把它当作一个普通组件使用，也就是不管官方的“自定义tabbar”的用法，我直接用小程序API隐藏小程序自带的tabbar，然后把lin-ui的tabbar当作一个页面组件使用，这样应该没问题吧？所以能否重新打开这个组件的文档。
我现在使用的是vant ui里的tabbar，就是这样用的，只可惜它那个功能太弱了，连自定义背景这些都没有。

**Comment by murongg** [comment]
不推荐在生产环境使用

**Comment by juzi214032** [comment]
0.8.12 版本将会上线重构后的版本
