### ISSUE TITLE
案例展示

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#1092]
小程序名称：si哩si哩
小程序简介：一个可以听音乐的小程序客户端，参照慕课黄轶老师的课程开发 https://coding.imooc.com/class/107.html
移动端音乐Web App，同样是抓取qq音乐的接口，有兴趣的朋友可以联系qq:570906732交流实现的过程。
小程序类型：个人
使用到的组件：l-loading，l-loadmore，l-icon，l-dialog， l-popup，l-message, l-circle
l-tabs,l-tabpanel,l-button

二维码：
![silisili](https://user-images.githubusercontent.com/30004721/96443598-73349e80-123f-11eb-8cdf-9fc35359d075.png)

**Comment by murongg** [comment]
请回复到此issue中：https://github.com/TaleLin/lin-ui/issues/947
