### ISSUE TITLE
wx.lin.restForm 在真机下不生效

### ISSUE THREAD

**Issue by xiaolong7yang** [TaleLin/lin-ui#1093]
**LinUI版本（必填）：*0.8.9*

**设备（必填）：*IPhone X*

**基础库版本（必填）：*2.13.1*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
  
 wx.lin.resetForm('questionFrom')

使用wx.lin.resetForm 在开发阶段是生效的，用微信电脑版的微信小程序也是生效的。但是 IOS 和安卓上 。 wx.lin.resetForm('questionFrom') 不生效

**Comment by juzi214032** [comment]
您好，我这边测试手机端是正常的，建议您更换设备试一下，如果还有问题，欢迎提交代码片段给我们排查

机型：小米 8 UD
安卓版本： Android 10
