### ISSUE TITLE
按照官网教程一步步来操作，报错：VM391:1 miniprogram_npm/lin-ui/common/async-validator/rule/index.js: Error: module "miniprogram_npm/lin-ui/common/async-validator/rule/whitespace.js" is not defined 以为是自己操作有问题，重新创建项目，依旧报错，还望作者能帮忙处理一下，谢谢

### ISSUE THREAD

**Issue by rao261488647** [TaleLin/lin-ui#1096]
**LinUI版本（必填）：0.8.10

**设备（必填）：微信开发工具

**基础库版本（必填）：2.13.1

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

按照官网教程一步步来操作，报错：VM391:1 miniprogram_npm/lin-ui/common/async-validator/rule/index.js: Error: module "miniprogram_npm/lin-ui/common/async-validator/rule/whitespace.js" is not defined 以为是自己操作有问题，重新创建项目，依旧报错，还望作者能帮忙处理一下，谢谢

**Comment by murongg** [comment]
小程序会有这样的问题，有时候npm构建会丢失文件，请重新尝试使用npm构建

**Comment by rao261488647** [comment]
重新尝试使用npm构建， 提示：[ app.json 文件内容错误] app.json: ["usingComponents"]["l-button"] 未找到，

**Comment by murongg** [comment]
> 重新尝试使用npm构建， 提示：[ app.json 文件内容错误] app.json: ["usingComponents"]["l-button"] 未找到，

实现不行可以把源码从git拉取下来，dist目录下就是所有组件源码

**Comment by rao261488647** [comment]
将dist内的文件全部复制到/plugins/lin-ui 目录下
然后在  app.json中，如下配置

"usingComponents": {
    "l-toast": "/plugins/lin-ui/button/index",
    "l-message": "/plugins/lin-ui/message/index"
  },

在 wxml里  配置：  <l-button width="500" height="120">按钮</l-button>

编译运行后， 没有展示出来样式

**Comment by rao261488647** [comment]
`  <l-button width="500" height="120">按钮</l-button>`

**Comment by rao261488647** [comment]
可以了，我再继续研究，谢谢。
