### ISSUE TITLE
官方网站文档里，tabbar在左侧菜单查询不到，搜索可以查询到，另外使用介绍感觉很粗糙

### ISSUE THREAD

**Issue by rao261488647** [TaleLin/lin-ui#1097]
**LinUI版本（必填）：0.8.10

**设备（必填）：微信开发工具

**基础库版本（必填）：2.13.1

UI问题，请附上截图

重现步骤，必要时请提供代码片段链接

tabbar在官网左侧菜单没有查到，搜索却可以搜到，不知道是不是bug
没有具体示例代码，对于刚接触的小白，不太友好
能否提供一个demo版本的代码参考一下
现在不知道怎么上手

**Comment by murongg** [comment]
现在此组件已被废弃

**Comment by juzi214032** [comment]
近期会对该组件重新上线，欢迎持续关注
