### ISSUE TITLE
2020-10-27 新构建lin-ui 报错

### ISSUE THREAD

**Issue by xuwenfeng93** [TaleLin/lin-ui#1099]
![QQ截图20201027143924](https://user-images.githubusercontent.com/48546665/97265942-785aa480-1862-11eb-8663-5659ad953b5b.png)

**Comment by murongg** [comment]
https://github.com/TaleLin/lin-ui/issues/1096

**Comment by juzi214032** [comment]
请删掉node_modules重新构建一下，应该是构建过程中出了问题，文件不完整
