### ISSUE TITLE
【Feature Request】

### ISSUE THREAD

**Issue by chronosAeon** [TaleLin/lin-ui#11]
1.加载进度条
2.折叠面板TreeView

**Comment by uniquenaer** [comment]
可以根据下面两点补充更多信息么？

1 你希望的支持的新功能的业务场景

2 你期望的 API 是怎样的？

**Comment by chronosAeon** [comment]
1.官方进度条在Ui上定制化太少不是很好看。
2.官方进度条，数据绑定100%后，立马跳转页面不会显示100%再跳转页面。
希望改进：如果进度条再没有100%就要跳转页面的话，进度条快速加载到100%，然后再跳转页面。

**Comment by 7insummer** [comment]
> 1.官方进度条在Ui上定制化太少不是很好看。
> 2.官方进度条，数据绑定100%后，立马跳转页面不会显示100%再跳转页面。
> 希望改进：如果进度条再没有100%就要跳转页面的话，进度条快速加载到100%，然后再跳转页面。

进度条我们有计划，谢谢。

**Comment by juzi214032** [comment]
您好，`0.8.2`已增加 [Progress 组件](http://doc.mini.7yue.pro/component/view/progress.html)
您说的 TreeView 大概是一个什么样子呢，能提供一个截图吗
