### ISSUE TITLE
lin-ui 相册组件（Album）

### ISSUE THREAD

**Issue by gzz-215** [TaleLin/lin-ui#1100]
**LinUI版本（必填）：*0.8.7*

> **设备（必填）：*ios*

**基础库版本（必填）：*2.13.1*

单张图片会有一个下边距，多张图片没有，示列小程序里好像也是，因为像素太小，不容易看出来，但是加入元素后就看的比较明显了！（不知道算不算问题，勿喷~）

![image](https://user-images.githubusercontent.com/34476582/97287057-15c3d180-187f-11eb-988c-ba6c442138d1.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
感谢你的反馈，确实存在此问题，我们会进行修复。为你的仔细和认真点赞:+1:
