### ISSUE TITLE
对PC端文档的建议

### ISSUE THREAD

**Issue by 1335951413** [TaleLin/lin-ui#1101]
**描述你希望的支持的新功能？**

希望PC端文档可以像 vant weapp 文档那么直观

**你期望的 API 是怎样的？**

第一眼看到 lin-ui 就想去尝试，但挡在我面前的是文档不如 [vant weapp](https://vant-contrib.gitee.io/vant-weapp/#/button) 那么的直观

大家开发小程序应该都是在PC端进行操作的，如果需要一边手机看组件样式效果，一边电脑看文档，再一边往开发者工具里复制，感觉很不爽呀...（[官方提示：组件开发体验爽，一直使用一直爽！](https://doc.mini.talelin.com/start/component.html)略显尴尬）

当然 lin-ui 文档里也有示例图片，但真实体验下来感觉还是差了不少，何况有些文档页面的图片还展示不出来...
比如打开组件文档映入眼帘的 [button 组件](https://doc.mini.talelin.com/component/)示例图
![image](https://user-images.githubusercontent.com/28770135/97520955-736b3180-19d7-11eb-832f-133ceefdcf1b.png)

当然，这紧急性也不是特别高，希望可以优先把文档里失效图片处理一下，后续慢慢考虑文档更加直观些

**Comment by juzi214032** [comment]
感谢建议，文档图片的问题我们近两天就会修复
而网页端直接查看效果这个我们暂时没有想到好的解决方案，vant能查看是因为他们有vue版本（网页端的预览效果和小程序实际效果可能并不一致），而lin ui是一个纯小程序组件，无法直接在网页端预览。

**Comment by juzi214032** [comment]
文档图片已修复，在线预览的解决方案我近期会进行一下调研
