### ISSUE TITLE
dialog 的确定可否支持下 bindtap

### ISSUE THREAD

**Issue by qm88888888** [TaleLin/lin-ui#1103]
**描述你希望的支持的新功能？**
dialog 的确定可否支持下 bindtap
**你期望的 API 是怎样的？**

**Comment by juzi214032** [comment]
`dialog`支持`bind:linconfirm`事件，请问你说的确定的 bindtap 是指什么？

**Comment by qm88888888** [comment]
就是我需要确定指点调用 微信的一些比如支付功能这样的api
  因为不是userTap 无法调用

**Comment by aQingYun** [comment]
bind:linconfirm事件是可以支持调用支付等相关的原生api的

**Comment by qm88888888** [comment]
但是我调用模版消息接口 还是报错了呢

**Comment by qm88888888** [comment]
VM336:1 Uncaught (in promise) thirdScriptError
{"errMsg":"requestSubscribeMessage:fail can only be invoked by user TAP gesture."}
Object

**Comment by qm88888888** [comment]
![Uploading image.png…]()

**Comment by juzi214032** [comment]
官方已经废弃模板消息 API，建议使用[订阅消息](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html)。
麻烦尝试一下订阅消息是否可用，如果仍不可用，我会进行修复
