### ISSUE TITLE
count组件问题

### ISSUE THREAD

**Issue by zhuoNy** [TaleLin/lin-ui#1106]
**LinUI版本（必填）：**
"lin-ui": "^0.8.9",
**设备（必填）：**
开发工具稳定版 Stable Build (1.03.2010240)
**基础库版本（必填）：**
"libVersion": "2.8.3",
**UI问题，请附上截图**
1、页面初始化后，点击+/-时会按min值增加步长面不是input值，当设定的count小于min时如count=2，min=5，点击+时还是显示3；
2、比如step为1，初始值为2时，将input改为5时再点击+/-时会显示2再跳为6；
3、当将input值从大改小，初始值为9，手动改为5，再次点击+时，还是为5；与预期不符；
4、当改动数值不在有效值范围时，小于最小值给定最小值，反之给啊大值，应有提示；

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
您好，感谢反馈。123提出的问题均以修复，将在下个版本更新。第4点只需要监听`bind:linout`事件即可
