### ISSUE TITLE
error during "Build npm" in wechat dev tool

### ISSUE THREAD

**Issue by guozheng** [TaleLin/lin-ui#1108]
**LinUI版本（必填）：**
0.8.10

**设备（必填）：**
Wechat Devtool: Stable Build (1.03.2010240)

**基础库版本（必填）：**
2.0.4

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
   1. Create a simple Wechat app using Devtool
   1. Follow Lin UI setup guide to install through npm
   1. In the page's `json` config file, add: 
```
"usingComponents": {
    "l-icon": "/miniprogram_npm/lin-ui/button/index"
  }
```
   1. Tools -> Build npm

Got this error:
```
[ miniprogram_npm/lin-ui/checkbox-group/index.json file content error] miniprogram_npm/lin-ui/checkbox-group/index.json: ["usingComponents"]["l-error-tip"]: "../error-tip/index" not found
```

**Comment by guozheng** [comment]
tried a couple of other Debug Base Library versions: 2.13.2, 2.14.0, same error.

**Comment by guozheng** [comment]
closed the project and then opened it again, now the error is gone. It might be related to the compilation order of the components? For example, the parent component was compiled first before the dependent component, then it gives the error. If the dependent component was compiled first, then it works fine?

**Comment by 7insummer** [comment]
The base version library is too low. Try to raise it

**Comment by juzi214032** [comment]
From what you describe, the problem is that the error-tip and grid-item components don't exist. Please be sure to check that the relevant files are complete, as there is no order issue with using Lin UI!
