### ISSUE TITLE
增加类似安卓的SlidingUpPanel组件

### ISSUE THREAD

**Issue by sunxivincent** [TaleLin/lin-ui#1115]
**描述你希望的支持的新功能？**
增加类似安卓的SlidingUpPanel组件 比如这个例子https://github.com/umano/AndroidSlidingUpPanel

**你期望的 API 是怎样的？**

**Comment by murongg** [comment]
您看一下 `ArcPopup` 这个组件是否满足您的需求

**Comment by sunxivincent** [comment]
> 您看一下 `ArcPopup` 这个组件是否满足您的需求

感谢回复，这个和我预期的需求不太一样，我希望能够随着手势把arcPopUp这个窗口拉上去，而不是用一个button来trigger。 如果能在`ArcPopup` 里面bind手势移动就更好了

**Comment by murongg** [comment]
我们会考虑此功能的研发

**Comment by juzi214032** [comment]
小程序平台做不到和原生那样流畅的动画，做出来效果会很差，所以这个组件我们无法实现
