### ISSUE TITLE
price unit与value大小差距过大时，deleted线会严重断层

### ISSUE THREAD

**Issue by LeeSamFong** [TaleLin/lin-ui#1116]
**LinUI版本（必填）：0.8.10

**设备（必填）：微信开发工具

**基础库版本（必填）：**

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/47028881/99615689-d429df00-2a56-11eb-9b29-685f1f36150e.png)

**重现步骤，必要时请提供代码片段链接**
![image](https://user-images.githubusercontent.com/47028881/99615703-da1fc000-2a56-11eb-9a48-9939592d5bd8.png)

**Comment by murongg** [comment]
您好，此问题已复现，我们会讨论该问题怎么解决！

**Comment by murongg** [comment]
抱歉，此问题我们内部讨论后不予修复，因为该组件的 `unit` 与 `value` 的值可定制化太高，没办法满足所有用户！
