### ISSUE TITLE
Button组件使用bind:lintap事件，点击时按钮事件没有触发

### ISSUE THREAD

**Issue by willflow** [TaleLin/lin-ui#1118]
**LinUI版本（必填）：
0.8.10

**设备（必填）：
稳定版1.03.2010240，所有机型均可复现

**基础库版本（必填）：
2.8.1

**重现步骤，必要时请提供代码片段链接**

Button组件在0.8.10的版本下，点击时绑定的函数没有执行；将lin-ui版本替换成0.6.14和0.7.6之后，下方同样的代码，都可以执行成功。
``
    <l-button 
      shape="circle"
      l-class="search-btn"
      icon="research"
      icon-size="24"
      icon-color="#C4C9D2"
      height="64"
      bind:lintap="onGoTosearch"
    >
      搜索商品
    </l-button>
``

**Comment by murongg** [comment]
您好，并未复现此bug，可以检查一下是否为您的其他代码有问题
