### ISSUE TITLE
<l-form-item>标签的label-placement="column"，输入框<input>并不位于label的正下方

### ISSUE THREAD

**Issue by ziyedy** [TaleLin/lin-ui#1120]
**LinUI版本（必填）：**
0.8.10
**设备（必填）：**
Windows10微信小程序开发工具
**基础库版本（必填）：**
微信小程序2.14.0版本
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/39487834/99880961-b96f8a00-2c51-11eb-8713-9776098e36e0.png)

**重现步骤，必要时请提供代码片段链接**
按照官网教程使用（https://doc.mini.talelin.com/component/form/form.html）<l-form-item>标签的label-placement="column"出现的bug，输入框<input>并不位于label的正下方

**Comment by juzi214032** [comment]
可以提供一个代码片段给我们测试一下吗

**Comment by juzi214032** [comment]
这个问题我们会进行优化
