### ISSUE TITLE
lin ui image-clipper图片剪裁工具提示错误

### ISSUE THREAD

**Issue by jerryliushilin** [TaleLin/lin-ui#1129]
**LinUI版本（必填）：最新版本

**设备（必填）：微信开发工具

**基础库版本（必填）：最新版

**UI问题，请附上截图**

使用图片剪裁组件一直提示:Component “miniprogram_npm/lin-ui/image-clipper/index” does not have a method “true” to handle event “touchmove”,只能上下缩放，不能左右缩放
**重现步骤，必要时请提供代码片段链接**

**Comment by murongg** [comment]
可否提供一下复现代码

**Comment by jerryliushilin** [comment]
Wxml：<l-image-clipper show="{{show}}" image-url="{{imageUrl}}"bindlinclip="linclip">
  <l-image-clipper-tools />
</l-image-clipper>

Js: upload() {
    wx.chooseImage({
      count: 1,
      sizeType: ['original', 'compressed'],
      sourceType: ['album', 'camera'],
      success: (res) => {
        console.log(res)
        const tempFilePaths = res.tempFilePaths;
        this.setData({
          imageUrl: tempFilePaths,
          show: true
        });
      }
    });
  },
我都是按照文档写的

发件人: 木荣 <notifications@github.com>
发送时间: 2020年11月27日 21:55
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


可否提供一下复现代码

**Comment by murongg** [comment]
我们测试后给您回复

**Comment by jerryliushilin** [comment]
好的，感谢，但是我看你们的源码DEMO好像是正常的

发件人: 木荣 <notifications@github.com>
发送时间: 2020年11月27日 22:02
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


我们测试后给您回复

**Comment by jerryliushilin** [comment]
我刚才新建了个小程序，放入图片剪裁工具还是提示错误，您这边修复后，麻烦您告诉我下更新，谢谢了！

发件人: 木荣 <notifications@github.com>
发送时间: 2020年11月27日 22:02
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


我们测试后给您回复

**Comment by murongg** [comment]
抱歉，并未复现您所说的问题，请问您的 **LinUI** 是什么版本

**Comment by jerryliushilin** [comment]
我之前用的是V0.8.6版本的，之前版本是没有剪裁这个组件的，昨天我就下载了最新的源码，然后新建了一个小程序页面测试还是报错。
[cid:image001.jpg@01D6C575.BCD353E0]
我只要移动图片就会提示错误
发件人: 木荣 <notifications@github.com>
发送时间: 2020年11月28日 8:37
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


抱歉，并未复现您所说的问题，请问您的 LinUI 是什么版本

**Comment by murongg** [comment]
可否把 `project.config.json` 文件中的代码发一下

**Comment by murongg** [comment]
我这里组件使用正常，只是报了 `VM21:2 Component "miniprogram_npm/lin-ui/image-clipper/index" does not have a method "true" to handle event "touchmove".` 的警告，不影响功能使用

**Comment by jerryliushilin** [comment]
{
  "description": "项目配置文件",
  "packOptions": {
    "ignore": []
  },
  "setting": {
    "urlCheck": true,
    "es6": true,
    "enhance": false,
    "postcss": true,
    "preloadBackgroundData": false,
    "minified": true,
    "newFeature": true,
    "coverView": true,
    "nodeModules": true,
    "autoAudits": false,
    "showShadowRootInWxmlPanel": true,
    "scopeDataCheck": false,
    "uglifyFileName": false,
    "checkInvalidKey": true,
    "checkSiteMap": true,
    "uploadWithSourceMap": true,
    "compileHotReLoad": false,
    "useMultiFrameRuntime": false,
    "useApiHook": true,
    "babelSetting": {
      "ignore": [],
      "disablePlugins": [],
      "outputPath": ""
    },
    "useIsolateContext": true,
    "useCompilerModule": true,
    "userConfirmedUseCompilerModuleSwitch": false,
    "userConfirmedBundleSwitch": false,
    "packNpmManually": false,
    "packNpmRelationList": [],
    "minifyWXSS": true,
    "bundle": false
  },
  "compileType": "miniprogram",
  "libVersion": "2.12.0",
  "appid": "wxd4c4e22fde875c49",
  "projectname": "AdminCloud",
  "debugOptions": {
    "hidedInDevtools": []
  },
  "isGameTourist": false,
  "simulatorType": "wechat",
  "simulatorPluginLibVersion": {},
  "condition": {
    "plugin": {
      "list": []
    },
    "game": {
      "list": []
    },
    "gamePlugin": {
      "list": []
    },
    "miniprogram": {
      "list": [
        {
          "id": 0,
          "name": "pages/repair/repair",
          "pathName": "pages/repair/repair",
          "query": "",
          "scene": null
        },
        {
          "id": 1,
          "name": "pages/repair/detail/detail",
          "pathName": "pages/repair/detail/detail",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/fastmail/fastmail",
          "pathName": "pages/fastmail/fastmail",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/fastmail/detail/detail",
          "pathName": "pages/fastmail/detail/detail",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/confirm/confirm",
          "pathName": "pages/confirm/confirm",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/repair/submit/submit",
          "pathName": "pages/repair/submit/submit",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/repair/submit/submit",
          "pathName": "pages/repair/submit/submit",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/repair/list/list",
          "pathName": "pages/repair/list/list",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/repair/article/article",
          "pathName": "pages/repair/article/article",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/FAQ/faq",
          "pathName": "pages/FAQ/faq",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/FAQ/faq",
          "pathName": "pages/FAQ/faq",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Account/account",
          "pathName": "pages/Account/account",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Account/account",
          "pathName": "pages/Account/account",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Disk/disk",
          "pathName": "pages/Disk/disk",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Work/work",
          "pathName": "pages/Work/work",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Order/List/list",
          "pathName": "pages/Order/List/list",
          "query": "",
          "scene": null
        },
        {
          "id": 16,
          "name": "pages/Work/detail/detail",
          "pathName": "pages/Work/detail/detail",
          "query": "id=135",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Work/zcdetail/zcdetail",
          "pathName": "pages/Work/zcdetail/zcdetail",
          "query": "id=135",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Take/take",
          "pathName": "pages/Take/take",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Take/take",
          "pathName": "pages/Take/take",
          "query": "",
          "scene": null
        },
        {
          "id": -1,
          "name": "pages/Take/detail/detail",
          "pathName": "pages/Take/detail/detail",
          "query": "id=814",
          "scene": null
        },
        {
          "id": 21,
          "name": "pages/license/license",
          "pathName": "pages/license/license",
          "query": "",
          "scene": null
        },
        {
          "name": "pages/index/goods/goods",
          "pathName": "pages/index/goods/goods",
          "query": "",
          "scene": null
        },
        {
          "name": "pages/Card/card",
          "pathName": "pages/Card/card",
          "query": "",
          "scene": null
        }
      ]
    }
  }
}
这是配置项的代码，我也是报了“VM23 WAService.js:2 Component "miniprogram_npm/lin-ui/image-clipper/index" does not have a method "true" to handle event "touchmove".”警告，但是移动裁剪框的时候就报错：“MiniProgramError
Cannot read property 'width' of undefined
TypeError: Cannot read property 'width' of undefined
    at Je.clipTouchMove (http://127.0.0.1:31009/appservice/miniprogram_npm/lin-ui/image-clipper/index.js:107:39)”

发件人: 木荣 <notifications@github.com>
发送时间: 2020年11月28日 11:32
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


可否把 project.config.json 文件中的代码发一下

**Comment by juzi214032** [comment]
您是在开发者工具上试的吗，请问是 mac 还是 windows
另外尝试我们的 demo 没有问题，是吧

**Comment by jerryliushilin** [comment]
您好，是在微信开发工具上试的， 使用的是windows系统，在LIN-UI小程序的DEMO上可以正常使用，然后我新建的小程序上直接用文档的教程创建，只要拖动片剪裁就会提示错误WIDTH问题

发件人: 桔子 <notifications@github.com>
发送时间: 2020年11月28日 12:04
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


您是在开发者工具上试的吗，请问是 mac 还是 windows
另外尝试我们的 demo 没有问题，是吧

**Comment by juzi214032** [comment]
您好，这个问题我这边没有复现，可以提供一个代码片段吗

**Comment by jerryliushilin** [comment]
[cid:image003.jpg@01D6C5A6.19451890]
[cid:image004.jpg@01D6C5A6.19451890]
新建的测试页面，加入剪裁组件，只要移动裁剪框就报WIDTH错误
WXML：<view class="container">
  <l-button bind:lintap="upload" size="large">选择图片</l-button>
<l-image-clipper show="{{show}}" image-url="{{imageUrl}}"bindlinclip="linclip">
  <l-image-clipper-tools />
</l-image-clipper>

</view>
JS：Page({
  data: {
    show: false,
    imageUrl: ''
  },
  linclip(event) {
    const targetImageUrl = event.detail.url;
    console.log('生成的图片链接为：', targetImageUrl);
  },

  upload() {
    wx.chooseImage({
      count: 1,
      sizeType: ['original', 'compressed'],
      sourceType: ['album', 'camera'],
      success: (res) => {
        const tempFilePaths = res.tempFilePaths;
        this.setData({
          imageUrl: tempFilePaths,
          show: true
        });
      }
    });
  },


发件人: 桔子 <notifications@github.com>
发送时间: 2020年11月28日 14:45
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


您好，这个问题我这边没有复现，可以提供一个代码片段吗

**Comment by jerryliushilin** [comment]
[cid:image002.jpg@01D6C5A6.636A6B50]
只要移动裁剪框就一直报width没有定义
发件人: 桔子 <notifications@github.com>
发送时间: 2020年11月28日 14:45
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


您好，这个问题我这边没有复现，可以提供一个代码片段吗

**Comment by juzi214032** [comment]
请使用微信小程序开发者工具的代码片段功能上传代码片段

**Comment by jerryliushilin** [comment]
[cid:image002.jpg@01D6C5D5.8B1B33D0]是这样吗？

发件人: 桔子 <notifications@github.com>
发送时间: 2020年11月28日 22:25
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


请使用微信小程序开发者工具的代码片段功能上传代码片段

**Comment by juzi214032** [comment]
你发的这个图片看不到，请到 github 上回复，不要使用邮件直接回复

**Comment by jerryliushilin** [comment]
您好，是用微信小程序开发者工具上传代码吗？上传后就是体验版

**Comment by juzi214032** [comment]
参考此链接
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by jerryliushilin** [comment]
代码片段已经分享，这是链接https://developers.weixin.qq.com/s/XiEnccmj7Tmm

**Comment by juzi214032** [comment]
这个代码片段我测试过了，没有问题，建议你把基础库设置为`2.14.0`再试一下，如果不行，就换台设备测试一下，99%不是代码的问题

**Comment by juzi214032** [comment]
@murongg  mac测一下

**Comment by jerryliushilin** [comment]
我基础库就是2.14.0的，而且我还把微信开发工具升级成最新的了，我刚才创建代码片段的时候，就只放了图片剪裁组件，就会提示“VM22 WAService.js:2 Component "miniprogram_npm/lin-ui/image-clipper/index" does not have a method "true" to handle event "touchmove".”，然后移动裁剪框就报错 错误内容是:"MiniProgramError
Cannot read property 'width' of undefined
TypeError: Cannot read property 'width' of undefined
    at ie.clipTouchMove (http://127.0.0.1:36375/appservice/miniprogram_npm/lin-ui/image-clipper/index.js:107:39)
    at Object.n.safeCallback (http://127.0.0.1:36375/appservice/__dev__/WAService.js:2:2958768)
    at http://127.0.0.1:36375/appservice/__dev__/WAService.js:2:3129449
    at n (http://127.0.0.1:36375/appservice/__dev__/WAService.js:2:3035851)
    at http://127.0.0.1:36375/appservice/__dev__/WAService.js:2:3036428
    at http://127.0.0.1:36375/appservice/__dev__/WAService.js:2:1857978
    at i (http://127.0.0.1:36375/appservice/__dev__/asdebug.js:1:44030)
    at c (http://127.0.0.1:36375/appservice/__dev__/asdebug.js:1:44141)
    at http://127.0.0.1:36375/appservice/__dev__/asdebug.js:1:9891
    at Set.forEach (<anonymous>)"
那我换MAC电脑试下

**Comment by juzi214032** [comment]
可以把开发者工具卸载重装试一下

**Comment by jerryliushilin** [comment]
好的，我在试试，我卸载重装，这个报错就是影响功能使用了，不能左右缩放，只能上下

**Comment by juzi214032** [comment]
手机端也会报错吗

**Comment by juzi214032** [comment]
这个问题我复现了 下个版本会解决

**Comment by jerryliushilin** [comment]
手机端也会报错，也不能左右移动，您刚才是不是也出现了我说的问题？大概多久可以解决？

**Comment by juzi214032** [comment]
嗯 一周内我们会解决

**Comment by jerryliushilin** [comment]
好的，谢谢您，辛苦了！

**Comment by jerryliushilin** [comment]
您好，我更了剪裁的代码，虽然没有报错了，还是有2个BUG，1：对图片剪裁的时候只能上下缩放，不能左右缩放。2：剪裁后点确认就一直显示加载中。

**Comment by jerryliushilin** [comment]
您好，我更新了剪裁的代码，虽然没有报错了，还是有2个BUG，1：对图片剪裁的时候只能上下缩放，不能左右缩放。2：剪裁后点确认就一直显示加载中。

发件人: 桔子 <notifications@github.com>
发送时间: 2020年12月6日 22:59
收件人: TaleLin/lin-ui <lin-ui@noreply.github.com>
抄送: 刘士麟 <liushilin@xdf.cn>; Author <author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] lin ui image-clipper图片剪裁工具提示错误 (#1129)


Closed #1129<https://github.com/TaleLin/lin-ui/issues/1129> via 652a62f<https://github.com/TaleLin/lin-ui/commit/652a62f8f7c52c9c6d10ec843b8f54db3ec92766>.

**Comment by murongg** [comment]
@jerryliushilin 请重新提 issue 反应此问题
