### ISSUE TITLE
关于用户在使用Tabs组件所制作的类似饿了么菜单滑动效果

### ISSUE THREAD

**Issue by qiuchengguang** [TaleLin/lin-ui#113]
**描述你希望的支持的新功能？**
在右侧列表下拉滑动过程中可以定位在左侧2种种类中间，不会超过这个区域就自动滑到下一个区域或者上一个区域
**你期望的 API 是怎样的？**

**Comment by 7insummer** [comment]
感谢建议，这个新功能会单独写成一个组件支持，目前已在研发中，研发测试完毕后会上线

**Comment by juzi214032** [comment]
您好，可以提供一个视频或者动图吗
