### ISSUE TITLE
如何在taro中实现冒泡功能

### ISSUE THREAD

**Issue by san346596324** [TaleLin/lin-ui#1133]
LinUI版本：0.8.11
开发工具：taro

taro开发是不支持使用呢catch的，他那边的冒泡功能也有问题，目前使用Linui的遮罩层，时间使用bind:lintap在taro中是写成onLintap的,现在想使用冒泡功能却不知道怎么.

**Comment by juzi214032** [comment]
您哈 这个建议去 Taro 仓库提问，这属于框架问题 lin ui 这边无法解答 不好意思
