### ISSUE TITLE
吸顶tab没有吸到顶部

### ISSUE THREAD

**Issue by fuckphptxt** [TaleLin/lin-ui#1138]
l-sticky-item 吸顶容器触发吸顶后会在距离顶部一个导航头的高度悬浮，但是我用了lin-ui的自定义导航胶囊栏就是正常的，用了微信原生的的头部导航，吸顶的部分就会在距离顶部一个导航头的高度悬浮，尝试过用top控制但是貌似没有效果

**Comment by fuckphptxt** [comment]
<l-sticky scrollTop="{{scrollTop}}">
  <l-sticky-item top='0'>
    <view slot="header" class="active">
      
      <view class="shaixuan">
        
    </view>
    <view slot="body">
      
      <view class="contenList">       
        <view style='width:100%;height:2000rpx;'>
          <v-shops-mall shopsList="{{dataArr}}" typesOr='推荐'/>
        </view>
      </view>
    </view>

  </l-sticky-item>
</l-sticky>

**Comment by juzi214032** [comment]
可以提供个代码片段吗

**Comment by fuckphptxt** [comment]
那个问题已经解决了，原因是用了linui得自定义导航头吸顶会和导航头重叠，所以我加了吸顶得padding距离，但是貌似现在吸顶又出现了一个问题，问题如下：现在分为两种状况1、第一种吸顶是正常的吸顶，2、第二种的是需要吸顶的内容滑动到顶部时，可以正常的吸顶，但是继续向上滑动时吸顶的内容会脱离fixed布局而变成文档流被顶到视图之外的内容去，我这边排查暂未找到原因请问开发者得大佬们是什么原因？
