### ISSUE TITLE
小程序构建NPM失败

### ISSUE THREAD

**Issue by xuwenfeng93** [TaleLin/lin-ui#1139]
**LinUI版本（必填）：**0.811

**设备（必填）：**小程序开发者工具

**基础库版本（必填）：**2.14.1

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/48546665/100968784-f5b5bb00-356c-11eb-9064-4d9dd335a433.png)

我用小程序构建 NPM 一直都报这个错误，我删除重新构建还是一样，新建小程序重新安装构建也是这样错误
**重现步骤，必要时请提供代码片段链接**

**Comment by murongg** [comment]
请删除 node_modules 与 miniprogram_npm 文件后重启微信开发者工具，运行 npm install 后尝试重新构建
