### ISSUE TITLE
胶囊栏左上角能否自定义内容？

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1140]
比如，我现在要做一个城市选择按钮，类似美团那样，左上角有个城市，点击可以切换城市，
现在胶囊栏左上角是固定的返回和首页按钮，无法自定义

**Comment by juzi214032** [comment]
可以给个截图吗

**Comment by KuoKongQingYun** [comment]
https://s3.ax1x.com/2020/12/05/DOPJbR.png
类似这样，左上角有个城市选择。

**Comment by KuoKongQingYun** [comment]
因为首页不需要返回按钮或者首页按钮，
所以可以加入一个城市选择按钮，来补齐空位。

**Comment by juzi214032** [comment]
添加了一个标题栏的 Slot，将在下个版本上线
