### ISSUE TITLE
表单验证问题，表单项输入内容，仍验证失败，提示输入内容

### ISSUE THREAD

**Issue by xuefengoye** [TaleLin/lin-ui#1142]
![62149971](https://user-images.githubusercontent.com/26404881/100996094-9e771100-3593-11eb-91b5-1b98a584f176.jpg)
![790452983](https://user-images.githubusercontent.com/26404881/100996100-a040d480-3593-11eb-90b5-e36266db47a6.jpg)

重现步骤
1.快速通过键盘打字，不点击键盘推荐的文字，直接点击屏幕关闭键盘。
2.点击提交表单，提示没有内容，实际内容已经录入。

**Comment by juzi214032** [comment]
您好，我这边没有复现这个问题，您是在 Lin UI 线上小程序测试的吗
