### ISSUE TITLE
关于打包lin-ui按需加载组件缺少core 文件的问题

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#1146]
**LinUI版本（必填）：0.8.11

**设备（必填）：开发者工具

**基础库版本（必填）：2.14.0

添加按需加载lin-ui组件的配置：
{
  "components": [
  	"button",
	"countdown",
	"message",
	"popup",
	"price",
	"dialog"
  ]
}
打包出来的文件，在运行项目的时候缺少 core 文件夹的js
![image](https://user-images.githubusercontent.com/30004721/101139161-199bfe00-364c-11eb-97f3-aeafdce92adb.png)

![image](https://user-images.githubusercontent.com/30004721/101139226-33d5dc00-364c-11eb-9830-bd4a2d2bd408.png)

需要手动添加core文件夹的东西，可以优化下打包的配置。

**Comment by juzi214032** [comment]
可以尝试使用我们的脚手架进行自动按需加载
https://doc.mini.talelin.com/cli/
