### ISSUE TITLE
Form 表单使用图片选择器 ImagePicker,提交后报错

### ISSUE THREAD

**Issue by changmingdev** [TaleLin/lin-ui#1147]
**LinUI版本（必填）：0.8.11

**设备（必填）：开发者工具 基础库

**基础库版本（必填）：2.14.0

**UI问题，请附上截图**
点击提交后，会出现错误
<img width="279" alt="截屏2020-12-05 00 45 27" src="https://user-images.githubusercontent.com/73325623/101190584-82f32f80-3693-11eb-9553-8779a751e051.png">
<img width="754" alt="截屏2020-12-05 00 48 39" src="https://user-images.githubusercontent.com/73325623/101190666-a5854880-3693-11eb-845b-10ae51b7e677.png">

**重现步骤，必要时请提供代码片段链接**
<img width="513" alt="截屏2020-12-05 00 46 19" src="https://user-images.githubusercontent.com/73325623/101190807-e0877c00-3693-11eb-81d8-0e2b424eae25.png">
<img width="232" alt="截屏2020-12-05 00 49 27" src="https://user-images.githubusercontent.com/73325623/101190862-ef6e2e80-3693-11eb-869c-a6c138e47719.png">

**Comment by juzi214032** [comment]
`0.9.0`将支持 ImagePicker

**Comment by changmingdev** [comment]
你好，我现在的版本是0.8.11，如果想在form中用imagePicker，有办法吗？还是只能等到0.9.0再使用？

**Comment by juzi214032** [comment]
> 你好，我现在的版本是0.8.11，如果想在form中用imagePicker，有办法吗？还是只能等到0.9.0再使用？

目前 ImagePicker 的 Form 支持还没有上线，请等待上线后升级到相应版本使用

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
