### ISSUE TITLE
微信原生 textarea 中的 placeholder中的文字浮现在 lin-ui中l-arc-popup组件的上面，设置z-index无效

### ISSUE THREAD

**Issue by ziyedy** [TaleLin/lin-ui#1152]
**LinUI版本（必填）：
0.8.10

**设备（必填）：
华为 Android 10

**基础库版本（必填）：
2.14.0

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/39487834/101283488-ae9e2300-3815-11eb-9892-ec88eb8b4d9f.png)
![image](https://user-images.githubusercontent.com/39487834/101283499-bc53a880-3815-11eb-888d-916c15388cc0.png)

**重现步骤，必要时请提供代码片段链接**
微信原生 textarea 中的 placeholder中的文字浮现在 lin-ui中l-arc-popup组件的上面，设置z-index无效

**Comment by juzi214032** [comment]
这是小程序的限制，原生组件层级高于任何非原生组件，建议在 arc-popup 弹出时，将 textarea 隐藏
