### ISSUE TITLE
lin ui image-clipper图片剪裁工具BUG

### ISSUE THREAD

**Issue by jerryliushilin** [TaleLin/lin-ui#1156]
**LinUI版本（必填）：*0.8.12*

**设备（必填）：*微信开发工具*

**基础库版本（必填）：**

**UI问题，请附上截图**
之前剪裁组件使用时会报错，今日更新后错误取消，但是不能左右缩放，可以上下缩放，裁剪完成图片时一直显示加载中。
**重现步骤，必要时请提供代码片段链接**

**Comment by murongg** [comment]
请问不能左右缩放代表的是裁剪框，还是图片

**Comment by jerryliushilin** [comment]
是剪裁框不能左右拖动，可以上下拖动，剪裁完毕后点确认一直显示加载中，我已在2台机器上测试了

**Comment by murongg** [comment]
显示加载中问题已经定位，不能左右拖动确定一下是不是开启了锁定裁剪框比例

**Comment by jerryliushilin** [comment]
没有开启锁定剪裁框比例，是只能对角上下缩放，不能左右缩放，您们的DEMO的小程序是可以左右缩放的

**Comment by murongg** [comment]
![image](https://user-images.githubusercontent.com/38655613/101319971-d5a03780-389d-11eb-836f-badd90b45d78.png)
目前关于裁剪框有这三种锁定模式，默认是锁定裁剪框比例，请确定 `lock-ratio` 设置为 `false`

lock-ratio
--




lock-ratio
--




lock-ratio
--



lock-ratio
--




lock-ratio
--


`

**Comment by jerryliushilin** [comment]
不好意思，第二个问题解决了，lock-ratio=false才行。现在就是一直加载图片中这个问题了

**Comment by murongg** [comment]
> 不好意思，第二个问题解决了，lock-ratio=false才行。现在就是一直加载图片中这个问题了

这个问题已定位，正在解决

**Comment by jerryliushilin** [comment]
谢谢，辛苦您们了

**Comment by juzi214032** [comment]
0.8.13 版本已修复此问题

**Comment by jerryliushilin** [comment]
谢谢，问题已得到了解决！
