### ISSUE TITLE
吸顶的内容吸顶过后继续上滑会脱落

### ISSUE THREAD

**Issue by fuckphptxt** [TaleLin/lin-ui#1159]
**LinUI版本（必填）：**未知

**设备（必填）：**所有的机型

**基础库版本（必填）：**2.14.0

**UI问题，请附上截图**
这个是刚抵到达吸顶的呈现
![image](https://user-images.githubusercontent.com/38744782/101564326-e7045380-3a05-11eb-9caa-59010b0aa74a.png)
以下是继续上滑一段距离的呈现
![image](https://user-images.githubusercontent.com/38744782/101564359-f84d6000-3a05-11eb-8188-d368202c154f.png)

**重现步骤，必要时请提供代码片段链接**
问题如下：现在分为两种状况1、第一种吸顶是正常的吸顶，2、第二种的是需要吸顶的内容滑动到顶部时，可以正常的吸顶，但是继续向上滑动时吸顶的内容会脱离fixed布局而变成文档流被顶到视图之外的内容去，我这边排查暂未找到原因请问开发者得大佬们是什么原因？

**Comment by juzi214032** [comment]
你的意思是这个本来是吸附在顶部的，但是滑动一段距离后就不吸附了吗

**Comment by fuckphptxt** [comment]
是的，就是滑动到顶部过后可以吸附，但是继续滑动一段距离就不吸附了

**Comment by juzi214032** [comment]
麻烦贴一段wxml代码看一下

**Comment by fuckphptxt** [comment]
`<l-sticky scrollTop="{{scrollTop}}">
  <l-sticky-item top='0'>
    <view slot="header" class="active">
      
      <view class="shaixuan">
        <view class="quyu {{isShowAdd?'redColor':''}}" bindtap="addressSlected">
          <l-popup show="{{isShowAdd}}" animation="show" bind:lintap='hideBg' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="left-scroll">
                <scroll-view scroll-y="true" style="width: 250rpx;height: 820rpx;">
                  <view class="city {{cityNot?'redColor':''}}"  bindtap="Limit">不限</view>
                  <block wx:for="{{cityList}}" wx:key="item">
                  <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}"  bindtap="selectCitys">{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;">
                  <view class="city {{notLimit?'redColor':''}}"  bindtap="notLimit">不限</view>
                  <block wx:for="{{countyList}}" wx:key="item">
                  <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}"  bindtap="selectCounty">{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{areas}}
          <view class="{{isShowAdd?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu  {{priceShow?'redColor':''}}" bindtap="priceSlected">
          <l-popup show="{{priceShow}}" animation="show" bind:lintap='hideprice' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <block wx:for="{{pirceList}}" wx:key='item'>
                  <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="priceBind" >{{item.name}}</view>
                </block>
              </view>
            </view>
          </l-popup>
          {{price}}
          <view class="{{priceShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{areaShow?'redColor':''}}" bindtap="areaSelect">
          <l-popup show="{{areaShow}}" animation="show" bind:lintap='hidearea' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;">
                  <block wx:for="{{areaList}}" wx:key='item'>
                  <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="areaBind" >{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{square}}
          <view class="{{areaShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{moreShow?'redColor':''}}" bindtap="moreSelect">
          <l-popup show="{{moreShow}}" animation="show" bind:lintap='hidemore' content-align="right">
            <view slot='ews-right' class="more-select">
              <view class="more-scroll" >
                <scroll-view scroll-y="true" style="width: 650rpx;height: 100vh;background-color: #fff">
                  <view class="box-more">
                    <view class="title-box">类型</view>
                    <block wx:for="{{moreTypes}}" wx:key='item'>
  <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"  bindtap="moreTypes" >
                      {{item.name}}
                    </view>
                  </block>
                    
                  </view>
                  <view class="box-more">
                  <view class="title-box">来源</view>
                  <block wx:for="{{sourceTypes}}" wx:key='item'>
    <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}" bindtap="sourceTypes">
                      {{item.name}}
                    </view>
                  </block>
                  </view>
                  <view class="box-more">
                  <view class="title-box">排序</view>
                  <block wx:for="{{sortingTypes}}" wx:key='item'>
      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"bindtap="sortingTypes">
                      {{item.name}}
                    </view>
                  </block>
                  </view>
                  <view style=" width: 450rpx;height: 125rpx;"></view>
                </scroll-view>
                <view class="miniso">
                  <view class="clear" bindtap="bindReset">重置</view>
                  <view class="determine" bindtap="bindDetermine">确定</view>
                </view>
              </view>
            </view>
          </l-popup>
          更多
          <view class="{{moreShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
      </view>
    </view>
    <view slot="body">
      
      <view class="contenList">       
        <view style='width:100%;'>
          <block wx:if="{{dataArr}}">
            <v-merchants shopsList="{{dataArr}}" />
          </block>
          <block wx:if="{{!dataArr}}">
            <v-null />
          </block>
        </view>
      </view>
    </view>

  </l-sticky-item>
</l-sticky>`

**Comment by fuckphptxt** [comment]
`<l-sticky scrollTop="{{scrollTop}}">
  <l-sticky-item top='0'>
    <view slot="header" class="active">
      
      <view class="shaixuan">
        <view class="quyu {{isShowAdd?'redColor':''}}" bindtap="addressSlected">
          <l-popup show="{{isShowAdd}}" animation="show" bind:lintap='hideBg' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="left-scroll">
                <scroll-view scroll-y="true" style="width: 250rpx;height: 820rpx;">
                  <view class="city {{cityNot?'redColor':''}}"  bindtap="Limit">不限</view>
                  <block wx:for="{{cityList}}" wx:key="item">
                  <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}"  bindtap="selectCitys">{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;">
                  <view class="city {{notLimit?'redColor':''}}"  bindtap="notLimit">不限</view>
                  <block wx:for="{{countyList}}" wx:key="item">
                  <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}"  bindtap="selectCounty">{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{areas}}
          <view class="{{isShowAdd?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu  {{priceShow?'redColor':''}}" bindtap="priceSlected">
          <l-popup show="{{priceShow}}" animation="show" bind:lintap='hideprice' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <block wx:for="{{pirceList}}" wx:key='item'>
                  <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="priceBind" >{{item.name}}</view>
                </block>
              </view>
            </view>
          </l-popup>
          {{price}}
          <view class="{{priceShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{areaShow?'redColor':''}}" bindtap="areaSelect">
          <l-popup show="{{areaShow}}" animation="show" bind:lintap='hidearea' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;">
                  <block wx:for="{{areaList}}" wx:key='item'>
                  <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="areaBind" >{{item.name}}</view>
                </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{square}}
          <view class="{{areaShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{moreShow?'redColor':''}}" bindtap="moreSelect">
          <l-popup show="{{moreShow}}" animation="show" bind:lintap='hidemore' content-align="right">
            <view slot='ews-right' class="more-select">
              <view class="more-scroll" >
                <scroll-view scroll-y="true" style="width: 650rpx;height: 100vh;background-color: #fff">
                  <view class="box-more">
                    <view class="title-box">类型</view>
                    <block wx:for="{{moreTypes}}" wx:key='item'>
  <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"  bindtap="moreTypes" >
                      {{item.name}}
                    </view>
                  </block>
                    
                  </view>
                  <view class="box-more">
                  <view class="title-box">来源</view>
                  <block wx:for="{{sourceTypes}}" wx:key='item'>
    <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}" bindtap="sourceTypes">
                      {{item.name}}
                    </view>
                  </block>
                  </view>
                  <view class="box-more">
                  <view class="title-box">排序</view>
                  <block wx:for="{{sortingTypes}}" wx:key='item'>
      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"bindtap="sortingTypes">
                      {{item.name}}
                    </view>
                  </block>
                  </view>
                  <view style=" width: 450rpx;height: 125rpx;"></view>
                </scroll-view>
                <view class="miniso">
                  <view class="clear" bindtap="bindReset">重置</view>
                  <view class="determine" bindtap="bindDetermine">确定</view>
                </view>
              </view>
            </view>
          </l-popup>
          更多
          <view class="{{moreShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
      </view>
    </view>
    <view slot="body">
      
      <view class="contenList">       
        <view style='width:100%;'>
          <block wx:if="{{dataArr}}">
            <v-merchants shopsList="{{dataArr}}" />
          </block>
          <block wx:if="{{!dataArr}}">
            <v-null />
          </block>
        </view>
      </view>
    </view>

  </l-sticky-item>
</l-sticky>`

**Comment by fuckphptxt** [comment]
`<l-sticky scrollTop="{{scrollTop}}">
  <l-sticky-item top='0'>
    <view slot="header" class="active">
    </view>

  </l-sticky-item>
</l-sticky>`

**Comment by fuckphptxt** [comment]
`<l-sticky scrollTop="{{scrollTop}}">
  <l-sticky-item top='0'>
    <view slot="header" class="active">
    </view>

  </l-sticky-item>
</l-sticky>`

**Comment by fuckphptxt** [comment]
![Uploading image.png…]()

**Comment by fuckphptxt** [comment]
![image](https://user-images.githubusercontent.com/38744782/101591972-73c00900-3a28-11eb-8a73-5cff040535b0.png)
贴上去的代码有问题，所以截图了

**Comment by juzi214032** [comment]
请确定下`l-sticky`组件有把你所有的内容包裹起来吗，通过这个代码我暂时没看出问题
如果还是无法解决，可以提供一个代码片段给我调试一下

**Comment by fuckphptxt** [comment]
是的，所有的都用l-sticky 和l-sticky-item包括起来的

**Comment by juzi214032** [comment]
那麻烦一共一个代码片段我们排查一下
https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html

**Comment by fuckphptxt** [comment]
`<l-sticky mode='js' scrollTop="{{scrollTop}}">
  <l-sticky-item   top='0'>
    <view slot="header" class="active">
      
      <view class="shaixuan">
        <view class="quyu {{isShowAdd?'redColor':''}}" bindtap="addressSlected">
          <l-popup show="{{isShowAdd}}" animation="show" bind:lintap='hideBg' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="left-scroll">
                <scroll-view scroll-y="true" style="width: 200rpx;height: 820rpx;">
                  
                  <block wx:for="{{clonArr}}" wx:key="item">
                    <view class="city {{item.isSelect?'redColor':''}}" data-id="{{index}}" bindtap="selectClon">
                      {{item.name}}</view>
                  </block>
                </scroll-view>
              </view>
              <view class="left-scroll" wx:if="{{runType==1}}">
                <scroll-view scroll-y="true" style="width: 250rpx;height: 820rpx;">
                  <view class="city {{cityNot?'redColor':''}}" bindtap="Limit">不限</view>
                  <block wx:for="{{cityList}}" wx:key="item">
                    <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}" bindtap="selectCitys">
                      {{item.name}}</view>
                  </block>
                </scroll-view>
              </view>
              <view class="left-scroll" wx:if="{{runType==2}}">
                <scroll-view scroll-y="true" style="width: 250rpx;height: 820rpx;">
                  <view class="city {{bindSubway?'redColor':''}}" bindtap="bindSubway">不限</view>
                  <block wx:for="{{subwayArr}}" wx:key="item">
                    <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" data-list="{{item.list}}"
                      bindtap="selectSubway">
                      {{item.stationName}}</view>
                  </block>
                </scroll-view>
              </view>
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;" wx:if="{{runType==1}}">
                  <view class="city {{notLimit?'redColor':''}}" bindtap="notLimit">不限</view>
                  <block wx:for="{{countyList}}" wx:key="item">
                    <view class="city {{item.isSelect?'redColor':''}}" data-id="{{item.id}}" bindtap="selectCounty">
                      {{item.name}}</view>
                  </block>
                </scroll-view>
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;" wx:if="{{runType==2}}">
                  
                  <block wx:for="{{subwayList}}" wx:key="item">
                    <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="selectway">
                      {{item.stationName}}</view>
                  </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{areas}}
          <view class="{{isShowAdd?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu  {{priceShow?'redColor':''}}" bindtap="priceSlected">
          <l-popup show="{{priceShow}}" animation="show" bind:lintap='hideprice' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <block wx:for="{{pirceList}}" wx:key='item'>
                  <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="priceBind">
                    {{item.name}}</view>
                </block>
              </view>
            </view>
          </l-popup>
          {{price}}
          <view class="{{priceShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{areaShow?'redColor':''}}" bindtap="areaSelect">
          <l-popup show="{{areaShow}}" animation="show" bind:lintap='hidearea' content-align="bottom">
            <view slot='news' class="address-select">
              <view class="right-scroll">
                <scroll-view scroll-y="true" style="width: 480rpx;height: 820rpx;">
                  <block wx:for="{{areaList}}" wx:key='item'>
                    <view class="city {{item.isSelect?'redColor':''}}" data-index="{{index}}" bindtap="areaBind">
                      {{item.name}}</view>
                  </block>
                </scroll-view>
              </view>
            </view>
          </l-popup>
          {{square}}
          <view class="{{areaShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
        <view class="quyu {{moreShow?'redColor':''}}" bindtap="moreSelect">
          <l-popup show="{{moreShow}}" animation="show" bind:lintap='hidemore' content-align="right">
            <view slot='ews-right' class="more-select">
              <view class="more-scroll">
                <scroll-view scroll-y="true" style="width: 650rpx;height: {{windowHeight}}px;background-color: #fff">
                  <view class="box-more">
                    <view class="title-box">类型</view>
                    <block wx:for="{{moreTypes}}" wx:key='item'>
                      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"
                        bindtap="moreTypes">
                        {{item.name}}
                      </view>
                    </block>

                  </view>
                  <view class="box-more">
                    <view class="title-box">来源</view>
                    <block wx:for="{{sourceTypes}}" wx:key='item'>
                      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"
                        bindtap="sourceTypes">
                        {{item.name}}
                      </view>
                    </block>
                  </view>
                  <view class="box-more">
                    <view class="title-box">硬件配套</view>
                    <block wx:for="{{hardwareArr}}" wx:key='item'>
                      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"
                        bindtap="hardwareTypes">
                        {{item.name}}
                      </view>
                    </block>
                  </view>
                  <view class="box-more">
                    <view class="title-box">业态</view>
                    <block wx:for="{{formatsArr}}" wx:key='item'>
                      <view class="title-list {{item.isSelect?'bgRedColor':''}}" data-index="{{index}}"
                        bindtap="sortingTypes">
                        {{item.name}}
                      </view>
                    </block>
                  </view>
                  <view style=" width: 450rpx;height: 200rpx;"></view>
                </scroll-view>
                <view class="miniso">
                  <view class="clear" bindtap="bindReset">重置</view>
                  <view class="determine" bindtap="bindDetermine">确定</view>
                </view>
              </view>
            </view>
          </l-popup>
          更多
          <view class="{{moreShow?'sanjiao':'notsanjiao'}}"></view>
        </view>
      </view>
    </view>
    <view slot="body">
      
      <view class="contenList">
        <view style='width:100%;'>
          <block wx:if="{{dataArr}}">
            <v-shops shopsList="{{dataArr}}" bind:bindNavigator='bindNavigator' />
          </block>
          <block wx:if="{{!dataArr}}">
            <v-null />
          </block>
        </view>
      </view>
    </view>

  </l-sticky-item>
</l-sticky>`

**Comment by juzi214032** [comment]
请使用小程序的代码片段功能提供

**Comment by fuckphptxt** [comment]
https://developers.weixin.qq.com/s/F0miFump7omW

**Comment by fuckphptxt** [comment]
这个代码片段功能我不是很会用，但是把那个项目的目录扔进来了 大致就是这个链接的样子

**Comment by juzi214032** [comment]
你的页面是不是划到底部的时候会请求api，然后往列表中填充新的数据

**Comment by fuckphptxt** [comment]
目前还没有使用下拉或者上拉填充新数据，如果有的话是按照官方文档说的添加了wx.lin.flushSticky()方法刷新吸顶容器，但是目前数据量不多，暂时没有用到过这个

**Comment by juzi214032** [comment]
只要你的数据会变，就必须要用这个方法刷新数据，不然就会错位。跟数据量大小没关系

**Comment by fuckphptxt** [comment]
但是目前还没数据填充变化，基本上数据时固定的，这样的话我再重新写一下试试，谢谢大大~

**Comment by juzi214032** [comment]
如果没有数据填充变化的话，按理说是不会出现错位的时候，建议你再排查下是不是其他样式影响到了Sticky。实在排查不出可以学下代码片段怎么弄，你之前提交的代码片段我这边是没法排查的
