### ISSUE TITLE
期望增加几个组件 

### ISSUE THREAD

**Issue by baiyuxiong** [TaleLin/lin-ui#1161]
1、表单页面
各种表单组件的页面设计和功能，因为这里会涉及到一些布局的问题。现在的布局解决不了。
2、搜索组件，类似下图：
![image](https://user-images.githubusercontent.com/230689/101624005-4426f600-3a54-11eb-8d56-c6a7f1e709d1.png)
截取自活动行小程序的“找活动”菜单
3、列表，类似这样的：
![image](https://user-images.githubusercontent.com/230689/101624561-0d051480-3a55-11eb-8178-8468133788c1.png)
4、增加一些灵活的间距样式，
如 mt-5 表示到margin-top: 5 ，my-5 表示 margin-top:5,margin-botton:5 之类的
5、幻灯片
6、可以左右滑动的列表，最后一个元素显示一半，提示用户后面还有，可以朝左滑一下：
![image](https://user-images.githubusercontent.com/230689/101625267-1f338280-3a56-11eb-92d4-3a3626812833.png)

**Comment by juzi214032** [comment]
您好，感谢您的建议：
1. 表单页面这个其实不属于组件，更像是一种页面模板，关于模板我们目前没有多余的精力去制作
2. 您说的搜索组件已在计划中，会尽快上线
3. 列表组件目前有`List`，并且都提供了 Slot，建议您在这个组件的基础上进行定制
4. 这种样式我们会进行考虑，但这并不是一个优先级特别高的需求，排序会靠后一些
5. 不知道您说的幻灯片是不是页面 Banner，如果是 Banner 的话小程序原生提供的已经可以比较方便的使用了，如果您有什么特殊的需求，也可以继续提出
6. 这种左右滑动的列表首先很难抽象出一个通用的组件，因为每个人的元素大小都不一样，而从组件内部去确定元素的性能开销是比较大的。这类组件直接在页面中由开发者控制样式会更好实现，因为开发者可以明确的知道元素大小
