### ISSUE TITLE
rate组件 其他图片设定 大小尺寸后  错位问题

### ISSUE THREAD

**Issue by steavengong** [TaleLin/lin-ui#1165]
**LinUI版本（必填）：0.8.12

**设备（必填）：微信开发者工具 stable 

**基础库版本（必填）：2.14.1

![image](https://user-images.githubusercontent.com/10862092/101788868-90993100-3b3b-11eb-8c51-bd9eea2f382a.png)

**wxml**
```
  <!-- 这行没有问题 -->
  <view class="rete-container">
    <l-rate score="3" size="22" disabled/>
    <text class="score">3</text>
  </view>

  <!-- 这行有问题 -->
  <view class="rete-container">
    <l-rate inActive-image="/assets/images/icon/none-star.png" active-image="/assets/images/icon/star.png"
    score="3"
    disabled
    l-image-class="star"/>
    <text class="score">7</text>
  </view>
```
我是用的图片 来源慕课网  图片大小是17*17像素

**wxss**
```
.rete-container{
  display: flex;
  flex-direction: row;
  align-items: baseline;
  margin-top: 6rpx;
}

.star{
  width: 22rpx;
  height: 22rpx;
}
.score{
  margin-left: 20rpx;
  font-size: 24rpx;
}
```
按照原图换算 rpx  
.star 的宽度和高度 设置到  34rpx 都没问题
但是如果小于34rpx后就出问题了

**Comment by juzi214032** [comment]
麻烦提供一下你的图片呢

**Comment by steavengong** [comment]
![image](https://user-images.githubusercontent.com/10862092/101792998-52524080-3b40-11eb-8259-648b78267c22.png)
![image](https://user-images.githubusercontent.com/10862092/101793010-55e5c780-3b40-11eb-8061-b2675d5a4b02.png)

**Comment by steavengong** [comment]
![image](https://user-images.githubusercontent.com/10862092/101793180-7a41a400-3b40-11eb-9e99-9b9781ecf677.png)

**Comment by juzi214032** [comment]
`0.9.0`会修复此问题
