### ISSUE TITLE
button disabled="{{true}}" 不能置灰

### ISSUE THREAD

**Issue by EasonQwQ** [TaleLin/lin-ui#1171]
**LinUI版本（必填）：**^0.8.11

**设备（必填）：** 手机电脑 
**基础库版本（必填）：**2.14.1

**UI问题，请附上截图** 
disabled 设置为true 不能置灰

**重现步骤，必要时请提供代码片段链接**
<l-button size="long"  type="default" bindlintap="participate" disabled="{{true}}">{{btnText}}</l-button>

**Comment by murongg** [comment]
您好并未能复现此问题，`Button` 组件 `disabled` 设置为 `true` 后，会将 `opacity` 的透明度设置为 `0.8`，以此达到置灰效果

**Comment by EasonQwQ** [comment]
那请问我想要灰色的效果，或者你们文档里面 那个效果，怎么搞，自己写css实现？
![微信截图_20201214203433.png](https://i.loli.net/2020/12/14/LZ3YA1UOWyz85oh.png)

**Comment by murongg** [comment]
可通过动态修改 `bg-color` 属性来达到您想要的效果

**Comment by EasonQwQ** [comment]
好的，谢谢。  一个建议，文档中显示这个按钮，但是没办法通过组件中的属性来实现，可以改下？

**Comment by murongg** [comment]
好的，将会修改此组件文档展示的图片

**Comment by EasonQwQ** [comment]
改成 可以通过修改bg-color 属性来达到这种效果把。 要disabled 之后变灰 而不是 蓝色变成淡蓝色的需求应该更多一点。那个淡蓝色根本看不出来disabled
