### ISSUE TITLE
l-album 组件动态渲染图片无法显示和无渲染

### ISSUE THREAD

**Issue by fuckphptxt** [TaleLin/lin-ui#1172]
**LinUI版本（必填）：*未知*

**设备（必填）：*iphone 6 7 8*

**基础库版本（必填）：*2.14.0*

**UI问题，请附上截图*
![image](https://user-images.githubusercontent.com/38744782/102204438-d6bc0f00-3f04-11eb-8d0d-e37b2776d0fb.png)
*

**重现步骤，必要时请提供代码片段链接**
l-album 组件动态渲染图片无法显示图片和无渲染，通过onload方法渲染图片后 对应数组的数据图片没有进行渲染，而通过data里面进行定义一个数组的图片可以进行渲染，请问开发大大是什么问题，截图如上，右边是打印出来得要渲染的数据

**Comment by juzi214032** [comment]
通过 onload 方法渲染什么意思，麻烦贴下代码

**Comment by fuckphptxt** [comment]
![image](https://user-images.githubusercontent.com/38744782/102293549-50461280-3f82-11eb-88f8-13a68d344369.png)
![image](https://user-images.githubusercontent.com/38744782/102293727-a2873380-3f82-11eb-9a99-389ab82cdc10.png)
以上是说明：刚开始我以为是this.setData没有赋值得问题，但是我打印出以上的赋值发现是赋值成功了的，并且格式和第二张图片在data里定义的是一样的，并且我还单独写了一个image标签通过this.setData进行赋值发现是可以显示图片的：如下图：
![image](https://user-images.githubusercontent.com/38744782/102294119-80da7c00-3f83-11eb-8702-67ca03e79c17.png)
请问开发大大知道是什么原因吗

**Comment by juzi214032** [comment]
感谢反馈 0.9.0 版本会修复此问题
