### ISSUE TITLE
arc-popup组件和form组件使用，input不显示（安卓可以，iOS不行）

### ISSUE THREAD

**Issue by manongpei** [TaleLin/lin-ui#1174]
**LinUI版本（必填）：*0.8.13*

**设备（必填）：*iPhone SE*

**基础库版本（必填）：*2.14.0*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
iOS：https://static.dingtalk.com/media/lADPGoGu-5WZW0jNBQDNAtA_720_1280.jpg_720x720q90g.jpg?bizType=im
安卓：https://static.dingtalk.com/media/lADPD26eNfLX2VPNCWDNBDg_1080_2400.jpg_720x720q90g.jpg?bizType=im
代码：
[新建文本文档 .txt](https://github.com/TaleLin/lin-ui/files/5699732/default.txt)

**Comment by murongg** [comment]
您好，我这里使用 iphone xr 测试并未出现此问题

**Comment by juzi214032** [comment]
可以提供一个代码片段吗

**Comment by manongpei** [comment]
<l-arc-popup show="{{arcPopup.show}}" min-height="{{arcPopup.minHeight}}">
<l-form name="searchForm" bind:linsubmit="searchSubmit" bind:linreset="searchReset"
			l-form-container-class="l-form-container-class" l-form-btn-class="l-form-btn-class">
			<l-form-item label="名称:" name="goodsName" tip-type="{{tipType}}">
				<l-input id="goodsName" value="{{search.goodsName}}" hide-label="{{true}}" show-row="{{false}}"
					clear="{{true}}" placeholder="请输入商品名称" placeholder-style="placeholder-style-class" />
			</l-form-item>
			<l-form-item label="类别id:" name="categoryId" l-form-item-class="l-form-item-hidden-class">
				<l-input id="categoryId" value="{{search.categoryId}}" hide-label="{{true}}" show-row="{{false}}" />
			</l-form-item>
			<l-form-item label="类别:" name="categoryName" catch:tap="changeCate">
				<l-input id="categoryName" disabled="{{true}}" value="{{search.categoryName}}" hide-label="{{true}}"
					show-row="{{false}}" placeholder="请选择类别" />
			</l-form-item>
			<l-form-item label="状态:" name="status">
				<l-radio-group current="{{currentStatus}}" id="status" placement="row" catch:linchange="changeStatus">
					<l-radio wx:for="{{statusArr}}" wx:key="id" key="{{index}}">{{item.name}}</l-radio>
				</l-radio-group>
			</l-form-item>
			<view slot="submit">
				<l-button bg-color="#FA6869">搜索</l-button>
			</view>
			<view slot="reset">
				<l-button type="default" plain="{{true}}" l-class="l-form-btn-submit-class">重置</l-button>
			</view>
		</l-form>
</l-arc-popup>

**Comment by manongpei** [comment]
[代码.txt](https://github.com/TaleLin/lin-ui/files/5706580/default.txt)

**Comment by manongpei** [comment]
这边是用的 iPhone se 测试出现问题、iPhone xs 也不可以，可以给看看吗？有点急。

**Comment by manongpei** [comment]
> [，] iphone xr =，]

我能看看你测试的代码吗

**Comment by manongpei** [comment]
direction: top

**Comment by manongpei** [comment]
direction:top 试了试不可以。

**Comment by manongpei** [comment]
direction:top 试了试不可以。
direction:bottom 没问题。

**Comment by murongg** [comment]
> > [，] iphone xr =，]
> 
> 我能看看你测试的代码吗

我使用的是你给的测试代码

**Comment by manongpei** [comment]
> [，] iphone xr =，]



> > > [，] iphone xr =，]
> > 
> > 
> > 我能看看你测试的代码吗
> 
> 我使用的是你给的测试代码

direction:top 试了试不可以。
direction:bottom 没问题。
你那边是这样吗？

**Comment by murongg** [comment]
> > [，] iphone xr =，]
> 
> > > > [，] iphone xr =，]
> > > 
> > > 
> > > 我能看看你测试的代码吗
> > 
> > 
> > 我使用的是你给的测试代码
> 
> direction:top 试了试不可以。
> direction:bottom 没问题。
> 你那边是这样吗？

![image](https://user-images.githubusercontent.com/38655613/102442226-db94d600-405e-11eb-94fb-f02edf90de94.png)
iphone xr 测试的

**Comment by manongpei** [comment]
> > > [，] iphone xr =，]
> > 
> > 
> > > > > [，] iphone xr =，]
> > > > 
> > > > 
> > > > 我能看看你测试的代码吗
> > > 
> > > 
> > > 我使用的是你给的测试代码
> > 
> > 
> > direction:top 试了试不可以。
> > direction:bottom 没问题。
> > 你那边是这样吗？
> 
> ![image](https://user-images.githubusercontent.com/38655613/102442226-db94d600-405e-11eb-94fb-f02edf90de94.png)
> iphone xr 测试的

测试的新情况，你看下。
[arc_popup.docx](https://github.com/TaleLin/lin-ui/files/5707766/arc_popup.docx)

**Comment by murongg** [comment]
@manongpei 也就是说目前插槽内部的元素必须与 arc-popup 组件的 `show` 属性同时显示隐藏才会解决问题吗

**Comment by manongpei** [comment]
> @manongpei 也就是说目前插槽内部的元素必须与 arc-popup 组件的 `show` 属性同时显示隐藏才会解决问题吗

是的。

**Comment by manongpei** [comment]
看看可以给个解答呗

**Comment by murongg** [comment]
@manongpei 您先采用您自己的临时方案解决一下，我们会尽快解决此问题

**Comment by murongg** [comment]
抱歉，我已经试了多数场景，仍然无法复现此问题，您可不可以提供微信官方的代码片段供我们测试，可以点这里查看[微信小程序代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)如何创建

**Comment by beibeiaiwuhao** [comment]
我也遇见了你这样的情况，在popup使用top的时候，里面添加input，无法弹出键盘输入，按照你给的例子可以解决这个问题，但是不知道这个属于什么问题？现在有解决办法吗？
