### ISSUE TITLE
新手，求解释，点击操作菜单的子菜单，success函数不返回任何值

### ISSUE THREAD

**Issue by Tesla-colder** [TaleLin/lin-ui#1177]
![屏幕截图 2020-12-17 094237](https://user-images.githubusercontent.com/63287116/102427644-b8f9c180-404c-11eb-8a92-1d7dd14cf566.jpg)
引用ui后无法使用该格式   bind:lintap="showActionSheet"  触发事件
且调用showActionSheet组件后success函数无返回值

**Comment by juzi214032** [comment]
直接打印 `res`，不要打印 `res.data`
