### ISSUE TITLE
开发者工具基础版本库2.14.1运行example目录示例项目会报错

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-ui#1182]
**LinUI版本（必填）：**
0.8.13

**设备（必填）：**
开发者工具

**基础库版本（必填）：**
2.14.1

**UI问题，请附上截图**

![image](https://user-images.githubusercontent.com/49727104/102715671-0064a400-4312-11eb-9841-bfcbad2a4924.png)

**重现步骤，必要时请提供代码片段链接**

切换开发者工具的基础版本库，低于2.14.1没问题。

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/102715832-f000f900-4312-11eb-8ca5-b4da5a1c3551.png)
我这边 windows 测试没问题，是用的mac吗

**Comment by ChenJinchuang** [comment]
> ![image](https://user-images.githubusercontent.com/38206169/102715832-f000f900-4312-11eb-8ca5-b4da5a1c3551.png)
> 我这边 windows 测试没问题，是用的mac吗

我是在mac下出现的问题。群里有个win的出现这个问题。可能还和开发者工具版本有关？我是最新版

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/102735699-114aff00-437e-11eb-973f-c3d69c0bdb96.png)
我是这个版本

**Comment by juzi214032** [comment]
@murongg  木荣你试试呢

**Comment by ChenJinchuang** [comment]
> ![image](https://user-images.githubusercontent.com/38206169/102735699-114aff00-437e-11eb-973f-c3d69c0bdb96.png)
> 我是这个版本

我也是这个版本

**Comment by juzi214032** [comment]
重新拉下代码 新建一个项目试试呢 开发者工具经常会出莫名其妙的问题

**Comment by ChenJinchuang** [comment]
> 重新拉下代码 新建一个项目试试呢 开发者工具经常会出莫名其妙的问题

代码是单独重新拉的。clone后直接导入example未作改动。

重启开发者工具无效。

该问题在群里见过几次，复现不了也无所谓，知道有这个情况即可

**Comment by ChenJinchuang** [comment]
勾选“增强编译”后，最新基础库版本也正常。
