### ISSUE TITLE
ImagePicker某些时候显示不正常

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1183]
**LinUI版本（必填）：0.8.13

**设备（必填）：Android

**基础库版本（必填）：2.12.2

**UI问题，请附上截图**
如图：https://s3.ax1x.com/2020/12/21/rdW6te.png

**重现步骤，必要时请提供代码片段链接**
实际项目中要复杂一些，下面是是我精简以后的wxml代码，也能复现问题，外面有两层view容器，两层容器使用了padding，结果会导致错行。本来一行应该3个，结果只显示了2个，第三个元素被挤下去了。
分析发现是grid组件的问题，grid组件是通过min-width配合百分比来分配的宽度，实测改为width就正常了，不清楚为什么小程序使用min-width和百分比的时候，实际width要比min-width大一点点，导致每一行的最后一个被挤在下一行了。

```
<view style="display:block;padding:0 30rpx">
  <view style="padding:30rpx">
    <l-image-picker id="photos" urls="{{photos}}" size-type="compressed" bind:linchange="onAddPhoto"
      bind:linremove="onRemovePhoto" />
  </view>
</view>
```

**Comment by KuoKongQingYun** [comment]
另外，貌似ImagePicker的cells属性被弃用了？
文档里说 url字符串数组用 urls，对象数组用cells。实测 字符串数组 和 对象数组 都是用urls，cells没用

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
目前 cells 和 urls 均可生效，urls 优先级高于 cells

**Comment by juzi214032** [comment]
样式显示问题也已修复
