### ISSUE TITLE
Calendar 日历组件 iPhone12机型上，底部适配问题

### ISSUE THREAD

**Issue by LeeSamFong** [TaleLin/lin-ui#1188]
**Feature 名称：**
Calendar 日历组件 iPhone12机型上，底部适配问题

![IMG_1303-2](https://user-images.githubusercontent.com/47028881/102741634-e2d52000-438d-11eb-835e-45f2d1fe15d0.PNG)

**Comment by murongg** [comment]
我们将在下个版本修复此问题

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
