### ISSUE TITLE
npm安装之后无法构建出组件

### ISSUE THREAD

**Issue by niubx** [TaleLin/lin-ui#1189]
**设备型号：** （与此无关）

**LinUI 版本：** ^0.9.0

**微信小程序基础库版本：** 2.14.1

**问题描述及重现步骤：** 通过npm方式安装最新的0.9.0版本linui后，再使用构建工具无法构建出组件，构建出的文件与github代码库中dist文件下内容相同，但 miniprogram_npm/lin-ui 里面本应构建出组件的
**相关截图**：
![image](https://user-images.githubusercontent.com/47147939/102771405-d0280e80-43c0-11eb-9ec4-e22a03fba475.png)
![image](https://user-images.githubusercontent.com/47147939/102771638-36149600-43c1-11eb-84fe-d5ec32ffd209.png)
![image](https://user-images.githubusercontent.com/47147939/102771799-7aa03180-43c1-11eb-9a86-36d217d5e6be.png)

**Comment by murongg** [comment]
最新版本有bug，今晚会修复，您可以尝试安装其0.8.13版本

**Comment by juzi214032** [comment]
0.9.1 该问题已修复
