### ISSUE TITLE
0.9.1版本构建npm后编译报错，calendar组件中未找到“l-toast”

### ISSUE THREAD

**Issue by Eumenides1** [TaleLin/lin-ui#1193]
**微信小程序开发工具 **

**LinUI 版本：0.9.1**

**微信小程序基础库版本：2.14.1**

**问题描述及重现步骤：*构建npm后编译报错，calendar组件中未找到“l-toast”*

**相关截图**：
![image](https://user-images.githubusercontent.com/42667189/102837212-5d597a80-4436-11eb-9212-68dff4490df3.png)

**Comment by murongg** [comment]
请参考此 issue， https://github.com/TaleLin/lin-ui/issues/1139

**Comment by murongg** [comment]
具多人反应，确实有这个问题，

**Comment by murongg** [comment]
已修复
