### ISSUE TITLE
tabbar缺少点击事件和动画展示功能

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1206]
例如在今日头条app中，tabbar点击一下可以切换，再次点击当前tabbar图标触发刷新事件，同时tabbar图标显示相应刷新动画。我看了官方文档，没有发现tabbar点击事件，也没有动画展示功能。请问可以实现这两个功能吗？

**Comment by juzi214032** [comment]
感谢反馈，点击事件会支持，图标动画的话暂时不支持，因为在小程序端没有较好的图标动画方案

**Comment by juzi214032** [comment]
目前 tabbar 是支持 lintap 点击事件的，请使用 `mut-bind:lintap` 监听该事件

**Comment by a516117636** [comment]
> 目前 tabbar 是支持 lintap 点击事件的，请使用 `mut-bind:lintap` 监听该事件

我没在web文档里发现mut-bind:lintap，另外切换标签页的时候不会触发这个mut-bind:lintap吧，切换标签页后再次点击才会触发mut-bind:lintap对吗？还有就是tabbar支持双击事件吗？比如要实现双击刷新功能。

**Comment by juzi214032** [comment]
文档上是遗漏了，会尽快补上，代码里直接使用`mut-bind:lintap`即可
不管是点击还是切换标签页都会触发`mut-bind:lintap`
双击事件会在`0.9.3`版本更新

**Comment by juzi214032** [comment]
双击事件比较复杂，暂时不会支持，如果要做刷新，可以自己根据 lintap 事件做下定制，可以实现相应功能
