### ISSUE TITLE
collapse点击无法展开

### ISSUE THREAD

**Issue by dh13899396662** [TaleLin/lin-ui#1208]
**设备型号：开发者工具 

**LinUI 版本：0.9.2

**微信小程序基础库版本：2.8.1

**问题描述及重现步骤：1.按照文档步骤npm install lin-ui 2.注册collapse以及collapse-item组件 3.复制官方文档实例代码 4.点击无效，折叠面板无法展开

**相关截图**：
![image](https://user-images.githubusercontent.com/32675044/103059510-4bb3d680-45e0-11eb-9ec7-e7f64ad4bf70.png)
![image](https://user-images.githubusercontent.com/32675044/103059539-59695c00-45e0-11eb-84d9-c0219406e1e8.png)

**Comment by juzi214032** [comment]
看一下 console 有报错吗

**Comment by juzi214032** [comment]
Lin UI 内部使用 `mut-bind` 监听事件，小程序基础库自`2.8.2` 开始支持此特性，所以调整到 2.8.2 以上即可
