### ISSUE TITLE
组件是否适配小程序评测

### ISSUE THREAD

**Issue by Mr-houzi** [TaleLin/lin-ui#1219]
**Feature 名称：** 组件是否适配小程序评测

**简要描述：** 组件是否适配小程序评测

**使用场景：** 组件在微信提供的小程序评测中因部分问题拉低跑分，致使小程序在性能评测方面无法达到优秀

**其他组件库或类似功能的截图：**
![微信截图_20201227175153](https://user-images.githubusercontent.com/26339918/103168288-b5481500-486c-11eb-980c-b3db421eec6c.png)

**Comment by juzi214032** [comment]
除了 Segment 还有其他组件吗，这个我们会进行优化

**Comment by Mr-houzi** [comment]
> 除了 Segment 还有其他组件吗，这个我们会进行优化

程序暂时主要用了 Segment 组件

**Comment by ElanYoung** [comment]
![image](https://user-images.githubusercontent.com/39727435/103746880-afcf9500-4ff9-11eb-898d-c26ae055c365.png)
还有这个

**Comment by juzi214032** [comment]
@ElanYoung  用最新的基础库版本和最新版本的开发者工具也会有这个问题吗

**Comment by ElanYoung** [comment]
> @ElanYoung 用最新的基础库版本和最新版本的开发者工具也会有这个问题吗

我刚刚试了下 最新的基础库版本和最新版本的开发者工具没有这个问题咯

**Comment by juzi214032** [comment]
最新版本开发者工具和基础库版本已无该问题，关闭 issue
