### ISSUE TITLE
使用l-image-picker时，编译报错，提示add.png路径问题

### ISSUE THREAD

**Issue by changmingdev** [TaleLin/lin-ui#1230]
**设备型号：iOS

**LinUI 版本：0.9.2

**微信小程序基础库版本：2.13.1

**问题描述及重现步骤：使用l-image-picker时，编译报错，检查路径也没问题啊，报错路径可以找到add.png

**相关截图**：
<img width="738" alt="截屏2020-12-28 23 05 14" src="https://user-images.githubusercontent.com/73325623/103254063-d751ac80-49be-11eb-9d7c-cb615d7f5976.png">

<img width="738" alt="截屏2020-12-28 23 05 14" src="https://user-images.githubusercontent.com/73325623/103254073-e3d60500-49be-11eb-8e2e-4e6518baabb4.png">

<img width="328" alt="截屏2020-12-28 23 05 56" src="https://user-images.githubusercontent.com/73325623/103254085-ee909a00-49be-11eb-84b3-5a1b3a4b5a52.png">

<img width="825" alt="截屏2020-12-29 10 20 39" src="https://user-images.githubusercontent.com/73325623/103254263-94dc9f80-49bf-11eb-92d1-db5a3165e8a3.png">

**Comment by murongg** [comment]
请退出开发者工具，重新 npm 构建试一下，我这里没有复现此问题

**Comment by changmingdev** [comment]
重构了还是这样，是不是因为我用了云函数开发，根路径从miniprogram开始了
"usingComponents": {
    "l-image-picker": "/miniprogram_npm/lin-ui/image-picker/index"
  }

<img width="200" alt="截屏2021-01-13 16 33 15" src="https://user-images.githubusercontent.com/73325623/104426732-46cdbb80-55bd-11eb-9af8-b4a5221b7b5b.png">

**Comment by juzi214032** [comment]
基础库版本调到最高试一下
