### ISSUE TITLE
复选框组件 设置 placement="right" 后 按钮的右外边距默认样式依然存在，影响页面布局

### ISSUE THREAD

**Issue by niubx** [TaleLin/lin-ui#1231]
**设备型号：** 和设备型号无关

**LinUI 版本：** 0.9.0

**微信小程序基础库版本：** 2.14.1

**问题描述及重现步骤：** 
在使用 复选框组件 时，若将 复选框组件属性中的 placement 属性设置为 right，按钮默认的样式 margin-right: 20rpx; 依然存在并无法通过设置 复选框组件外部样式类 改变，因此和页面的整体布局产生冲突。
希望修改为 将 placement 设置为 right 后该右外边距的默认数值会自动归零或可以自行调整。
 
**相关截图**：
![image](https://user-images.githubusercontent.com/47147939/103266558-d0409380-49ea-11eb-9423-d12bae0a68ac.png)
![image](https://user-images.githubusercontent.com/47147939/103267402-5f9a7680-49ec-11eb-8cd6-b75ca8ce8e0d.png)
![image](https://user-images.githubusercontent.com/47147939/103266970-afc50900-49eb-11eb-8ead-7ba1f1b8d04a.png)

**Comment by juzi214032** [comment]
感谢反馈，我们会修复这个问题并添加相应外部样式类

**Comment by niubx** [comment]
> 感谢反馈，我们会修复这个问题并添加相应外部样式类

辛苦啦哈哈！新年快乐！

**Comment by juzi214032** [comment]
> > 感谢反馈，我们会修复这个问题并添加相应外部样式类
> 
> 辛苦啦哈哈！新年快乐！

新年快乐！:smile:

**Comment by juzi214032** [comment]
0.9.4 版本已修复该问题
