### ISSUE TITLE
npm下载包不全

### ISSUE THREAD

**Issue by czj6** [TaleLin/lin-ui#1237]
**设备型号：**

**LinUI 版本：**

**微信小程序基础库版本：**

**问题描述及重现步骤：**

**相关截图**：

**Comment by murongg** [comment]
请详细描述您的问题

**Comment by czj6** [comment]
用npm install的包不全，连基本的button都缺失了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "木荣"<notifications@github.com&gt;; 
发送时间: 2020年12月31日(星期四) 中午1:51
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "陈志君"<673330108@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] npm下载包不全 (#1237)





 
请详细描述您的问题

**Comment by murongg** [comment]
请提供一下错误代码

**Comment by czj6** [comment]
好像没错误代码，抱歉我重新试试
