### ISSUE TITLE
form-item组件校验规则required的label之前的‘*’字符样式如何修改，或者设置不显示

### ISSUE THREAD

**Issue by zst-steven** [TaleLin/lin-ui#1238]
form-item组件校验规则required的label之前的‘*’字符样式如何修改，或者设置不显示？
这个源代码中的样式，尝试用外部样式覆盖，但是不起作用。

.form-item-container .label-text-required::before {
    display: inline-block;
    margin-right: 4px;
    color: #f5222d;
    font-family: SimSun,sans-serif;
    content: '*';
}

**Comment by juzi214032** [comment]
使用 `l-form-label-class::before`  的 content 属性修改

**Comment by juzi214032** [comment]
外部样式类中这样写
```
content:"" !important;
```
