### ISSUE TITLE
我想在Form里的提交旁边增加自定义按钮咋办?希望新增slot

### ISSUE THREAD

**Issue by KuoKongQingYun** [TaleLin/lin-ui#1241]
**Feature 名称：** 希望lin-ui的form能自定义其它按钮

**简要描述：** 现在form就两个slot，一个reset一个submit，希望新增一个other（或者其它名字其它方式也行）

**使用场景：** 比如我现在有个登录表单，我想在登录按钮旁边放一个注册按钮，但是我把注册按钮加入到submit的slot里以后，点这个注册，也会触发表单提交，我使用catchtap也没用，原因是submit的slot使用了capture-bind，所以加入submit这个slot的任何内容被点击都一定会触发表单提交。我尝试把注册按钮放到submit这个slot之外，但那样又没办法和登录按钮放在同一行了，因为不属于同一个view，除非使用绝对定位，那样也太惨了。

**其他组件库或类似功能的截图：**

**Comment by juzi214032** [comment]
感谢反馈，我们会对这个场景进行优化

**Comment by juzi214032** [comment]
0.9.4 版本已增加相关 slot
