### ISSUE TITLE
SlideView组件无法自动关闭

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1242]
想要实现如下效果：SlideView组件左滑打开菜单后，点击非菜单部分就自动关闭菜单。
按照文档中的说明，设置了close="{{true}}"后无任何效果。我不知道是不是我对这个属性的理解有误。

**Comment by juzi214032** [comment]
在`left`这个slot上监听 bindtap 事件，然后在事件代码中设置 close 为 true
