### ISSUE TITLE
更新最新版1.03.2012120 Stable开发者工具 状态展示页的图片报错

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-ui#1247]
**设备型号：**开发者工具

**LinUI 版本：**0.9.1

**微信小程序基础库版本：**2.14.1

**问题描述及重现步骤：**
更新1.03.2012120 Stable版本的开发者工具（2021.01.04） 报错
回退1.03.2011120 Stable版本（2020.11.26）则没报错

**相关截图**：
![image](https://user-images.githubusercontent.com/39727435/103736449-311e2c00-4fe8-11eb-8310-40b08d07023a.png)

**Comment by Bruce-zxy** [comment]
same

![image](https://user-images.githubusercontent.com/22904758/103836940-7a907900-50c5-11eb-9ae1-e3fcd680e2f1.png)

**Comment by murongg** [comment]
请将 lin-ui 升级到 0.9.3 版本

**Comment by ElanYoung** [comment]
> 请将 lin-ui 升级到 0.9.3 版本

文档中最新版本不就只有0.9.1嘛

**Comment by murongg** [comment]
@ElanYoung 不好意思，手抖打错了，最新版本是0.9.2
