### ISSUE TITLE
通告栏不滚动

### ISSUE THREAD

**Issue by evanwu66** [TaleLin/lin-ui#1248]
通过请求接口获取通告内容文字放入，它不会走动，

直接写死在页面正常走动

**Comment by juzi214032** [comment]
感谢反馈，这个问题会在`0.9.3`修复

**Comment by juzi214032** [comment]
0.9.4 已增加 linFlush 函数用于刷新组件
开放函数使用方法详见：https://doc.mini.talelin.com/start/open-function.html
