### ISSUE TITLE
tabs组件的bind:linchange无效

### ISSUE THREAD

**Issue by dustq** [TaleLin/lin-ui#1249]
`
<view>
  <l-tabs active-key="{{activeKey}}" active-color="#1890ff" bind:linchange="changeTabs">
    <l-tabpanel tab="我对企业的评价" key="1" slot="1">
      <view class="tab-content">我对企业的评价</view>
    </l-tabpanel>
    <l-tabpanel tab="企业对我的评价" key="2" slot="2">
      <view class="tab-content">企业对我的评价</view>
    </l-tabpanel>
  </l-tabs>
</view>
`

**Comment by juzi214032** [comment]
您好，这边没有复现问题，可以提供一下[微信代码片段](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)

**Comment by dustq** [comment]
在小程序编辑器不可以点击，手机上是可以点击的

**Comment by juzi214032** [comment]
那建议重装一下微信开发者工具

**Comment by dustq** [comment]
好的，谢谢。
