### ISSUE TITLE
在微信小程序开发工具上运行image-clipper组件时报错

### ISSUE THREAD

**Issue by jerryliushilin** [TaleLin/lin-ui#1255]
错误如下：

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/photo.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/rotate-along.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/rotate-inverse.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/sure.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/close.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

之前使用挺好的，就是这两天更新开发工具后就报错了

**Comment by murongg** [comment]
请使用标准 issue 提交模板提交 issue：https://github.com/TaleLin/lin-ui/issues/new/choose
