### ISSUE TITLE
Input组件disabled=true的时候，对弹出dialog组件的按钮区域产生遮挡，导致按钮点击无效。

### ISSUE THREAD

**Issue by zst-steven** [TaleLin/lin-ui#1256]
当input组件disabled=true的时候，对弹出dialog组件的按钮区域产生遮挡，导致按钮点击无效。
看了看源代码的css，应该是input组件disabled=true的mask遮罩z-index:999，高于dialog组件popup的z-index:777

**相关截图**：
<img width="353" alt="error_shot" src="https://user-images.githubusercontent.com/37972452/104193936-9eecac80-545b-11eb-8ab9-84a8d49177fa.png">

**Comment by murongg** [comment]
请使用规范的 issue 提交模板：https://github.com/TaleLin/lin-ui/issues/new/choose
