### ISSUE TITLE
导航栏 TabBar，定义两个按钮或者多个，只显示第一个按钮的图片

### ISSUE THREAD

**Issue by dongdianxinNK** [TaleLin/lin-ui#1259]
list:[
      {
          pagePath:"largeclass",
          text:"首页1",
          unselectedIconPath:"img/bq.png",
          selectedIconPath:"img/mx.png"
      },
      {
        pagePath:"../labelsclass/labelsclass",
        text:"首页2",
        unselectedIconPath:"img/bq1.png",
        selectedIconPath:"img/mx1.png"
    },      
  ]
===================================
不管list里面创建几个，永远只显示第一个按钮的图片，好几个小伙伴试了试都这样

![捕获](https://user-images.githubusercontent.com/41938199/104416938-94dbc280-55af-11eb-9962-29a48cdee921.PNG)
![捕获1](https://user-images.githubusercontent.com/41938199/104416941-95745900-55af-11eb-9c31-2595376a3cf7.PNG)
![捕获1](https://user-images.githubusercontent.com/41938199/104416943-96a58600-55af-11eb-8ad7-bc1ccb73a2bd.PNG)
![捕获](https://user-images.githubusercontent.com/41938199/104416946-96a58600-55af-11eb-8d8c-ace57f32af14.PNG)

**Comment by juzi214032** [comment]
`unselectedIconPath`改为`iconPath`，这个是文档错误，会尽快修正
