### ISSUE TITLE
Textarea部分机型下显示有问题

### ISSUE THREAD

**Issue by MinCpopo** [TaleLin/lin-ui#1260]
**设备型号：**

**LinUI 版本：**

**微信小程序基础库版本：**

**问题描述及重现步骤：**
iphone8机型下Textarea显示宽度出现问题
**相关截图**：

![image](https://user-images.githubusercontent.com/42403875/104567843-3d5e5500-568a-11eb-9d5c-83a3197a3ccc.png)

**Comment by murongg** [comment]
抱歉，未复现您说的问题，可否提供可复现的代码片段
