### ISSUE TITLE
album组件，urls属性对应数组长度为1时不显示

### ISSUE THREAD

**Issue by changmingdev** [TaleLin/lin-ui#1263]
**设备型号：iOS

**LinUI 版本：0.9.2

**微信小程序基础库版本：2.14.3

**问题描述及重现步骤：使用album组件时，urls属性对应数组长度为1时，album组件不显示,数组长度为2及以上可以正常显示
主要代码：
data: {
    urls11: ['https://656e-env-9eb476-1258886794.tcb.qcloud.la/images/album/photo-3.jpg?sign=d71bb290f896e14bb800d0fb807f6764&t=1590025427'
  ]
}

<l-album urls='{{urls11}}'></l-album>

**相关截图**：

**Comment by murongg** [comment]
抱歉，未复现您说的问题，可否提供可复现的代码片段

**Comment by cnfi** [comment]
> 抱歉，未复现您说的问题，可否提供可复现的代码片段

预览的图片数量为1，开启预览，手机扫一下，在手机里看，就是空白。大于1张图片的，都能正常显示
