### ISSUE TITLE
微信开发工具使用LIN-UI image-clipper组件时在PC端提示错误信息，在手机端可以正常使用 #1258

### ISSUE THREAD

**Issue by jerryliushilin** [TaleLin/lin-ui#1264]
**设备型号：*PC端*

**LinUI 版本：*0.9.2*

**微信小程序基础库版本：*2.14.4*

**问题描述及重现步骤：*使用微信最新的开发工具image-clipper组件报错,在移动端使用正常，PC段提示错误信息，组件并不能使用*

**相关截图**：
错误信息如下:
[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/photo.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/rotate-along.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/rotate-inverse.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/sure.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 

[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/image-clipper/images/close.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)

**Comment by murongg** [comment]
请问您是采用 npm 安装的方式还是复制 dist 目录安装的方式

**Comment by jerryliushilin** [comment]
NPM的方式安装的LIN UI

**Comment by murongg** [comment]
调整下基础库版本试试呢，我这里没有复现出来

**Comment by jerryliushilin** [comment]
我基础库用的最新的是2.14.4版本的，还是报错，组件下面的一排操作按钮也不显示

**Comment by murongg** [comment]
我自己测试了 2.14.4 与 2.14.3 基础库都没问题

**Comment by jerryliushilin** [comment]
我把代码片段共享您试试，我就是新开的项目，就放了一个剪裁组件

**Comment by jerryliushilin** [comment]
https://developers.weixin.qq.com/s/Mqpqqrmr7xnP
共享的代码片段您试试，我这边还是报错

**Comment by murongg** [comment]
已发现问题，正在尝试解决

**Comment by jerryliushilin** [comment]
好的，谢谢

**Comment by murongg** [comment]
经过测试发现可能是微信开发者工具的问题，需要再观察一段时间

**Comment by jerryliushilin** [comment]
好的，是需要等到微信开发工具版本在升级吗？

**Comment by murongg** [comment]
看看微信官方后续有没有什么修复版本吧

**Comment by jerryliushilin** [comment]
好的，谢谢了，在移动端可以正常使用，就是PC端不行，调试不太方便。

**Comment by jerryliushilin** [comment]
我电脑操作系统是WIN10，64位专业版，开发工具版本号是1.03.2101150

**Comment by juzi214032** [comment]
**确认问题为微信开发者工具的问题，回退到 1.03.2011120 Stable 版本可正常使用**

1.03.2011120 Stable 下载地址：
- [Windows](https://dldir1.qq.com/WechatWebDev/release/p-ae42ee2cde4d42ee80ac60b35f183a99/wechat_devtools_1.03.2011120_x64.exe)
- [Mac OS](https://dldir1.qq.com/WechatWebDev/release/p-ae42ee2cde4d42ee80ac60b35f183a99/wechat_devtools_1.03.2011120.dmg)
