### ISSUE TITLE
在taro中使用选项卡segment的时候segment item的key没有用，点击后activeKey为空

### ISSUE THREAD

**Issue by ckdroid** [TaleLin/lin-ui#1267]
**设备型号：**
微信开发者工具 稳定版 Stable Build (1.03.2012120)

**LinUI 版本：**
^0.9.2

**微信小程序基础库版本：**
2.14.3

**问题描述及重现步骤：**
在taro中使用选项卡segment的时候segment item的key没有用，点击后activeKey为空

```
  changeTabs = (e) => {
    console.log(e)
  }

  render() {
    return (
      <l-segment activeKey="one" onLinchange={this.changeTabs}>
        <l-segment-item tab="客厅" key="one" />
        <l-segment-item tab="卧室" key="two" />
        <l-segment-item tab="厨房" key="three" />
    </l-segment>   
    )
  }
```
**相关截图**：
![123](https://user-images.githubusercontent.com/8552889/104730867-c2726880-5775-11eb-8cd3-8383dbe262e8.PNG)
![122](https://user-images.githubusercontent.com/8552889/104733021-0a46bf00-5779-11eb-91b6-ff3b0901d155.PNG)

**Comment by juzi214032** [comment]
抱歉 lin-ui 不对第三方框架做适配，这应该是 taro 的问题，可以给他们提 issue 解决

**Comment by puzzle9** [comment]
最后情况如何 我也遇到了
