### ISSUE TITLE
message组件，外部样式类l-image-class

### ISSUE THREAD

**Issue by TXxyin** [TaleLin/lin-ui#1270]
**设备型号：**

**LinUI 版本：**
0.9.2
**微信小程序基础库版本：**

**问题描述及重现步骤：**
wxml中写的是l-class-image，js中写的是l-image-class，文档里写的是l-image-class。名称不一致导致更改自定义图片样式无效。
**相关截图**：

**Comment by juzi214032** [comment]
感觉反馈，0.9.3 版本会修复此问题

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
