### ISSUE TITLE
在弹出层 arc-popup或popup中如何使用瀑布流 waterflow？

### ISSUE THREAD

**Issue by nivyan2020** [TaleLin/lin-ui#1274]
设备型号：

LinUI 版本：
0.9.2
微信小程序基础库版本：

问题描述及重现步骤：
在弹出层 arc-popup或popup中如何使用瀑布流 waterflow？出现所有数据显示在左边，右边没有数据显示
相关截图：

**Comment by murongg** [comment]
可否提供可复现代码供我们测试
