### ISSUE TITLE
增加：右上角带×的popup

### ISSUE THREAD

**Issue by CrossLee** [TaleLin/lin-ui#1276]
**Feature 名称：增加【右上角带×的popup】**

**简要描述：增加【右上角带×的popup】**

**使用场景：需要主动点击×才能关闭的popup**

**其他组件库或类似功能的截图：
![image](https://user-images.githubusercontent.com/4584905/105442741-3d231280-5ca5-11eb-9022-bb985c96d6f5.png)

**

**Comment by juzi214032** [comment]
popup 的所有内容都是通过slot传入的，如果需要关闭按钮，自己写一个就好。

组件内部无法做到添加一个关闭按钮
