### ISSUE TITLE
PC小程序白屏

### ISSUE THREAD

**Issue by iblackly** [TaleLin/lin-ui#1277]
**设备型号：**
PC
**LinUI 版本：**
0.9.2
**微信小程序基础库版本：**
2.14.3
**问题描述及重现步骤：**
PC 微信：3.1.0.67(我试了其他版本也这样)，
只要引入LinUi哪怕不引用组件，上传为体验版后，PC小程序打开就是白屏！
其他设备都正常，模拟器也正常！
我试了手动复制LinUi，也是如此！
我等下去微信那边也反馈下！

https://developers.weixin.qq.com/s/mQC7rxm27Xnc

**相关截图**：
![bp](https://user-images.githubusercontent.com/3168355/105445080-08fe2080-5caa-11eb-8682-277b262bf748.jpg)

**Comment by juzi214032** [comment]
控制台有报错信息吗

**Comment by iblackly** [comment]
> 控制台有报错信息吗

没有报错信息

**Comment by juzi214032** [comment]
微信开发者工具：1.05.2101181
操作系统：Windows 10 19042.685
使用你提供的代码片段，没有复现你说的问题，建议重装你的微信开发者工具到最新版尝试一下
![image](https://user-images.githubusercontent.com/38206169/105573572-82c10780-5d99-11eb-92c6-6ab10efe0cc7.png)

**Comment by juzi214032** [comment]
这个问题是 lin ui calender 组件使用了 padStart 函数，目前 PC 微信暂不支持这个函数，导致的报错。下个版本会替换掉这个函数。
临时解决办法：删除 miniprogram_npm/lin-ui/calendar 文件夹

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
