### ISSUE TITLE
npm无法更新 lin-ui

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1278]
使用npm update lin-ui命令无法更新lin-ui，一直停留在0.8.13

**Comment by juzi214032** [comment]
package.json 文件内容贴一下呢

**Comment by a516117636** [comment]
{
  "_from": "lin-ui@^0.8.13",
  "_id": "lin-ui@0.8.13",
  "_inBundle": false,
  "_integrity": "sha1-4cyQAQzxR5Jaifgg0UVNLPGlAh8=",
  "_location": "/lin-ui",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "lin-ui@^0.8.13",
    "name": "lin-ui",
    "escapedName": "lin-ui",
    "rawSpec": "^0.8.13",
    "saveSpec": null,
    "fetchSpec": "^0.8.13"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npm.taobao.org/lin-ui/download/lin-ui-0.8.13.tgz",
  "_shasum": "e1cc90010cf147925a89f820d1454d2cf1a5021f",
  "_spec": "lin-ui@^0.8.13",
  "_where": "D:\\Ddisk\\miniDev\\miniprogram",
  "author": {
    "name": "Lin Team"
  },
  "bugs": {
    "url": "https://github.com/TaleLin/lin-ui/issues"
  },
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "A high quality UI components library with MiniProgram",
  "devDependencies": {
    "@commitlint/cli": "^8.3.5",
    "@commitlint/config-conventional": "^8.3.4",
    "child_process": "^1.0.2",
    "del": "^5.0.0",
    "eslint": "^7.2.0",
    "eslint-plugin-import": "^2.21.2",
    "eslint-plugin-promise": "^4.2.1",
    "gulp": "^4.0.2",
    "gulp-clean-css": "^3.9.3",
    "gulp-htmlmin": "^5.0.1",
    "gulp-imagemin": "^7.1.0",
    "gulp-jsonminify": "^1.1.0",
    "gulp-less": "^4.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-uglify-es": "^2.0.0",
    "gulp-util": "^3.0.8",
    "husky": "^4.2.5",
    "jest": "^24.8.0",
    "less": "^3.12.2",
    "lodash": "^4.17.15",
    "miniprogram-simulate": "^1.0.7"
  },
  "directories": {
    "example": "examples"
  },
  "files": [
    "dist"
  ],
  "homepage": "http://doc.mini.talelin.com",
  "license": "MIT",
  "main": "app.js",
  "miniprogram": "dist",
  "name": "lin-ui",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/TaleLin/lin-ui.git"
  },
  "scripts": {
    "build": "gulp -f build/index.js build",
    "changelog": "conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -n .convention-changelog-config.js",
    "dev": "gulp -f build/index.js dev",
    "fix": "eslint . --fix",
    "lint": "eslint .",
    "release": "sh build/release.sh",
    "watch": "gulp -f build/index.js watch"
  },
  "version": "0.8.13"
}

**Comment by juzi214032** [comment]
我是说贴你项目的 package.json 不是 linui 的

**Comment by a516117636** [comment]
`{
  "name": "miniprogram",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vant/weapp": "^1.6.6",
    "lin-ui": "^0.8.13"
  }
}
`

**Comment by juzi214032** [comment]
`^0.8.13`限制了只会更新 patch 版本，所以上不了 0.9.2，手动修改成 0.9.2 再 `npm i` 就可以了

**Comment by a516117636** [comment]
我确定一下哈，是将^0.8.13改成^0.9.2还是0.9.2？然后直接再 npm i lin-ui就行了？

**Comment by juzi214032** [comment]
修改为`^0.9.2`，再执行`npm i`

**Comment by a516117636** [comment]
解决了，谢谢
