### ISSUE TITLE
胶囊栏高级用法bug

### ISSUE THREAD

**Issue by 184177677** [TaleLin/lin-ui#1280]
小程序基础库2.14.4 新建的项目 胶囊栏高级用法按文档例子引入   背景图无法定位到导航栏 而是在页面内容部分置顶定位的 capsule-button-color="white" 属性也没起作用

**Comment by juzi214032** [comment]
麻烦贴个截图 谢谢

**Comment by 184177677** [comment]
没截图  这里我也没找到哪里可以提交图片

**Comment by juzi214032** [comment]
直接在输入框粘贴图片就可以

**Comment by juzi214032** [comment]
您的文字描述我没有太明白 **导航栏** 不知道您是指的哪部分

**Comment by 184177677** [comment]
就是胶囊按钮所在的那个导航栏  关闭了默认的  用你的自定义的 胶囊栏CapsuleBar中的高级用法案例 出现的错误

**Comment by juzi214032** [comment]
不好意思，是文档有一些错误，会尽快修正。
背景图片可以参考这个[代码片段](https://developers.weixin.qq.com/s/yX1BqHmY7vn8)的实现方式。

` capsule-button-color`属性名更改为了`capsule-color`

**Comment by 184177677** [comment]
好的 谢谢：）
