### ISSUE TITLE
按需引入组件l-input 报缺少common/**下js

### ISSUE THREAD

**Issue by dAskyacc** [TaleLin/lin-ui#1281]
**设备型号：**
无关
**LinUI 版本：**
master branch
**微信小程序基础库版本：**
无关
**问题描述及重现步骤：**
- git clone https://https://github.com/TaleLin/lin-ui.git 

- yarn install
- 配置 config component.json input 
- page 引用l-input

**相关截图**：

**Comment by dAskyacc** [comment]
我修改了编译脚本 build/index.js 第19,20行
const result = `{common/*,common/**/*,core/*,behaviors,utils,${componentData()}}`;

解决此问题,但不知道我的解决方式是否正确

**Comment by juzi214032** [comment]
感谢反馈，你的解决方式是正确的，下个版本会修复此问题

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
