### ISSUE TITLE
表单组件使用中，提交表单显示“表单项不存在name”

### ISSUE THREAD

**Issue by Eumenides1** [TaleLin/lin-ui#1282]
**LinUI 版本：0.9.2**

**微信小程序基础库版本：2.14.1**

**问题描述及重现步骤：表单组件，提交表单显示“表单项不存在name”**

**相关截图**：
`<l-form name="form" bind:linsubmit="submit" l-form-btn-class="l-form-btn-class">
            <l-form-item label="第一次核酸检测时间" name="firTime">
                <input  id="firTime" value="{{form.firTime}}"></input>
            </l-form-item>
            <l-form-item label="第一次核酸检测结果" name="firResult">
                <input id="firResult" value="{{form.firResult}}"></input>
            </l-form-item>
            <l-form-item label="第二次核酸检测时间" name="secTime">
                <input id="secTime" value="{{form.secTime}}"></input>
            </l-form-item>
            <l-form-item label="第二次核酸检测结果" name="secResult">
                <input id="secResult" value="{{form.secResult}}"></input>
            </l-form-item>
            <view slot="submit">
                <l-button>更新</l-button>
            </view>
        </l-form>`
`data: {
    userid:null,
    name:null,
    idnum:null,
    form:{
      firTime:'',
      firResult:'',
      secTime:'',
      secResult:'',
    }
  },`

**Comment by Eumenides1** [comment]
![image](https://user-images.githubusercontent.com/42667189/105822889-7f2abc00-5ff7-11eb-8a29-6c6d3a9284c9.png)

**Comment by Eumenides1** [comment]
解决了、、、、智障错误，组件引入错误了

**Comment by Huang-Shijie-SDUWH** [comment]
请问是怎么解决的。。孩子自闭了
