### ISSUE TITLE
dialog 组件，在页面和页面组件分别调用dialog组件，两个会互相影响

### ISSUE THREAD

**Issue by Lin-Kangjing** [TaleLin/lin-ui#1286]
**设备型号：**

**LinUI 版本：0.92**

**微信小程序基础库版本：2.12**

**问题描述及重现步骤：页面使用 js 调用dialog组件（dialog1），页面的子组件使用 wxml（自定义子节点）调用dialog组件（dialog3），使用dialog1的时候，会把dialog2的自定义子节点带上，确认按钮时，会同时调用dialog1，dialog2的回调方法**

**相关截图**：

**Comment by juzi214032** [comment]
这个问题后续会解决，感谢反馈

**Comment by juzi214032** [comment]
0.9.4 版本支持使用[**开放函数**](https://doc.mini.talelin.com/start/open-function.html)解决该问题
