### ISSUE TITLE
九宫格事件经常需要点两次才能触发

### ISSUE THREAD

**Issue by evanwu66** [TaleLin/lin-ui#1291]
**设备型号：iphone 7**

**LinUI 版本：0.9.2**

**微信小程序基础库版本：2.13.2**

**问题描述及重现步骤：九宫格事件经常需要点两次才能触发，在开发工具上正常**

**相关截图**：无

**Comment by evanwu66** [comment]
点击跳转页面，然后右划页面返回，再次点击无法触发事件

**Comment by evanwu66** [comment]
如果手指左划位置在宫格内就会产生这种触发不了的情况

**Comment by juzi214032** [comment]
> 如果手指右划位置在宫格内就会产生这种触发不了的情况

这个是什么意思，方便录个屏说明一下吗

**Comment by evanwu66** [comment]
怎么发录屏给你呀？

录屏也完全体现不了，就是
在九宫格里绑定了一个跳转页面的事件；
第一次点击宫格正常触发事件 并执行了页面跳转，
然后，手指往右划动返回上一页，再次点击宫格无法触发事件；
需要又一次点击才能触发；

**Comment by juzi214032** [comment]
这个问题没有复现，建议打印日志确认一下是事件没有触发还是页面跳转没有生效

这是测试代码片段：
https://developers.weixin.qq.com/s/z4AgFNmK7Mnn

如果还有疑问可上传你的代码片段供我排查
