### ISSUE TITLE
image-picker通过l-item-class改变宫格图片大小的BUG

### ISSUE THREAD

**Issue by joyoak** [TaleLin/lin-ui#1292]
**设备型号：**
安卓
**LinUI 版本：**
0.9.2
**微信小程序基础库版本：**
2.14.3
**问题描述及重现步骤：**
通过l-item-class改变宫格图片大小
`<l-image-picker l-item-class="logo-img-class">
...
</l-image-picker>`
`.logo-img-class{
  width: 120rpx!important;
  height: 120rpx!important;
}`
当选择图片后，宫格大小变为220rpx*220rpx
查看源码
`<image class="{{size === 3? 'img': 'min-img'}}" mode="{{ mode }}" src="{{newOrOld==='old'? item:item.url }}"/>`
改为下面代码后，问题修复
`<image class="{{size === 3? 'img': 'min-img'}} l-item-class" mode="{{ mode }}" src="{{newOrOld==='old'? item:item.url }}"/>`
**相关截图**：

**Comment by juzi214032** [comment]
感谢反馈，0.9.3 会修复这个问题

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
