### ISSUE TITLE
苹果手机上tabbar标签名被横线遮挡 

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1293]
苹果手机上tabbar标签名被横线遮挡 ，如图，图中画横线部分
![1 (2)](https://user-images.githubusercontent.com/17865841/106468524-046f0e80-64d9-11eb-83ef-18963f6d0683.png)

**Comment by juzi214032** [comment]
感谢反馈，0.9.3 会修复这个问题

**Comment by juzi214032** [comment]
0.9.4 版本已修复这个问题
