### ISSUE TITLE
价格Price组件小数部分会被全局设置的字体样式影响

### ISSUE THREAD

**Issue by ctx-ya** [TaleLin/lin-ui#1294]
**简要描述：** 
在app.wxss 中设置了字体样式  价格Price组件的小数部分被影响了
希望可以增加设置小数部分样式的属性

![image](https://user-images.githubusercontent.com/37658940/106582457-f5db3280-657e-11eb-94aa-6df7aeb9c438.png)
![image](https://user-images.githubusercontent.com/37658940/106582466-f7a4f600-657e-11eb-8daf-bb92f2ef400b.png)

**Comment by juzi214032** [comment]
使用 l-decimal-class 覆盖小数部分样式
