### ISSUE TITLE
在list组件 slot="right-section" 中，使用input组件，input（iphone  6s plus）经常点击不到（不聚焦）

### ISSUE THREAD

**Issue by Lin-Kangjing** [TaleLin/lin-ui#1296]
**设备型号：iphone  6s plus**

**LinUI 版本：0.92**

**微信小程序基础库版本：2.12**

**问题描述及重现步骤：**

**相关截图**：
![image](https://user-images.githubusercontent.com/32667898/106695554-cd524780-6615-11eb-9f91-861ad68c5a86.png)

**Comment by juzi214032** [comment]
给 input 加个背景色看一下，是不是 input 触发区域太小了

**Comment by Lin-Kangjing** [comment]
[cid:image001.png@01D6FA23.490F09D0]
在安卓手机上是可以

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 桔子<mailto:notifications@github.com>
发送时间: 2021年2月3日 11:51
收件人: TaleLin/lin-ui<mailto:lin-ui@noreply.github.com>
抄送: LinKangJing<mailto:linkangjing@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] 在list组件 slot="right-section" 中，使用input组件，input（iphone 6s plus）经常点击不到（不聚焦） (#1296)


给 input 加个背景色看一下，是不是 input 触发区域太小了

―

**Comment by juzi214032** [comment]
建议你把 input 设置得大一点，ip6p 屏幕比较小

**Comment by Lin-Kangjing** [comment]
[cid:image001.png@01D6FA24.228C3930]
在安卓手机上是可以


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 桔子<mailto:notifications@github.com>
发送时间: 2021年2月3日 11:58
收件人: TaleLin/lin-ui<mailto:lin-ui@noreply.github.com>
抄送: LinKangJing<mailto:linkangjing@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] 在list组件 slot="right-section" 中，使用input组件，input（iphone 6s plus）经常点击不到（不聚焦） (#1296)


建议你把 input 设置得大一点，ip6p 屏幕比较小

―

**Comment by juzi214032** [comment]
你发的这个图片看不到，安卓手机具体型号是什么呢

**Comment by Lin-Kangjing** [comment]
刚才是给input 设置背景颜色的，安卓用了2台都行，小米10， 荣耀v10。Iphone 6s plus 不行

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 桔子<mailto:notifications@github.com>
发送时间: 2021年2月3日 12:05
收件人: TaleLin/lin-ui<mailto:lin-ui@noreply.github.com>
抄送: LinKangJing<mailto:linkangjing@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [TaleLin/lin-ui] 在list组件 slot="right-section" 中，使用input组件，input（iphone 6s plus）经常点击不到（不聚焦） (#1296)


你发的这个图片看不到，安卓手机具体型号是什么呢

―

**Comment by juzi214032** [comment]
可以提供下代码片段吗，我这边无法定位这个 bug
