### ISSUE TITLE
安卓上机滑动菜单SlideView组件关闭BUG

### ISSUE THREAD

**Issue by 250786898** [TaleLin/lin-ui#1297]
<!--
以下为必读项，不仔细阅读会导致你的 Issue 被关闭：

**设备型号：*小米CC9*

**LinUI 版本：*lin-ui@0.9.2*

**微信小程序基础库版本：*1.14.1*

**问题描述及重现步骤：* 滑动了自动滚回去*

**相关截图**：

**Comment by juzi214032** [comment]
请详细描述
