### ISSUE TITLE
【Bug Report】npm 安装和git下来的源码，组件属性不一样

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#13]
对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。

**Comment by 7insummer** [comment]
马上有人会处理，主要是这几天小程序改了构建规则，昨天有点仓促，非常感谢你！

**Comment by YpchenLove** [comment]
> 对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。

已经收到反馈，现在重新编译上传。感谢反馈！

**Comment by YpchenLove** [comment]
> 对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。

重新测试了一下，线上版本在10点多发了一个alpha.2的版本，这个版本是最新的，控制显示隐藏的属性是show，可以麻烦看下你的package里的版本号，如果是alpha 1 ，那么这个问题已经修复，希望看到后回复一下。再次感谢反馈！

**Comment by YpchenLove** [comment]
> 对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。

最新版本 alpha.2 里已经修复，麻烦看下你的package.json里的版本号，如果你的版本号是alpha 1 ，那么请删除相关依赖，并重新安装即可，希望看到后回复一下。再次感谢反馈！

**Comment by virtualChan** [comment]
> > 对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。
> 
> 已经收到反馈，现在重新编译上传。感谢反馈！

这个组件控制显示和隐藏我是按show还是status？你们文档里写的是status

**Comment by aQingYun** [comment]
这个地方是show属性，文档没更新，感谢反馈

**Comment by YpchenLove** [comment]
> > > 对比了下git下的dist目录和miniprogram_npm目录下的组件源码，比如说说l-dialog组件，在dist目录下，该组件控制显示隐藏是show属性，miniprogram_npm下的该组件，控制显示隐藏的是status。
> > 
> > 
> > 已经收到反馈，现在重新编译上传。感谢反馈！
> 
> 这个组件以后控制显示和隐藏按show还是status？你们文档里写的是status

status 是早先版本的，已经废弃，改用show来控制，文档晚上会重新更新并部署，感谢反馈，带来不便还请谅解！感谢您的支持！！
