### ISSUE TITLE
StatusShow控件加载本地图片失败

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1303]
wxml代码：
`<l-status-show show="{{true}}" type="success"></l-status-show>`
json配置：
`"l-status-show":"/miniprogram_npm/lin-ui/status-show/index"`
报错：
`[渲染层网络层错误] Failed to load local image resource /miniprogram_npm/lin-ui/status-show/image/success.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)`
页面截图：
![11](https://user-images.githubusercontent.com/17865841/107124396-ab3f1a80-68de-11eb-8c89-8cd3069e1d37.png)
我在报错路径下去找success.png，这个文件是存在的。不知道是哪里的错误。。。

**Comment by a516117636** [comment]
开发客户端无效，真机可正常显示。

**Comment by juzi214032** [comment]
参考 #1251
