### ISSUE TITLE
linui的Loadmore组件会被linui的tabbar组件遮挡

### ISSUE THREAD

**Issue by a516117636** [TaleLin/lin-ui#1305]
同时使用linui的tabbar和Loadmore组件，将Loadmore作为一个布局组件的方式引入页面，由于Loadmore组件在页面最底部显示效果，但会被tabbar遮挡住，看不到任何效果。请问官方如何解决该问题？急

**Comment by a516117636** [comment]
最好的办法感觉是给tabbar加一个等高的占位元素

**Comment by juzi214032** [comment]
麻烦给个截图看看效果呢
