### ISSUE TITLE
使用胶囊栏CapsuleBar，固定在底部的输入框弹出时会把胶囊栏顶出屏幕之外

### ISSUE THREAD

**Issue by Huang-Shijie-SDUWH** [TaleLin/lin-ui#1324]
**设备型号：**
Redmi K30 至尊纪念版
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**
2.7.1
**问题描述及重现步骤：**
问题描述：使用胶囊栏CapsuleBar，固定在底部的输入框弹出时会把胶囊栏顶出屏幕之外
重现步骤：在底部设置一个输入框，使用CapsuleBar即可重现
**相关截图**：
![code](https://user-images.githubusercontent.com/57386430/108454242-fbd35200-72a6-11eb-927d-263314cfcab5.png)

![content](https://user-images.githubusercontent.com/57386430/108454158-d3e3ee80-72a6-11eb-9bdc-37859b8c9a39.jpg)

**Comment by juzi214032** [comment]
这是 input 组件的问题，非 CapsuleBar 的问题
