### ISSUE TITLE
在pc版微信中打开lin ui小程序白屏

### ISSUE THREAD

**Issue by Lin-Kangjing** [TaleLin/lin-ui#1326]
![image](https://user-images.githubusercontent.com/32667898/108651535-f111fa80-74fc-11eb-863c-bde3468b3a39.png)

![image](https://user-images.githubusercontent.com/32667898/108651475-c9bb2d80-74fc-11eb-9647-b1f707befaf9.png)

**Comment by juzi214032** [comment]
感谢反馈，会尽快修复

**Comment by juzi214032** [comment]
已修复
