### ISSUE TITLE
0.9.4版本counter组件的输入框，在iPhone12上需要点击两次才能输入

### ISSUE THREAD

**Issue by LeeSamFong** [TaleLin/lin-ui#1327]
**设备型号：**
iPhone 12

**LinUI 版本：**
0.9.4

**微信小程序基础库版本：**
2.13.1

**问题描述及重现步骤：**
0.9.4版本counter组件的输入框，在iPhone12上需要点击两次才能输入

**Comment by juzi214032** [comment]
感谢反馈 但这么暂时没有 iPhone 12，所以这个bug复现不了，欢迎提交 pr 修复
