### ISSUE TITLE
0.9.4 版本 使用popup  只有黑色背景没有弹框

### ISSUE THREAD

**Issue by xuwenfeng93** [TaleLin/lin-ui#1330]
**设备型号：**
微信开发者工具
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**
2.14.4
**问题描述及重现步骤：**
0.9.4 版本 使用popup  只有黑色背景没有弹框
**相关截图**：
![image](https://user-images.githubusercontent.com/48546665/109101090-06875e80-7761-11eb-9828-062c5f49ea5b.png)
![image](https://user-images.githubusercontent.com/48546665/109101105-0f783000-7761-11eb-9106-fb9040bd7636.png)

**Comment by xuwenfeng93** [comment]
![image](https://user-images.githubusercontent.com/48546665/109101452-ad6bfa80-7761-11eb-880c-1d42d319f00e.png)

**Comment by juzi214032** [comment]
popup节点内要写你自己的东西

**Comment by Chenzhiwen7** [comment]
没有解决。有想要的的东西。但是里面白色背景区域没有了
