### ISSUE TITLE
Taro中无法通过bg-color改变按钮背景色

### ISSUE THREAD

**Issue by AKmoex** [TaleLin/lin-ui#1333]
**设备型号：**
iphone6

**LinUI 版本：**
0.9.4

**微信小程序基础库版本：**
2.15.0

**问题描述及重现步骤：**
在taro中使用lin-ui，在使用button组件时，无法通过bg-color属性改变按钮的背景色，button的其他属性都可以正常使用

**相关截图**：
<img width="696" alt="截屏2021-02-25 下午5 41 39" src="https://user-images.githubusercontent.com/63089888/109134385-f0919200-7790-11eb-9db9-bb2bb45f45bb.png">
<img width="274" alt="截屏2021-02-25 下午5 39 29" src="https://user-images.githubusercontent.com/63089888/109134446-01420800-7791-11eb-83d6-5b7dd2b50999.png">

**Comment by juzi214032** [comment]
lin ui 暂不对第三方框架做适配
