### ISSUE TITLE
index-list 滚动列表 Sidebar 最后一位 定位选中出错

### ISSUE THREAD

**Issue by gongsan9527** [TaleLin/lin-ui#1338]
**设备型号：**
IOS和安卓
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**
全部
**问题描述及重现步骤：**
当页面滚动到 Sidebar 最后一个索引位置时 Sidebar计算不正确 选中为第一个高亮
**相关截图**：
![image](https://user-images.githubusercontent.com/4644769/110433597-9d520480-80eb-11eb-812b-5271a092f2a6.png)

**Comment by juzi214032** [comment]
麻烦提供一个代码片段

**Comment by gongsan9527** [comment]
[https://developers.weixin.qq.com/s/xcZTRGmg7zo0](url)
这是代码片段

**Comment by juzi214032** [comment]
`stick-offset-top="100"`
1. 对于你的代码片段，加上这个属性就能正常显示
2. ios 这个问题，我这边没有ios的设备，所以没法复现，可以录个屏看一下吗

**Comment by fjx5762** [comment]
`
const sideBarData = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'W', 'X', 'Y', 'Z'
];

const nameData = [
    ['安冉', '艾浩宇'],
    ['白昕玥'],
    ['陈麟', '曹毛毛', '蔡博坤'],
    ['邓波光', '董睿希'],
    ['鄂卓烆', '洱惜文'],
    ['冯月滢', '范源'],
    ['郭若诗', '高薇竹'],
    ['黄琪琪', '胡纩鸯'],
    ['蒋馥蔓', '金倜厅'],
    ['孔薇竹', '康艳霞'],
    ['李舒旬', '刘笑'],
    ['马亦', '孟熠彤'],
    ['倪靓', '牛彗伶'],
    ['欧玉兰', '欧阳漂泊'],
    ['潘静', '皮文涛'],
    ['钱卫国', '秦健容'],
    ['任倩倩', '荣盈盈'],
    ['孙桢', '沈业轩'],
    ['陶小树', '唐子翊'],
    ['吴洁立', '王紫耘'],
    ['许子豪', '谢亚希'],
    ['杨思远', '尤庭亮'],
    ['赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶', '赵容', '周承瑶']
];`

当最后一个sideBar超过一屏幕数据时，会出现该问题。
