### ISSUE TITLE
表单align-items对齐无效

### ISSUE THREAD

**Issue by evanwu66** [TaleLin/lin-ui#1344]
**设备型号：iphone**

**LinUI 版本：0.9.4**

**微信小程序基础库版本：2.13.0**

**问题描述及重现步骤：表单align-items对齐无效**

**相关截图**：

**Comment by juzi214032** [comment]
测试 `align-items` 是有效的，需要通过 `l-form-label-class` 外部样式类修改 label 宽度才能看出来效果
