### ISSUE TITLE
开放函数使用

### ISSUE THREAD

**Issue by ctx-ya** [TaleLin/lin-ui#1351]
**LinUI 版本：**0.9.2

**微信小程序基础库版本：**2.15.0

**相关截图**：
![image](https://user-images.githubusercontent.com/37658940/112442722-1eb1c400-8d87-11eb-897e-ab3bc2bcaa83.png)
![image](https://user-images.githubusercontent.com/37658940/112442762-2709ff00-8d87-11eb-894b-38b003fb0a24.png)
![image](https://user-images.githubusercontent.com/37658940/112442803-30936700-8d87-11eb-9cff-529ce09f5640.png)

**Comment by juzi214032** [comment]
lin-ui 是否更新到了最新版
