### ISSUE TITLE
image-picker 引入报错，还有我引入了icon，但是还是报错

### ISSUE THREAD

**Issue by 251205668** [TaleLin/lin-ui#1357]
**设备型号：**
开发者工具
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**

**问题描述及重现步骤：**

**相关截图**：

![](https://image.yangxiansheng.top/img/20210330184550.png?imglist)
![](https://image.yangxiansheng.top/img/20210330184656.png?imglist)

**Comment by juzi214032** [comment]
开启增强编译即可
