### ISSUE TITLE
calendar 日历组件formatter方法无效

### ISSUE THREAD

**Issue by 18876406890** [TaleLin/lin-ui#1358]
<l-calendar show="{{ true }}" formatter="{{ formatter }}" show-confirm="{{ false }}" min-date="{{ minDate }}" max-date="{{ newDate }}" bind:linselect="formatter" />

1、show-confirm参数无效，个人检查认为没有对btn做if操作
2、formatter接入方法后，方法未被i调用
3、希望增平铺参数，由使用者根据实际情况，是作为日期选择组件还是作为日历展示组件

**Comment by juzi214032** [comment]
您好，我这边测试是有效的，建议仔细阅读文档，如仍有问题，请上传程序片段以供排查
