### ISSUE TITLE
表单，自定义input组件左边(label)部分---示例

### ISSUE THREAD

**Issue by miaorongqiang** [TaleLin/lin-ui#1359]
![image](https://user-images.githubusercontent.com/66403868/113395622-ba1ce780-93cc-11eb-8672-58b7e511ad20.png)

1） 小程序中 图片组件是image，原生组件拼写错误
2）`<img>`标签没有加结尾符，正确如`<image />`

**Comment by juzi214032** [comment]
感谢反馈，会修正该示例
