### ISSUE TITLE
custom-tab-bar组件自定义部分少了个逗号

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-ui#136]
**重现步骤（可选）：**
源文件少逗号会报错

**期望的结果是什么？**
![image](https://user-images.githubusercontent.com/15071824/54124963-b7927280-443e-11e9-8561-1e7b228aa967.png)
    // isSwitchTab: true 这一行代码

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/15071824/54124949-b06b6480-443e-11e9-80e3-8b71ffb0e6b1.png)

**Comment by uniquenaer** [comment]
感谢反馈~我们会尽快修复，修复完成后会告知您的~~

**Comment by YpchenLove** [comment]
已经做了修改~ 14号晚上发布新版本~

**Comment by gaojx97** [comment]
麻烦各位~
