### ISSUE TITLE
i-card的image能否支持按比例缩放？

### ISSUE THREAD

**Issue by cnfi** [TaleLin/lin-ui#1361]
**Feature 名称：**
i-card的image能否支持按比例缩放？

**简要描述：**
不管是primary还是cover模式，引入的图片拉伸比例变形严重，能否做到按比例缩放呢？

**其他组件库或类似功能的截图：**
![image](https://user-images.githubusercontent.com/1331723/113572369-a8e10e80-964a-11eb-86af-6f4a32b7758e.png)

**Comment by juzi214032** [comment]
设置 image-mode 属性即可
