### ISSUE TITLE
通告栏 NoticeBar不能设置背景色和字体颜色

### ISSUE THREAD

**Issue by springphp** [TaleLin/lin-ui#1362]
<l-notice-bar show="{{true}}">我是通告栏</l-notice-bar>没有设置背景色和字体颜色的属性，自己修改也无法覆盖

**Comment by juzi214032** [comment]
NoticeBar 的内容是你通过 slot 传入的，你自己写个view控制样式即可

**Comment by springphp** [comment]
但是 这个默认的背景改不了

**Comment by juzi214032** [comment]
使用 l-class 外部样式类并添加 `!important`

**Comment by juzi214032** [comment]
.l-class{
  background-color: red !important;
}
