### ISSUE TITLE
Form 表单 input输入报错

### ISSUE THREAD

**Issue by wusacard** [TaleLin/lin-ui#1369]
**设备型号：**
mac
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**
2.16.0
**问题描述及重现步骤：**
复制 官网 form表单示例 input输入时报错
**相关截图**：
<img width="1410" alt="WX20210414-173232@2x" src="https://user-images.githubusercontent.com/15819750/114688603-6d7bc980-9d47-11eb-880b-15466e79a741.png">

**Comment by juzi214032** [comment]
解决了吗

**Comment by mounan** [comment]
也不说一下怎么解决的就closed。。
