### ISSUE TITLE
Tabs 组件下的 tabpanel组件中 tab-content  的如果写入p标签内容，没有按照正常显示。

### ISSUE THREAD

**Issue by jiangjiali** [TaleLin/lin-ui#1370]
Tabs 组件下的 tabpanel组件中 tab-content  的如果写入p标签内容，没有按照正常显示。
` <l-tabpanel tab="推荐" key="1" slot="1">
          <view class="tab-content">
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
            <p>asdasdasd</p>
          </view>
        </l-tabpanel>`

这些，结果显示成一排。

**Comment by juzi214032** [comment]
小程序不支持p标签
