### ISSUE TITLE
使用image-picker等组件时，组件中的图片加载失败

### ISSUE THREAD

**Issue by loveyii** [TaleLin/lin-ui#1374]
**设备型号：**
iPhone 6/7/8
**LinUI 版本：**
0.9.4
**微信小程序基础库版本：**
2.16.0
**问题描述及重现步骤：**
组件中的图片加载不出来
Failed to load local image resource /miniprogram_npm/lin-ui/image-picker/image/add.png 
 the server responded with a status of 500
**相关截图**：
![image](https://user-images.githubusercontent.com/25079252/115499790-9ef21900-a2a2-11eb-90a1-6db04d82f111.png)

**Comment by loveyii** [comment]
![image](https://user-images.githubusercontent.com/25079252/115517305-96590d00-a2b9-11eb-9631-e032617f160c.png)

**Comment by juzi214032** [comment]
真机预览是不是没问题，这个是微信开发者工具的bug，我们这边干预不了
