### ISSUE TITLE
tabBar问题

### ISSUE THREAD

**Issue by ghost** [TaleLin/lin-ui#138]
**重现步骤（可选）：**
按照文档使用自定义tabBar

**期望的结果是什么？**
点击tabBar的一项，页面正常切换。
**实际的结果是什么？**
点击tabBar的一项，页面能正常切换，但是tabBar被选中颜色错乱

**Comment by YpchenLove** [comment]
这是一个bug，我会在今天修复，并且更新最迟明天更新，谢谢反馈~

**Comment by linzhipenghn** [comment]
好像还没修复？

**Comment by YpchenLove** [comment]
没有合并到master上，还有其他问题，在修改测试~这周肯定会发布新版，感谢支持~
