### ISSUE TITLE
什么时候发新版本。

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#1380]
啥时候发新版啊?两个多月了，是在憋大招吗？

**Feature 名称：**

**简要描述：**

**使用场景：**

**其他组件库或类似功能的截图：**

**Comment by jiangjiali** [comment]
我觉得作者是在完善后续工作吧。

**Comment by aQingYun** [comment]
你是有什么新的需求或者是bug等着发版吗

**Comment by workingCar** [comment]
主要是看到作者这次的更新周期比较长，所以才比较好奇。

**Comment by jiangjiali** [comment]
其实之前的，已经够用了。那些微微的小BUG不影响。
