### ISSUE TITLE
ImagePicker图片选择器外部样式类l-item-class无效

### ISSUE THREAD

**Issue by YYJeffrey** [TaleLin/lin-ui#1383]
**设备型号：iphone6**

**LinUI 版本：0.9.4**

**微信小程序基础库版本：2.16.1**

**问题描述及重现步骤：ImagePicker[文档中](https://doc.mini.talelin.com/component/form/image-picker.html#%E5%9B%BE%E7%89%87%E9%80%89%E6%8B%A9%E5%99%A8%E5%A4%96%E9%83%A8%E6%A0%B7%E5%BC%8F%E7%B1%BB)提到l-item-class可修改每个图片的外部样式，尝试无果，发现实际源码中并未实现，对比[Master](https://github.com/TaleLin/lin-ui/blob/master/src/image-picker/index.wxml)和[先前版本](https://github.com/TaleLin/lin-ui/blob/3e66d0954ba5a393cbdd1ccd661c00a84727a8a7/src/image-picker/index.wxml)**

**相关截图**：

**Comment by HQ-Dev** [comment]
image-picker 这个组件课程中 0.8.7 版本 和最新的 0.9.4 版本使用起来区别很大。测试了下前者可设置size，最新版本的图片组件会挤在一起。
