### ISSUE TITLE
【Bug Report】tabs组件加上swipeable后 滑动内容不显示，只显示标题

### ISSUE THREAD

**Issue by Scott1995** [TaleLin/lin-ui#14]
tabs组件加上swipeable后 滑动内容不显示，只会显示标题

**Comment by YpchenLove** [comment]
@uniquenaer 来解决一下。感谢反馈！

**Comment by uniquenaer** [comment]
> tabs组件加上swipeable后 滑动内容不显示，只会显示标题

收到，我们修复一下这个问题，晚上会一起发布新版本修复这些问题

**Comment by 7insummer** [comment]
核心库0.0.1.alpha3版本已修复，感谢提出
