### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by 2235602974** [TaleLin/lin-ui#1414]
**设备型号：**

**LinUI 版本：**

**微信小程序基础库版本：**

**问题描述及重现步骤：**

**相关截图**：

**Comment by aQingYun** [comment]
你指的官网是哪一个 文档地址吗？

**Comment by aQingYun** [comment]
www.doc.mini.talelin.com
这个是文档地址

**Comment by aQingYun** [comment]
https://doc.mini.talelin.com/

**Comment by 2235602974** [comment]
https://7yue.pro/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月31日(星期六) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TaleLin/lin-ui] 官网无法访问 (#1414)





 
https://doc.mini.talelin.com/
