### ISSUE TITLE
折叠面板collapse-item使用l-title-class覆盖折叠面板子项标题样式不生效？

### ISSUE THREAD

**Issue by hustjiangtao** [TaleLin/lin-ui#1423]
**设备型号：**

**LinUI 版本：**
latest, v0.9.4

**微信小程序基础库版本：**
2.14.1

**问题描述及重现步骤：**
折叠面板子项使用l-title-class覆盖折叠面板子项标题样式不生效
```
# index.wxml
<l-collapse-item title="Lin UI" l-title-class="item-text" l-body-class="item-text">
    Lin UI 是基于微信小程序原生语法实现的组件库。遵循简洁，易用的设计规范。
  </l-collapse-item>
```

```
#index.wxss
.item-text {
  color: red;
}
```

如上，l-body-class生效, l-title-class不生效

不知是我用错了，还是真的bug？烦请解惑

**相关截图**：

![image](https://user-images.githubusercontent.com/13832759/129434777-0ee6937f-273a-4c66-b4f6-d845b32632cb.png)

**Comment by smileShirmy** [comment]
![image](https://user-images.githubusercontent.com/30590134/142336150-20652ec9-b8d1-42f5-853c-e45cf6dbd8b6.png)

如上图，会被默认的样式覆盖，因此需要加上 `!important` 如下所示：

```scss
.item-text {
  color: red !important;
}
```

**Comment by smileShirmy** [comment]
具体请看文档 [Lin UI 外部样式类使用](https://doc.mini.talelin.com/start/class.html)
