### ISSUE TITLE
切换小程序基础库版本后大量警告

### ISSUE THREAD

**Issue by evanwu66** [TaleLin/lin-ui#1430]
**设备型号：**
iphoneX

**LinUI 版本：**
0.9.4

**微信小程序基础库版本：**
2.19.5

**问题描述及重现步骤：**
切换小程序基础库版本后大量类似以下这种警告
[Component] the type of property "minDate" is illegal (when preparing behavior "components/lin-ui/calendar/components/mounth/index")
 [Component] the type of property "opacity" is illegal (when preparing behavior "components/lin-ui/mask/index")
 [Component] slot "4" is not found.

**相关截图**：

**Comment by ElanYoung** [comment]
我也遇到了

**Comment by aQingYun** [comment]
这个警告挺像使用吗？

**Comment by ElanYoung** [comment]
> 这个警告影响使用吗？

不影响使用，只是强迫症看着难受

**Comment by lilue** [comment]
强迫症受不了这么多警告，有大佬说一下怎么处理吗

**Comment by aQingYun** [comment]
问题已修改  详见 #1444

**Comment by ElanYoung** [comment]
![image](https://user-images.githubusercontent.com/39727435/143772573-f358a426-8c09-4826-bf7a-98dc62d9cbf1.png)
刚刚升级了0.9.5版本 这个警告还是存在 应该是grid组件那里引起的
