### ISSUE TITLE
l-form组件里不能用微信原型的表单组件，比如switch

### ISSUE THREAD

**Issue by Chenzhiwen7** [TaleLin/lin-ui#1431]
**设备型号：*开发环境*

**LinUI 版本：*最新版本*

**微信小程序基础库版本：**

**问题描述及重现步骤：** l-form组件里不能用微信原型的表单组件。

**相关截图**：

![image](https://user-images.githubusercontent.com/25706050/135582466-58caebb3-f13b-45bc-9368-29eba32cfd8c.png)

**Comment by jiangjiali** [comment]
我咋没有遇到你的这个问题呢？

**Comment by aQingYun** [comment]
由于目前组件是单独维护了一个form，与微信原生的form并不相关，所以无法使用原生组件的switch

**Comment by aQingYun** [comment]
如果有使用的需求，可以提一个feature issue，后续会考虑添加该组件

**Comment by smileShirmy** [comment]
0.9.7 版本已新增 switch 组件
[Switch](https://doc.mini.talelin.com/component/form/switch.html)
