### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by MichaelWilliams8844** [TaleLin/lin-ui#1439]
无法运行程序 。
提示：
[ app.json 文件内容错误] app.json: app.json 未找到(env: Windows,mp,1.05.2110290; lib: 2.21.0)
![图片](https://user-images.githubusercontent.com/6623162/142753707-e5620f55-4743-43a0-8c53-43bada796967.png)

**Comment by aQingYun** [comment]
你这个应该是微信开发者工具所导致的问题，试着重新编译或者重启一下开发者工具
