### ISSUE TITLE
popup组件slot中使用input组件，input异常

### ISSUE THREAD

**Issue by llinwind** [TaleLin/lin-ui#1445]
**设备型号：**
HONOR 30
**LinUI 版本：**
0.9.5
**微信小程序基础库版本：**
2.21.0

**微信开发者工具版本：**

**问题描述及重现步骤：**
popup组件slot中使用input组件，删除input之前的内容，再次输入会有之前删除内容的阴影。开发者工具中不会出现问题
`<l-button shape="circle" bind:lintap="showUpdatePopup">修改设备名</l-button>
<l-popup show="{{popupDeviceName}}">
  <view class="popup-container">
    <l-input  label-width="170" label="设备名" placeholder="请输入设备名" showRow="{{false}}"
      value="{{deviceName}}" bind:lininput="onUpdateDeviceName" />
  </view>
</l-popup>`

**相关截图**：
![图片](https://user-images.githubusercontent.com/53851505/143397070-e1acc2d5-9446-497b-8e3f-58fa9a1085af.png)

**Comment by llinwind** [comment]
留下阴影后，点击背景，popup组件会隐藏，但是阴影还在
![图片](https://user-images.githubusercontent.com/53851505/143397707-a6c0ec0a-950f-4562-a770-60808902ea4d.png)

**Comment by aQingYun** [comment]
感谢反馈  我们会排查一下该问题  有代码链接吗  如果有的话最好提供一下复现的代码链接

**Comment by smileShirmy** [comment]
用IOS和安卓都尝试了一下均无法复现，考虑是小程序本身没有做好兼容，检查了一下代码逻辑也没什么问题
