### ISSUE TITLE
@babel/runtime/helpers/slicedToArray.js" is not defined

### ISSUE THREAD

**Issue by HWYD** [TaleLin/lin-ui#1448]
**设备型号：微信开发工具

**LinUI 版本：0.9.5

**微信小程序基础库版本：2.21.0

**微信开发者工具版本：最新稳定版

**问题描述及重现步骤：尝试使用l-calendar日历组件时报错

**相关截图**：
![1638174476(1)](https://user-images.githubusercontent.com/52754591/143832996-7a2d95b7-fe7d-4c81-ba2b-6fce9843f0c1.png)

![1638174706(1)](https://user-images.githubusercontent.com/52754591/143833579-af6277f4-f8b6-40fb-91fb-3d5ec2b5c7bb.png)

**Comment by aQingYun** [comment]
开启增强编译了吗？

**Comment by lidesheng111** [comment]
使用image-pickerzuj 时也有类似报错：
module "@babel/runtime/helpers/createForOfIteratorHelper.js

**Comment by aQingYun** [comment]
未复现该问题，方便的话可以发一个代码示例链接可以更准确的定位问题

**Comment by lidesheng111** [comment]
上个月月初创建的小程序可以正常使用image-picker，任何版本的基础调试基础库都没问题。
对于今天测试新建的小程序，刚发现，调试基础库为2.19.6的时候不报错，超过这版本就报错。

**Comment by smileShirmy** [comment]
网上查资料发现，这是微信官方的问题，并说后面版本会修复
- [https://developers.weixin.qq.com/community/develop/doc/000886043d8278b9770de6b3c51400](https://developers.weixin.qq.com/community/develop/doc/000886043d8278b9770de6b3c51400)
- [https://developers.weixin.qq.com/community/develop/doc/00040675c841180c342ba2d105b400](https://developers.weixin.qq.com/community/develop/doc/00040675c841180c342ba2d105b400)

**Comment by HWYD** [comment]
好的，感谢
