### ISSUE TITLE
用npm安装构建完npm直接报错

### ISSUE THREAD

**Issue by JiuSword** [TaleLin/lin-ui#1449]
**设备型号：**
Windows10 64位
**LinUI 版本：**
0.9.5
**微信小程序基础库版本：**
2.14.1

**微信开发者工具版本：**
1.05.2110290
**问题描述及重现步骤：**
构建完npm编译直接报错
**相关截图**：
![image](https://user-images.githubusercontent.com/87112542/143887323-e6f454dc-ebd1-4123-a166-ee6ae1a1f921.png)

**Comment by aQingYun** [comment]
在同样环境下未复现相同的问题 你是引入的组件所报的错误吗

**Comment by JiuSword** [comment]
未引入组件，在安装完，使用小程序工具里的构建npm，之后编译直接报错
也试过直接下源码还是一样

**Comment by JiuSword** [comment]
> 未引入组件，在安装完，使用小程序工具里的构建npm，之后编译直接报错
> 也试过直接下源码还是一样

**Comment by jeff845997715** [comment]
我也遇到相同的问题，小程序工具里面的构建npm也成功了，也是报同样的错误

**Comment by yichengq** [comment]
我也遇到了
```
VM1904:5138 页面【miniprogram_npm/lin-ui/mask/index]错误:
 TypeError: Cannot read property 'name' of undefined
```

触发原因是
```
  "usingComponents": {
    "l-toast": "/miniprogram_npm/lin-ui/toast/index"
  }
```

**Comment by wanglei520** [comment]
我也发现同样的问题
![image](https://user-images.githubusercontent.com/16570172/146504389-ed25a71a-2691-4f39-a3ca-1de6dc49b700.png)
{
    "usingComponents": {
        "l-toast": "/components/lin-ui/toast/index"
    }
}

**Comment by wanglei520** [comment]
换了一下版本就没报错了，换成之前的版本---lin-ui-0.9.4

**Comment by LgAz** [comment]
降一下版本确实好了

**Comment by star00138** [comment]
升级后，我也遇到了这个：
TypeError: Cannot read property 'name' of undefined
我的是miniprogram_npm/lin-ui/calendar/index报错

**Comment by Gaozizhong** [comment]
不用降版本，升级小程序调试基础库问题即被解决

**Comment by peas7777** [comment]
出现同样的问题，因为要在企业微信中开发，然后企业微信目前最高2.17.很难受

**Comment by hrpc** [comment]
升级基础库可解决
