### ISSUE TITLE
【Feature request】希望新增一个索引页组件

### ISSUE THREAD

**Issue by JoeyGaojingxing** [TaleLin/lin-ui#146]
**描述你希望的支持的新功能？**
希望新增一个全屏索引页面，带有搜索功能
![image](https://user-images.githubusercontent.com/15071824/54596679-1a53c180-4a70-11e9-9e61-aade7f65ddc9.png)
单个选项可以带图片，有主副标题就万能了

**你期望的 API 是怎样的？**
对前端不是很了解，，就不瞎期望了

**Comment by 7insummer** [comment]
贴个图看看吧，不太理解你的描述。。。

**Comment by gaojx97** [comment]
![image](https://user-images.githubusercontent.com/15071824/54605028-3745c000-4a83-11e9-94b7-9eaaa06bce0d.png)
这样

**Comment by YpchenLove** [comment]
反馈已收到~
这个组件已经在计划中了~因为要发布正式版暂时搁置了，正式版上线后，这个组件就会放出来~
谢谢反馈~

**Comment by gaojx97** [comment]
哈哈哈，期待lin-ui正式版的发布~

**Comment by juzi214032** [comment]
你好，该组件正在开发，预计下个版本发布，可以先看一下文档是否满足你的需求，如有其他需求，欢迎随时反馈。
[文档地址](http://doc.mini.7yue.pro/component/layout/index-list.html)

**Comment by JoeyGaojingxing** [comment]
辛苦辛苦~
