### ISSUE TITLE
【Bug Report】官方文档中TabBar 文字未选中时的颜色 属性名和源码中的有误差

### ISSUE THREAD

**Issue by AliceZ413** [TaleLin/lin-ui#1463]
**设备型号：**
所有

**LinUI 版本：**
0.9.5

**微信小程序基础库版本：**
2.19.6

**微信开发者工具版本：**
Stable 1.05.2108130

**问题描述及重现步骤：**
官方文档中【TabBar 文字未选中时的颜色】的属性名是【text-unselected-color】，但是并不能生效。
在查看源码时发现并没有【text-unselected-color】字段只有【text-color】，这点和文档有出入
**相关截图**：
![image](https://user-images.githubusercontent.com/52058780/145370749-d7bdfba8-dfbb-4fe2-a9a5-1d96c7e7040d.png)
![image](https://user-images.githubusercontent.com/52058780/145370866-b5235ac8-bed2-43c8-9635-703de3e68640.png)

**Comment by smileShirmy** [comment]
感谢反馈，后面会调整文档，统一使用 text-color
