### ISSUE TITLE
最新版本倒计时失效

### ISSUE THREAD

**Issue by xiaohan13145200** [TaleLin/lin-ui#1464]
**设备型号：iphoneX

**LinUI 版本：win

**微信小程序基础库版本：2.21.0

**微信开发者工具版本：1.05.2110290

**问题描述及重现步骤：粘贴例子

**相关截
![b30e4a629ffd1c00dea355a2cb99a04](https://user-images.githubusercontent.com/48642545/145586460-63ac8e74-b552-4437-9fb1-30024d9c369c.png)
图**：

**Comment by smileShirmy** [comment]
已修复，待更新
