### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by pokid** [TaleLin/lin-ui#1475]
关于反馈的的这个问题
![image](https://user-images.githubusercontent.com/23217359/147938101-d6e4c0ae-fab2-4504-8ebf-36c9b19c26a2.png)

**Comment by pokid** [comment]
经测试，0.9.4(不含0.9.4)以上版本均会报个错误

**Comment by xczizz** [comment]
尝试更改小程序基础库版本，我在2.14也构建错误了，更改为2.19成功（但构建过程中console显示不少错误）
