### ISSUE TITLE
tab-bar组件没法根据页面的切换而改变图标选中状态

### ISSUE THREAD

**Issue by xiaowangzine** [TaleLin/lin-ui#1490]
**设备型号：**

**LinUI 版本：*0.97*

**微信小程序基础库版本：*2.22.0*

**问题描述及重现步骤：*j界面可以正常的切换，但对应的图标状态不会改变，不管在那个界面，都是默认第一个图标被选中*

**相关截图**：
![image](https://user-images.githubusercontent.com/99120150/152751216-1f5c597c-7eba-4040-a4ca-16cca7891160.png)

**Comment by smileShirmy** [comment]
有没有具体的代码？这边没能复现
