### ISSUE TITLE
l-rate 使用 bind:linChange 不生效

### ISSUE THREAD

**Issue by Black-Dong** [TaleLin/lin-ui#1497]
标题： l-rate 使用 bind:linChange 不生效

代码片段：
https://developers.weixin.qq.com/s/wri4aBmu7Gx3

**Comment by Black-Dong** [comment]
是 bind:linchange 不是 bind:linChange，我真是个大傻吊

**Comment by pwjpj52** [comment]
感谢，这是他文档的问题
