### ISSUE TITLE
组件arc-popup 属性direction无效

### ISSUE THREAD

**Issue by CHEN-J-H** [TaleLin/lin-ui#1498]
**设备型号：** 模拟器

**LinUI 版本：**  0.98

**微信小程序基础库版本：**2.19.6

**微信开发者工具版本：**

**问题描述及重现步骤：** direction=bottom 设置无效

**相关截图**：
![image](https://user-images.githubusercontent.com/24712031/157799353-fb1957fa-e4c7-4339-8997-7ee922288174.png)
设置无效 源码案例设置了也是居中的

分析报告
l-popup 组件中虽然定义了属性 但是并没有使用

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/24712031/157799586-f345cce8-1bd0-4b6b-9110-ef2e0f73031a.png">
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/24712031/157799613-d79c688d-5d7e-4762-b79e-004d0a37ac19.png">

经过发现 direction属性作用应该是对应 contentAlign的。所以直接修改arc-popup 组件中wxml的direction。  改为contentAlign即可修复

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/24712031/157799769-deaf3835-7fed-4f95-a255-aea23911bd41.png">

arc-popup 属性设置direction bottom 目的达到

**Comment by smileShirmy** [comment]
感谢 bug 反馈，将在下个版本修复
