### ISSUE TITLE
[Feature Request] 阿里小程序支持

### ISSUE THREAD

**Issue by Akimotorakiyu** [TaleLin/lin-ui#150]
**描述你希望的支持的新功能？**
阿里小程序支持
钉钉小程序、支付宝小程序

**你期望的 API 是怎样的？**
阿里小程序和微信小程序非常接近，期望可以方便移植就好了。

**Comment by uniquenaer** [comment]
感谢反馈~我们团队之前讨论过支持支付宝小程序的问题，考虑到目前精力分配问题，会先专注于小程序组件的开发，等小程序组件趋于稳定后，会考虑支持支付宝小程序的。
