### ISSUE TITLE
Counter组件设定最小值为1时，输入0，数字溢出bind:linout不会被触发

### ISSUE THREAD

**Issue by sizeoflove1** [TaleLin/lin-ui#1501]
**设备型号：**
iPhone12 

**LinUI 版本：**
0.9.7

**微信小程序基础库版本：**
2.22.1

**微信开发者工具版本：**
1.06.2111300

**问题描述及重现步骤：**
Counter组件通过设定min属性、设定最小值为1时，输入0（input方式，不是icon），数字溢出bind:linout不会被触发。

现在的behavior是：输入0，bind:linout不被触发，但是0也没有被accept，count的数字是上一个有效数字。比如上一个数字是99，输入0后，count还是99，linout不被触发。

期望的hehavior是：输入0，linout被触发，count自动变为设定的最小值1.

**相关截图**：

**Comment by smileShirmy** [comment]
感谢反馈，问题已修，将在下个版本中推出
