### ISSUE TITLE
小程序文档 ，为什么不让复制？  需要一行一行的敲。

### ISSUE THREAD

**Issue by baican2008** [TaleLin/lin-ui#1516]
**Feature 名称：**
小程序文档 ，为什么不让复制？  需要一行一行的敲。
**简要描述：**
文档不能复制
**使用场景：**
需要一行一行的敲。
**其他组件库或类似功能的截图：**
![image](https://user-images.githubusercontent.com/12045747/173505148-3f9aadc4-ce6b-4f3a-a30b-6e8fb7f8b3fc.png)

**Comment by smileShirmy** [comment]
你好，感谢反馈，我试了一下可以复制的，哪里不能复制给个网址看看
![image](https://user-images.githubusercontent.com/30590134/174480743-e0d52c7a-37c5-4bdd-bd1a-29e97f70e3f3.png)

**Comment by baican2008** [comment]
在小程序里面复制不了。文档还有其他的入口？有地址吗

**Comment by baican2008** [comment]
文档找到了。
