### ISSUE TITLE
l-button的事件响应增加chooseAvatar

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-ui#1517]
**Feature 名称：**

l-button的事件响应增加chooseAvatar

**简要描述：**

按照新的"小程序用户头像昵称获取规则调整公告" https://developers.weixin.qq.com/community/develop/doc/00022c683e8a80b29bed2142b56c01
获取用户头像"需要将 button 组件 open-type 的值设置为 chooseAvatar，当用户选择需要使用的头像之后，可以通过 bindchooseavatar 事件回调获取到获取到头像信息的临时路径。"
目前l-button似乎不能响应chooseAvatar,希望增加该功能

**使用场景：**

自定义选择头像

**其他组件库或类似功能的截图：**

**Comment by smileShirmy** [comment]
感谢反馈，最新的 0.9.11 版本已更新该事件，文档也一并更新了
