### ISSUE TITLE
l-collapse-item title颜色样式有误

### ISSUE THREAD

**Issue by Yilimmilk** [TaleLin/lin-ui#1519]
**设备型号：iPhone8**

**LinUI 版本：0.9.11**

**微信小程序基础库版本：2.24.6**

**微信开发者工具版本：**

问题描述及重现步骤：
```html
<l-collapse-item l-title-class="agreement-collapse-item-title" title="标题"></l-collapse-item>

.agreement-collapse-item-title {
  color: #000000;
}
```
上述代码无法通过`l-title-class`覆盖collapse-item原本的title样式，查看源代码发现，`collapse-item/index.wxss`文件中的`.container-title`样式里面有个`color`优先级比自己定义的要高，导致无法自定义颜色，这是否是一个bug?
**

**相关截图**：无

**Comment by smileShirmy** [comment]
关于这个问题建议使用 `!important` 具体请查看 [Lin UI 外部样式类使用](https://doc.mini.talelin.com/start/class.html)
