### ISSUE TITLE
希望增加表格组件

### ISSUE THREAD

**Issue by Wangs121** [TaleLin/lin-ui#1537]
**Feature 名称：希望增加表格组件**

**简要描述：希望再增加表格组件**

**使用场景：数据需要列成表格样式**

其他组件库或类似功能的截图：
1. [ThorUI的表格组件](https://thorui.cn/doc/docs/extend/tui-table.html)
2. [habc0807](https://github.com/habc0807)/[miniprogram-table-component](https://github.com/habc0807/miniprogram-table-component)

**Comment by smileShirmy** [comment]
感谢反馈，后续会纳入考虑

**Comment by QuintinTao** [comment]
同希望。加油lin UI
