### ISSUE TITLE
custom-tab-bar和tab-bar是什么关系呢？

### ISSUE THREAD

**Issue by totoro52** [TaleLin/lin-ui#1541]
**设备型号：**
MI 6
**LinUI 版本：**
0.19.12
**微信小程序基础库版本：**
2.19.4
**问题描述及重现步骤：**
我查阅了代码提交记录，在代码中发现了一个叫custom-tab-bar的代码，又找到一个tab-bar，目前我在使用tab-bar组件，发现他不支持icon的自定义尺寸大小，而这个custom又支持设置大小，但好像看起来这个custom已经被遗弃了
**相关截图**：
![image](https://user-images.githubusercontent.com/25952444/196881623-c3991677-438e-4108-b677-04606d168450.png)

**Comment by smileShirmy** [comment]
感谢反馈，我看一下
