### ISSUE TITLE
l-form-item的id不能是数字吗？会显示Error: 表单项不存在name

### ISSUE THREAD

**Issue by beibei87970** [TaleLin/lin-ui#1553]
如果id是index,index是wx:for的序号标签(wx:for-index="index")，就会报错
![图片](https://user-images.githubusercontent.com/57718033/201253797-c6aa3a3f-5227-487b-9cda-5d7c09fb3e25.png)
![图片](https://user-images.githubusercontent.com/57718033/201253854-529418ec-6775-43b6-b764-5e09fc13df48.png)
除非在前面加字母才不会报错，比如下图这样
![图片](https://user-images.githubusercontent.com/57718033/201254089-8f1ac361-fede-4edf-8096-4ff9ba2a3271.png)

请问这个问题怎么解决？我js里需要用到这个序号

**Comment by smileShirmy** [comment]
对的，id 不能为序号，否则会有问题，因为内部实现是这样的 
```js
      const formItem = _this.selectComponent(`#${id}`);
      if (formItem) {
        currentTarget.validatorData(params, type);
      } else {
        throw new Error(`表单项不存在name：${id}`);
      }
```
因此，如果是 `#数字` 是不合法的，无法正确获取到 formItem
