### ISSUE TITLE
吸顶容器，js 模式下 top 未转成 px 计算

### ISSUE THREAD

**Issue by proxiti** [TaleLin/lin-ui#1554]
**设备型号：**
iPhone13

**LinUI 版本：**
0.9.12

**微信小程序基础库版本：**
2.27.3

**微信开发者工具版本：**
Stable 1.06.2209190

**问题描述及重现步骤：**
在官方 examples 代码中 吸顶容器->动态插入内容，修改 Sticky top 值为 100，此时滑动屏幕，header 自动跳到顶部。
原因也找到，
```javascript
const isFixedTop = scrollTop > stickyItemTop - top && scrollTop < stickyItemHeight + stickyItemTop - top;
```
在计算的时候，top 值没有转成 px，导致 top 值偏大，从而导致 isFixedTop 过早地被置为 true，展现在屏幕上就是 header 跳到顶部。

**相关截图**：

![QQ录屏20221205171637](https://user-images.githubusercontent.com/25367586/205600200-4c013e15-7172-4dbc-83db-179573c81330.gif)

**Comment by smileShirmy** [comment]
感谢反馈
