### ISSUE TITLE
未使用badge组件却显示 property "value" of "miniprogram_npm/lin-ui/badge/index"received type-uncompatible value: expected <String> but get null value. Use empty string instead.

### ISSUE THREAD

**Issue by jian279141** [TaleLin/lin-ui#1556]
**设备型号：iphone 5**

**LinUI 版本：^0.9.12**

**微信小程序基础库版本：2.29.0**

**微信开发者工具版本：1.06.2209190**

**问题描述及重现步骤：未使用badge组件，但是报警告 property "value" of "miniprogram_npm/lin-ui/badge/index"received type-uncompatible value: expected <String> but get null value. Use empty string instead.**

**相关截图**：
<img width="749" alt="1672653361777" src="https://user-images.githubusercontent.com/119093050/210216316-1206ee13-cd13-4ffb-99e7-60c17e215f64.png">

**Comment by smileShirmy** [comment]
这个应该不影响正常使用，后续会进行优化
