### ISSUE TITLE
Avatar组件的头像变成椭圆形了

### ISSUE THREAD

**Issue by h2appy** [TaleLin/lin-ui#1563]
MacBook Pro 16（Apple M1 Max）
macOS 13.2.1
机型：iPhone 6
LinUI版本：0.9.13
微信小程序基础库版本：2.30.2
微信开发者工具版本：1.06.2303060

问题描述及重现步骤：
在页面中加入Avatar组件：
<l-avatar placement="bottom" open-data="{{['userAvatarUrl', 'userNickName']}}"></l-avatar>
显示的圆形头像变成了椭圆形，头像尺寸60*65

解决方法：
把avatar/index.less文件中.l-avatar-image的flex: 1去掉即可。

相关截图：
<img width="1340" alt="截屏2023-03-17 14 40 31" src="https://user-images.githubusercontent.com/11326053/225831483-44d3e51c-c8bd-458c-956c-becec72fa3e2.png">

**Comment by smileShirmy** [comment]
这个问题，可能是被其他什么样式影响到了，解决了就好
