### ISSUE TITLE
[Feature Request]数量选择器组件支持自定义数量

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#166]
描述你希望的支持的新功能？
因为小程序是面向代理的，有时候可能一次要下十几二十张票，每次都要不停点击，比较麻烦。希望增加一个自定义输入数量的功能

你期望的 API 是怎样的？
![IMG_20190329_111554](https://user-images.githubusercontent.com/25305886/55207456-19135900-5215-11e9-838a-1a92943357c5.JPG)
1.点击中间数字区域后可以编辑数字
2.失去焦点或者点击了键盘的完成按钮就绑定当前的输入值

**Comment by YpchenLove** [comment]
已经收到~~内部评估后，发现这一点确实是我们考虑欠缺的地方，很感谢反馈，已经讲这个组件的升级完善列入日程。预计会在本月正式版中新增这一功能。
