### ISSUE TITLE
希望出个Picker

### ISSUE THREAD

**Issue by llc12300913** [TaleLin/lin-ui#180]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by uniquenaer** [comment]
微信官方现有的picker是不能满足你的需求么，能否提供一些场景以及预期的API信息

**Comment by 7insummer** [comment]
麻烦按照feature的模板提一下具体的场景和需求信息，感谢。

**Comment by zhc525349965** [comment]
长时间未回复，关闭此issue
