### ISSUE TITLE
tabs切换闪现白色

### ISSUE THREAD

**Issue by wseek** [TaleLin/lin-ui#182]
**重现步骤（可选）：**
代码片段：https://developers.weixin.qq.com/s/jdPrexmf7d7d
**期望的结果是什么？**
tabs能正常切换
**实际的结果是什么？**
将背景色改成深色，在切换tab时发现切换时会闪现白色

**Comment by uniquenaer** [comment]
感谢反馈，今天会修复完毕的

**Comment by uniquenaer** [comment]
你好，这个问题目前修复版本在develop分支上，您可以下载develop上的dist文件使用~~
