### ISSUE TITLE
希望可以增加提供数据展示功能的preview组件

### ISSUE THREAD

**Issue by guomz** [TaleLin/lin-ui#187]
**描述你希望的支持的新功能？**
布局类似卡片，具体效果类似下图
![image](https://user-images.githubusercontent.com/37978545/56074521-fb361e80-5de6-11e9-9558-7666e88723b4.png)

**你期望的 API 是怎样的？**

**Comment by YpchenLove** [comment]
首先感谢你的反馈~另外根据你提供的这图片素材，我们评估后觉得场景不够广泛，这个截图有点类似微信的模板消息，如果你有其他好的想法，或者更好的素材都可以在本issue下，继续回复。
我们暂时不关闭issue，也希望你会有后续的跟进~thanks O(∩_∩)O~~

**Comment by guomz** [comment]
那在你们的示例小程序中出现的类似小标题一样的组件会有吗？
![image](https://user-images.githubusercontent.com/37978545/56090102-04e78100-5ed0-11e9-9df8-ef2e4a491a0e.png)
![image](https://user-images.githubusercontent.com/37978545/56090114-1df03200-5ed0-11e9-9c91-e5d332b463c1.png)

**Comment by YpchenLove** [comment]
小标题这个不需要抽象成公共组件啊，简单的flex布局就可以搞定了。一个icon+一段文本，如果需要布局相关的组件的吧，可以查看下list组件~
