### ISSUE TITLE
【Bug Report】button组件样式

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#19]
button不占宽高,而且无法改变里面嵌套文字的样式,除非再在里面嵌套一层<text>
在外面包裹一个view display flex 它的宽高又回来了，
但是包裹一个form display flex宽高还是0

**Comment by aQingYun** [comment]
button组件这个地方是进行了重置的 所以button的宽高是0

**Comment by YpchenLove** [comment]
外部样式类可以解决这一类的样式问题，详细请查阅button组件的文档，本issue已经手动关闭，如有其它疑问，请重新提issue~感谢反馈~
