### ISSUE TITLE
倒计时组件 time="2020-5-1 18:30" 在真机上不显示

### ISSUE THREAD

**Issue by Sunday-web** [TaleLin/lin-ui#206]
**重现步骤（可选）：**
时间格式为datetime时，在真机预览无法显示，模拟器正常

**期望的结果是什么？**
可以在真机上正常显示
**实际的结果是什么？**

**Comment by Sunday-web** [comment]
线上版的Lin ui小程序示例也不现实

**Comment by uniquenaer** [comment]
感谢反馈~~争取明天修复
