### ISSUE TITLE
Checkbox-Group 多选框all数组bug

### ISSUE THREAD

**Issue by yubin2010rain** [TaleLin/lin-ui#209]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by YpchenLove** [comment]
可以提供下代码片段或者 截图吗？

**Comment by yubin2010rain** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/3079238/56777403-eeacbf80-6803-11e9-8ed9-102a66f3df36.png">
这是version": "0.0.1-alpha.20的all数组，但是后来修复了current 属性后，all数组就乱了。
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/3079238/56777424-1dc33100-6804-11e9-9f3c-00509613bc0d.png">

**Comment by YpchenLove** [comment]
3q~all属性现在是重复携带了自身的数据，这个是一个bug =-=，我现在在努力想办法修复他，这个对于目前的开发来说，有没有特别重大的影响？比如说造成了bug没法让组件继续使用？

**Comment by YpchenLove** [comment]
已经复现了该bug，明天修复后会合并到dev分支上~感谢反馈

**Comment by YpchenLove** [comment]
bug已经修复~，在分支hotfix/check上，需要可自行下载，下周三会发布合并到master上
