### ISSUE TITLE
【Bug Report】button嵌套在form中无法触发submit事件

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#21]
<form bind:submit="onSubmit">
        <l-button form-type="submit" size="large" l-class="text" >
          完成
        </l-button>
        <button form-type="submit">完成</button>
    </form>
下面那个原生的button能触发submit，l-button无法触发submit。

**Comment by chenjunup** [comment]
> tip: 目前，设置了 form-type 的 button 只会对当前组件中的 form 有效。因而，将 button 封装在自定义组件中，而 from 在自定义组件外，将会使这个 button 的 form-type 失效。

没怎么看懂。。。所以，目前不能把l-button放在form组件中使用吗？

**Comment by aQingYun** [comment]
这是微信小程序文档中注明的，暂时还不支持自定义button组件的的form-type属性。

**Comment by 7insummer** [comment]
> > tip: 目前，设置了 form-type 的 button 只会对当前组件中的 form 有效。因而，将 button 封装在自定义组件中，而 from 在自定义组件外，将会使这个 button 的 form-type 失效。
> 
> 没怎么看懂。。。所以，目前不能把l-button放在form组件中使用吗？

建议在submit的时候使用原生button，微信不支持自定义触发submit

**Comment by chenjunup** [comment]
> > > tip: 目前，设置了 form-type 的 button 只会对当前组件中的 form 有效。因而，将 button 封装在自定义组件中，而 from 在自定义组件外，将会使这个 button 的 form-type 失效。
> > 
> > 
> > 没怎么看懂。。。所以，目前不能把l-button放在form组件中使用吗？
> 
> 建议在submit的时候使用原生button，微信不支持自定义触发submit

好的，也只能这么办了。但是不是可以实现当设置form-type="submit"的时候，引用原生button，但只是改了样式？

**Comment by 7insummer** [comment]
> > > > tip: 目前，设置了 form-type 的 button 只会对当前组件中的 form 有效。因而，将 button 封装在自定义组件中，而 from 在自定义组件外，将会使这个 button 的 form-type 失效。
> > > 
> > > 
> > > 没怎么看懂。。。所以，目前不能把l-button放在form组件中使用吗？
> > 
> > 
> > 建议在submit的时候使用原生button，微信不支持自定义触发submit
> 
> 好的，也只能这么办了。但是不是可以实现当设置form-type="submit"的时候，引用原生button，但只是改了样式？

原生的button样式很难改的，我们的button是自己封装的，没有包含原生。
