### ISSUE TITLE
【Bug report】Dialog和textarea组合显示异常

### ISSUE THREAD

**Issue by Pan-Hongzhi** [TaleLin/lin-ui#217]
**重现步骤（可选）：**
1.  Dialog第二种使用方法：调用wx.lin.showDialog
2.  type:  "alert" 
3.  textarea是使用小程序原生组件，自适应高度auto-height="{{true}}"
4.  textarea使用placeholder占位
`<textarea name='detail' class="weui-textarea" placeholder="在此描述你的宝贝：如品牌、规格、成色、购买渠道、转手原因等" style="height: 3.3em" maxlength="200" auto-height="{{true}}" bindinput="handleContentInput" />`

**期望的结果是什么？**
显示正常

**实际的结果是什么？**
异常状态：Dialog弹出时，textarea的placeholder字会呈现在Dialog之上，遮挡Dialog框

**说明：**
仅测试上述条件，其他条件：如Dialog第一种使用方法、textarea替换其他属性等未进行测试

**Comment by YpchenLove** [comment]
好的，我复现一下，明天修复~

**Comment by uniquenaer** [comment]
您好，这个问题暂时无法解决，微信官方内cover-view不支持覆盖textarea的层级，只能等待微信官方处理textaera的层级之后在解决这个问题了
[textarea 层级最高的问题，覆盖住了底部固定的内容 | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002c63bf440e827afb6e838551800)
