### ISSUE TITLE
custom-tab-bar的跳转问题

### ISSUE THREAD

**Issue by cjqbaba** [TaleLin/lin-ui#219]
**期望的结果是什么？**
通过switchTab（e）方法进行跳转tab页面
**实际的结果是什么？**
无法跳转页面
建议解决方案：
1.跳转问题：在使用lin-UI提供custom-tab-bar，无法跳转，原因在于 wx.redirectTo无法跳转tab页面 wx.redirectTo({url})更正为 wx.switchTab({url})
2.   在文档中onshow()中加入this.getTabBar().setData({selected: 0})
需要判断，否则会报错，这里我参照了官方的案例进行改正
 if (typeof this.getTabBar === 'function' &&
      this.getTabBar()) {
      this.getTabBar().setData({
        selected: 0
      })
    }

**Comment by YpchenLove** [comment]
反馈已经收到，针对第一个bug，我们会修复好，第二个问题是自定义用法里的，暂时已经移除，等待微信官方对自定义的tabbar优化足够好时，再做开放。谢谢反馈哦！
