### ISSUE TITLE
【Bug Report】button要嵌套在view中size属性才能生效

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#22]
1.<l-button size="medium" />
    2.<view><l-button size="medium" /></ view>

只有在第二种情况下，并且要把 view的display设为flex  size属性才能生效

**Comment by YpchenLove** [comment]
可以查阅button组件的相关文档，具体如设置外部样式类。如果已经解决了问题，请关闭此issue，感谢~
