### ISSUE TITLE
【Bug Report】input组件 大小无法调整

### ISSUE THREAD

**Issue by landmadename** [TaleLin/lin-ui#220]
**期望的结果是什么？**
期望 l-input 组件能够自适应大小，或者是可以设置大小
最好可以设置一下input下面横条的颜色

**实际的结果是什么？**
把 l-input 组件放在一个容器里的时候，组件不会自适应大小
官方文档里没有写 width 属性 （而且用 class 设置 width 也没用）
input下面横条的大小无法设置

**我的解决方法：**
1.在文档中提及 width属性，或者提及 width无法用class设置
2.input 下面的横条设置成 动态调整的

**Comment by YpchenLove** [comment]
感谢反馈，下个版本将会修复
