### ISSUE TITLE
l-list组件bug

### ISSUE THREAD

**Issue by Chenzhiwen7** [TaleLin/lin-ui#223]
**重现步骤（可选）：**
right-desc属性定义的和 right-section插槽定义的样式不一样。原因是没加上class
**期望的结果是什么？**

**实际的结果是什么？**

**Comment by uniquenaer** [comment]
您好，不是很明白你的意思，可以附上您期望的结果的图和实际的图么？

**Comment by Chenzhiwen7** [comment]
` <l-list right-desc="请填写简介">
      </l-list>

      <l-list>
        <view slot="right-section">
          <text>请填写简介</text>
        </view>
      </l-list>`

这两种写法渲染的效果不一样。

我期望是一样的

实际效果是不一样的。

**Comment by 7insummer** [comment]
您好，插槽定义的元素的样式需要自己去设置。我们不能控制的，否则就与设计插槽的初衷——用户自定义样式和内容违背了

**Comment by Chenzhiwen7** [comment]
原来如此 了解。
