### ISSUE TITLE
按需加载组件无效

### ISSUE THREAD

**Issue by ITxiaohao** [TaleLin/lin-ui#227]
**重现步骤（可选）：** 根据文档的提示，先删除了 dist 目录，并在 component.json 填入需要的组件名，npm run build 后还是会生成全部的组件

![image](https://user-images.githubusercontent.com/18286210/57422408-8669cf00-7242-11e9-895e-7566c3a71529.png)

**期望的结果是什么？**  期望根据 component.json 配置的组件来生成

**实际的结果是什么？** 生成全部组件

![image](https://user-images.githubusercontent.com/18286210/57422441-a4cfca80-7242-11e9-930f-bf8c1236b222.png)

**Comment by YpchenLove** [comment]
收到，文档这里有一些错误，组件写在extends下即可。我会尽快修复，相关结果也会在这条issue下面回复，thanks~

**Comment by aQingYun** [comment]
问题已修复，等待最新版本发布即可。
