### ISSUE TITLE
底部导航栏的属性我用的时候有点失效

### ISSUE THREAD

**Issue by du-jassin** [TaleLin/lin-ui#228]
**重现步骤（可选）：**
我直接复制你们的gitthub上的例子到我的小程序里面，然后我尝试修改底部导航栏的属性，没有效果。也可能是我哪里写错了。
**期望的结果是什么？**
能跟文档一样。
**实际的结果是什么？**

**Comment by YpchenLove** [comment]
收到，会审查一下，相关结果会在本issue下面回复，感谢反馈~thanks

**Comment by du-jassin** [comment]
您好，那个问题我已经解决了。谢谢。是我自己的问题。


| |
杜佳欣
邮箱：jassin_du@163.com
|

签名由 网易邮箱大师 定制

在2019年05月11日 00:05，宁缺 写道：

收到，会审查一下，相关结果会在本issue下面回复，感谢反馈~thanks
