### ISSUE TITLE
希望l-radio可以额外传递一个值（如id），并以此判断是否被选中

### ISSUE THREAD

**Issue by druid985** [TaleLin/lin-ui#229]
希望l-radio可以额外传递一个值，在linchange事件中传回来，以便可以把id传给l-radiao，等用户选择后程序可以知道用户选择的id是什么。在l-radio-group中判断“哪个radio被选中”的时候，也希望用这个额外值（很可能是id）来实现。

**Comment by YpchenLove** [comment]
感谢反馈~，下个版本支持。具体属性可参见改版后的checkbox组件的事件回调

**Comment by aQingYun** [comment]
已添加，感谢反馈，下个版本即可使用。
