### ISSUE TITLE
【Bug Report】button open-type的示例代码有误

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#23]
<l-button bind:getuserinfo="getUserInfo" openType="getuserinfo"></l-button>

应该改为

    <l-button bind:getuserinfo="getUserInfo" open-type="getUserInfo"></l-button>

**Comment by aQingYun** [comment]
好的 感谢提醒

**Comment by YpchenLove** [comment]
感谢反馈，目前bug已经修复很长一段时间了，所以这个issue，我们就手动关闭了，如有其它问题，可以重新提新的issue~
