### ISSUE TITLE
button用catchtap绑定会触发两次事件 如何只触发一次且不冒泡到上级

### ISSUE THREAD

**Issue by rhinoc** [TaleLin/lin-ui#230]
**重现步骤（可选）：**
```
<view class="" wx:if="{{matched[index]}}" bindtap='onTap' data-id='{{index}}'>
        <l-button l-class="button" shape="square" width='110' catchtap='onChange' data-idx='{{index}}'>{{data}}</l-button>
 </view>
```
**期望的结果是什么？**
点击只触发一次事件，且不冒泡上级
**实际的结果是什么？**
catchtap: 触发两次事件
bind:lintap: 触发一次，会冒泡到上级
catch:lintap: 触发一次，会冒泡到上级

**Comment by YpchenLove** [comment]
如果用了l-button，需要使用bind:lintap哦，使用组件前，还是需要耐心细致的看看文档~

**Comment by rhinoc** [comment]
> 如果用了l-button，需要使用bind:lintap哦，使用组件前，还是需要耐心细致的看看文档~

使用bind:lintap的话会冒泡到上级，也就是我点击了button，button上级view的绑定的事件也会被触发。
我现在问的是如何能不冒泡到上级绑定事件。

**Comment by YpchenLove** [comment]
@aQingYun

**Comment by aQingYun** [comment]
该问题已修复，下个版本即可正常使用，感谢反馈。
