### ISSUE TITLE
textarea与popup组件组合使用遮罩会被击穿

### ISSUE THREAD

**Issue by BigYearsss** [TaleLin/lin-ui#231]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/48822698/57564818-4858e080-73e5-11e9-80a1-c76a73dbc028.png)

**期望的结果是什么？**
popup的遮罩可以阻止点击，不会击穿点击到遮罩后的组件

**实际的结果是什么？**
遮罩被击穿
![54BD47C47535AFCFBD135C26B5BFF560](https://user-images.githubusercontent.com/48822698/57564814-3414e380-73e5-11e9-86d1-dc2809d7836c.jpg)

**Comment by YpchenLove** [comment]
感谢铁子~bug已经在ios上复现，原因是textarea是微信原生组件，层级过高，需要用cover-view来重写popup组件，预计下版本修复。

**Comment by uniquenaer** [comment]
您好，我们使用cover-view之后，发现还是无法覆盖textarea的层级
[textarea 层级最高的问题，覆盖住了底部固定的内容 | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002c63bf440e827afb6e838551800)
只能等待微信官方处理textaera的层级之后在解决这个问题了

**Comment by BigYearsss** [comment]
在项目中也尝试进行修改，同样没有找到好的解决办法，谢谢
