### ISSUE TITLE
l-price组件 count-color 不起作用

### ISSUE THREAD

**Issue by kolterr** [TaleLin/lin-ui#232]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by aQingYun** [comment]
可以把具体的代码贴一下吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kolterr** [comment]
<view class='price-container l-class {{delete ? "price-del" : ""}}' style='color: {{delColor}}'>
  <slot name="before"/>
  
  <text class="l-unit-class" style="color: {{delete?delColor:unitColor}}; font-size: {{unitSize}}rpx; font-weight: {{unitBold}}">{{unit}}</text>

  <text class="l-count-class" style="color: {{delete?delColor:unitColor}}; font-size: {{countSize}}rpx; font-weight: {{countBold}}">{{count}}</text>
  <slot name="after" />
</view>

这是源代码 countColor 没有使用

**Comment by kolterr** [comment]
`<view class='price-container l-class {{delete ? "price-del" : ""}}' style='color: {{delColor}}'>
  <slot name="before"/>
  
  <text class="l-unit-class" style="color: {{delete?delColor:unitColor}}; font-size: {{unitSize}}rpx; font-weight: {{unitBold}}">{{unit}}</text>

  <text class="l-count-class" style="color: {{delete?delColor:unitColor}}; font-size: {{countSize}}rpx; font-weight: {{countBold}}">{{count}}</text>
  <slot name="after" />
</view>`

**Comment by kolterr** [comment]
`
<view class='price-container l-class {{delete ? "price-del" : ""}}' style='color: {{delColor}}'>
  <slot name="before"/>
  
  <text class="l-unit-class" style="color: {{delete?delColor:unitColor}}; font-size: {{unitSize}}rpx; font-weight: {{unitBold}}">{{unit}}</text>

  <text class="l-count-class" style="color: {{delete?delColor:unitColor}}; font-size: {{countSize}}rpx; font-weight: {{countBold}}">{{count}}</text>
  <slot name="after" />
</view>
`
 这是源代码

**Comment by kolterr** [comment]
`
func hello(){}
`

**Comment by kolterr** [comment]
`
<view class='price-container l-class {{delete ? "price-del" : ""}}' style='color: {{delColor}}'>
  <slot name="before"/>
  
  <text class="l-unit-class" style="color: {{delete?delColor:unitColor}}; font-size: {{unitSize}}rpx; font-weight: {{unitBold}}">{{unit}}</text>

  <text class="l-count-class" style="color: {{delete?delColor:unitColor}}; font-size: {{countSize}}rpx; font-weight: {{countBold}}">{{count}}</text>
  <slot name="after" />
</view>
`

**Comment by kolterr** [comment]
源代码中 没有使用countColor

**Comment by aQingYun** [comment]
文档里面就没有这个属性啊。。这个是要通过外部样式类去修改的


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kolterr** [comment]
![image](https://user-images.githubusercontent.com/29474199/57579450-87af2c00-74ce-11e9-9a99-f14baa7f22dd.png)

**Comment by kolterr** [comment]
![image](https://user-images.githubusercontent.com/29474199/57579468-c2b15f80-74ce-11e9-88b8-31391235a85a.png)

**Comment by aQingYun** [comment]
不好意思 看错了。。。我复现下 结果会回复你的


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by kolterr** [comment]
ok

**Comment by aQingYun** [comment]
已修复 下个版本即可正常使用

**Comment by kolterr** [comment]
status-show 组件  properties.custom 未定义 index.js 里面

**Comment by kolterr** [comment]
![image](https://user-images.githubusercontent.com/29474199/57703335-6c8d1980-7692-11e9-9efc-d30f66097d9e.png)
多包了一层吧
