### ISSUE TITLE
textarea和popup组件

### ISSUE THREAD

**Issue by ToWeLong** [TaleLin/lin-ui#233]
**重现步骤（可选）：**当我的popup不显示的时候  如果textarea里面有内容的话 内容就会显示在上方

**期望的结果是什么？**避内容出现在小程序上方

**实际的结果是什么？**

**Comment by ToWeLong** [comment]
![QQ图片20190512170710](https://user-images.githubusercontent.com/41502558/57580147-6ce1b500-74d8-11e9-939b-6a2f63374684.jpg)
![QQ图片20190512170715](https://user-images.githubusercontent.com/41502558/57580148-6d7a4b80-74d8-11e9-9c78-7ae16c5e37b8.jpg)

**Comment by YpchenLove** [comment]
收到，修复后会在本条issue下回复！

**Comment by uniquenaer** [comment]
您好，我们使用cover-view之后，发现还是无法覆盖textarea的层级
[textarea 层级最高的问题，覆盖住了底部固定的内容 | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002c63bf440e827afb6e838551800)
只能等待微信官方处理textaera的层级之后在解决这个问题了
