### ISSUE TITLE
希望添加一个文本域清空的一个方法

### ISSUE THREAD

**Issue by ToWeLong** [TaleLin/lin-ui#234]
**描述你希望的支持的新功能？**当文本框的内容提交后自动清空文本域

**你期望的 API 是怎样的？**当文本框的内容提交后自动清空文本域

**Comment by ToWeLong** [comment]
这个问题还没有解决么

**Comment by juzi214032** [comment]
不好意思，回复晚了，请问在提交之后手动设置一下value值为空字符串不能实现您的需求吗

**Comment by ToWeLong** [comment]
> 不好意思，回复晚了，请问在提交之后手动设置一下value值为空字符串不能实现您的需求吗

还是没有用的，手动设置value值无效

**Comment by juzi214032** [comment]
您好 我刚才测试了一下 是可以清空的
```html
<l-textarea value="{{testValue}}" style="width:100%" indicator="{{false}}"  placeholder="说说你的想法吧..."/>
```

```js
// 在你提交之后设置空字符串即可
this.setData({
      testValue:''
})
```

**Comment by ToWeLong** [comment]
> 您好 我刚才测试了一下 是可以清空的
> 
> ```
> <l-textarea value="{{testValue}}" style="width:100%" indicator="{{false}}"  placeholder="说说你的想法吧..."/>
> ```
> 
> ```js
> // 在你提交之后设置空字符串即可
> this.setData({
>       testValue:''
> })
> ```

好的我试试看，很早前是没用的
