### ISSUE TITLE
按需加载组件能否打包该组件的依赖组件

### ISSUE THREAD

**Issue by ITxiaohao** [TaleLin/lin-ui#237]
**描述你希望的支持的新功能？**

我根据 component.json 中的配置打包出了两个组件，分别是 button 和 input

```js
{
  "extends": ["button", "input"]
}
```

但是这里还会多生成两个带 image 的文件，分别为 image-picker 和 status-show，翻阅代码发现

```js
gulp.task('copy', () => {
  return gulp.src('../src/**/image/**').pipe(gulp.dest('../dist/'));
});
```

是直接将 src 下包含 image 的文件全部 copy 到 dist 目录下

可以加个过滤条件吗，比如我按需加载的组件里没有 image，就不用打包出来，还有一个 feature 建议

```js
{
  "component": true,
  "usingComponents": {
    "l-icon":"../icon/index"
  }
}
```

打包出来的 button 组件，内部有依赖 l-icon 组件，如果我直接使用 button，却没有 l-icon肯定也
会有问题，能不能也将组件所依赖的组件也一起打包出来呢

**Comment by aQingYun** [comment]
目前正在修改 感谢反馈


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by briquet0605** [comment]
请问直接npm run build就可以呢，还是还需要装gulp

**Comment by aQingYun** [comment]
问题已修复，请等待最新版本发布。
