### ISSUE TITLE
通告栏，动态赋值不起作用

### ISSUE THREAD

**Issue by dreamkill** [TaleLin/lin-ui#239]
**重现步骤（可选）：**
`<l-notice-bar type="roll" front-icon-name="notification">{{notice}}</l-notice-bar>`
**期望的结果是什么？**
滚动
**实际的结果是什么？**
不滚动
在写死值得时候是好用的，动态赋值就不好用了

**Comment by aQingYun** [comment]
感谢反馈 ，bug会尽快修复。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by dreamkill** [comment]
有人在修复这个问题吗？
在data中直接赋值是没问题的
在onLoad中有个网络请求就不好用了

**Comment by aQingYun** [comment]
正在修复 你说的网络请求不起作用是内容没有显示吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by dreamkill** [comment]
目前是开发工具时好时坏，在手机是好用的。。。，你们也可以忽略了
