### ISSUE TITLE
custom-tab-bar 事件问题

### ISSUE THREAD

**Issue by lxc939134342** [TaleLin/lin-ui#240]
**描述你希望的支持的新功能？**

bind:lintap 添加一个path 路径的返回值

**你期望的 API 是怎样的？**

bind:lintap （detail）只有一个当前下标的返回值，对于自定义事件方法太过局限
希望能够增加一个path返回值

**Comment by 7insummer** [comment]
感谢反馈，会考虑在新版本中加入的~
