### ISSUE TITLE
倒计时组件扩展增加距离指定时间过去多久的功能

### ISSUE THREAD

**Issue by zhc525349965** [TaleLin/lin-ui#246]
**描述你希望的支持的新功能？**
可以指定一个过去的日期，例如：2018.08.08 18:08:08   计时器显示距离这个时间已经过去久。 例如显示为 XX天XX分XX秒 。如指定时间没精确到时分秒，则默认当天00:00:00（假设这种纪念日功能叫做正计时模式）

**你期望的 API 是怎样的？**
增加一个属性，用来区别是倒计时模式还是正计时模式。默认倒计时模式，不影响当前组件使用。
增加一个属性指定过去的时间。当模式为正计时模式时显示距离指定时间过去多久。

**Comment by uniquenaer** [comment]
感谢建议~~会在后续版本之中加上这个功能的

**Comment by zhc525349965** [comment]
close as solved
