### ISSUE TITLE
倒计时组件跳转页面回退后倒计时停止

### ISSUE THREAD

**Issue by geekwill** [TaleLin/lin-ui#247]
**重现步骤（可选）：**
1: 使用倒计时的页面，第一次进入时正常倒计时，但是当跳转页面在退回次页面时，倒计时停止。
2: 如何倒计时time值为空，但页面加载完后setState time为新值时，倒计时未启动。(因为我的倒计时时间是从后台获取的，页面加载完请求好数据后才开始的倒计时，我发现倒计时一直是00000，且setState时间后并未开始倒计时)

**期望的结果是什么？**
虽然倒计时页面隐藏或者销毁是需要停止销毁倒计时，但是在页面进入或再次显示时应该是需要在重启倒计时的吧

**Comment by uniquenaer** [comment]
收到反馈，这个bug会在下周更新版本中修复
