### ISSUE TITLE
弹出层 Popup嵌套文本域 Textarea样式混乱问题

### ISSUE THREAD

**Issue by AnkerLeng** [TaleLin/lin-ui#254]
**重现步骤（可选）：**

**期望的结果是什么？**

![5703432818EB98902D58917ACC0FE598](https://user-images.githubusercontent.com/15144679/58064861-5c0b0080-7bb6-11e9-846f-abcfa19549db.jpg)

**实际的结果是什么？**
![B4280FADD862155721CABECB9C35AAC8](https://user-images.githubusercontent.com/15144679/58064849-544b5c00-7bb6-11e9-8439-a2da5fb32a7f.jpg)

有没有什么替代方案？

**Comment by aQingYun** [comment]
感谢反馈，目前这个问题已经在解决了

**Comment by aQingYun** [comment]
这个问题是微信的 Textarea层级的问题，暂时还没有考虑到比较好的解决方案。给你造成的不便敬请谅解！
