### ISSUE TITLE
文档中popup命名错误

### ISSUE THREAD

**Issue by SureLam** [TaleLin/lin-ui#259]
![@V_R_N(C{ }D5PY@VPR ~2M](https://user-images.githubusercontent.com/50863582/58078556-9f2e9900-7be1-11e9-88d3-e13cb75fa5da.png)
lin ui 的 官方文档 里面 popup 写错了。。

**Comment by aQingYun** [comment]
已修改 感谢反馈


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
