### ISSUE TITLE
dialog 组件type不能修改

### ISSUE THREAD

**Issue by hyyyyyy** [TaleLin/lin-ui#266]
**重现步骤（可选）：**

**期望的结果是什么？*只有一个确定键*

**实际的结果是什么？*type不管是alert还是confirm取消键都在*

**Comment by uniquenaer** [comment]
您好，麻烦提供一下可复现的示例代码给我们~

**Comment by aQingYun** [comment]
两种方法的type设置是不相同的，您使用的是那种用法？wx.lin.showDialog这种？
