### ISSUE TITLE
checkbox自己控制checked属性点击没反应问题

### ISSUE THREAD

**Issue by ForrestSnape** [TaleLin/lin-ui#267]
`<l-checkbox checked="{{demoFunc(id)}}" bind:linchange="demoChange" />`
如果checked需要我自己控制（demoFunc里面挺复杂的，需要跟很多个checkbox联动），
当我点击触发linchange时，我的demoChange方法会做些处理使得demoFunc(id)为true，
下面是checkbox源码
`// 点击 checkbox
    onCheckBoxChangeTap() {
      if (this.data.disabled) return;
      const item = {
        current: !this.data.checked,
        value: this.data.value,
        detail: this.data.detail,
        all: null
      };
      const parent = this.getRelationNodes('../checkbox-group/index')[0];
      parent ? parent.onEmitEventHandle(item) : this.triggerEvent('linchange', item);
      // parent ? console.log('') : this.onChangeHandle(true);
      this.setData({
        checked: !this.data.checked
      })
    }`
问题在于，未选中状态下，this.data.checked为false，点击选择，走到`this.triggerEvent('linchange', item);`这里，
我的demoFunc(id)会把checked设为true并传回组件中，此时this.data.checked已经为true了，再下面的
` this.setData({
        checked: !this.data.checked
      })`又会把checked设为false，导致页面出现点击没反应的现象。
我建议：
要么在函数开头用一个临时字段记录this.data.checked，current和setData都以此临时字段判断；
要么把setData置于triggerEvent之前。

**Comment by uniquenaer** [comment]
感谢反馈，这个问题我们复现后会尽快解决

**Comment by YpchenLove** [comment]
是单独使用了checkbox？ 还是和checkbox-group一起使用？

**Comment by ForrestSnape** [comment]
> 是单独使用了checkbox？ 还是和checkbox-group一起使用？

单独使用checkbox

**Comment by YpchenLove** [comment]
@ForrestSnape 和checkbox-group一块使用

**Comment by zhc525349965** [comment]
close as solved
