### ISSUE TITLE
icon图标,怎样新增?

### ISSUE THREAD

**Issue by kuwo2016** [TaleLin/lin-ui#268]
尝试从 https://www.iconfont.cn/ 选择好自己要的图标,并下载好代码,按文档添加到组件CSS样式中去,但是不能使用.老师能不能给个添加icon图标的示例,或者方法步骤.

**Comment by kuwo2016** [comment]
我已经解决了,原来,新增自定义的图标,是将下载下来的代码放到自己小程序项目的css样式文件中,而不是放在icon组件的css样式文件,是我理解偏了.

**Comment by 7insummer** [comment]
自己解决问题的能力很棒哦~~

可以多看看小程序的示例demo里的代码，组件的使用一般都在示例demo里有代码
