### ISSUE TITLE
tabs 组件，为什么不能随内容而撑开高度 版本0.3.0

### ISSUE THREAD

**Issue by junxian123** [TaleLin/lin-ui#269]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by uniquenaer** [comment]
不知道你的具体场景是什么，建议使用segment组件替代

tabs组件在设置swiperable为true时，内部实现使用的是微信内的swiper组件，swiper组件自带高度和宽度，必须自己计算。
