### ISSUE TITLE
notice-bar 组件 设置不显示时

### ISSUE THREAD

**Issue by Yang-yibu** [TaleLin/lin-ui#27]
** 重现步骤（可选）：**
1 直接下载下来源码运行 `npm run dev`，将 examples 中的代码直接拷贝到项目中报错

拷贝的源码
```html
<l-notice-bar 
    style="margin-bottom:20rpx" 
    show="{{showIcon}}" 
    bind:lintap="handleIcon" 
    type="roll" 
    front-icon-name="notification" 
    end-icon-name="close"
>我是通告栏我是通告栏我是通告栏我是通告栏我是通告栏我是通告栏</l-notice-bar>
```

直接报错了
```
Cannot read property 'width' of null;at SelectorQuery callback function
TypeError: Cannot read property 'width' of null
```

** 期望的结果是什么？**
设置  `show={{showIcon}}` ，不显示 NoticeBar , 时不报错。
> 因为是源码里直接拷贝的代码，showIcon 以为是控制 显示 图标的，没细想结果导致报错；还花了挺长时间找错误

** 实际的结果是什么？**

**Comment by Yang-yibu** [comment]
这是代码片段

https://developers.weixin.qq.com/s/c81X0lmh7B56

**Comment by 7insummer** [comment]
我们尽快查看 @aQingYun

**Comment by YpchenLove** [comment]
本issue的问题已经解决，我们将关闭它，如果有其他疑问，可以重新提出issue~ 感谢反馈
