### ISSUE TITLE
l-list组件如何绑定open-type

### ISSUE THREAD

**Issue by rhinoc** [TaleLin/lin-ui#270]
**重现步骤（可选）：**

**期望的结果是什么？**
`<l-list title="帮助" image="../../images/help.svg" open-type="contact"  is-link="{{false}}"/>`
能进入客服会话
**实际的结果是什么？**
无法进入客服会话

**Comment by rhinoc** [comment]
目前的解决办法：`<l-list title="帮助" image="../../images/help.svg" is-link="{{false}}">
<view slot="right-section"><button class='service-button' open-type='contact'>placeholder</button></view></l-list>`
`.service-button{
  opacity: 0;
  display: inline-block;
  line-height: 88rpx;
  position: absolute;
  left:75rpx;
  width: 80%;
  margin-top: -44rpx;
}`

**Comment by aQingYun** [comment]
l-list外边包裹一层l-button就可以了 具体用法看button组件文档


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
