### ISSUE TITLE
微信小程序端通过npm获取的linui某些组件缺少css样式

### ISSUE THREAD

**Issue by kuwo2016** [TaleLin/lin-ui#271]
**重现步骤（可选）：**
通过npm获取linui源码,在调用宫格组件时,宫格按钮的下的文字很大,和linui演示小程序中不一样,然后去查看宫格组件css样式,确定缺少对 text 的css定义,但是github 源码dist中有.
**期望的结果是什么？**
希望通过npm获取的代码可以获取完整的代码.
**实际的结果是什么？**

**Comment by aQingYun** [comment]
你说的是示例代码的css样式吧 那个文件是在example文件里面的 npm包里面只有组件的css 没有关于文字的css代码


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
