### ISSUE TITLE
search-bar里面的 onCancel 方法是不是忘了写了？

### ISSUE THREAD

**Issue by ForrestSnape** [TaleLin/lin-ui#274]
**重现步骤（可选）：**
搜索栏点击取消 提示我没有onCancel  我去看了真没有
**期望的结果是什么？**
是不是忘了写了
**实际的结果是什么？**
`onCancel() {
      this.triggerEvent('onCancel', {});
    },`

**Comment by aQingYun** [comment]
感谢反馈 这个地方确实少了这个方法
