### ISSUE TITLE
如何解决swiper高度适配的问题

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#275]
##### 问题

>  重现https://developers.weixin.qq.com/community/develop/doc/00008aaf4a473056d1c69a8b253c04?highLine=swiper%25E8%2587%25AA%25E9%2580%2582%25E5%25BA%2594%25E9%25AB%2598%25E5%25BA%25A6 思路4实现固定高度适配

##### 代码片段

> tabs/index.wxml
> ```
> <swiper wx:else class="l-tabpanel-content l-tabpanel-swiper l-class-content" bindchange="swiperChange" current="{{currentIndex}}" vertical="{{placement=='left'||placement=='right'}}" style="height:{{swiper_height}}">
>     <swiper-item class="l-tabpanel {{item.key===activeKey?'l-tabpanel-active':''}}" wx:for="{{tabList}}" wx:key="{{item.key}}">
>     	<view id="start{{isIndex}}"></view>
>     	<slot name="{{item.key}}"></slot>
>     	<view id="end{{isIndex}}"></view>
>     </swiper-item>
> </swiper>
> ```

>tabs/index.js
>```js
>    ready() {
>      this.initTabs();
>      //首次加载swiper高度
>      this.autoHeight();
>   	},
>        
>	swiperChange(e) {
>        const {
>            source,
>            current
>        } = e.detail;
>        if (source == 'touch') {
>            const currentIndex = current;
>            const activeKey = this.data.tabList[current].key;
>            this._setChangeData({
>                activeKey,
>                currentIndex
>            });
>            //swiper事件改变后重新加载容器高度
>            this.setData({
>                isIndex: e.detail.current
>            });
>            this.autoHeight();
>        }
>    },
>
>    autoHeight() {
>        let isIndex = this.data.isIndex;
>        console.log('isIndex',isIndex);
>        this.createSelectorQuery()
>            .select('#end' + isIndex).boundingClientRect()
>            .select('#start' + isIndex).boundingClientRect().exec(rect => {
>            console.log('rect',rect);
>            let _space = rect[0].top - rect[1].top;
>            _space = _space === 0 ? '100%' : _space + 'px';
>            this.setData({
>                swiper_height: _space
>            });
>            console.log('swiper_height', _space); //输出的高度是150px
>        })
>    }
>```
> 请问下为什么这样设置会不起作用呢？

**Comment by aQingYun** [comment]
这个问题你可以加群去问下其他同学 issue主要处理bug
