### ISSUE TITLE
l-tabs 组件swipeable属性会影响swiper显示问题

### ISSUE THREAD

**Issue by zhc525349965** [TaleLin/lin-ui#277]
**重现步骤（可选）：**
1.l-tabs组件中swipeable属性设置为true（即允许滑动切换）
2.在l-tabpanel中设置swiper组件，并在swiper中增加轮播图片（2张即可）
3.在swiper组件下方增加任意组件

**期望的结果是什么？**
swipeable为true时，不应该影响到swiper组件的显示及排在swiper后方组件的显示，这些组件显示不出来
**实际的结果是什么？**
swipeable为true时，swiper组件及排在swiper后方的组件显示不出来

下方的示例代码，swiper及<text>swiper下方</text>显示不出来，将swipeable去除或设置为false即可正常显示

示例代码：
<view class="index-container">
    <l-tabs swipeable="{{true}}" equal-width="{{true}}">
        <l-tabpanel tab="京东物流" key="one" slot="one">
            <view class="tabpanel-container">
                <text>swiper上方</text>
                <view class="swiper-container">
                    <swiper autoplay="{{true}}" circular="{{true}}">
                        <swiper-item item-id="1">
                            <view class="swiper-item">
                                <image class="swiper-item-image" src="/images/index/banner1.jpg" />
                            </view>
                        </swiper-item>
                        <swiper-item item-id="1" class="swiper-item">
                            <image class="swiper-item-image" src="/images/index/banner2.jpg" />
                        </swiper-item>
                    </swiper>
                </view>
                <view>
                    <text>swiper下方</text>
                </view>
            </view>
        </l-tabpanel>
        <l-tabpanel tab="品牌" key="two" slot="two">
            <view class="tab-content">品牌</view>
        </l-tabpanel>
    </l-tabs>
</view>

**Comment by zhc525349965** [comment]
`<view class="index-container">
    <l-tabs swipeable="{{false}}" equal-width="{{true}}">
        <l-tabpanel tab="京东物流" key="one" slot="one">
            <view class="tabpanel-container">
                <text>swiper上方</text>
                <view class="swiper-container">
                    <swiper autoplay="{{true}}" circular="{{true}}">
                        <swiper-item item-id="1">
                            <view class="swiper-item">
                                <image class="swiper-item-image" src="/images/index/banner1.jpg" />
                            </view>
                        </swiper-item>
                        <swiper-item item-id="1" class="swiper-item">
                            <image class="swiper-item-image" src="/images/index/banner2.jpg" />
                        </swiper-item>
                    </swiper>
                </view>
                <view>
                    <text>swiper下方</text>
                </view>
            </view>
        </l-tabpanel>
        <l-tabpanel tab="品牌" key="two" slot="two">
            <view class="tab-content">品牌</view>
        </l-tabpanel>
    </l-tabs>
</view>`

**Comment by uniquenaer** [comment]
您好，您附的示例图片不可见，并且没有复现出来您的问题，我这里swiper是可见的
<img width="386" alt="Screen Shot 2019-05-28 at 5 49 50 PM" src="https://user-images.githubusercontent.com/17964628/58468901-08c61e80-8171-11e9-8f1e-26bbaaba35ce.png">

**Comment by zhc525349965** [comment]
把上面的代码拷贝到本地，然后替换swiper-item中image的src，让图片可以显示，这时“swiper下方”文字是可以显示的。将swipeable="{{false}}"改为swipeable="{{true}}"，“swiper下方”文字就不会正常显示

**Comment by uniquenaer** [comment]
swipeable="{{true}}"时，是有默认高度的，内容超出高度被隐藏掉了。
内部实现时用的微信swiper组件，高度可以通过外部样式类的方式覆盖默认值

**Comment by zhc525349965** [comment]
好的，感谢回复。

**Comment by zhc525349965** [comment]
close as solved
