### ISSUE TITLE
选项卡组件l-segment 在flex布局，头部底部固定中间滚动，下面横线样式看不到。

### ISSUE THREAD

**Issue by kuwo2016** [TaleLin/lin-ui#278]
**重现步骤（可选）：**
index.wxml
`<view class='wraper'>
  <view class='header'>
  <l-segment active-key="one" segment="top" bind:linchange="changeTabs">
    <l-segment-item tab="最新" key="one" dot-badge="{{true}}" />
    <l-segment-item tab="排行榜" key="two" badge-count="" />
    <l-segment-item tab="Office技巧" key="three" badge-count="" l-class-badge="badge-view" />
    <l-segment-item tab="随笔" key="four" />
  </l-segment>
  </view>
  <view class='main'>
    <scroll-view class='main-scroll' scroll-y style="height: 100%">
      <view class='main-list'>
        <view class='card' wx:for="{{cardList}}">
          <view class='card-box'></view>
          <view>{{item.name}}</view>
          <view class='card-content'>{{item.content}}</view>
        </view>
      </view>
    </scroll-view>
  </view>
  <view class='footer'>footer</view>
</view>
`
index.js
`Page({

  /**
   * 页面的初始数据
   */
  data: {
    cardList: [
      {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      }, {
        name: 'aa',
        content: 'bb'
      },
    ]
  },
})`
index.wxss
`page{
  width: 100%;
  height:100%;
}
 
.wraper{
  display: flex;
  flex-direction: column;
  width: 100%;
  height:100%;
}
 
.header{
  color: #fff;
  line-height: 100rpx;
  flex: 0 0 100rpx; /* 不放大不缩小固定100rpx */
}
 
.main{
  flex: 1;
  position: relative;
}
 
.main-scroll{
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
}
 
.main-list{
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  margin-left: 2vw;
  margin-right: 2vw;
}
 
.card{
  width: 47vw;
  margin-top: 10rpx;
  margin-bottom: 10rpx;
}
 
.card-box{
  width: 100%;
  height: 200rpx;
  border-radius: 6rpx;
  background: #ccc;
}
 
.card-content{
  color: blue;
}
 
.footer{
  background: rgb(8, 117, 94);
  color: #fff;
  line-height: 100rpx;
  flex: 0 0 100rpx; /* 不放大不缩小固定100rpx */
}
`
**期望的结果是什么？**
选项卡组件l-segment，在flex布局中，能显示选项下面的横线
**实际的结果是什么？**
选项卡组件l-segment，在flex布局中，不能显示选项下面的横线。就算是用微信小程序原生scroll-view组件，也不能显示选项下的横线。

**Comment by uniquenaer** [comment]
您好，横线不显示与flex布局无关，与你在header中设置的`line-height:100rpx`有关,这个属性被组件内部继承导致高度超出被隐藏，
您可以通过l-class 设置外部样式类覆盖默认高度

**Comment by kuwo2016** [comment]
谢谢老师的解答,我已经解决了问题.

**Comment by zhc525349965** [comment]
close as solved
