### ISSUE TITLE
l-tabs源码的第150行-153行有问题

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#279]
**重现步骤（可选）：**
1. 去掉  .l-tabs .l-tabs-header .l-tabs-equal-width 的 flex:1
2. 外部样式设置 l-class-inactive与l-class-active的宽度为62.5px
3. 在源码的149行添加console.log(res.left)
3. 滑动l-tabpanel，打印信息为 62.5、63、124.5、126、186.5、189、248.5.、...

**期望的结果是什么？**
- 打印信息为：62.5、125、187.5、....

**Comment by uniquenaer** [comment]
收到反馈，会尽快确认一下问题，并修复~

**Comment by KDWangBoss** [comment]
嗯嗯，好的，感觉好像是小程序scroll-view获取节点有误差。
![Animation](https://user-images.githubusercontent.com/40023056/58615117-db05e480-82ec-11e9-9cc0-e3539ed2c868.gif)
像这个第一次滑动的时候向右滚动了62.5，第二次的时候就不正常了

**Comment by uniquenaer** [comment]
麻烦提供一下相关的代码片段吧~
