### ISSUE TITLE
Tabs 内容 显示不全；不能滑动

### ISSUE THREAD

**Issue by Yang-yibu** [TaleLin/lin-ui#28]
** 重现步骤（可选）：**

代码片段：https://developers.weixin.qq.com/s/6f4TllmU7k5r

![image](https://user-images.githubusercontent.com/23130670/51015875-ced0f300-15a8-11e9-80f4-24a13da80951.png)

** 期望的结果是什么？**

想做到的效果 
类似于 饿了么 的商品列表，点击左侧分类，右侧显示滚动到响应的位置；滑动右侧的商品，左侧显示响应的分类自动切换；

** 实际的结果是什么？**

#14 修改前 内容能显示，但是滑动商品时，分类下的商品没触底就切换标签页了；
![2](https://user-images.githubusercontent.com/23130670/51015808-8d404800-15a8-11e9-975c-27739674b3fc.gif)

#14 修改后，（尝试修改样式暂时没奏效）
![image](https://user-images.githubusercontent.com/23130670/51015748-5cf8a980-15a8-11e9-9f7a-8e4fda66423c.png)

**Comment by Yang-yibu** [comment]
最后一个图（图3）是代码片段中的，倒数第二个（图2）是 项目中的；我把 #14 修改后的代码放到项目后，表现与 图3 一致

**Comment by uniquenaer** [comment]
代码片段打开没有内容，麻烦再提供一下可以么？便于我们尽快的定位问题在哪里

**Comment by uniquenaer** [comment]
> 最后一个图（图3）是代码片段中的，倒数第二个（图2）是 项目中的；我把 #14 修改后的代码放到项目后，表现与 图3 一致
新版本中已解决~~
