### ISSUE TITLE
combined-tabs组件：一个subKey设置时的小bug

### ISSUE THREAD

**Issue by wushuangabao** [TaleLin/lin-ui#282]
**重现步骤：**

将示例pages/nav/pages/combined-tabs/index.js中的dubbleTabs数据改为下面这样：

```
dubbleTabs: [{
          tab: '女装',
          key: 'women',
          subKey: 0,
          subTab: '鞋'
        },
        {
          tab: '女装',
          key: 'women',
          subKey: 1,
          subTab: 'T恤衫',
        },
        {
          tab: '男装',
          key: 'men',
          subKey: 2,
          subTab: '衬衫'
        }
      ]
```

**期望结果：**

**女装-鞋的内容**可以正常显示成“鞋”

**实际结果：**

无法显示**女装-鞋的内容**

**找到问题的原因：**

后来我将`subKey: 0`改为`subKey: '0'`，就正常了。

不是很理解wx:key的机制，我只能认为是wx:key设成数字0的话会被认为是“无”。

建议lin-ui文档里写明一下这个注意点。

**Comment by uniquenaer** [comment]
感谢反馈~会优化一下处理key的机制，预计下个版本时会优化好这个问题

**Comment by uniquenaer** [comment]
您好，subkey可接受的值的类型是 `string`，这个是在文档内说明了的。内容不显示是因为组件接收的值和传入的值类型不统一有关，跟wx:key 无关。
