### ISSUE TITLE
combined-tabs：新增一个控制高度的属性

### ISSUE THREAD

**Issue by wushuangabao** [TaleLin/lin-ui#283]
**希望支持的新功能**

我使用l-combined-tabs组件时，在slot中使用了若干个l-list组件。
当list的数量过多，所有list的总高度**超过**combined-tabs组件的高度时，后面的list无法完全显示。

因此我希望给combined-tabs增加一个height属性，可以通过它改变整个组件的高度。

**期望的API** 

给combined-tabs自定义组件增加一个height属性，控制它里面两个swiper组件的高度样式。

**其他**

非计算机专业学生，业余时间写小程序，所以用lin-ui的次数不多。不过感到它确实对开发效率很大有提升。
l-tabs组件还没用到过，它应该也有类似需求。

**Comment by uniquenaer** [comment]
感谢建议，我们会评估后再回复你~

**Comment by juzi214032** [comment]
CombinedTabs 组件已新增 l-content-class 外部样式类用于控制高度
