### ISSUE TITLE
使用segment出现了问题

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#285]
**重现步骤（可选）：**
页面用wx:if切换的时候出错，找不到具体原因

**实际的结果是什么？**
![点击复制标题搜索框出现了问题](https://user-images.githubusercontent.com/40023056/58679839-bca8f300-8397-11e9-9682-f580b3132226.gif)

**Comment by uniquenaer** [comment]
麻烦提供一下可复现的代码片段

**Comment by KDWangBoss** [comment]
https://developers.weixin.qq.com/s/QXNbQQmh7j82

**Comment by KDWangBoss** [comment]
这里有2个问题
问题1：使用组件切换segment出现了问题
问题2：设置toast的center为false，但toast不居中

**Comment by uniquenaer** [comment]
一个issues处理一个问题哈，toast ceter不生效的问题，已经在处理了

**Comment by KDWangBoss** [comment]
###### 复现步骤：
> segment设置scrollable为true， segment-item 设置slot
>循环10个segment-item

###### 实际结果：
> 出现 Uncaught (in promise) 找不到元素
