### ISSUE TITLE
l-toast 设置center 为false不起作用

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#286]

**Comment by YpchenLove** [comment]
@KDWangBoss 看一下代码，false需要加{{}}

**Comment by KDWangBoss** [comment]
试过了的，应该是源码有问题，在index.xml里我找了下好像没有引用center

**Comment by YpchenLove** [comment]
这个是设计之初考虑到toast除了垂直居中弹出，还有一些app里，会让toast显示在底部，所以当时设计了这个api接口。
但是在后续的开发过程里，我们发现toast是要给人最直接的反馈和提示，显示在正中央会更合适！
这个功能就pass了qaq，但是文档和源码里都没有删除这个api，给大家造成了误解。不好意思，今天就会修复！ 0.0

**Comment by YpchenLove** [comment]
http://doc.mini.7yue.pro/component/response/toast.html#

**Comment by KDWangBoss** [comment]
可以保留吗，有些时候感觉在底部提示会比较好看点，比如用户用手点击的时候在中间弹出的提示很容易被忽略😂
