### ISSUE TITLE
countdown组件正计时模式，超过999天，布局显示错误

### ISSUE THREAD

**Issue by zhc525349965** [TaleLin/lin-ui#287]
**重现步骤（可选）：**
`<l-countdown countdownType="anniversary" time="1989-01-01"></l-countdown>`
**期望的结果是什么？**
超过999天，外面的数字包裹框可以动态改变大小，将天数显示完全
**实际的结果是什么？**
超过999天，数字会被遮挡一部分

![image](https://user-images.githubusercontent.com/43640797/58770778-7b0c8800-85e3-11e9-8d94-fc262490ae6e.png)

**Comment by uniquenaer** [comment]
您好，组件里提供了修改数字包裹框的样式的外部样式类，可以通过这个修改样式~http://doc.mini.7yue.pro/component/view/countdown.html#%E5%80%92%E8%AE%A1%E6%97%B6-countdown-attributes%EF%BC%89

**Comment by zhc525349965** [comment]
好的，感谢回复。

**Comment by AilonHuang** [comment]
可以添加年和月这种格式把，比如2019年6月1日开始，到2019年7月1日就显示`1月0天`，7月2号就显示`1月1天`，到2020年6月1日就显示`1年0月0天`

**Comment by zhc525349965** [comment]
close as solved
