### ISSUE TITLE
支持组件data-**的自定义参数属性

### ISSUE THREAD

**Issue by qiuchengguang** [TaleLin/lin-ui#289]
**描述你希望的支持的新功能？**
在组件中支持data-**的应用
**你期望的 API 是怎样的？**
html:
  <i-input-number square="{{ true }}"  id="{{ item.shop_cart_id }}" data-count="{{ item.goods_count }}" data-idx="{{ index }}" size="large" disabled="{{ false}}" custom-class="custom-btn" value="{{ item.goods_count }}" min="1" max="{{ item.stock || 999 }}"  bindchange="itemCountNumChange" />
js
itemCountNumChange({ currentTarget, detail }) {
    const sp_list =  pageModel.clone(this.data.cardList) // 这个从全局data中获取购物的列表
    const { dataset, id } = currentTarget  // 这个从 自定义参数中获取 id 和别的东西 A
    const { value, type } = detail         // 这个从 组件中知道这个组件返回的数量和加减操作 B
    sp_list[dataset.idx].goods_count = value // A+B
    this.setData({                            // A+B
      cardList: sp_list
    })
你可以看到iview的这个组件，他里面是没有说过可以嵌套data-**这类型的自定义参数的，但是我在现在这套源码上看到别人运用的时候是可以用这类型的自定义参数的，并且在点击触发的函数的时候是可以传一个{currenttarget，detail}，这类型的数据出来，而我的疑问是，data—**这样的自定义参数在我们编写组件的时候是怎么可以把它写上去，欢聚话就是说我怎么编写组件才可以做到能像普通的view容器一样运用data-**这类型的自定义参数

**Comment by uniquenaer** [comment]
data-*直接使用即可，自定义组件同样支持data-*自定义属性

**Comment by zhc525349965** [comment]
close as solved
