### ISSUE TITLE
【Feature Request】自定义选项内容的单选框和复选框

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#29]
** 描述你希望的支持的新功能？**
radio和checkbox可以自定义选项内容
** 你期望的 API 是怎样的？**

    <l-radio-group DIY="{{true}}">
        <l-radio /> 
    </l-radio-group>

当在l-radio-group设置DIY属性为true时，下面的radio可以不传value，在后面跟一个输入框，输入自定义的内容。CheckBox也类似。

**Comment by YpchenLove** [comment]
设置custom为true 时，即可传入slot。
详见文档：http://doc.mini.7yue.pro/component/form/radio.html
如解决了疑问，请在下方回复~谢谢反馈。

**Comment by chenjunup** [comment]
> 设置custom为true 时，即可传入slot。
> 详见文档：http://doc.mini.7yue.pro/component/form/radio.html
> 如解决了疑问，请在下方回复~谢谢反馈。

不好意思，没看到。但好像还是有疑问，我需要checked与自定义的value值绑定，如果传插槽进去，那checked为true时，绑定的value值是什么？

**Comment by YpchenLove** [comment]
文档在自定义这里描述的不清楚，我会添加上，同时对组件做一些调整。感谢反馈

**Comment by YpchenLove** [comment]
插入slot时，依然需要设置value属性，并且在每次选中项更改或则增加的时候，radio-group和checkbox-group都会有事件监听到value的改变。开发者只需要记住自己设置的value对应的是哪个自定义的slot即可。具体的方法会在本周三更新文档。

**Comment by chenjunup** [comment]
> 插入slot时，依然需要设置value属性，并且在每次选中项更改或则增加的时候，radio-group和checkbox-group都会有事件监听到value的改变。开发者只需要记住自己设置的value对应的是哪个自定义的slot即可。具体的方法会在本周三更新文档。

嗯。但是，我想要的需求是，双向绑定value，也就是说既可以在代码里传value值，也可以在界面上放空的CheckBox，然后在里面自定义输入内容。

**Comment by YpchenLove** [comment]
这个"放空"是什么意思啊，我再解释一下，拿radio为例，
1. radio的value属性是要写入一个有效值的，当我们不需要插入slot的时候，value的值会显示在radio组件内，每次更改选项，在group上都会监听到改变，可以打印查看。
2 . 插入slot的情况，这个时候custom 属性需要设置为true。value的值在radio组件内不显示，只显示你插入的slot的内容。
同时，每次radio选项变动，都会在group上监听到值的改变，也就是绑定在value。
3，不管是是否插入slot。我们在每次选中项的时候，都需要知道我们改变的是哪个选项，所以value是必须要写进去的~
ps：如有其它问题，可以继续提问。

**Comment by YpchenLove** [comment]
追加一条，很感谢你的积极反馈，并帮助lin-ui完善。thanks~
