### ISSUE TITLE
使用card组件时，无事件点击监听函数，需要手动修改源码。

### ISSUE THREAD

**Issue by rainysweet** [TaleLin/lin-ui#290]
**描述你希望的支持的新功能？**
使用card组件时能和grid和list组件一样，有类似的点击监听方法。
**你期望的 API 是怎样的？**
既然同为界面组件，可以在使用方法上保持一致就好。

**Comment by aQingYun** [comment]
card组件一般适用于文件列表、商品列表等场景，所以使用bindtap事件监听更好，这样可以接受到data-传入的数据。感谢反馈。
