### ISSUE TITLE
【Bug Report】raido组件checked属性失效

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#30]
** 重现步骤（可选）：**

    <l-radio-group>
        <l-radio value="北方"  checked="{{true}}" /> 
        <l-radio value="南方"  checked="{{false}}" /> 
    </l-radio-group>

** 期望的结果是什么？**
渲染的结果应该是 "北方" 被选中，“南方”没选中

** 实际的结果是什么？**
 "北方" 和“南方”都没被选中，放在l-radio-group中 checked属性失效

**Comment by YpchenLove** [comment]
当不与<l-radio-group> 一起使用的时候，checked是生效的，但是仅有展示功能，会尽快完善文档与功能，并修改改bug，感谢反馈！

**Comment by YpchenLove** [comment]
周三会完善 radio 和checkbox 组件的文档，文档中不清楚和缺少里的示例都会补上。
