### ISSUE TITLE
可以添加自定义导航栏

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#305]
**描述你希望的支持的新功能？**
> 小程序自定义导航栏，可以自定义返回键、或者home键，导航栏文字（字体大小，字体颜色），导航栏背景颜色或背景图片或者可以设置渐变色。
> 可以添加插槽，比如导航栏可以添加input文本框

**你期望的 API 是怎样的？**
> 和其他的api类似

**Comment by uniquenaer** [comment]
感谢反馈~会考虑新增这个的

**Comment by 7insummer** [comment]
自定义导航栏目前微信有bug，不建议使用。
