### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [TaleLin/lin-ui#307]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/TaleLin/lin-ui/blob/master/package.json#L35

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by uniquenaer** [comment]
Thank you very much，we will remove it in the next release.

**Comment by 7insummer** [comment]
we have removed it.thx。
