### ISSUE TITLE
【Bug Report】tabs非等宽标签在部分安卓机型下显示横向滚动条

### ISSUE THREAD

**Issue by Samuel-Sx** [TaleLin/lin-ui#308]
**重现步骤（可选）：**

设备: 小米8
现象: 横向滑动非等宽标签tab栏时，标签栏下方会出现横向滚动条

**期望的结果是什么？**
建议使用高度溢出+父容器隐藏溢出属性进行隐藏

**实际的结果是什么？**

**Comment by 7insummer** [comment]
Android机上的默认特性，这个不方便去掉。
