### ISSUE TITLE
segment组件的badge-count这个属性不能实时更新

### ISSUE THREAD

**Issue by zpinsist** [TaleLin/lin-ui#310]
![1](https://user-images.githubusercontent.com/49331277/59761913-8b518200-92c8-11e9-8017-8a90356b1ebb.png)

![2](https://user-images.githubusercontent.com/49331277/59761983-b2a84f00-92c8-11e9-8cc7-18a5b4dc30a7.png)
数据已经更新了,但是页面并没有数据,除非我手动设置data里面的值,才会显示出数字来.

**Comment by uniquenaer** [comment]
感谢反馈，会尽快想方案解决这个问题

**Comment by zpinsist** [comment]
有解决方案了麻烦通告一声.谢谢了.

**Comment by 7insummer** [comment]
问题已解决，在下一个版本中修复

**Comment by zhc525349965** [comment]
close as solved
