### ISSUE TITLE
dialog组件问题

### ISSUE THREAD

**Issue by dushanshan** [TaleLin/lin-ui#316]
dialog组件蒙层盖不住下方，文本域中输入的文字，Android系统下可以盖住，IOS下不行。求大佬解决办法。

**Comment by uniquenaer** [comment]
目前cover-view是无法覆盖textarea的，微信官方的回复是下面这个地址：
[textarea 层级最高的问题，覆盖住了底部固定的内容 | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002c63bf440e827afb6e838551800)

除此之外只能等微信官方~

**Comment by uniquenaer** [comment]
目前cover-view是无法覆盖textarea的，微信官方的回复是下面这个地址：
[textarea 层级最高的问题，覆盖住了底部固定的内容 | 微信开放社区](https://developers.weixin.qq.com/community/develop/doc/0002c63bf440e827afb6e838551800)

除此之外只能等微信官方~

**Comment by zhc525349965** [comment]
close as solved
