### ISSUE TITLE
SearchBar 组件自动获取焦点

### ISSUE THREAD

**Issue by AilonHuang** [TaleLin/lin-ui#317]
**描述你希望的支持的新功能？**
搜索栏 SearchBar 自动获取焦点
**你期望的 API 是怎样的？**
设置 focus 属性后 SearchBar 自动获取焦点，默认不自动获取焦点

**Comment by aQingYun** [comment]
搜索栏输入框的属性和input属性基本上一致 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/37834281/59961164-8d088900-9506-11e9-9a30-fc94f808fed4.png">
直接设置即可
