### ISSUE TITLE
l-icon与自定义iconfont发生冲突，导致icon错乱

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#323]
**重现步骤（可选）：**
/*iconfont图标*/
@font-face {font-family: "iconfont";
  src: url('iconfont.eot?t=1561019510175'); /* IE9 */
  src: url('iconfont.eot?t=1561019510175#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAABEUAAsAAAAAHfwAABDHAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCGBgqqFKE3ATYCJANYCy4ABCAFhG0HghQbpxhFRoaNAxDC+2Bk/5cJ3BTBZwW9kShY2iJQtdYYw93AFWMbfouyftYv0U7oRl5Z0DrfyzOFx5ap4stO6WaKeGwoJQ9f+/E7d3ff++Ka/tB9umkmkcniCaYzVA9RG3QSjbTgoegQbfP+n/iHf3hCUHDylJVzkaCssAh7ISvEZlXA1rh0rlgGukqWwTZdtIss/3e62FtHGNgKdXvbe7/tT/rbkkBIGOuEljffe72faT2zKIJdV+JfUAHJ78xvsLrO+tK1gtN+Pqa5ZFkPAAj8R3D3lXMF/79pzSbUKkwdujvhFqFwLjM5bjOZCff+9cnVWWqoyfahdwsWYXgoZLK716uidFeqawqhHd7jXA1v9OnldBZFBRmMzbxV4gqjEBlixn+PTaDbvGjQkZunr1hOQexA1mUSEMu5qhXOytC5u2X0WZp4UKMz3Zsf9+mfj+/2IkfSZGRcRy9de7GzCr4Mz/LlLmalq+oENv2RsQsoxC9m4xeQTbpLWTcrWLzEov6saFSoltpfR4lIUBTCROhaK+uL+vvL6n8zFXBX99XhWLJZ5tKxNixSrFYJjxVJMJJRTL2Kfn26jUGMVML/8vToMqDVaRAPXwAQLZLZCzGJI+NABXckqNsZBSptOx1UYju9VI7Z+pwPm58LYBPjQoBucBHAGLgEIIPLYJPhFEACVwA04GEAPeARAF3gXQEGwCsBWvAXAJ3gf7CdQeDLUDBE+TCAYfDhqDNWE9wIKHFKrP1E5+3IkhdESMuoxiCmVpdsHy6SPEpohgHC9ZWTqElTRFBhQSROklzuE+tdsVmsgM66NjkUl+E4QSiUxcIwIUGgZCa3j4MdSH6A6vP+OBxxZAiOtyTxYJwvIDEVjreO4uOESGQyH5KegQbq6vMZCeqq/eMLIp+etYVzL4FSVe4jPcXghinVFq05OogdsdFBy6RcK2dWRWSy5cUHRNxfrhIryYyy6Vnfw9Qg7g/IwYK1BLOOE8o3AV/BZMPUjMWrsNOZZWjvbgbLFOSBqfu9B/PPTnkO9NhLCffOnd9gb82irk+z77625jQ62yyLl6O2LbiuVAUc53jnf6KFD9L6Z8nIkE/M/ndq/n/JccQhb51Jde72N/bEamsLaO+XB8gzZXAZOAvNQoBKFhHKlwFQSrxKQ50FBoc0hoeqStE0hIgBgKGfPMyVmxX9DMuFEK/uOwlxmHNJGT5g5Y2JoqSOUSd6OcXVFHnnMEg7B9g7mpp0LB8GqWk5EMn9ZpaBhI/yJDTliNFhXedT0yBI4QDl8TFvmED5401ycJMjOi6HIeXfIfTG3qklaIjZr2InrB6whKqCDsTxXJHVuTSSCNMQtflLJP8aHjU4g9VplY6eF+AzCKmMpiDECYSq19gKV56PNDqzLFxhbKlqCjTS0oIzYIZxhrqT0tOgIRhcmsWB6g0J0QiDawoja4HOpuL0mUxybv2ebKZNfza/Iti9EdKZ2tArCZFwGkIekSQlZwhyBSoch0SVKQalx8RWztJ5lUEGzWd2mMnpfbMbpPQi8bRcTKpaAvFD65+GXyi48N+9/a4e8VeWiJ1ZkaRN3HCsYIntDkaZGsjAjvTaCpz7SDkPPZ0/Y6Dq13LvMdxiw/OCY3hQeUYG5H7RLMhFUlZKJ2vdLU3z9SQbRgz4O35ED/mkYPhYUx2S+f5gWLI41d8f9KHBUxArCJEyZZglABTSZ0B+mE0f3LJlyYoZPbU5cwKBSESlVPwgv+Kg8ucyTHPh8Hxu9urpy0mnl8XTYfv3CA+PC9xUrt4LO7Vcmn8WLiqOs8cr2WKQShRwKQQUzihfNkqmy9O1IqNR1MLDojDSRaWk67D9zIII9gBMiXrUEtX6MPB3pV6llCJHqgXowyV2uFFGiKl79yFSZGI5ofInLxegB5foXZSRlxSpc56om4UEI2h57qyRKpn0Q8ye0TF9SsW6wp0tk5mnNVnd58k5P1srZhQG0aiUbBjoQd6O9eWq0FDDly5bM75Dz9A2HNopNLTW2fbamnCf/etPGEgCb9t7M8Mbmd/HJZFnc47ISuJNCBCA0jpeXCNAik3dE2yA9jdIECgGeudOjqFF10FTSUpWoboCNfZWTaNkPj9oZ9tfIva285CBrPlcypteNLy7uLex7tm7ngbqYb+IzUSymM2n218578M6K+ppKVykENoj+A/yao4VRzOloCVMO1kvM4JkEChFep+qnj1rVCyujeHLzGmtq4q9+fp7pMLe2uXGK3+ezA2GKr+2hPc5kuifsp07xBr6f+2pXq2crXKJHXWlrkW6oKSSfXyaw1NelSPOJKTXSWBd8M9+dNia+gK94XXu+fyV4g7zyIdGmRQpptzu14qtSJQ45d3UM7iklDkvyz5mU9ToGN09zOUgVhMaYjQmS+mF1JPf4QxPP5vuJYyW1BBJs6lQCXoqlg5bM289BhtPWFa0ZidHcEaqucT8ts2sBEfJ2tTppStLnVAhGRIJy7qp9hS99OQzulImzOnk2VJbB4RraqHgCkd0zGiBZv8p95kWHvIXZ7w9RVKroC9IpjRs7MctilCJnv1NTTke/Kk4GECJv1/oG2W8wBBTwvoUQWmILbzvtGzZbvmxXfIc2chHMMQWUJq49KvIB+UzRvW98F0sV/scbxpmydQaNVuapn+0rb1K2kl5FXSu+cX1arzcwCuNKYpP5JU0vnFk5zb9xdzFWi8XXZeXmDFGz91OPExVPO5Fbp+yDoAcjffjibuXL3y4mp/8ZOLaGr5W+pD36Tfoo9pYutxVBmy7/RFsvmgvSPL53JU9Dxo2DMqL/t5uou/W8Iw2Ylxt36OhvJ9w8L/9bEkVfxlSc+zYnLGQMmC8phxc5ezhgDdshB1kNch19IFzedWwY+NGB7yW0ulgxAuo+AUIHBZ/BtSleFMOpPgAwyep1xqWwmvp5wVrDfUoIvIS1xiWtRbG2me+LjrGkkeLoQ9DFCMfiVFOXQBiDHkObTJletpoeQ0GGPAnqCczYgj8bixo6C5khuJDE05uUEnv3JWlyFrheewq88yZqut7nOCQHFgBOC9lYF/CAuEandoOWSPwY7dM6ZDIAgqxIpSrnhk/fzIFF8OhHg5jc/I1KxVGWeMR9Pw6ARw/YkRQyoio+LD4KPMffEQ8aO6sBzPihvcaF6Hh6YV5krpeC6cX5wSsX69iQQOC2fOTV8E00xwNPiJiFDjraFkRb2UN5kzfc8YtLQ6fB9/bqqihFvSoBoX0yFUw1m3Me2khuzersHBZ91ZpbXoJ2UlCezLpPPN0tq60NEjSE++hkYR0b8OjQW2IDrhy6N9zMxaf/6lP2t5xNvF5dtG1dAGn16LGDgItnIV3IvC2ssLYlflsfZwxljeFEcFMeUaaD42uOf1sK5ScfSCSY5yM6BaNXfESd36NXhBIzFiPrlnlquisfC4X8W7US4V2OkcLOPr9ZBYmaWGTBvfshrFyWKw429mi246s9eOe/664EbCky3bup+BPncn+CYHse+1gen01tIKbxSU3Ghf72vBKF5giSUAhuedoOE4b69yGEbfz8DU2L/LoEQLLWxjnLEN+RGXyapBAM+VQ8UCkJpMXmb8yk1+DBPlWBCFzm4+MVvAWKFZbuUuMWvvQcVAZaJY7QOgLo0D7hysbDXx6GZ1naGxQiu+LykX3xZtvDNgoVSYrkhOTk4JKqWmh+rBjP6nKGE2WiZYmRoGqgK4wTDQo6LzzF54QqZYPNtD5iYOLGOHdXDC8EzeK3ot+vZahPPQeqGwVPzh4pv2sZgpvEa1QHmgjf8afd+24BxYkR89OvZrl3hn/9vCGighWETbcPBx7flou9qq0e79fNN/KSxluZE4ZWDdMVbSKPacYLcKK53B2Ss3jh+QKtsJC4NV6wbYJha4WG4+jU7Ei9joZOQIqgkaoiqE0MiTGYtzBd3dNPjR05JCGuAGgFeTi8DiWYsELFRlNmZDP593SxfCk7lyUQnNcGlcOStnN4vVis11D2ZqI6ho2SWgIkr0ecQHsZqkcL1Vsntop1ms19++DGckMnTZtoV3OdK9Y4V7plnV2oynjPaDTIDfLunvXW9XbnbusgnvCgbt2b0rftGe3ld/09/LzhxopdFnmxPxCP+akZyZ9Ez3X2KAjNCfqF9zDnMGkprqLW9cW0hX21AEdSBFIF4C9ZIGNWoB3G2+gX6tfdufEy+AlQ1c0Ggol3ZdNGV+uP7zpzofdF2unzTXlOQcV6/Z0b9qorJJ2y6yYCfbYPJm1HSaUlw8cSqyB53OZ0KE209PJs73Dds8Ws99loB9kv2NpU3WwQJdKrbzPOk43uIJiHB7SYbQoEfxZz53A9/MncNf/NvcBKf0QUx8N6/IjAXxU0JJOc5KwJ/sk8H3lKDx6QVcwoOQ4DkT56yLsTaBoWPBjgmC/F79b+Q7XJnWasy57Ipw7f/USrxUessxMHWJtM0slEZ9lc5/7+q3aNkI8YsmmY/1u1Mj0t4Pugj7jplZ7JIlBnuWrPI8ul/gj5voBOAeaudzOGvDRT43LbVYtbFhdbm9LZVBt7eWrG7b52KW4b1vd0Tq8lF03/lgWZCuBMstns2XBmXBMO68EjEl71SWpj7p41ZPMDo8TN1mApUkct/tthsFpKRqNMwbnc03Kb4HWt5X/iAPGarVQKTSVPPNwgvmjR6P/IkgyuQielMdJDnV5OQ0BNEfeKVVT9cApIo7mHn1KIsdLdLlq4gbeDlhuvC5eA7P9tCaW3T6vLOQSlJJfkAr9OJqDm/CcoxEt6vPiz2F4Y6T88bKkCKDRkiZyPijwIw8aOhTKu9Siui8ap42uShtbrKVzK9r0nfSWoW2RUBevnTurVze5ndUkbGL1Q62egUH9WBeFF1lVfXrMrwFXh0mn5uT4FR6FvzUxjdCcnI+g2VkLDubBujZSXQtsPTU/v5Y7GVrZRSJx7WTI1Lr+1Lha6GAurMN8Ah8WbDqh0uDDb88uXAIPxz5Mf///1txMOZRcDsD/Q37tBp/MzsTXTeCkM8lVgMh8MvEa3lHv8wG6drl7+fThd17js2bfXLuCi2XtPv+NX/vHVPjhm97lHRUrH1OvOryveLnybfrlXneFF6f0iYiuPNqc7uRI2xn4o7CUD7Gzv9U134r9f+L+jwmtqPVP+qgcmUp0Sn9hcH8C1pRNpYyfKwgdv9g4UODtnXK/jSWYqawf9x3pJXTr9/BHYOuw+3lxxoTJgna6yjco6TCHsk6repm7ixo99qFWp/2o245u/fcYMVhSlC5sm6yhMGgrSvq9Qdmgi3qZ24Qa496h1mAkUbfTMX6IPdaDCps1gkGPOVtGrpJcdaZgZH+gsBFoZwVd84N6SfvZMDbee+wWJWoV3SxXYmQMZ1yrGbvRxodRpNhcqwBd0/ONmU/7cVZWtz1XzWIFh2kImOeWHqafbdkSLkXiDzYKvt//AQlWBGjOBU9lfyBtiR6fSRArXkC/ZVLognlRh1gRRoYuBMfup2vKDNN1IVCkH1YYO7tYALmMHpuENzcVt7iRVZT10ndmQ4HpfBclIxiPROTdhjQtZfsBO93jer421jjj0RgsLrp8C1KIR2XBrBqmG2yok/Qp2vmURb1GmkF+C2pBUkB01mrruT5KwSy4sFvrAUWUWcMnZ6FUiNwWNcq1VaNGlN75douFaNEOgTLULdxX1rdvRYPMPOPMQZ3lIH2ym71HyUcGlPWVFA6orJdYqgcyx1EGq2nQWq0rrm/TLZ/k0e3GAA==') format('woff2'),
  url('iconfont.woff?t=1561019510175') format('woff'),
  url('iconfont.ttf?t=1561019510175') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('iconfont.svg?t=1561019510175#iconfont') format('svg'); /* iOS 4.1- */
}

.l-icon-huangguan:before {
  content: "\e600";
}

.l-icon-huangguan1:before {
  content: "\e620";
}

.l-icon-icon4:before {
  content: "\e61a";
}

.l-icon-dizhi:before {
  content: "\e60e";
}

.l-icon-erweima:before {
  content: "\e622";
}

.l-icon-yaoqingma:before {
  content: "\e66e";
}

.l-icon-woyaochengweiquyudaili:before {
  content: "\e604";
}

.l-icon-wallet:before {
  content: "\e6e7";
}

.l-icon-kefu:before {
  content: "\e629";
}

.l-icon-renwuguanli:before {
  content: "\e614";
}

.l-icon-zhuye:before {
  content: "\e627";
}

.l-icon-weibiaoti-:before {
  content: "\e60d";
}

.l-icon-youhuiquan:before {
  content: "\e613";
}

.l-icon-Member:before {
  content: "\e612";
}

.l-icon-fanhui-:before {
  content: "\e646";
}

.l-icon-xiangji:before {
  content: "\e6fb";
}

.l-icon-hongbao:before {
  content: "\e874";
}

.l-icon-dingdan:before {
  content: "\e875";
}

.l-icon-fenxiang:before {
  content: "\e61f";
}

.l-icon-arrow:before {
  content: "\e601";
}

.l-icon-changyongicon-:before {
  content: "\e616";
}

.l-icon-coin-copy:before {
  content: "\e876";
}
**期望的结果是什么？**
在使用l-icon时，name为erweima的时候应该是二维码的icon，实际出现的却是lin-ui中right的图标样式，使得我自定义的iconfont不能正常生效

**Comment by Jokky6** [comment]
example：.l-icon-erweima:before {
                     content: "\e622";
                  }
                  与
                 .l-icon-right:before{
                   content:"\e622";
                   }

**Comment by YpchenLove** [comment]
@uniquenaer
