### ISSUE TITLE
avatar组件open-data，UserNickName在配置项中无法取消

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#326]
**重现步骤（可选）：**
<l-avatar slot="right-section"  open-data="{{['userAvatarUrl']}}"></l-avatar>
**期望的结果是什么？**
只显示userAvatar，而不显示userNickName
**实际的结果是什么？**
userNickName显示，配置项配置不成功！

**Comment by uniquenaer** [comment]
此问题0.5.3版本已修复
