### ISSUE TITLE
l-card不能自适应宽度问题

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#328]
在组件l-card外层嵌套一层带宽度的view，l-card不能自适应宽度，现在出现这个问题是因为l-card的宽度是固定住的，应该需要加强其自适应能力。谢谢！

**Comment by aQingYun** [comment]
目前已经在考虑修改该部分的自适应问题了 感谢反馈


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
