### ISSUE TITLE
loading.wxml存在重复的style属性

### ISSUE THREAD

**Issue by heiye9** [TaleLin/lin-ui#333]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/24930493/60408391-49420d80-9bf1-11e9-95fc-df4e328859cc.png)
loading/index.wxml中存在重复的style属性，并且内容是一样的。导致打包时报异常。
![image](https://user-images.githubusercontent.com/24930493/60408355-2283d700-9bf1-11e9-8ace-cc47ca289241.png)

**Comment by aQingYun** [comment]
感谢反馈 我们会尽快处理


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by YpchenLove** [comment]
最新版本已经修复~
