### ISSUE TITLE
希望input组件，清除按钮的可触摸区域大一点

### ISSUE THREAD

**Issue by AilonHuang** [TaleLin/lin-ui#335]
**描述你希望的支持的新功能？**
希望input组件，清除按钮的可触摸区域大一点
**你期望的 API 是怎样的？**

**Comment by YpchenLove** [comment]
感谢一直以来的支持和积极的反馈~ 这个会在下周增强！同时input输入框，也新增了几个demo案例，这周小程序demo会更新。
![image](https://user-images.githubusercontent.com/26370242/60439081-ab782e00-9c44-11e9-876e-48c210b5af7a.png)

**Comment by YpchenLove** [comment]
@AilonHuang 已经增大了点击范围~

**Comment by YpchenLove** [comment]
已经更新到最新版本里了

**Comment by zhc525349965** [comment]
close as solved
