### ISSUE TITLE
返回桌面倒计时停止，

### ISSUE THREAD

**Issue by AilonHuang** [TaleLin/lin-ui#339]
**重现步骤（可选）：**
假如倒计时是60秒，返回桌面的时候是50，在桌面停留20秒，重新显示小程序，倒计时还是从50开始，而不是从30开始
短信验证码重发功能，用户返回桌面查看短信内容，再次打开小程序，倒计时不走用户也会觉得奇怪
**期望的结果是什么？**
倒计时在后台继续
**实际的结果是什么？**
倒计时在小程序进入后台时停止了

**Comment by 7insummer** [comment]
这是一种场景，同时也存在页面隐藏时销毁定时器的场景，因此下一版本中会新增一个属性来控制是否进入后台时不清除定时器

**Comment by zhc525349965** [comment]
close as solved
