### ISSUE TITLE
【Feature Request】条形的tabbar导航组件

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#34]
** 描述你希望的支持的新功能？**

条形的tabbar导航组件

** 你期望的 API 是怎样的？**

    <bar img="" tip="" text="" data="" navigateTo="" />

**Comment by chenjunup** [comment]
> 可否详细描述一下，特别是你希望实现什么样的API？

好的。
我经常会在个人中心页面，放上几个导航条。以您的旧岛小样为例， 我可能会放上一个导航条表示我喜欢的classic。导航条的左边img放一张表示喜欢的图标，然我文字提示tip=“喜欢”,然后右边放上一些状态数据，比如喜欢的classic个数text=“{{numberofloved}}”,然后，点击导航条进入喜欢classic的页面，展示所有喜欢的classic。甚至，导航条的下边可以放一个横向的scroll-view展示缩略的classic，当然这已经是另一个组件了。然后下面还可方其他bar。

还有一种bar，针对某个特定的内容点击后在正下方显示一个二级菜单， 编辑  查看 删除。

**Comment by 7insummer** [comment]
感谢提出反馈，下个大版本就会提供这个组件。

**Comment by chenjunup** [comment]
> 感谢提出反馈，下个大版本就会提供这个组件。

好好。感谢！

**Comment by juzi214032** [comment]
您好， [List 组件](http://doc.mini.7yue.pro/component/layout/list.html)可以满足您的需求
