### ISSUE TITLE
checkbox 样式能否改成类似原生的对号

### ISSUE THREAD

**Issue by ThoughtZer** [TaleLin/lin-ui#342]
**描述你希望的支持的新功能？**
目前的demo的checkbox的样式和radio的样子看上去没有什么区别，是否应该做一个区分呢？
**你期望的 API 是怎样的？**

**Comment by 7insummer** [comment]
感谢提出建议建议，我们会考虑增加一种checkbox方形的选项

**Comment by YpchenLove** [comment]
@ThoughtZer 已经做了更改默认是方形 对号的形式~

**Comment by zhc525349965** [comment]
close as solved
