### ISSUE TITLE
l-input当label默认没有时，需要隐藏

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#345]
**描述你希望的支持的新功能？**
在使用l-input时，当label为空字符串时，label还是被占位住的。
**你期望的 API 是怎样的？**
在label为空字符串时，label位置应该被隐藏，input宽度默认为100%

**Comment by zhc525349965** [comment]
已处理，等待下个版本升级。

**Comment by zhc525349965** [comment]
已经增加隐藏label模式，详情请查看官方文档。

**Comment by zhc525349965** [comment]
closed as solved
