### ISSUE TITLE
rules校验组件需要开放自定义校验规则

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#346]
**描述你希望的支持的新功能？**
通过现在lin-ui文档中的rules，我不能很明确知道，在lin-ui中如何自定义校验规则，因为有些需要动态校验的，比如密码与确认密码的校验，提现的输入框，往往会根据现有金额进行最大值的校验。
**你期望的 API 是怎样的？**
希望在rules组件完善这一部分功能，或者是已经支持该功能，但是文档中并未写demo。我认为这个是rules最重要的一环，请尽快完善！谢谢

**Comment by Jokky6** [comment]
> **描述你希望的支持的新功能？**
> 通过现在lin-ui文档中的rules，我不能很明确知道，在lin-ui中如何自定义校验规则，因为有些需要动态校验的，比如密码与确认密码的校验，提现的输入框，往往会根据现有金额进行最大值的校验。
> **你期望的 API 是怎样的？**

希望在rules组件完善这一部分功能，或者是已经支持该功能，但是文档中并未写demo。我认为这个是rules最重要的一环，请尽快完善！谢谢

**Comment by uniquenaer** [comment]
rules 文档中有标明高级用法直接参考[yiminghe/async-validator: validate form asynchronous](https://github.com/yiminghe/async-validator)

建议多多探索，认真阅读文档

**Comment by Jokky6** [comment]
其实我觉得这种高级用法还是要在文档中写上一个demo，这样可以一目了然啊，小白用户的期待！
