### ISSUE TITLE
缺少Form表单组组件

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#348]
**描述你希望的支持的新功能？**
在登陆注册页面的时候，往往会出现表单组，我们在点击button按钮时，可以获取到绑定表单的所有value值。
**你期望的 API 是怎样的？**
可能目前lin-ui中已经可以实现该功能了，但是文档中丝毫未提及。如果已经有该功能，建立做个demo，如果还没有实现，是否能够实现一下？

**Comment by uniquenaer** [comment]
感谢反馈，在设计表单组件初期就考虑过是否封装form组件，但是受微信的一些设计限制，button不能以组件的形式存在在form之中，所以form没有封装。

**Comment by Jokky6** [comment]
But 这个需求的确很值得期待，建议在最近版本内可以开放出来，谢谢！

**Comment by uniquenaer** [comment]
感谢建议，但是我们讨论后认为 form组件暂时不适合封装组件
