### ISSUE TITLE
l-Step组件现在过于模式化，希望能够一些diy，以适应更加复杂的场景

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#351]
**描述你希望的支持的新功能？**
l-step组件现在还比较趋于模式化，希望能够提供一些定制化的api，可以让开发者能够做到更加炫酷的step。
**你期望的 API 是怎样的？**
希望在l-step添加一些插槽，使得step能够实现一些定制化的模式，还需要加上一个content，可以在不同的step显示不同的step-content。

**Comment by uniquenaer** [comment]
自定义步骤条不能满足你的需求么？如果不能的话 还请更加详细的说明，最好附图，非常感谢！

**Comment by AilonHuang** [comment]
+1
自定义步骤条只能把123修成成自己想要的文字或者样式，但是有些功能就无法实现，比如在title或describe里加入icon
