### ISSUE TITLE
你好，发现一个小问题，使用segment的solt时出现找不到元素

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#357]
**重现步骤（可选）：**
```
...
  <l-segment-item key="{{item.key}}" slot="{{item.key}}">
      <view>
           <image src="{{item.image}}" />
      </view>
 </l-segment-item>
...
```

**期望的结果是什么？**
不报错

**实际的结果是什么？**
:16204/appservice/appservice?t=1563174616354?load:1 Uncaught (in promise) 找不到元素

**建议**
https://github.com/KDWangBoss/Images/blob/master/LinUI/segement.jpg?raw=true

**Comment by uniquenaer** [comment]
麻烦提供可供复现的代码

**Comment by KDWangBoss** [comment]
好的，代码片段为：https://developers.weixin.qq.com/s/PExE71mC7Za9

**Comment by 7insummer** [comment]
你好，我们下个版本将修复这个问题，感谢提出。
