### ISSUE TITLE
l-input组件  rules验证有问题

### ISSUE THREAD

**Issue by beibei3030630** [TaleLin/lin-ui#362]
**重现步骤（可选）：**  
   phoneRules: [{
      required: true,
      min: 11,
      max: 11,
      message: "请输入正确手机号码",
      type: "regexp",
      pattern:"^1([38]\d|5[0-35-9]|7[3678])\d{8}$"
    }],

**期望的结果是什么？**

**实际的结果是什么？**
验证不了，正则表达式肯定没问题。而且是有时候验证的了，有时候就验证不了。有时候明明是错的，isError返回false。如果type为number的话验证就没问题。

**Comment by beibei3030630** [comment]
l-input组件 rules验证有问题

**Comment by 7insummer** [comment]
你输入的手机号码是字符串或者数字，所以type的类型是字符串或者数字，而不是说你是用正则校验的

**Comment by beibei3030630** [comment]
> 你输入的手机号码是字符串或者数字，所以type的类型是字符串或者数字，而不是说你是用正则校验的

那我就是说这里不能用正则去校验吗？我就想用正则去校验手机号码
