### ISSUE TITLE
请问l-input  的tip-type为toast时 可以自定义toast框吗

### ISSUE THREAD

**Issue by beibei3030630** [TaleLin/lin-ui#363]
**重现步骤（可选）：**

**期望的结果是什么？**
请问l-input  的tip-type为toast时 可以自定义toast框吗

**实际的结果是什么？**
我尝试了很多次 在引入的<l-toast>上调用的了很多方法，效果都为最初的。请问这里可以自定义吗

**Comment by aQingYun** [comment]
tip-type暂时还不支持自定义。
