### ISSUE TITLE
自定义配置时候，选择textarea编译报错

### ISSUE THREAD

**Issue by plusprimer** [TaleLin/lin-ui#365]
**重现步骤（可选）：**
根据文档进行自定义配置时候，选择textarea选项进行编译，无法成功进行自定义配置
**期望的结果是什么？**
自动引入前置需求组件
**实际的结果是什么？**
提示缺少common以及behaviors

**Comment by aQingYun** [comment]
目前问题已经修改 下个版本即可正常使用

**Comment by zhc525349965** [comment]
closee as Solved
