### ISSUE TITLE
希望lin-ui能够开发一个栅格布局的组件l-row 、l-col

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#376]
**描述你希望的支持的新功能？**
发现组件中提供了Grid布局，然而栅格布局也是一种常用的布局方式，使页面排版美观、舒适，希望能够支持！
**你期望的 API 是怎样的？**
组件l-row、l-col，offset--栅格左侧的间隔格数，间隔内不可以有栅格

**Comment by 7insummer** [comment]
我一直不理解在flex这么好用的前提下，为什么还有这种布局组件的需求。。。

**Comment by alexosng** [comment]
之所以出现这样的需求我猜测可能有几个原因
1.应该是h5前bootstrap 用习惯了
2.没有深入了解小程序产生的初衷目的。
3.对flex布局没有真正掌握。不能做到信手拈来。

**Comment by Jokky6** [comment]
如果需要适配iPad等大屏幕的设备，且布局不一样的话，栅格布局会不会更有优势一点呢？

**Comment by Jokky6** [comment]
小程序现在有些也是要适应iPad横屏这种场景的
