### ISSUE TITLE
当配置 `config/component.json` 中的自定义组件后，编译的 dist 仍然包含所有组件

### ISSUE THREAD

**Issue by abrahamgreyson** [TaleLin/lin-ui#378]
**重现步骤（可选）：**
当配置 `config/component.json` 中的自定义组件后，编译的 dist 仍然包含所有组件。
**期望的结果是什么？**
只编译配置过的组件。
**实际的结果是什么？**

**Comment by aQingYun** [comment]
文档里面说明了 需要先删除掉dist文件再进行编译

**Comment by abrahamgreyson** [comment]
好的，增加了一个 commit
