### ISSUE TITLE
【Bug Report】Tabs scroll-view组件底部有一条灰色线能去掉吗

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#38]
** 期望的结果是什么？**
./components/tabs/index.wxss:1
.l-placement-top .l-tabs-header-line {
border-bottom:1px solid #f3f3f3;
}
这要灰色线能去掉吗？如果不能，能不能自定义自己想要的颜色？好像没找到自定义class，加了!important也不起作用

**Comment by uniquenaer** [comment]
新版本内提拱了自定义选项卡底线的自定义样式
