### ISSUE TITLE
使用openApi调用自定义组件的错误

### ISSUE THREAD

**Issue by yenche123** [TaleLin/lin-ui#380]
**重现步骤（可选）：**
actionsheet和dialog都允许使用 “wx.lin + 组件名” 的方式来调用，但是若a、b两个页面同时需要同一个组件，会发现从a页面跳入b页面，再从b页面naviBack回a页面时，此时在a页面调用 “wx.lin + 组件名”会不起作用，因为此时调用的时b页面的组件了，而b页面已经被销毁了。

**期望的结果是什么？**
在a页面仍可以成功调用并唤起相对应的组件

**实际的结果是什么？**
可以调用、不会报错，但组件不起作用。

解决方案：
不要在attached里初始化openApi的函数，而是在pageLifetimes的show()里初始化，如此即确保了，在当前页面会调用当前页面下的自定义组件了。

**Comment by uniquenaer** [comment]
非常感谢您的建议，我们会在下个版本中修复这个问题~

**Comment by zhc525349965** [comment]
build 0.5.13已经修复这个问题，关闭此issue。
