### ISSUE TITLE
l-checkbox的使用问题

### ISSUE THREAD

**Issue by fessorfeng** [TaleLin/lin-ui#381]
**重现步骤（可选）：**
在微信小程序引用linui，购物车页，我引用自定义的购物车自定义组件（cart），cart组件内用了l-checkbox-group组件，购物车缓存有数据，第一次进入购物车页，选中的产品都打勾的，但是点过其他页面加入新的产品再次进入购物车页（新数据缓存默认是选中的，而且我在cart组件里面页面show的时候就重新获取cart的数据的）
![0](https://user-images.githubusercontent.com/14170826/62034813-3edf5780-b221-11e9-9eda-d7e5de1e1ab6.png)
![1](https://user-images.githubusercontent.com/14170826/62034876-58809f00-b221-11e9-8429-6da52bfac173.png)
![2](https://user-images.githubusercontent.com/14170826/62034877-59193580-b221-11e9-83e0-28a360f4d58b.png)
![3](https://user-images.githubusercontent.com/14170826/62034880-59b1cc00-b221-11e9-8337-057992baf958.jpg)

视频：[复选框的疑问.zip](https://github.com/TaleLin/lin-ui/files/3441108/default.zip)

**### cart自定义组件的js**
`import {
  commonBev
} from '../../behaviors/common';
import {
  getDataSet,
  getArrColumn
} from '../../../utils/util'
import {
  Cart
} from '../../../models/cart';
const cart = new Cart

Component({
  behaviors: [commonBev],
  /**
   * 组件的属性列表
   */
  properties: {
    hidden: Boolean
  },

  /**
   * 组件的初始数据
   */
  data: {
    cartData: [],
    selectedCurrent: [],

    allSelectStatus: 0,
    account: 0,
    selectedCounts: 0,
    selectedTypeCounts: 0,
    allCurrent: null, //全选后的选项集合
    allBtnCurrent: []
  },

  lifetimes: {
    attached: function () {},
  },
  pageLifetimes: {
    show: function () {
      this._loadData()
    },
  },
  observers: {
    // 'cartData': function (cartData) {
    //   this.setSelectedGoods(cartData)
    // }
  },
  /**
   * 组件的方法列表
   */
  methods: {

    _loadData: function () {
      const cartData = cart.getCartDataFromLocal()
      this._getCartGoods(cartData)
    },
    _getCartGoods(cartData) {
      const newData = cartData.map(val => {
        //val['check_val'] = val['check_val'] ? val['check_val'] : `${val.id}-${val.spec_key}`
        return val
      })
      // this.setData({
      //   cartData: newData
      // })
      this.setSelectedGoods(newData)
    },
    setSelectedGoods(cartData) {
      console.log(cartData, this.data.selectedCurrent)
      const selectedGoods = cartData.filter(val => val.selectStatus),
        selectedCurrent = getArrColumn(selectedGoods, 'check_val')
      this.setData({
        cartData,
        selectedCurrent,
      })
      console.log(cartData, this.data.selectedCurrent)
    }
}
})`
**### cart自定义组件的wxml**
`<view class="body">
            <l-checkbox-group l-class="l-radio-group" current="{{selectedCurrent}}" bind:linchange="onCartProductToggleTap">
                <l-checkbox class="l-checkbox" l-title-class="l-title-class" l-class="l-radio" placement="left" color='#fa671f' value="{{item.check_val}}" data-v="{{item.check_val}}" custom="{{true}}" wx:for="{{cartData}}" wx:key="{{item.check_val}}">
                    <l-card class="goods-item-container1" type="primary" plaintext l-class="card goods-item-container" title="">
                        <l-slide-view class="slide-con" height="200" width="600" slide-width="340">
                            <view slot="left" class="slide-left">
                                <view class="goods-item">
                                    <view class="product-info">
                                        <image class="goods-img" src="{{item.thumb_img}}" mode="widthFix" />
                                        <view class="right">
                                            <view class="text">{{item.name}}</view>
                                            <view class="spec-container">
                                                
                                                <text class="spec-text">{{item.key_name}}</text>
                                            </view>
                                            <view class="price-num">
                                                <l-price l-class="price" unit="￥" count="{{item.shop_price}}" unit-color="#E93A3E" count-color="#E93A3E" unit-size="22" count-size="28" count-blod="{{true}}" unit-blod="" delete="{{false}}" del-color="" />
                                                <l-count-selector l-symbol-class="fabled" l-class="count" min="{{1}}" count="{{item.count}}" max="99999" step="1" disabled="{{false}}" bind:lintap="onChangeCountTap" data-key="{{item.spec_key}}" data-id="{{item.id}}" />
                                            </view>
                                        </view>
                                    </view>
                                </view>
                            </view>
                            <view slot="right" class="slide-right">
                                <text>喜欢</text>
                                <text>分享</text>
                                <text catchtap="deleteTap" data-id="{{item.id}}" data-key="{{item.spec_key}}">
                                    删除
                                </text>
                            </view>
                        </l-slide-view>
                    </l-card>
                </l-checkbox>
            </l-checkbox-group>
        </view>`
**期望的结果是什么？**
进入购物车页面，选中的数据就是选中的
**实际的结果是什么？**
第一次进入购物车页面都可以 新加入购物车的再次进入就没选中但是缓存select状态是选中的
@7insummer

**Comment by fessorfeng** [comment]
不是特别优雅的解决了这个bug，在cart自定义组件wx:if 判断购物车显示，在页面hide的周期函数 购物车隐藏，但是还是很疑惑，不是从checkbox-group解决的
![001](https://user-images.githubusercontent.com/14170826/62095288-89f57b00-b2b2-11e9-8c4e-7a7129645a21.png)
![image](https://user-images.githubusercontent.com/14170826/62095883-59164580-b2b4-11e9-9555-8f709426d4ef.png)

**Comment by uniquenaer** [comment]
非常感谢你的反馈 以及思考过程，我们会尽快想办法解决此问题

**Comment by dpp050700** [comment]
您好， 我们已经对checkbox组件进行重构，版本已经发布，您可以试试最新版本。如有问题，欢迎指正。
