### ISSUE TITLE
你好，请问下water-flow组件如何传递事件给父组件呢

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#389]
**重现步骤（可选）：**
代码片段：https://developers.weixin.qq.com/s/ISmnMimj7qa4
点击添加到购物车，在page父组件中定义的onAddToShoppingCar没有反应，想请问下在填入的组件里面如何传递事件到 父组件呢

**期望的结果是什么？**
点击购物车会打印-添加到购物车

**实际的结果是什么？**
没有反应

**Comment by aQingYun** [comment]
抽象节点里面的事件只能在组件内部处理 不能与页面通信 微信机制问题 敬请谅解

**Comment by KDWangBoss** [comment]
好的，谢谢解答

**Comment by aQingYun** [comment]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/37834281/62282872-eb6c4400-b482-11e9-9a80-e83d56bfa73b.png">
这样设置就可以监听到了 你试下

**Comment by KDWangBoss** [comment]
问题解决了，谢谢大佬😊

**Comment by zhc525349965** [comment]
close as solved
