### ISSUE TITLE
【Feature Request】计数组件

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#39]
** 描述你希望的支持的新功能？**
计数组件（不知道这么叫合适不。。），选择商品数量的时候用到，由增加、减少、数量三个元素组成（例如：-  1  + ），点击增加/减少，数量会对应增加/减少。

** 你期望的 API 是怎样的？**
1.可以设置最大值和最小值，当数量等于最大值/最小值时，继续点击增加/减少会触发一个事件；
2.当数值成功发生改变时触发一个事件；
3.组件有个属性，控制是否数值成功改变时带动画效果
4.组件有个属性，数值成功改变时动画效果类型，可选：效果1（默认），效果2，效果3

**Comment by 7insummer** [comment]
alpha-13版本已支持
