### ISSUE TITLE
npm构建失败

### ISSUE THREAD

**Issue by Jazk-Z** [TaleLin/lin-ui#390]
**重现步骤（可选）：**
`开启npm构建`
`npm init -y`
`npm i lin-ui`
`npm 构建`
**期望的结果是什么？**

**实际的结果是什么？**
`miniprogram_npm/lin-ui/water-flow/index 文件内容错误`
`VM618:1 pageJSON["componentGenerics"]["l-water-flow-item"] 字段需为 boolean/object`
`“true" -> true 也不好用  需要删了再重新编译？`

**Comment by aQingYun** [comment]
版本号说下

**Comment by 7insummer** [comment]
下载最新版本Lin-UI，调高小程序开发工具基础库版本试试

**Comment by flyprotoss86** [comment]
我也遇到了这个问题，lin-ui版本：0.5.14，微信小程序基础库版本：2.8.0
