### ISSUE TITLE
【Feature Request】 布局组件计划提议

### ISSUE THREAD

**Issue by zhgv** [TaleLin/lin-ui#40]
** 描述你希望的支持的新功能？**
## Grid宫格
![image](https://user-images.githubusercontent.com/44568852/51084222-21eda600-1761-11e9-9cb1-83b79e9173b5.png)
缺点：

1. `紧凑的宫格布局`

2. `图标不丰富，最好能引入阿里巴巴图标库`

>示例：
![uk_nepdys_wp9d 193ba 5e](https://user-images.githubusercontent.com/44568852/51084314-4dbd5b80-1762-11e9-8a2a-15260359ab2b.png)
>图标下的文字可以居中显示

** 你期望的 API 是怎样的？**
`  <view class="">
    <text class="title"></text>
    <view class="list">
      <view class="items" bindtap='calendartap'>
        <image src=""></image>
        <text></text>
      </view>
   </view>
  </view>`
>这里我没有分界线，最好还是有个清晰分明的分界线

## card卡片
![image](https://user-images.githubusercontent.com/44568852/51093878-c401a280-17e2-11e9-9050-e2c23c2b08ec.png)
>iview ui做的就可以，不过还是好像不能自己添加块状元素，view之类的

## list列表
![image](https://user-images.githubusercontent.com/44568852/51093915-36728280-17e3-11e9-9f0b-df488d69b02c.png)

## 手风琴
![image](https://user-images.githubusercontent.com/44568852/51093968-9a954680-17e3-11e9-8667-d2e1f19f6ec0.png)

>随便截取的几张图，仅供参考。不合适可以忽略我的消息。

**Comment by uniquenaer** [comment]
非常感谢您的建议，Grid、icon组件的图标库和list列表是在计划里，这三个一定会支持的。

至于card和手风琴组件，可以提供一些你使用的场景么？

**Comment by zhgv** [comment]
查询的课表内容以card卡片的形式展示
![image](https://user-images.githubusercontent.com/44568852/51094504-a59ea580-17e8-11e9-96e6-082bf595a6a0.png)
手风琴，这个作为软件使用说明展示

**Comment by YpchenLove** [comment]
list和grid已经发布，card和手风琴还在计划中~感谢反馈

**Comment by juzi214032** [comment]
手风琴已在 0.7.6 版本加入 @zhgv
