### ISSUE TITLE
【Bug Report】单选框 Radio 组件，横向排列

### ISSUE THREAD

**Issue by vanoneang** [TaleLin/lin-ui#41]
### 期望结果
![image](https://user-images.githubusercontent.com/29253688/51102832-6dfd2100-181b-11e9-9ea0-b2033635a0ef.png)

### 描述
在演示小程序中，有展示 Radio 组件横向排列的效果，但是文档中没有体现配置项，希望更新

**Comment by YpchenLove** [comment]
在radio-group上添加placement="row" 即可，checkbox 和radio的文档 有不详细的地方，会在周二完善好~ 感谢反馈！~

**Comment by vanoneang** [comment]
![image](https://user-images.githubusercontent.com/29253688/51154826-58860680-18b0-11e9-9664-55b7339223db.png)
![image](https://user-images.githubusercontent.com/29253688/51154831-5f147e00-18b0-11e9-808e-a5e06dda9baf.png)
![image](https://user-images.githubusercontent.com/29253688/51154867-8e2aef80-18b0-11e9-971c-7eb05b257668.png)

貌似不行啊，另外` { name: 'CHN', value: '中国', checked: 'true' },` 有checked属性，没有选中

@YpchenLove

**Comment by YpchenLove** [comment]
js代码中的items是复制文档里面的吗？这个应该是文档写错了，linchange返回的是绑定在radio组件value属性上的值。文档在周三会更改完成。感谢这个反馈！
