### ISSUE TITLE
grid 组件 bindlintap会触发两次

### ISSUE THREAD

**Issue by zhc525349965** [TaleLin/lin-ui#412]
**重现步骤（可选）：**
宫格组件绑定在grid上的bindlintap事件会触发两次。
原因是grid和griditem抛出的自定义事件名称相同，且抛出的时间是可冒泡的，所以在gird上监听的lintap事件会被触发两次。

**期望的结果是什么？**
只触发一次

**实际的结果是什么？**
触发两次

**Comment by zhc525349965** [comment]
准备将griditem组件抛出的事件名称改为lintapitem.
不影响grid组件的事件，也不影响向上冒泡。

**Comment by zhc525349965** [comment]
已处理

**Comment by zhc525349965** [comment]
和7月讨论后决定暂不更改，等待周日例会一起讨论

**Comment by 7insummer** [comment]
已修复，请更新最新版本，并查看Grid文档

**Comment by zhc525349965** [comment]
closed as solved
