### ISSUE TITLE
提供 ES5 的构建版本

### ISSUE THREAD

**Issue by zaxlct** [TaleLin/lin-ui#416]
**描述你希望的支持的新功能？**
目前 dist 目录是 ES6 版本的，但是用 Mpvue 等第三方开发的话，不需要开启小程序开发者工具的 ES6 转 ES5 功能；希望能提供 ES5 版本的 dist
**你期望的 API 是怎样的？**

**Comment by zhc525349965** [comment]
感谢提供的建议，我们会内部讨论此功能，讨论后通知结果。

**Comment by 7insummer** [comment]
可否具体描述下具体原因？不用小程序的转换，那么MpVue不能转吗？babel应该也是可以的吧。

**Comment by zaxlct** [comment]
某些小程序框架会要求关闭ES6转ES5选项，比如 Mpvue

Mpvue 引入 lin-ui 的时候，会放到 static 目录下，此目录不会被 babel 编译
@7insummer

**Comment by juzi214032** [comment]
您好，请问是使用mpvue不能开发开发者工具的es6转es5吗？
