### ISSUE TITLE
ICON 组件 及文档修改建议

### ISSUE THREAD

**Issue by Yang-yibu** [TaleLin/lin-ui#42]
** 描述你希望的支持的新功能？**
1. 希望在文档中将 Icon 全部列出来；
场景：当我只是暂时忘记 Icon 名字的时候，希望可以直接在文档中查看，而不是打开手机，或者打开在开发者工具去寻找
2. 希望可以开放 图标库（我猜测是阿里图标库）的 地址，方便开发者自己自定义加入需要的图标
> 我发现少图标如 `+` ，只能暂时由 `close ` 加 旋转 实现  

** 你期望的 API 是怎样的？**

**Comment by 7insummer** [comment]
我们后期会考虑在线调用图标，或者是开发者自行编译自己的图标库用来代替默认图标。感谢支持。

**Comment by SilverLeaves** [comment]
可以考虑嵌入fontAwasomes的图标

**Comment by uniquenaer** [comment]
目前lin ui 支持开发者在icon组件中使用自己的图标库来扩展图标，具体用法在这儿：
[lin-ui-图标 Icon](http://doc.mini.7yue.pro/component/basic/icon.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9B%BE%E6%A0%87)

**Comment by YpchenLove** [comment]
本issue的问题已经解决~我们将关闭它，如果有其他疑问，请重新提出issue~ 感谢反馈
