### ISSUE TITLE
mask层级默认-99，导致mask容器背景无法显示，文档中写的是默认99

### ISSUE THREAD

**Issue by wseek** [TaleLin/lin-ui#426]
**重现步骤（可选）：**

**期望的结果是什么？**
mask层级默认-99，导致mask容器背景无法显示，文档中写的是默认99
**实际的结果是什么？**

**Comment by aQingYun** [comment]
感谢反馈 这个问题我们会在下个版本修复

**Comment by 7insummer** [comment]
已修改 更新最新版本即可
