### ISSUE TITLE
【Bug Report】textarea组件设置value属性不起作用

### ISSUE THREAD

**Issue by chenjunup** [TaleLin/lin-ui#43]
** 重现步骤（可选）：**

    <l-textarea name="name" value="这是value值" />
    <l-textarea name="name" value="这是value值" placeholder="这是占位文本" />

** 期望的结果是什么？**
   textarea区域显示 value值
** 实际的结果是什么？**
 value值无法显示出来，用原生的textarea测试，没有这个问题

**Comment by YpchenLove** [comment]
这是一个bug，感谢反馈！我们已经修复，明天会更新核心库，如果你时间紧迫，在组件源码的index.wxml里的补充下列代码：  value="{{  value }}"
代码示例：
<textarea value="{{ value }}">
