### ISSUE TITLE
lin-ui中的icon组件中的 content与自定义的icon content重复了怎么办

### ISSUE THREAD

**Issue by beibei3030630** [TaleLin/lin-ui#434]
**重现步骤（可选）：** 
自定义了一个图标文件iconfont.wxss并 放在了根目录下，里面有若干个图标。
在页面中去实现的时候由于自定义图标的content名称与lin-ui icon组件中的content名称重复，所以把lin-ui icon组件中的重复content名注释掉了

**期望的结果是什么？**
使用自定义icon

**实际的结果是什么？**
即使注释掉了lin-ui icon组件中的重复content名，结果显示的还是lin-ui icon组件中的图标

**Comment by 7insummer** [comment]
http://doc.mini.7yue.pro/start/QA.html#关于自定义iconfont与lin-ui内置的iconfont相冲突的问题

**Comment by 7insummer** [comment]
![image](https://user-images.githubusercontent.com/24819249/63473844-8d42e780-c4a9-11e9-8a3f-081b350cfabf.png)
刚好有段代码贴给你

**Comment by 7insummer** [comment]
使用的时候 
![image](https://user-images.githubusercontent.com/24819249/63473913-bfece000-c4a9-11e9-8df3-e9a1e261198f.png)

**Comment by Mr-houzi** [comment]
@7insummer 若ActionSheet中使用第三方icon该如何操作？
