### ISSUE TITLE
【Bug Report】l-loading change 样式不居中

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#44]
<l-loading show="{{true}}" type="change"></l-loading>
** 期望的结果是什么？**
change-spinner这个不是默认居中，可不可以满屏居中？
** 实际的结果是什么？**
./components/loading/index.wxss:1
.change-spinner {
width:240rpx;
text-align:center;
}

**Comment by YpchenLove** [comment]
满屏居中设置full-screen="{{true}}"即可，刚刚测试了4种类型都是生效的。
.change-spinner {
width:240rpx;
text-align:center;
}
上面代码中的width 是动画的父容器的宽度。
如果你对此还有疑问，请描述更详细一点。

**Comment by Donliang** [comment]
> 满屏居中设置full-screen="{{true}}"即可，刚刚测试了4种类型都是生效的。
> .change-spinner {
> width:240rpx;
> text-align:center;
> }
> 上面代码中的width 是动画的父容器的宽度。
> 如果你对此还有疑问，请描述更详细一点。

抱歉，我没说清楚，不是满屏，是满屏幕的宽，默认是居左了，只有240rpx，具体怎么能水平居中，要外包容器吗

**Comment by YpchenLove** [comment]
是的，这是一种解决办法，同样给父容器添加如下代码也能够解决你的问题！
display:flex;
align-items:center;
justify-content:center;
