### ISSUE TITLE
【Loadmore】关于在l-card中使用loadmore会使样式超出边界的问题

### ISSUE THREAD

**Issue by ShenQingchuan** [TaleLin/lin-ui#441]
# 问题描述：
1. 首先当我没有使用 load more 组件时，我的 l-card 内的所有内容都不会超出边界，下面给出两个例子，一个是 l-card 自己的标题，一个是 我在 l-card 内的 view
<img width="282" alt="QQ20190824-102949@2x" src="https://user-images.githubusercontent.com/46062972/63631433-2add1900-c65a-11e9-9442-10d40517f6fa.png">

2. 然后当在l-card中使用到 load more 组件的时候，发现 此 l-card 无论是标题 还是 内容区域 都已经超出了边界
下面给出图例：
<img width="307" alt="QQ20190824-103240@2x" src="https://user-images.githubusercontent.com/46062972/63631474-a8a12480-c65a-11e9-8f86-f9c83b2b025f.png">

<img width="307" alt="QQ20190824-103240@2x" src="https://user-images.githubusercontent.com/46062972/63631478-afc83280-c65a-11e9-9e76-c0134727c4f1.png">

# 问题暂时可行解决办法：
我查看了 **`miniprogram_npm/lin-ui/loadmore/index.wxss`** 源码文件

发现 **`line 9, 10`** 中有 Hard Code 的 width 和 height
<img width="789" alt="QQ20190824-103652@2x" src="https://user-images.githubusercontent.com/46062972/63631506-1d745e80-c65b-11e9-9f6e-aa27bf710db9.png">

而我注释了这两行，发现问题就解决了😖...
<img width="308" alt="QQ20190824-103808@2x" src="https://user-images.githubusercontent.com/46062972/63631518-590f2880-c65b-11e9-864c-b1119d263e4b.png">
<img width="300" alt="QQ20190824-103835@2x" src="https://user-images.githubusercontent.com/46062972/63631520-5ad8ec00-c65b-11e9-90ab-fd577826ac09.png">

**Comment by aQingYun** [comment]
问题已解决 最新版本发布后更新即可

**Comment by ShenQingchuan** [comment]
我试过将很多组件拼接成一张表单，然后做成一张表单卡片。

但是如果是这样，在 Lin-ui 组件库中的很多组件的外部 container包装壳都有 Hard Code 硬编码了的
width 属性。

由于根据 [Weixin app 官方文档 rpx 的相关定义](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html)
1 rpx = 0.5px = 1 物理像素

而大部分硬编码的 width 约 700 ~ 800 左右 也就是 350 - 400 px，
虽然刚好落在目前市面上的各种移动设备屏幕宽度区间内，


但是如果将这些组件内嵌到其他 **适合用来做容器的** 组件中时，就会有超出边界的现象

而这时除非自己再次硬编码定义宽度，

而恰恰 l-class 中关于 width 这时候似乎也出现问题，不起效果


希望下次更新版本中注意一下上述问题吧~
