### ISSUE TITLE
使用l-checkbox出现了问题

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-ui#442]
**重现步骤（可选）：**
代码片段为：https://developers.weixin.qq.com/s/59d3nUmV7AaJ
1、初始化界面，点击三只松鼠前面的复选框

**期望的结果是什么？**
三只松鼠能够被选中

**实际的结果是什么？**
三只松鼠不能够被选中

**Comment by 7insummer** [comment]
建议目前暂时不要使用CheckBox组件，我们正准备重构CheckBox。

**Comment by KDWangBoss** [comment]
好的，谢谢

**Comment by 7insummer** [comment]
Checkbox组件已重构，可以查看最新的组件和文档
