### ISSUE TITLE
图片选择器属性urls，没有能传入id问题

### ISSUE THREAD

**Issue by WEB-hxx** [TaleLin/lin-ui#443]
想在图片选择器组件传入对应服务器的图片id，但是图片选择器属性没有这个参数传入id对应服务器传来的图片；
期盼能传入id，以便做删除图片的时候拿到对应urls传入图片对应的id，请求接口传给后台删除服务器的图片

**Comment by 7insummer** [comment]
这个应该可以用数组来解决吧？不过我们考虑新增一个属性来支持绑定。感谢。

**Comment by zhc525349965** [comment]
已更新，等待升级。

**Comment by zhc525349965** [comment]
已经上线，关闭此issue
