### ISSUE TITLE
segment的一个错误提示

### ISSUE THREAD

**Issue by w0330t** [TaleLin/lin-ui#444]
**重现步骤（可选）：**
在定义了一个segment之后，在页面使用<wx:if>包裹该组件，当让js做数据绑定时让其为false不渲染的时候会报错，用hidden则没有这个问题。

**期望的结果是什么？**
没有错误

**实际的结果是什么？**
报错，`Uncaught (in promise) 找不到元素`
![image](https://user-images.githubusercontent.com/4970238/63785294-b25cad80-c922-11e9-953d-cf016cb2577b.png)

**Comment by 7insummer** [comment]
@uniquenaer  我们查看一下，感谢。

**Comment by 7insummer** [comment]
这是因为wx:if和hidden的机制不同， wx:if机制下segment组件不在页面所以会报这个错误， 不会影响组件的使用
