### ISSUE TITLE
textarea 组件methods携带数据问题

### ISSUE THREAD

**Issue by LOADINGG** [TaleLin/lin-ui#452]
**重现步骤（可选）：**

**期望的结果是什么？**
携带数据一层detail即可，如：event.detail.value
**实际的结果是什么？**
event.detail.detail.value，目前两层才可以获取到

**Comment by 7insummer** [comment]
感谢指出，这是个历史遗留问题，下个版本修复。

**Comment by zhc525349965** [comment]
已经修复该问题，等待升级。

**Comment by zhc525349965** [comment]
已合并到develop上，关闭此issue
