### ISSUE TITLE
toast组件duration设置为999999后，show设置false无效

### ISSUE THREAD

**Issue by LOADINGG** [TaleLin/lin-ui#453]
**重现步骤（可选）：**

**期望的结果是什么？**
show为true时候提示框打开，为false时提示框关闭，而不是duration到期后自动关闭
**实际的结果是什么？**
duration为999999时，show设置false提示框没有关闭

**Comment by 7insummer** [comment]
感谢，这是一个场景支持不完善的问题。下个版本会新增由开发者自己控制，而不是依赖duration
