### ISSUE TITLE
 标签页 Tabs 文档描述错误

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-ui#458]
**重现步骤（可选）：**
## 原文：
> 在 tabs 上设置 animated="true" 开启标签页切换动画，默认不开启。

**期望的结果是什么？**
标签页切换有动画效果
**实际的结果是什么？**
没有效果，查看源码，属性名应该是aminmated，然后这里的示例参数值建议还是写{{true}}

**Comment by aQingYun** [comment]
感谢反馈 这个问题已经修改 将会在下个版本更新


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
