### ISSUE TITLE
【Feature Request】文档细节优化

### ISSUE THREAD

**Issue by woncs** [TaleLin/lin-ui#47]
我是小程序方面的小白，感谢团队带来这么有帮助的组件库。
文档也构建的很好，有些地方细节还希望加强。

比如第一步的引用组件就整懵了一会儿，`组件路径：path/to/${组件名称}/index` ，
没接触过小程序的还以为`path/to`是小程序的内置写法，需要变的只是后面的组件名。。。 
这里改成`${组件路径}/${组件名称}/index`可能就没歧义了。

然后按钮组件的文档，琢磨了好几分钟，楞是没看懂`long`属性是做什么的，看起来就像是宽100%。default按钮也是100%啊。。。后面看了代码才整明白。希望文档里能将这些容易困惑的属性做些讲解。

刚开始摸，可能后面还会有很多小白问题，团队辛苦了。。。

**Comment by 7insummer** [comment]
非常感谢提出意见，文档也是我们很重视的一块。我们会根据反馈优化文档。

**Comment by YpchenLove** [comment]
感谢你的反馈，**快速上** 这一块的内容我会再仔考虑一下怎么写更通俗易懂。因为在之前标注了需要了解小程序的组件化开发。所以也是默认了开发者会基本的引入方法。下面链接是小程序官方对组件化描述的文档。可以参考下~另外有一些开发上的小问题，也可以在群里提出来。
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/

**Comment by YpchenLove** [comment]
感谢你的反馈，**快速上手**这一块的内容我会再仔考虑一下怎么写更通俗易懂。因为在之前标注了需要了解小程序的组件化开发。所以也是默认了开发者会基本的引入方法。下面链接是小程序官方对组件化描述的文档。可以参考下~另外有一些开发上的小问题，也可以在群里提出来。
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/

**Comment by virtualChan** [comment]
> 感谢你的反馈，**快速上手**这一块的内容我会再仔考虑一下怎么写更通俗易懂。因为在之前标注了需要了解小程序的组件化开发。所以也是默认了开发者会基本的引入方法。下面链接是小程序官方对组件化描述的文档。可以参考下~另外有一些开发上的小问题，也可以在群里提出来。
> https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/

坦白说，“组件路径：path/to/${组件名称}/index ”，这个描述，我第一眼看了也是楞了一下

**Comment by YpchenLove** [comment]
刚刚更新了文档，新增了组件入手这一块的内容，帮助开发者快速正确的启动项目！~
http://doc.mini.7yue.pro/start/component.html
