### ISSUE TITLE
【Feature Request】Tag标签使用建议

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#48]
### **背景：我们是卖船票的，船票有余票数的概念。原型如下：**

![image](https://user-images.githubusercontent.com/25305886/51229906-0ff64800-1999-11e9-9667-5dc253879dec.png)

**描述你希望的支持的新功能？**

1. 新增disable属性。
2. 更好的控制显示与否和元素绑定的值

**你期望的 API 是怎样的？**

1. 动态绑定disable属性的值为接口返回数据中的余票字段，disable=”{{!item.count}}“，为true，不可选，样式灰色。
2. 如原型图所示，Tag标签的数量是多个的，目前组件的bind:lintap 只会返回两个属性，一个是标签名称，一个是选中状态，目前我的场景是，用户点击某个区域，才会显示对应价格和配套服务，我暂时用以下方式来实现标识用户点击了哪个区域：

![image](https://user-images.githubusercontent.com/25305886/51230905-8a749700-199c-11e9-8735-43586957b2aa.png)

**假数据：**

![image](https://user-images.githubusercontent.com/25305886/51231067-29998e80-199d-11e9-9bba-d6d08b79b0f3.png)

 **js**
![image](https://user-images.githubusercontent.com/25305886/51230933-a37d4800-199c-11e9-891d-07e1472f53e6.png)

设置data-price无效，所以只能拿到currentIndex后，date[currentIndex]找到对应的元素。这种实现方式有个问题就是，页面始终会有一个是选中的状态，不能取消选中，不知道还有没有其他更优雅方便的方法。

**Comment by aQingYun** [comment]
感谢提议，tag的禁用我会在后面的版本添加上。
