### ISSUE TITLE
使用tabs组件并附带上额外样式如position为fixed和z-index在指定位置显示不出问题

### ISSUE THREAD

**Issue by mengwuya** [TaleLin/lin-ui#485]
**重现步骤（可选）：**
使用tabs组件并附带上额外样式如position为fixed和z-index在指定位置显示，安卓机可以显示，但是当设置position为absolute时就显示不了了，ios机position设置为fixed也不能显示
**期望的结果是什么？**
希望是tabs组件设置position为fixed和absolute时安卓和ios都可以显示
**实际的结果是什么？**
使用tabs组件并附带上额外样式如position为fixed和z-index在指定位置显示，安卓机可以显示，但是当设置position为absolute时就显示不了了，ios机position设置为fixed也不能显示

**Comment by 7insummer** [comment]
有关设置fixed时在ios不限时的问题最新的版本已经修改 absolute我们再测试下

**Comment by uniquenaer** [comment]
设置absolute 后（设备 iphone7p）是可以显示的，那此问题就先关闭了~
