### ISSUE TITLE
radio-group在onLoad 中设置current显示无效

### ISSUE THREAD

**Issue by 1592400107** [TaleLin/lin-ui#498]
**重现步骤（可选）：**
 radio-group 中含有 radio 但在 onload 中设置current显示无效,还是在 data 中设置的 current
**期望的结果是什么？**
能在 onLoad 等其他函数动态改变 current 中的选中项动态变化
**实际的结果是什么？**
无法动态变化

**Comment by 7insummer** [comment]
你这个问题不是组件的问题，组件的行为和onload无关，你需要检查你是否正确的设置了current。或者提供更详细的代码片段。
