### ISSUE TITLE
button组件处于loading状态时仍然会触发tap事件

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#499]
**重现步骤（可选）：**

**期望的结果是什么？**
button组件处于loading状态时禁止触发tap事件
**实际的结果是什么？**
button组件处于loading状态时仍会触发tap事件

**Comment by 7insummer** [comment]
这个我们复查一下，感谢指出。

**Comment by 7insummer** [comment]
已修复，如有需求，可暂时更新develop版本，正式版稍后发出。
