### ISSUE TITLE
steps步骤条组件高度限制导致内容显示重叠

### ISSUE THREAD

**Issue by BigYearsss** [TaleLin/lin-ui#500]
**重现步骤（可选）：**
![8UU8 G`SQOARM05BF@4%44F](https://user-images.githubusercontent.com/48822698/65367656-522e0280-dc67-11e9-9397-9775cde1befb.png)
**期望的结果是什么？**
每个步骤之间的间隔高度相同，不受step容器本身高度限制
**实际的结果是什么？**
step本身高度限制为160rpx，当title内容过多时页面文字产生重叠

**Comment by 7insummer** [comment]
问题我们复查下，感谢指出。

**Comment by juzi214032** [comment]
您好， l-title-class 外部样式类可以修改标题高度

**Comment by suxiaogang** [comment]
@juzi214032 不好意思, 请问一下, `l-title-class` 这个具体怎么使用呢? 我在step中定义了这个自定义类, 然后wxss写了样式, 但是自定义样式没有起作用;

大概的代码如下: 
```
<l-step wx:for="{{steps}}" wx:key="unique" title="{{item.title}}" l-title-class="myTitle"></l-step>
```

```
.myTitle{
  font-size:24rpx;
}
```

**Comment by juzi214032** [comment]
@MuRongXiaoDouBi 处理一下

**Comment by MuRongXiaoDouBi** [comment]
> @juzi214032 不好意思, 请问一下, `l-title-class` 这个具体怎么使用呢? 我在step中定义了这个自定义类, 然后wxss写了样式, 但是自定义样式没有起作用;
> 
> 大概的代码如下:
> 
> ```
> <l-step wx:for="{{steps}}" wx:key="unique" title="{{item.title}}" l-title-class="myTitle"></l-step>
> ```
> 
> ```
> .myTitle{
>   font-size:24rpx;
> }
> ```

您好，由于css权重原因，自定义样式类需使用 `!important` 使样式权重达到最高级别，例：
```
.myTitle{
  font-size:24rpx !important;
}
```

**Comment by suxiaogang** [comment]
感谢 问题解决了 速度真快, 赞一个!

**Comment by MuRongXiaoDouBi** [comment]
> 感谢 问题解决了 速度真快, 赞一个!

感谢支持，请多多推荐我们的组件库哦！
