### ISSUE TITLE
steps组件的activeIndex属性为动态时未能正常显示第几步，看了源码activeIndex为0

### ISSUE THREAD

**Issue by wsq815** [TaleLin/lin-ui#512]
**重现步骤（可选）：**steps的 activeIndex属性为动态时

**期望的结果是什么？** steps 选中效果能动态选中

**实际的结果是什么？** 没有选中任何一个步骤

**Comment by wsq815** [comment]
> **重现步骤（可选）：**steps的 activeIndex属性为动态时
> 
> **期望的结果是什么？** steps 选中效果能动态选中
> 
> **实际的结果是什么？** 没有选中任何一个步骤

observers: {
    'activeIndex': function(row){
      this._initSteps();
    }
  },
  /**
   * 组件的方法列表
   */
  methods: {
    _initSteps() {
      let steps = this.getRelationNodes('../step/index');
      let length = steps.length;
      if (this.data.direction == 'row') this.setData({
        length
      });
      if (length > 0) {
        steps.forEach((step, index) => {
          console.log(this.data,'this.data');
          step.updateDataChange({
            length,
            index,
            ...this.data
          });
        });
      }
    }
  }

加了一步监听activeIndex属性在重新初始化后就可以了

**Comment by 7insummer** [comment]
已知悉，我们尝试复现下。

**Comment by 7insummer** [comment]
已在最新版本修复该问题
