### ISSUE TITLE
关于npm安装lin-ui

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#513]
**重现步骤（可选）：**
使用npm安装lin-ui时，在utils文件夹中util.js导出代码错误，现在是exports

**期望的结果是什么？**
应该是 module.exports或者export
**实际的结果是什么？**
实际导出代码是exports

**Comment by 7insummer** [comment]
0.6.6版本已修复。

**Comment by zhc525349965** [comment]
问题已修复，关闭此issue。
