### ISSUE TITLE
组件写的样式，iOS8不兼容

### ISSUE THREAD

**Issue by WEB-hxx** [TaleLin/lin-ui#518]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by aQingYun** [comment]
您说的不兼容 具体是那个组件 还是说所有的组件


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zhc525349965** [comment]
请详细描述一下遇到的问题，感谢反馈。
