### ISSUE TITLE
Segment 的选中问题

### ISSUE THREAD

**Issue by w0330t** [TaleLin/lin-ui#522]
**重现步骤（可选）：**
Segment在用代码进行选择的时候，如果横向标签较多，页面默认选项会显示不出来需要用户拖动。
图片是我自己用Segment定义的样式
![图片](https://user-images.githubusercontent.com/4970238/66011872-655a9100-e4f7-11e9-80dd-87bf8c9324d1.png)

**期望的结果是什么？**
可以将目前选中的项目显示出来。
![图片](https://user-images.githubusercontent.com/4970238/66011913-87541380-e4f7-11e9-8762-359a89102811.png)

**Comment by aQingYun** [comment]
提供下lin-ui版本号


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by w0330t** [comment]
应该是当前git上面的版本0.6.6，10月2日我刚刚dowload下来的，因为之前老师说这个问题会改，所以我更新了版本来看看。
引用办法不是用的npm，而是用的手动安装，直接把dist改了个名字引用到我的程序里。

**Comment by 7insummer** [comment]
是用代码滚动的时候 不好滚动是吗？我们复查下

**Comment by aQingYun** [comment]
这个问题我们复查了一下 是可以正常滚动的 你尝试一下更新下最新的版本
