### ISSUE TITLE
希望 radio 标签初始化后可以更改current值

### ISSUE THREAD

**Issue by lxc939134342** [TaleLin/lin-ui#526]
**描述你希望的支持的新功能？**
radio组件现在只能在初始化的时候设定current值，而如果我们有异步请求，返回值回来后想更改current的值，就不能更改radio的状态了。
**你期望的 API 是怎样的？**
希望radio组件支持初始化也可以更改值

**Comment by aQingYun** [comment]
感谢反馈 这个需求我们会在后续版本进行支持

**Comment by dpp050700** [comment]
最新版本已支持该功能，如果后续有问题可以再提出
