### ISSUE TITLE
count-down 组件外部样式类异常

### ISSUE THREAD

**Issue by coymaple** [TaleLin/lin-ui#527]
`<l-countdown l-class="tip-deadline" l-class-time="countdown-time" time="{{buyDeadline}}"/>`

如上所示使用lin-ui的倒计时组件时，在使用 l-class-time 设置外部样式类时，发现不能覆盖默认样式。使用 `!important` 强行提升样式权重以后，可以覆盖默认样式了。

在开发者工具里面观察到该组件内部相应位置默认样式类被放在最后面，猜测是这个原因。

![image](https://user-images.githubusercontent.com/28804891/66470320-ef889380-eabb-11e9-8b5d-5c8025833d3f.png)

**Comment by aQingYun** [comment]
外部样式类的使用参考http://doc.mini.7yue.pro/start/wx.html

**Comment by aQingYun** [comment]
外部样式类使用参考http://doc.mini.7yue.pro/start/class.html 建议都加上！important
