### ISSUE TITLE
使用模态框组件Dialog添加自定义插槽textarea，在真机中不能完全隐藏

### ISSUE THREAD

**Issue by haokj** [TaleLin/lin-ui#528]
**重现步骤（可选）：**
1. 在小程序页面中使用模态框组件，添加自定义插槽textarea
![image](https://user-images.githubusercontent.com/28664106/66481752-1eaaff00-ead4-11e9-9f16-bd19b92a98c7.png)

**期望的结果是什么？**
![image](https://user-images.githubusercontent.com/28664106/66481791-31bdcf00-ead4-11e9-95bc-0c856f5fc865.png)

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/28664106/66481953-83fef000-ead4-11e9-9c9d-c88ef749e756.png)

**Comment by 7insummer** [comment]
@zhc525349965

**Comment by 7insummer** [comment]
该问题已修复 在下个版本即可正常使用
