### ISSUE TITLE
错误报告：组件slide-view 样式问题

### ISSUE THREAD

**Issue by watebang** [TaleLin/lin-ui#540]
**重现步骤（可选）：**
**1.小程序代码片段复现**
https://developers.weixin.qq.com/s/jUWR56mZ7pcd

> 记得构建npm

**2.组件slide-view里仅有的样式**
`.movable-content {
  display: flex;
  direction: row;
  overflow: hidden;
}

.container {
  overflow: hidden;
}
`

**期望的结果是什么？**
[如林间有风文档案例所示](http://doc.mini.7yue.pro/component/response/slide-view.html#%E5%9F%BA%E7%A1%80%E6%A1%88%E4%BE%8B)

**实际的结果是什么？**
实际结果只有骨架，没有css

**Comment by 7insummer** [comment]
这个组件是没有问题的。样式这些东西写在demo里，查看源码下面的examples里的slideview。css太多了不适合写在文档里。

**Comment by watebang** [comment]
好的，谢谢，占用您时间了




------------------ 原始邮件 ------------------
发件人: "林白"<notifications@github.com>; 
发送时间: 2019年10月14日(星期一) 下午5:03
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com>; 
抄送: "waterbang"<409071692@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TaleLin/lin-ui] 错误报告：组件slide-view 样式问题 (#540)




这个组件是没有问题的。样式这些东西写在demo里，查看源码下面的examples里的slideview。css太多了不适合写在文档里。

**Comment by Zengxiaoer991214** [comment]
emmm...请问为什么我查看了examples里面的slideview，并没有找到CSS样式

**Comment by MuRongXiaoDouBi** [comment]
> emmm...请问为什么我查看了examples里面的slideview，并没有找到CSS样式

https://github.com/TaleLin/lin-ui/blob/master/examples/pages/components/response/pages/slide-view/index.wxss
