### ISSUE TITLE
Tabs 标签页设置图标大小无效

### ISSUE THREAD

**Issue by lxc939134342** [TaleLin/lin-ui#541]
标签页 icon-size 设置值无效，不起作用！
查看源码发现
` <l-icon wx:if="{{item.icon}}" l-class="l-class-icon l-icon-class" l-self-class="{{item.key===activeKey ? 'l-icon-active':'l-icon-inactive'}}" name="{{item.icon}}" color="{{item.key===activeKey?activeColor:inactiveColor}}" size="{{iconSize}}"/>
`
`size="{{iconSize}}"`应该改为 `size="{{item.iconSize}}"`
@7insummer

**Comment by zhc525349965** [comment]
感谢反馈，我们会在下个版本解决此问题

**Comment by lxc939134342** [comment]
是否可以支持一下自定义图标的样式类名呢？像icon组件一样可以使用自定义的图标 @zhc525349965

**Comment by zhc525349965** [comment]
自定义图标样式可以使用图片资源，
http://doc.mini.7yue.pro/component/nav/tabs.html#图片资源
文档中有使用方式

**Comment by zhc525349965** [comment]
已解决，等待下个版本升级

**Comment by zhc525349965** [comment]
已经上线发布，关闭此issue
