### ISSUE TITLE
loading组件l-class外部样式类问题

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#544]
**重现步骤（可选）：**

**期望的结果是什么？**
任何类型的loading都可以使用l-class
**实际的结果是什么？**
只有类型为flash的loading才能使用l-class

**Comment by dpp050700** [comment]
好的 我们复查一下 将尽快修复。感谢指出问题。

**Comment by dpp050700** [comment]
我们最新版本已经修复了该问题，感谢指出！后续问题欢迎issues
