### ISSUE TITLE
Segment组件在place为left时，属性scrollable无效

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#552]
**LinUI版本（必填）：**
0.6.7
**设备（必填）：**
微信开发者工具、小米8屏幕指纹版
**基础库版本（必填）：**
2.8.3
**UI问题，请附上截图**
![](https://i.loli.net/2019/10/18/CWpsOZHtDjh56x1.gif)

**重现步骤，必要时请提供代码片段链接**
placement为left
scrollable为true

**Comment by juzi214032** [comment]
找到原因了，将图中代码注释就好了
因为我是写后端的，不太清楚其中的原因
希望官方人员看到能解惑一下 谢谢
![](https://i.loli.net/2019/10/18/728AqSBKMtOenTH.png)

**Comment by dpp050700** [comment]
您好 感谢反馈。 我们先复查一下问题 将尽快解决，再下一版本发布。

**Comment by dpp050700** [comment]
您好 我们测试过目前的版本 Segment 组件是可以正常滚动的

**Comment by dpp050700** [comment]
您好 我们测试过目前版本的 Segment 组件是可以正常滚动的
开启scrollable 首先要给height属性设置一个固定的值，同时将even设置成false
我们先关闭此条issues 如果后续有使用问题可以再次提出， 感谢反馈！
以下是我们的使用案例可供参考：
![image](https://user-images.githubusercontent.com/24217083/67159724-496e4080-f37b-11e9-9b15-c39d32d71149.png)
