### ISSUE TITLE
复选框组件点击为什么没有效果？

### ISSUE THREAD

**Issue by russellxrs** [TaleLin/lin-ui#555]
**LinUI版本（必填）：0.6.7

**设备（必填）：微信开发工具

**基础库版本（必填）：2.0.4

复制文档里的代码，复选框出现了，但是点击没有反应（选中和取消选中），接收linchange的事件detail，checked属性永远为true

 
![image](https://user-images.githubusercontent.com/39029427/67193460-e71f4980-f427-11e9-9997-2a0dd14cf067.png)

**Comment by 7insummer** [comment]
2.0.4 都已经是前年的基础库了，现在都2.9.0了

**Comment by russellxrs** [comment]
还了2.9.0还是一样，点击没有反应。  基础组件checkbox checkbox-group正常的

**Comment by russellxrs** [comment]
是不是要通过改变l-checkbox组件上的checked属性来改变选中状态？

**Comment by 7insummer** [comment]
看文档，
![image](https://user-images.githubusercontent.com/24819249/67258795-e983b100-f4c4-11e9-898c-eb7f24acf406.png)
