### ISSUE TITLE
image-picker在编辑场景之下的使用

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#563]
**描述你希望的支持的新功能？**
在编辑场景之下，需要image-picker，有默认图片可以展示，但是现在urls这个配置项废弃之后，应该如何在编辑时，展示默认图片呢？
**你期望的 API 是怎样的？**
希望提供一个配置项urls，数据类型为Array

**Comment by zhc525349965** [comment]
urls之前的使用方式现在还在兼容，是否废弃团队内部还在讨论。
新的使用方式，也可以配置默认图片，只需要在urls中传入一组对象，对象包含url和key。
类似于：
urls = [{url: '1.jpg', key:'key1'}, {url:'2.jpg', key :'key2' }]

**Comment by zhc525349965** [comment]
官网文档已同步更新。详细使用方式请查看http://doc.mini.7yue.pro/component/form/image-picker.html#图片选择器属性（imagepicker-attributes）
