### ISSUE TITLE
【Bug Report】toast轻提示，z-index不够高

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#57]
**期望的结果是什么？**
toast轻提示，不能自定义z-index导致会被页面其它有层级的view所挡住
希望能自定义组件.container容器的z-index

**Comment by YpchenLove** [comment]
这是设计组件时没有考虑到的情况，很抱歉。我们会在下个alpha.7版本中，新增z-index属性，来自由控制toast的层级。
另外，会将toast默认的z-index设置的更加合理，让开发者不比每次都去调整z-index的值！
感谢问题的反馈！

**Comment by YpchenLove** [comment]
@Donliang 最新版本已经修复！感谢反馈
