### ISSUE TITLE
瀑布流组件   当数据为 [] 时，refresh 为true， 页面数据不会刷新,依旧保持之前的数据。 

### ISSUE THREAD

**Issue by webyzf0109** [TaleLin/lin-ui#572]
页面初始渲染：(这个时ok的)
wx.lin.renderWaterFlow([ {url:'http://www.baicu.com',name:'baidu'}], true, () => {
       console.log('渲染成功')
})

点击触发：(数据还是上面那个 )
wx.lin.renderWaterFlow([], true, () => {
       console.log('渲染成功')
})

**Comment by 7insummer** [comment]
感谢反馈 我们测试下 给出答复

**Comment by jackmanwu** [comment]
这个问题我刚遇到了，还修复吗

**Comment by juzi214032** [comment]
> 这个问题我刚遇到了，还修复吗

0.8.4 版本已修复
