### ISSUE TITLE
image-picker组件希望在返回的数据之中加上临时文件的size

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#575]
**描述你希望的支持的新功能？**
现在image-picker无法在选择图片之后拿到临时文件的内存大小值，进而无法对图片的上传进行拦截验证
**你期望的 API 是怎样的？**
希望在event.detail中能够返回文件临时大小的属性值

**Comment by 7insummer** [comment]
感谢反馈 我们会在后续开发考虑加入该功能

**Comment by zhc525349965** [comment]
已完成，等待升级

**Comment by zhc525349965** [comment]
0.6.13已经实现，具体见官方文档。
