### ISSUE TITLE
form的没有reset功能

### ISSUE THREAD

**Issue by Debaes** [TaleLin/lin-ui#580]
**LinUI版本（必填）：最新版本

**设备（必填）：微信开发工具

**基础库版本（必填）：最新版本

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by 7insummer** [comment]
自定义组件是无法替代原生的表达的 submit的，如果是用于表单的submit等功能，只能使用原生button

**Comment by Debaes** [comment]
<view class="message">
  <text >基本信息</text>
  </view>
 <form  bindsubmit="formSubmit" bindreset="formReset">
<view class="basic-info">
          <l-input label="学号:"  type="digit" name="user_stuNum" value="{{user.user_stuNum}}"   placeholder="请输入学号"   />
           <l-input label="联系方式:"   name="user_link" value="{{user.user_link}}" placeholder="请输入联系方式 如'QQ:xxxxx'"  />
         <l-input label="姓名:"   name="user_name" value="{{user.user_name}}"  placeholder="请输入姓名"  />
         <l-input label="地址:"   name="user_address" value="{{user.user_address}}"  placeholder="请输入你的取货地址"  />
     <button  form-type="submit">修改</button>
//此处  submit  可以提交   但是  reset 后无法对输入框内容进行初始化
      <button  form-type="reset">重置</button>

</view>
 </form>

**Comment by 7insummer** [comment]
@dpp050700

**Comment by dpp050700** [comment]
0.7.3 版本全新form组件已上线，欢迎使用。
