### ISSUE TITLE
关于使用checkbox-group获取当前选中所有值的问题

### ISSUE THREAD

**Issue by Mr-houzi** [TaleLin/lin-ui#582]
**LinUI版本（必填）：*0.6.7*

**设备（必填）：*微信开发者工具*

**基础库版本（必填）：*2.9.2*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

原生 `checkbox-group`触发`bindchange`，可以通过 `e.detail.value` 获取当前选中的所有值，但通过`l-checkbox-group`触发`bind:linchange`，在`e.detail`中仅能看到，当前点击的值。请问如何获取当前选中的所有值？

**Comment by 7insummer** [comment]
我们核查下这个问题 @dpp050700

**Comment by dpp050700** [comment]
您好， l-checkbox-group 组件要获取当前选中的所有值，需要在linchange事件中手动遍历选项list， 取出checked为true时的items。

**Comment by Mr-houzi** [comment]
> 您好， l-checkbox-group 组件要获取当前选中的所有值，需要在linchange事件中手动遍历选项list， 取出checked为true时的items。

好的，感谢。
另外：感觉l-checkbox封装后要比原生checkbox使用复杂。

**Comment by dpp050700** [comment]
l-checkbox封装时为了满足大部分用户的使用情况，在使用上有一点复杂。
如果您在使用过程中有更好的优化意见  欢迎给我们提出issue。

**Comment by Mr-houzi** [comment]
> l-checkbox封装时为了满足大部分用户的使用情况，在使用上有一点复杂。
> 如果您在使用过程中有更好的优化意见 欢迎给我们提出issue。

好的

**Comment by 7insummer** [comment]
原生的 checkbox太弱了，Lin的 CheckBox可以满足任意的样式需求，当然相应的成本就是使用起来稍微繁琐一点，这是没办法避免的。
