### ISSUE TITLE
is.wxs中TYPE[type] === val.constructor这个怎么会成立呢？val.constructor指向的应该是对象的引用吗？

### ISSUE THREAD

**Issue by lydat** [TaleLin/lin-ui#583]
**LinUI版本（必填）：**

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/36094163/68367150-fadce680-016f-11ea-99c4-eff12638f1ba.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by uniquenaer** [comment]
在微信小程序里返回的是该类型的字符串

**Comment by lydat** [comment]
> 在微信小程序里返回的是该类型的字符串
> [数据类型 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/06datatype.html)

谢谢，之前没怎么关注这个
