### ISSUE TITLE
基础库升级到2.93之后，textarea组件bindlininput不起作用了，字数统计也不起作用了

### ISSUE THREAD

**Issue by 254980080** [TaleLin/lin-ui#586]
![4TWJ6$0GOU@TR2{5`WD(P7U](https://user-images.githubusercontent.com/22535480/68747325-417d8580-0635-11ea-96b1-b128bac00b2b.png)
![20CAX{@L6YY@ZL3S4PO_FX2](https://user-images.githubusercontent.com/22535480/68747368-5a863680-0635-11ea-93cd-efda13516663.png)
基础库升级到2.93之后，textarea组件bindlininput不起作用了，字数统计也不起作用了

**Comment by dpp050700** [comment]
感谢反馈， 我们核查问题后尽快修复！

**Comment by zhc525349965** [comment]
有关基础库升级至2.9.3导致表单组件事件无法触发的问题，目前是由于微信开发者工具所导致的，在真机上调试并无该问题，把基础库调至2.9.2即可，或者可以使用真机调试。等待微信团队的修复，同时感谢反馈。
