### ISSUE TITLE
Tag组件cell属性文档描述错误

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-ui#588]
**LinUI版本（必填）：**
0.6.5
**设备（必填）：**
开发者工具
**基础库版本（必填）：**
2.4.3
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/49727104/68852118-38aeb180-0712-11ea-8b70-b8b371b54831.png)

**重现步骤，必要时请提供代码片段链接**

文档写着cell属性接收一个字符串，传入字符串后点击的事件回调里cell是null，看源码这个属性是接收一个Object，传入Object后正常。

**Comment by aQingYun** [comment]
感谢指正 我们会尽快修改


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zhc525349965** [comment]
已经修改。改写指正。
