### ISSUE TITLE
image-picker应该要支持signType配置，不能直接在组件写死signType

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#598]
**描述你希望的支持的新功能？**
在开发当中，如果一次性上传九张大图的情况在所难免，这时需要使用sizeType为compressed，否则低配置的手机会出现内存过大，导致程序卡死。
**你期望的 API 是怎样的？**
希望提供proprieties属性来控制signType

**Comment by zhc525349965** [comment]
当前版本已经支持，关闭此issue。
