### ISSUE TITLE
textarea 组件无法调节文本输入区域高度

### ISSUE THREAD

**Issue by yantonglan** [TaleLin/lin-ui#599]
textarea 组件 通过 外部样式类 改变heigh
整个组件占用空间是 改变了
但文本输入框的大小还是不变
里面只能显示一行内容

**Comment by zhc525349965** [comment]
感谢反馈，我们会讨论此问题的修改方式。

**Comment by zhc525349965** [comment]
l-class为Textarea 组件的外部样式类，不能更改内部textarea的高度，如需显示多行，需将auto-height设置为true

**Comment by zhc525349965** [comment]
预计提供一个外部样式类来解决此问题

**Comment by yzy132** [comment]
还有如果设置组件属性auto-height为true的时候，现在文本域高度自动变为一行，外部样式height无效，可是正常使用场景下那个文本框的高度不应该是只有一行吧，应该是有一个高度，等大于那个高度再自动增高，并且我同时希望那个高度值可以有用户自己设置~

**Comment by zhc525349965** [comment]
> 还有如果设置组件属性auto-height为true的时候，现在文本域高度自动变为一行，外部样式height无效，可是正常使用场景下那个文本框的高度不应该是只有一行吧，应该是有一个高度，等大于那个高度再自动增高，并且我同时希望那个高度值可以有用户自己设置~

这个组件是将官方的textarea做了封装，我看了一下官方的目前就不支持你上面所说的这种写法，所以我们也没办法支持。
