### ISSUE TITLE
checkbox-group设置min-selected后取消选择无法触发

### ISSUE THREAD

**Issue by Mr-houzi** [TaleLin/lin-ui#601]
**LinUI版本（必填）：*0.6.7*

**设备（必填）：*微信开发者工具*

**基础库版本（必填）：*2.9.3*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

问题：当我设置min-selected=1，但是我的data中设置advance数据为全没选中，然后我想在onLoad中请求数据，并对advance重新赋值，这时我点取消选中，是无法触发事件的。

我怀疑是min-selected是根据一开始data设置的数据判断的，而不是根据onLoad新赋值的数据判断的。（瞎猜）

[代码片段链接](https://developers.weixin.qq.com/s/s5JznWmE7Ncu)

**Comment by dpp050700** [comment]
感谢反馈！我将核查该问题，尽快修复。

**Comment by dpp050700** [comment]
我们已经修复了该问题并发布了新的版本。
