### ISSUE TITLE
视频上传组件（video-picker）

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#605]
**描述你希望的支持的新功能？**
需要一个视频上传组件可以做到视频上传，如果可以还需要一个l-video视频组件
**你期望的 API 是怎样的？**
希望后期版本能够开发一个video-picker，目前在电商小程序中，还会涉及到很多短视频的哦

**Comment by 7insummer** [comment]
暂时不支持video组件。这个用的不多。
