### ISSUE TITLE
"l-water-flow-item”: true微信上没问题，QQ小程序只能是字符串"true"

### ISSUE THREAD

**Issue by aioloscn** [TaleLin/lin-ui#606]
**LinUI版本（必填）：*0.6.11*

**设备（必填）：*mac*

**基础库版本（必填）：*QQ小程序1.8.0*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by 7insummer** [comment]
这个是由于qq小程序基础哭版本过低导致的该问题 true正常情况下是不应该加上引号的 这个等待qq小程序更新就好
