### ISSUE TITLE
在微信开发者工具v RC 1.02.1909111 部分使用wx:for以及bindtap的组件出现warning

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-ui#608]
**LinUI版本（必填）：**
0.6.11及其以下所有版本
**设备（必填）：**
全部
**基础库版本（必填）：**
2.9.2+
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
在lin-ui中使用l-grid、image-picker等使用wx:for的组件都会出现如下warning：
``` 
./dist/grid/index.wxml
 wx:key="{{item.key}}" does not look like a valid key name (did you mean wx:key="key" ?)
```

使用bindtap需要改成bind:tap这样的写法，否则也会出现warning！

**Comment by dpp050700** [comment]
感谢反馈！ 我们核查一下问题，将在下个版本修复。

**Comment by zhc525349965** [comment]
使用相同版本的开发工具和lin-ui，未复现该问题。请提供下复现代码。

**Comment by ThoughtZer** [comment]
@dpp050700 出现同样的问题。

`./components/lin-ui/grid/index.wxml
 wx:key="{{item.key}}" does not look like a valid key name (did you mean wx:key="key" ?)`

![image](https://user-images.githubusercontent.com/23690568/70621106-c5865580-1c53-11ea-8d1d-02e69f03956c.png)
