### ISSUE TITLE
关于SlideView组件自动关闭与主动关闭问题

### ISSUE THREAD

**Issue by NicolasDevil** [TaleLin/lin-ui#611]
**LinUI版本（必填）：v0.6.8**

**设备（必填）：iOS**

**基础库版本（必填）：2.9.1**

**使用SlideView组件执行列表删除操作，首先进行删除Ajax请求后重新请求后台列表接口（GetList方法）已达到刷新页面的效果，在这种情况下如果当前被删除列表index下标为1的话，那么在执行GetList方法后，下标为index+1的那条列表菜单栏会自动打开，然后关闭。很影响用户体验，请求大佬指点迷津！**

**Comment by dpp050700** [comment]
感谢反馈 我们先验证一下。

**Comment by dpp050700** [comment]
你把auto-close属性设置成true 看一下

**Comment by NicolasDevil** [comment]
我尝试过，改成true就是问题中的情况是一样的，改成false后，执行GetList方法后下标index+1的那个列表菜单栏会莫名其妙的打开

**Comment by dpp050700** [comment]
auto-close设置成true是每次点击后都会自动关闭的， false是需要手动关闭

**Comment by dpp050700** [comment]
你删除后获取列表只是相当于更新了数据  但是滑动状态还是之前的 你用close属性手动设置下关闭 应该是可以的。

**Comment by NicolasDevil** [comment]
就是因为更新了数据所以滑动状态作用到了下一条列表上，即列表下标为index+1的列表的滑动状态会打开，然后自动关闭

**Comment by dpp050700** [comment]
好的  我们后续先讨论一下你说的这种情况
