### ISSUE TITLE
counter组件 bug

### ISSUE THREAD

**Issue by yantonglan** [TaleLin/lin-ui#612]
通过count属性设置 counter 的 默认值, 显示还是1 但 增加会从默认值开始

**Comment by dpp050700** [comment]
我测试之后并未发现这个问题，你提供一下具体的使用方式或代码片段。

**Comment by yantonglan** [comment]
使用很简单 比如
<l-counter count="5" bind:lintap="onChange"/> 
初次显示 计数器应该是5 可是,计数器实际显示的是1  减号无法点, 点加号后显示6

**Comment by zhc525349965** [comment]
根据提供的代码，未复现你说的问题。请确认使用版本是否为最新版本。如果为最新版本，请提供基础库版本与开发工具版本。
