### ISSUE TITLE
混合标签 Combined Tabs 的一个小bug

### ISSUE THREAD

**Issue by spiderpm** [TaleLin/lin-ui#613]
**LinUI版本（必填）：0.6.8

**设备（必填）：安卓

**基础库版本（必填）：2.9.3

**UI问题，在swipeable="{{false}}"的情况下，只有第一个标签有内容，切换到其它标签下内容显示不出来，详细截图：https://www.jianshu.com/p/6837f1d45a2f

**Comment by dpp050700** [comment]
感谢反馈 我们将尽快修复该问题

**Comment by uniquenaer** [comment]
问题已修复在最新版本0.6.13中
