### ISSUE TITLE
l-tag组件bug

### ISSUE THREAD

**Issue by teevil** [TaleLin/lin-ui#618]
**LinUI版本（必填）：0.6.12
设置了icon-name不生效，还需要设置icon属性才能显示图标，更改部分没和文档同步。

**Comment by dpp050700** [comment]
感谢反馈！tag 图标的使用有 bug ！我们将尽快修复！

**Comment by dpp050700** [comment]
您好， 最新版本已修复了该问题，感谢反馈。
