### ISSUE TITLE
statusShow组件custom属性未声明

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#619]
**LinUI版本（必填）：**0.6.12

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
statusVIew组件，wxml中使用了custom属性，js中没有声明，使得自定义无效

**Comment by dpp050700** [comment]
感谢反馈 我们尽快修复 在下个版本发布。

**Comment by dpp050700** [comment]
您好， 最新版本已修复了该问题，感谢反馈。
