### ISSUE TITLE
Toast组件的placement属性通过api调用传入无效

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#629]
**LinUI版本（必填）：**
0.6.12
**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
```javascript
wx.lin.showToast({
      title:"刷新成功",
      placement:"bottom"
})
```
toast仍然显示在屏幕中间

**Comment by 7insummer** [comment]
placement属性是指文字相对于图片的位置 不是toast组件相对于屏幕的位置

**Comment by juzi214032** [comment]
> placement属性是指文字相对于图片的位置 不是toast组件相对于屏幕的位置

哦哦 那toast组件位置是无法修改的吗 有一些重要性低的toast信息不想显示在屏幕中央

**Comment by 7insummer** [comment]
toast组件在移动端一般都是显示在屏幕中间的 安卓系统提示的消息才会显示在屏幕下方

**Comment by juzi214032** [comment]
> toast组件在移动端一般都是显示在屏幕中间的 安卓系统提示的消息才会显示在屏幕下方

是的 我就是使用的android 没用过ios  底部toast看习惯了 哈哈哈

**Comment by 7insummer** [comment]
所以暂时不能修改toast组件位置 你可以通过外部样式类实现

**Comment by juzi214032** [comment]
> 所以暂时不能修改toast组件位置 你可以通过外部样式类实现

好的 谢谢了
