### ISSUE TITLE
toast组件设置为loading时可以手动关闭吗

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#631]
**LinUI版本（必填）：**
0.6.12
**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

例如我在请求后端接口之前显示toast，那么可以在拿到数据的回调中主动关闭toast吗

**Comment by zhc525349965** [comment]
设置show属性

**Comment by juzi214032** [comment]
> 设置show属性

我是用wx.lin的api形式调用的，用show来控制就得写到wxml中，感觉还是不太方便

**Comment by zhc525349965** [comment]
wx.lin的调用方式确实漏掉了，会补充wx.lin的方式隐藏。

**Comment by zhc525349965** [comment]
已经修改完成，等待升级。

**Comment by zhc525349965** [comment]
0.6.13已经修复。
