### ISSUE TITLE
希望在grid组件中添加一个排序功能

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#632]
**描述你希望的支持的新功能？**
grid-item根据传入的order进行排序
**你期望的 API 是怎样的？**
提供一个属性order

**Comment by zhc525349965** [comment]
griditem的排序应从后端通过接口返回，不应当在前端计算。

**Comment by juzi214032** [comment]
> griditem的排序应从后端通过接口返回，不应当在前端计算。

我的意思是后端会返回一个order字段，代表排第几，这样前端再根据这个order排序，这样也不合适吗

**Comment by 7insummer** [comment]
你自己在js里排好不行吗。。。

**Comment by juzi214032** [comment]
> 你自己在js里排好不行吗。。。

我知道js可以排，我看grid用的是flex布局，flex布局本身是支持order属性的，所以我觉得可能用flex自身的order属性来排序会更好一点

**Comment by zhc525349965** [comment]
组件中不增加排序功能，你需要在js中处理好，然后传递到组件中。
