### ISSUE TITLE
自定义组件不支持 ：‘组件和引用组件的页面不能使用id选择器（#a）、属性选择器（[a]）和标签名选择器，请改用class选择器。’

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-ui#633]
**LinUI版本（必填）：0.6.11

**设备（必填）：开发平台

**基础库版本（必填）：1.7

**UI问题，请附上截图**
VM1123:1 Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors
**重现步骤，必要时请提供代码片段链接**

https://github.com/TaleLin/lin-ui/blob/e3e36c7d1a6cd239f526ae774d17a27163acbf3e/src/loading/index.less#L253-L263

**Comment by 7insummer** [comment]
麻烦指出具体问题谢谢

**Comment by teevil** [comment]
微信开发者工具升级版本之后出现的。比如avatar组件中，如下写法就会报错。
open-data {
    width: 100%;
    height: 100%
}

.l-avatar-text open-data, .l-avatar-text text {
    font-size: inherit;
    color: inherit;
    line-height: inherit
}
报错内容：
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/lin-ui/avatar/index.wxss:1:358)

**Comment by zhc525349965** [comment]
没看明白你的描述。使用avatar组件时，并未出现你说的报错。你是更改了源码？还是在引用组件的地方写了外部样式类？
