### ISSUE TITLE
按需引入组件自定义编译时报错

### ISSUE THREAD

**Issue by plusprimer** [TaleLin/lin-ui#637]
**LinUI版本（必填）：**
0.6.12
**设备（必填）：**
windows 
**基础库版本（必填）：**
npm 6.9.0
node 10.16.0
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
按文档要求在config/component.json中填入所需组件，然后执行npm run build命令进行编译，编译失败。根据排查，执行npm run lint即报错
![image](https://user-images.githubusercontent.com/6312186/69926520-c13d9800-14ef-11ea-87e4-0c7de03c00fe.png)

报错log文件内容如下
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle lin-ui@0.6.12~prelint: lin-ui@0.6.12
6 info lifecycle lin-ui@0.6.12~lint: lin-ui@0.6.12
7 verbose lifecycle lin-ui@0.6.12~lint: unsafe-perm in lifecycle true
8 verbose lifecycle lin-ui@0.6.12~lint: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\plugins-wechat\lin-ui-master\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\yuyi\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH;C:\Program Files\TortoiseSVN\bin;C:\Users\yuyi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\yuyi\AppData\Roaming\npm;C:\Users\yuyi\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip;C:\Users\yuyi\AppData\Local\Programs\Fiddler
9 verbose lifecycle lin-ui@0.6.12~lint: CWD: D:\plugins-wechat\lin-ui-master
10 silly lifecycle lin-ui@0.6.12~lint: Args: [ '/d /s /c', 'eslint ./src/**/*.js' ]
11 silly lifecycle lin-ui@0.6.12~lint: Returned: code: 1  signal: null
12 info lifecycle lin-ui@0.6.12~lint: Failed to exec lint script
13 verbose stack Error: lin-ui@0.6.12 lint: `eslint ./src/**/*.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid lin-ui@0.6.12
15 verbose cwd D:\plugins-wechat\lin-ui-master
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error lin-ui@0.6.12 lint: `eslint ./src/**/*.js`
22 error Exit status 1
23 error Failed at the lin-ui@0.6.12 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by 7insummer** [comment]
感谢反馈 我们复现这个问题

**Comment by dpp050700** [comment]
您好  版本0.6.13已经修复了该问题
