### ISSUE TITLE
腾讯的wepy框架怎么去使用lin-ui

### ISSUE THREAD

**Issue by zhangkaivictor** [TaleLin/lin-ui#638]
{
    navigationBarTitleText: 'WePY 2.0 Feature Demo',
    usingComponents: {
      panel: '~@/components/panel',
      counter: '~counter',
      list: '../components/list',
      group: '../components/group',
      "slide-view": "module:miniprogram-slide-view",
      "l-list": "module:lin-ui/dist",
    }
}
我在wepy2的框架中去使用lint-ui的报错，
[20:14:36] ERR! Can't resolve 'lin-ui/dist' in 'D:\myminiapp\src\pages'
[20:14:36] ERR! compile Compile failed. Add "--log trace" to see more details

**Comment by dpp050700** [comment]
lin-ui是用原生小程序语言开发的，暂时不能和其他非原生UI框架一起使用。

**Comment by zhangkaivictor** [comment]
> lin-ui是用原生小程序语言开发的，暂时不能和其他非原生UI框架一起使用
好的，了解了，谢谢。
