### ISSUE TITLE
wx.lin使用Toast的自定义icon无法显示

### ISSUE THREAD

**Issue by hejunyuan** [TaleLin/lin-ui#639]
**LinUI版本（必填）：*0.6.12*

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
`<l-icon name="wenhao" l-class="icon-common"></l-icon>`
`<l-toast l-icon-class="icon-common"></l-toast>`

我写了一个button  用来激活
`  wx.lin.showToast({
            title:'请输入关键字',
            duration:2000,
            icon: "wenhao"
        })`

相关css
`@font-face {
    font-family: 'sleeve';  /* project id 1514070 */
    src: url('//at.alicdn.com/t/font_1514070_2f522389l3f.eot');
    src: url('//at.alicdn.com/t/font_1514070_2f522389l3f.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_1514070_2f522389l3f.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_1514070_2f522389l3f.woff') format('woff'),
    url('//at.alicdn.com/t/font_1514070_2f522389l3f.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_1514070_2f522389l3f.svg#sleeve') format('svg');
}

.icon-common {
    font-family: "sleeve" !important;
    font-size: 20px !important;
    font-style: normal !important;
}

.l-icon-wenhao:before {
    content: "\e71d";
}`

**Comment by hejunyuan** [comment]
l-icon可以显示出来  
l-toast无法显示

**Comment by dpp050700** [comment]
感谢反馈 我们复查一下。

**Comment by dpp050700** [comment]
toast组件中的l-icon-class 是 l-icon 组件 组件的外部样式， 你需要通过设置 l-icon-class下的 view 的样式来改变icon图标
