### ISSUE TITLE
popup文档中的默认z-index错误

### ISSUE THREAD

**Issue by YYJeffrey** [TaleLin/lin-ui#646]
**LinUI版本（必填）：0.6.12
**设备（必填）：iphone6
**基础库版本（必填）：2.9.4

文档中z-index默认值写了99，而在模拟器调试时它的层级为777。
![image](https://user-images.githubusercontent.com/25133698/70207170-e38c1b80-1764-11ea-9ae0-a12f00bb645b.png)

![image](https://user-images.githubusercontent.com/25133698/70207182-f30b6480-1764-11ea-96cf-1b5d9395ffbb.png)

**Comment by 7insummer** [comment]
感谢反馈 文档问题我们会尽快修改
