### ISSUE TITLE
dialog组件关闭时没有动画

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#647]
**描述你希望的支持的新功能？**
popup增加了关闭动画，但是dialog还没有关闭动画，希望dialog也增加关闭动画
**你期望的 API 是怎样的？**

**Comment by dpp050700** [comment]
您好 我们讨论下 在后续的版本考虑提供该功能

**Comment by dpp050700** [comment]
您好 dialog 组件目前已支持关闭动画
