### ISSUE TITLE
segment组件直接修改active-key时，内容不会自动滚动居中

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#648]
**LinUI版本（必填）：**
0.6.13
**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
直接点击segment-item会居中，但是直接修改active-key的值，不会自动滚动居中

**Comment by uniquenaer** [comment]
感谢反馈，我们核实后悔尽快修复此问题

**Comment by uniquenaer** [comment]
您好，不好意思回复晚了，这个问题已经修复了，更新最新版本即可使用
