### ISSUE TITLE
toast组件可以让其永久显示吗

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#649]
**描述你希望的支持的新功能？**
目前在js中通过wx.lin显示toast的loading样式，期望的是让loading永久显示，直到调用wx.lin.hiddeToast()手动关闭。建议可以当duration值为0时，就永久显示。
**你期望的 API 是怎样的？**

**Comment by dpp050700** [comment]
您好 我们将在后续的版本里面提供该功能。
