### ISSUE TITLE
Bug Report   textarea组件boder下边框线一直存在

### ISSUE THREAD

**Issue by yzy132** [TaleLin/lin-ui#651]
当我设置了属性值boder为false的时候
![图片](https://user-images.githubusercontent.com/52056297/70588700-8b439680-1c08-11ea-9db5-a6399f363d91.png)
效果预览如下
![图片](https://user-images.githubusercontent.com/52056297/70588724-a0b8c080-1c08-11ea-9c78-feba7c123243.png)
可以看到下边框线是依旧存在的，我想实现的效果为
![图片](https://user-images.githubusercontent.com/52056297/70588755-be862580-1c08-11ea-828e-d63f14593188.png)
但是当我设置了外部样式类的时候
预览效果如下
![图片](https://user-images.githubusercontent.com/52056297/70588827-f4c3a500-1c08-11ea-9241-ce42003f75bf.png)
可以看到下边框线是依旧存在的，我调试之后发现源码中有一个样式类单独控制这条下划线的显示效果，截屏如图
![图片](https://user-images.githubusercontent.com/52056297/70588922-3f452180-1c09-11ea-9f4f-6ac97d5d4bb9.png)

**Comment by zhc525349965** [comment]
感谢反馈。这个问题已经解决，等待下次升级。现在textarea区域以及border区域（textarea+字数统计）分别支持单独的外部样式类。

**Comment by Jokky6** [comment]
这边还是希望有一个l-border-class可以对border自定义的

**Comment by yzy132** [comment]
> 
> 
> 这边还是希望有一个l-border-class可以对border自定义的

boder通过l-class就可以改吧~

**Comment by zhc525349965** [comment]
> 这边还是希望有一个l-border-class可以对border自定义的

你说的border就是现在的的l-class
