### ISSUE TITLE
grid组件

### ISSUE THREAD

**Issue by superzhengcn** [TaleLin/lin-ui#654]
**LinUI版本（必填）：**

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
https://developers.weixin.qq.com/s/f2j5jxmz7odD

**Comment by zhc525349965** [comment]
请描述你所遇到的问题。另外，你发的链接无法打开。

**Comment by superzhengcn** [comment]
这是小程序代码片段，可以打开的呀。描述不清楚，你们打开我提供的代码片段切换试一下就知道了。大致就是：比如我有三组数据用grid组件显示，第一组有一个grid-item,然后切换到第二组2个grid-item的时候可以正常显示，但是如果我再切换到第三组一个grid-item时就会出问题。

**Comment by dpp050700** [comment]
这个问题我们已修复过了 你更新一下最新版本。
