### ISSUE TITLE
l-segment下的组件has-line设置以后无效

### ISSUE THREAD

**Issue by wuyanwei** [TaleLin/lin-ui#657]
**LinUI版本（必填）：*lin-ui@0.6.13*

**设备（必填）：*Iphone6*

**基础库版本（必填）：*2.9.4*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
<l-segment bind:linchange="changeTabs" has-line="false" active-color="#38b5ef" inactive-color="#333">

**Comment by uniquenaer** [comment]
您好，麻烦提供更详细的信息，方便我们定位问题以及解决问题

**Comment by wuyanwei** [comment]
不好意思，是我使用的方式错误造成
