### ISSUE TITLE
LinUI 0.6.13 最新版本的 l-card 卡片组件里，primary类型和cover类型里没有设置图片image组件的 mode属性可配置的数据的问题

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#659]
今天使用卡片组件来初始化瀑布流，通过图片的自适应高度来撑开容器的高度
正常：
![image](https://user-images.githubusercontent.com/30004721/71471204-c699b400-2809-11ea-9253-55ebc0ce7a8a.png)
有问题：
![image](https://user-images.githubusercontent.com/30004721/71471570-d5349b00-280a-11ea-9ca8-edbfa9254d12.png)

可是通过组件的入口添加 mode 的  widthFix 属性的时候,图片的高度并没有自适应 https://developers.weixin.qq.com/miniprogram/dev/component/image.html
（微信小程序image的mode属性）
![image](https://user-images.githubusercontent.com/30004721/71471272-f34dcb80-2809-11ea-933c-280e9cc64542.png)

看了lin-UI的card  组件的源码， primary 和cover 模式的mode 属性设置了aspectFill 默认值
这是故意而为，还是通过其他的方法进行更改图片的 mode值
![image](https://user-images.githubusercontent.com/30004721/71471390-4a53a080-280a-11ea-9600-1a4bd84826d6.png)

**Comment by dpp050700** [comment]
感谢反馈 我们核实一下。

**Comment by liangjuncheng1995** [comment]
请问反馈的问题有用吗

**Comment by aQingYun** [comment]
已经修改 下个版本就会更新


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 7insummer** [comment]
版本已发布 更新即可
