### ISSUE TITLE
Segment组件问题

### ISSUE THREAD

**Issue by whitmymyth** [TaleLin/lin-ui#660]
**LinUI版本（必填）：0.6.11

**设备（必填）：微信开发工具及iphone6s

**基础库版本（必填）：2.9.4

AB页面同时使用Segment组件，A页面redirectToB页面，Segment最后一个参数会闪一下，使用navigateTo则不会出现问题。

**Comment by dpp050700** [comment]
感谢反馈 我们核实一下问题。
