### ISSUE TITLE
请问会开发通讯录这样的索引列表组件吗?

### ISSUE THREAD

**Issue by BeFearless4U** [TaleLin/lin-ui#663]
**描述你希望的支持的新功能？**
希望能开发一个索引列表这样的一个组件

**Comment by zhc525349965** [comment]
详细描述一下你的需求。我们会开会讨论是否添加该组件。感谢关注。

**Comment by BeFearless4U** [comment]
> 详细描述一下你的需求。我们会开会讨论是否添加该组件。感谢关注。

像微信的通讯录一样,按姓名首字母分组,侧边点击字母跳转对应位置

**Comment by juzi214032** [comment]
你好，该组件正在开发，预计下个版本发布，可以先看一下文档是否满足你的需求，如有其他需求，欢迎随时反馈。
[文档地址](http://doc.mini.7yue.pro/component/layout/index-list.html)

**Comment by juzi214032** [comment]
0.8.0 版本已添加IndexList组件
