### ISSUE TITLE
mpvue里引用lin-ui报错或怎么在mpvue里使用lin-ui组件库

### ISSUE THREAD

**Issue by frcy9** [TaleLin/lin-ui#665]
**LinUI版本（必填）：*0.6.13*

**设备（必填）：*web开发者工具*

**基础库版本（必填）：*2.9.4*

**UI问题，请附上截图**

![image](https://user-images.githubusercontent.com/11570233/71656543-80e36b00-2d76-11ea-8ef7-6efbffa5f5f3.png)

![image](https://user-images.githubusercontent.com/11570233/71656552-8b056980-2d76-11ea-90a2-7f4f133de5f9.png)

![image](https://user-images.githubusercontent.com/11570233/71656554-922c7780-2d76-11ea-913b-b18d388c1e8b.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by frcy9** [comment]
引用绝对路径也不行

**Comment by dpp050700** [comment]
main.json 里面的路径不对 应该是 '../../static/linui/../..'
![image](https://user-images.githubusercontent.com/24217083/71780347-5e628380-2ffc-11ea-823e-4a54ecefd776.png)
![image](https://user-images.githubusercontent.com/24217083/71780354-9073e580-2ffc-11ea-9fb4-ba8519667d3d.png)
![image](https://user-images.githubusercontent.com/24217083/71780362-aaadc380-2ffc-11ea-8e79-0b4b9400c6d7.png)
![image](https://user-images.githubusercontent.com/24217083/71780356-99fd4d80-2ffc-11ea-8027-3c137f0e3e50.png)

**Comment by YpchenLove** [comment]
@dpp050700 感谢这位同学的回复 && @frcy9 可以查看下这条issue下的回答，看看有没有帮助到你~

**Comment by frcy9** [comment]
@YpchenLove 有的  谢谢 @dpp050700

**Comment by Damonlanyang** [comment]
使用mpvue引入linui按照上面的方法试了依然报错
![image](https://user-images.githubusercontent.com/23103070/79435281-04f9ef80-8002-11ea-8225-7cd102b50b9c.png)

![image](https://user-images.githubusercontent.com/23103070/79435359-1e9b3700-8002-11ea-9ac5-8a70a5013f61.png)

**Comment by juzi214032** [comment]
> 使用mpvue引入linui按照上面的方法试了依然报错
> ![image](https://user-images.githubusercontent.com/23103070/79435281-04f9ef80-8002-11ea-8225-7cd102b50b9c.png)
> 
> ![image](https://user-images.githubusercontent.com/23103070/79435359-1e9b3700-8002-11ea-9ac5-8a70a5013f61.png)

相对路径前面写../../../ 你只写了两个 目录层级不对

**Comment by Damonlanyang** [comment]
> > 使用mpvue引入linui按照上面的方法试了依然报错
> > ![image](https://user-images.githubusercontent.com/23103070/79435281-04f9ef80-8002-11ea-8225-7cd102b50b9c.png)
> > ![image](https://user-images.githubusercontent.com/23103070/79435359-1e9b3700-8002-11ea-9ac5-8a70a5013f61.png)
> 
> 相对路径前面写../../../ 你只写了两个 目录层级不对

![image](https://user-images.githubusercontent.com/23103070/79436583-a897cf80-8003-11ea-9779-8efce5051f5a.png)
改成../../../，依然报同样的错

**Comment by juzi214032** [comment]
@Damonlanyang  检查一下这个文件是否有问题 static/dist/action-sheet/index.js

**Comment by Damonlanyang** [comment]
> @Damonlanyang 检查一下这个文件是否有问题 static/dist/action-sheet/index.js

这个文件就是从linui的仓库下载后直接把dist文件夹复制进去的。这个文件就是个压缩js
![image](https://user-images.githubusercontent.com/23103070/79437622-07aa1400-8005-11ea-8af5-f99c98a6e932.png)

**Comment by Damonlanyang** [comment]
> @Damonlanyang 检查一下这个文件是否有问题 static/dist/action-sheet/index.js

解决了。在微信开发者工具里，把ES5->ES6选项勾选上就可以了。
