### ISSUE TITLE
不知道如何应用于Taro框架的项目中

### ISSUE THREAD

**Issue by djinFang** [TaleLin/lin-ui#678]
看到首页开始写的支持第三方框架Taro,mpvue,但不知道如何在项目中应用，喜欢在入门章节中可以简要做一些介绍，谢谢

**Comment by dpp050700** [comment]
1、在src目录下创建static文件夹

**Comment by dpp050700** [comment]
1、在src目录下创建static文件夹
2、将 lin-ui 源码dist 文件夹拷贝放入 static
![image](https://user-images.githubusercontent.com/24217083/72581289-cdec4300-3919-11ea-9537-6e69b1609945.png)
3、引入 button 组件 和 icon 组件
![image](https://user-images.githubusercontent.com/24217083/72581313-e3fa0380-3919-11ea-9af2-a672f98039d9.png)

4、使用组件 查看效果
![image](https://user-images.githubusercontent.com/24217083/72581331-f2e0b600-3919-11ea-8632-cbd9f462fb3c.png)
![image](https://user-images.githubusercontent.com/24217083/72581339-fbd18780-3919-11ea-8273-35071bb3ab60.png)

**Comment by dpp050700** [comment]
//config配置
config = {
      navigationBarTitleText: '首页',
      usingComponents: {
        'l-button': '../../static/dist/button/index',
        'l-icon': '../../static/dist/icon/index'
      }
    }
// 使用组件
<l-button>333</l-button>
        <l-icon name='add' />

**Comment by djinFang** [comment]
感谢解答！

**Comment by JunhaoHuang0615** [comment]
如果我需要使用lin-ui的一些api，比如在微信小程序中的wx.lin.renderWaterFlow(this.data.data_list) 应该怎么办呢？
