### ISSUE TITLE
新增相册组件在仅有一个图片时候好像显示不出来

### ISSUE THREAD

**Issue by 380862139** [TaleLin/lin-ui#680]
**LinUI版本（必填）：0.7.2

**设备（必填）：iPX

**基础库版本（必填）：2.8.3

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by zhc525349965** [comment]
提供下复现的代码

**Comment by 380862139** [comment]
直接下载打开你们的UI了example，然后在模拟器上打开相册组件，第一个图没有展示，失效的图片链接更换了，也没显示出来

**Comment by zhc525349965** [comment]
IDE是否勾选了不校验合法域名？

**Comment by 380862139** [comment]
谢谢，解决了
