### ISSUE TITLE
按需引入，npm run build 出错

### ISSUE THREAD

**Issue by IIIIIIIIF** [TaleLin/lin-ui#681]
**LinUI版本（必填）：**0.7

**设备（必填）：**
命令行
**基础库版本（必填）：**
node 12.14 npm6.13.4
**UI问题，请附上截图**
![QQ截图20200117154147](https://user-images.githubusercontent.com/29888011/72593452-f5560680-393f-11ea-88bd-29e2eb70507e.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by zhc525349965** [comment]
为复现问题，检查一下npm版本

**Comment by juzi214032** [comment]
将该文件内两处`\`删除即可
![](https://oss.juzibiji.top/image/wecqupt/20200209221935.png)
