### ISSUE TITLE
Grid组件wx:key属性填写错误

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#682]
**LinUI版本（必填）：**
0.7.2
**设备（必填）：**
与设备无关
**基础库版本（必填）：**
与基础库无关
**UI问题，请附上截图**
![截图](https://oss.juzibiji.top/image/20200126010314.png)
**重现步骤，必要时请提供代码片段链接**
Gird组件中代码`wx:key="{{item.key}}"`是错误的，正确的应为`wx:key="key"`

**Comment by aQingYun** [comment]
感谢反馈 我们核实后会进行修改

**Comment by GDC6203** [comment]
https://developers.weixin.qq.com/community/develop/doc/000600fb83c158c1e26999fa951400
