### ISSUE TITLE
Avatar组件文档错误

### ISSUE THREAD

**Issue by juzi214032** [TaleLin/lin-ui#683]
**LinUI版本（必填）：**

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
![](https://oss.juzibiji.top/image/20200126190356.png)
**重现步骤，必要时请提供代码片段链接**
`open-data`可选值错误，应为`['userAvatarUrl','userNickName']`

**Comment by aQingYun** [comment]
感谢指正 我们会尽快修改

**Comment by zhc525349965** [comment]
已经修改完成
