### ISSUE TITLE
两个linui组件嵌套时，事件名称相同导致点击内部组件会触发两次外部的组件的事件

### ISSUE THREAD

**Issue by fishwithwater** [TaleLin/lin-ui#687]
**LinUI版本（必填）：**
0.7.2
**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
```
<l-list gap="10" bind:lintap="tap" >
    <view slot="left-section">
      <l-avatar size="70" icon="user" iconColor="#fff" text="未登录"/> 
    </view>
</l-list>
```
点击l-avatar时会触发两次l-list的lintap事件。

很多组件都有lintap事件并且都是冒泡的，应该不止这种嵌套会有这样的问题

**Comment by zhc525349965** [comment]
暂时无法处理这个问题，需要整体更改设计。你可以先手动更改源码，更改事件名称。

**Comment by zhc525349965** [comment]
长时间未反馈，关闭此issue。

**Comment by juzi214032** [comment]
你好，这个问题我们已经定位了，主要是由原生的tap事件冒泡引起，因为涉及到所有组件的修改，所以解决方案还需要斟酌一下，已加入后期开发计划

**Comment by juzi214032** [comment]
该问题已解决，将在下个版本更新

**Comment by fishwithwater** [comment]
👍
