### ISSUE TITLE
选项卡 Segment设置高度问题—在iPhoneXR上

### ISSUE THREAD

**Issue by bhy135** [TaleLin/lin-ui#688]
iponeXS Mas，iphone11上高度不正确，设置为168rpx，给出的是184rpx=》92px

**Comment by zhc525349965** [comment]
我们查看一下。 
@uniquenaer

**Comment by uniquenaer** [comment]
不是给出的是184rpx,而是rpx与px的换算值变了，不再是1/2了，[WXSS | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html#%E5%B0%BA%E5%AF%B8%E5%8D%95%E4%BD%8D)
