### ISSUE TITLE
表单下的检验页面报错

### ISSUE THREAD

**Issue by BeFearless4U** [TaleLin/lin-ui#691]
**LinUI版本（必填）：0.7.2

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
![QQ截图20200219171418](https://user-images.githubusercontent.com/42951741/74819620-a3880e00-533b-11ea-9480-3da59893f2ee.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by dpp050700** [comment]
您好 麻烦详细描述一下这个问题。 这个图片现在我们网速问题也加载不出来。

**Comment by dpp050700** [comment]
您好  你先升级到最新版 看看有没有这个问题。

**Comment by BeFearless4U** [comment]
thirdScriptError
keys有重复元素, chekbox的key属性不能重复：; [Component] Relation Linked Callback Error @ dist/checkbox-group/index#linked
Error: keys有重复元素, chekbox的key属性不能重复

thirdScriptError
keys有重复元素, radio的key属性不能重复：; [Component] Relation Linked Callback Error @ dist/radio-group/index#linked
Error: keys有重复元素, radio的key属性不能重复：

然后radio和checkbox的value值页面不显示
