### ISSUE TITLE
 Segment 组件 选项卡的组件能实现左右滑动内容来切换栏目的变化吗

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#695]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by uniquenaer** [comment]
不能，需要你自己在切换内容时修改当前激活的选项卡

**Comment by liangjuncheng1995** [comment]
好的，明白了，
标签页 Tabs 组件
和 混合标签 Combined Tabs
是可以做到此功能的吧

**Comment by uniquenaer** [comment]
是的，Tabs 组件和 混合标签 Combined Tabs是支持的

**Comment by Damonlanyang** [comment]
请问，自定义选项卡，怎么把下面的内容放进去？
![image](https://user-images.githubusercontent.com/23103070/79840281-49adce00-83e8-11ea-8b3e-8c81adccef5b.png)

**Comment by juzi214032** [comment]
> 请问，自定义选项卡，怎么把下面的内容放进去？
请重新开个issue详细描述一下，这个截图看懂什么意思 @Damonlanyang
