### ISSUE TITLE
表单组件下的校验页面报错

### ISSUE THREAD

**Issue by BeFearless4U** [TaleLin/lin-ui#699]
**LinUI版本（必填）：0.7.3

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
![QQ截图20200225095151](https://user-images.githubusercontent.com/42951741/75207700-7496ef80-57b4-11ea-8117-3b466c352d43.png)

**重现步骤，必要时请提供代码片段链接**

1.由于 checkebox和radio上缺少key值,导致报错:keys有重复元素, chekbox的key属性不能重复/radio的key属性不能重复; 

2.checkbox和radio的value值无法在页面上显示

**Comment by dpp050700** [comment]
您好 由于网速问题 您的截图无法正常显示，麻烦到官方QQ群下反馈下这个问题，我们会尽快核实修复

**Comment by dpp050700** [comment]
感谢反馈，example中的代码我已经修复，下个版本将更新

**Comment by dpp050700** [comment]
您好 最新版已经修复了此问题
