### ISSUE TITLE
l-tabpanel 循环 不能加载异步返回的数据 

### ISSUE THREAD

**Issue by lalahuang** [TaleLin/lin-ui#70]
**重现步骤（可选）：**

**期望的结果是什么？** l-tabpanel  循环异步返回的数据 并且能加载样式

**实际的结果是什么？** 没有加载出来

**Comment by uniquenaer** [comment]
> **重现步骤（可选）：**
> 
> **期望的结果是什么？** l-tabpanel 循环异步返回的数据 并且能加载样式
> 
> **实际的结果是什么？** 没有加载出来


感谢反馈，这个问题我们会尽快修复，修复后会告知您的

**Comment by uniquenaer** [comment]
> **重现步骤（可选）：**
> 
> **期望的结果是什么？** l-tabpanel 循环异步返回的数据 并且能加载样式
> 
> **实际的结果是什么？** 没有加载出来
您好，问题在0.0.1 alpha.9版本修复了，你可以更新这个版本使用，再次感谢您的反馈
