### ISSUE TITLE
表单示例代码出错

### ISSUE THREAD

**Issue by dumian** [TaleLin/lin-ui#701]
**LinUI版本（必填）：0.7.3

**设备（必填）：微信开发者工具

**基础库版本（必填）：2.10.1

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
表单示例代码第一段在调试时出现两个问题：
1、input 的label不显示，直接在input中声明可显示。
2、submit后detail.values返回空值，error返回undefined。

**Comment by dumian** [comment]
![image](https://user-images.githubusercontent.com/1998115/75267910-cc277080-5831-11ea-9003-cd2fc9be6444.png)
补一个图

**Comment by dpp050700** [comment]
感谢使用，如有后续问题 欢迎反馈
