### ISSUE TITLE
使用组件的过程中，出现大量的警告信息，导致微信开发者工具导致卡顿崩溃。

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#702]
"lin-ui": "^0.7.2" 0.7.2 版本

在微信开发者工具中

基础库版本： 2.10.1

使用大部分的组件 比如  l-tabs 组件的时候

为什么会出现大量的警告信息

![image](https://user-images.githubusercontent.com/30004721/75305872-4c75c200-5882-11ea-97b6-a0d04a7ba1bf.png)

组件使用的频率一旦很多的时候就会出现开发者工具的卡顿，开发的体验不太好

在真机上是不会有卡顿的情况。

**Comment by dpp050700** [comment]
感谢反馈 我们将尽快修复。

**Comment by zhc525349965** [comment]
更新到最新版本。
