### ISSUE TITLE
关于l-tabs组件 想添加 设置内容区域（swiper）的高度。

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-ui#703]
希望 l-tabs组件 可以通过传入属性值 设置内容区域（swiper ） 的高度
![image](https://user-images.githubusercontent.com/30004721/75310943-353dd100-5890-11ea-905c-d9f6c646a8a3.png)
我这里的需求是tab 栏下面的区域全是显示的 内容
只能获取小程序整块的显示高度（wx.getSystemInfoSync().windowHeight） - tab栏的高度
这里使用lin-ui的工具类的 px2rpx 转 rpx 的方法计算出 高度 （wHeight）

然后传入 l-tabs 组件里面 

![image](https://user-images.githubusercontent.com/30004721/75311081-aa110b00-5890-11ea-9f22-0ed37ac2981e.png)

然后在 l-tabs 组件的properties 接收高度
![image](https://user-images.githubusercontent.com/30004721/75311249-18ee6400-5891-11ea-9282-3d5b44ab99c6.png)

接着在 组件的生命周期函数attached 里面 setData 
![image](https://user-images.githubusercontent.com/30004721/75311217-0b38de80-5891-11ea-9762-d8c342dfaf8b.png)

最后在组件的里面的swiper 组件加上内联样式的高度
![image](https://user-images.githubusercontent.com/30004721/75311273-315e7e80-5891-11ea-94b0-c2edb590cde0.png)

**Comment by uniquenaer** [comment]
感谢建议，我们会尽快加一下~

**Comment by juzi214032** [comment]
已添加 content-height 属性，将在下个版本上线
