### ISSUE TITLE
无法使用input组件中的rule校验规则功能。

### ISSUE THREAD

**Issue by rainysweet** [TaleLin/lin-ui#709]
**LinUI版本（必填）：最新版
按照文档介绍使用input组件中的rule校验功能，不能出现预想的结果，无任何错误提示。和QQ群里的维护人员已经沟通，确实存在此问题。

**Comment by dpp050700** [comment]
感谢反馈 我将尽快修复

**Comment by uniquenaer** [comment]
您好，问题已修复，更新最新版本即可查看
