### ISSUE TITLE
【Bug Report】消息提示显示图像会提前消失

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-ui#71]
**重现步骤（可选）：**
lin-UI中，“操作反馈”→“消息提示”，点击“成功提示”、“错误提示”等带图标的提示

**期望的结果是什么？**
图标与消息同时从上方弹出，同时收回

**实际的结果是什么？**
图标与消息同时从上方弹出，收回时图标直接消失，文字居中收回

**Comment by YpchenLove** [comment]
@gaojx97 收到了，是message组件吗，还是toast组件？

**Comment by aQingYun** [comment]
你好，问题已经解决，今天晚上更新。

**Comment by gaojx97** [comment]
感谢大佬，期待LinUI早日完善~
