### ISSUE TITLE
使用segment组件时报错height未定义，位置在behaviors/scrollCenter.js第16行

### ISSUE THREAD

**Issue by TXxyin** [TaleLin/lin-ui#712]
**LinUI版本（必填）：**
0.7.3
**设备（必填）：**
微信开发者工具
**基础库版本（必填）：**
2.10.3
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
使用segment组件时报错：
Uncaught (in promise) thirdScriptError
Cannot read property 'height' of undefined
TypeError: Cannot read property 'height' of undefined
    at http://127.0.0.1:16258/appservice/miniprogram_npm/lin-ui/behaviors/scrollCenter.js:32:16

**Comment by juzi214032** [comment]
感谢反馈，我们将尽快修复

**Comment by TXxyin** [comment]
补充：在微信开发者工具中，是自动暂停进入调试，点“继续执行脚本”按钮后，可以正常显示segment内容，高度也没问题。在手机上预览时，不会暂停进入调试，显示都正常。
（希望修复后可以告知一下，3Q~~）

**Comment by uniquenaer** [comment]
您好，问题已修复，更新最新版本即可查看
