### ISSUE TITLE
需求：小程序横向选择器

### ISSUE THREAD

**Issue by lzpswat** [TaleLin/lin-ui#715]
**描述你希望的支持的新功能？**

需求背景：目前市面所有选择器都是上下选择，有点占空间，且操作易用性方面不如横向选择器。

功能介绍：横向的选择器，通过左右滑动进行菜单选择，每个选项下面都有相关描述。

**你期望的 API 是怎样的？**

参数变量（对应gif图）：

-选择器名称（十一月）
-选项名称（日期）
-选项描述（周几）

![家政类动效展示1](https://user-images.githubusercontent.com/28242587/77026805-87759c00-69cf-11ea-8a0e-291e51d7ea79.gif)

**Comment by juzi214032** [comment]
使用`Segment`组件可实现该效果
