### ISSUE TITLE
除了图片选择器，未来会开发录音选择器、视频选择器吗？

### ISSUE THREAD

**Issue by xlsxuegao** [TaleLin/lin-ui#717]
**描述你希望的支持的新功能？**
录音选择器功能：支持录音，选择录音文件，可以听选择的录音内容和录音完成后的内容。
视频选择器功能：支持摄像，选择视频文件，在线预览视频。
**你期望的 API 是怎样的？**
API我暂时没好的想法，希望能像图片选择器一样好用。

**Comment by zhc525349965** [comment]
暂时还未有此计划。
近期的安排可查看 https://github.com/TaleLin/lin-ui/issues/445

**Comment by xlsxuegao** [comment]
图片选择器支持进度条使用吗？
