### ISSUE TITLE
小白来请教

### ISSUE THREAD

**Issue by wunanda** [TaleLin/lin-ui#718]
请问为什么我在根目录下没有找到config/style/_theme.less

**Comment by juzi214032** [comment]
在[项目源码目录](https://github.com/TaleLin/lin-ui/tree/master/config/styles)下，不是从npm下载的文件

**Comment by wunanda** [comment]
> 在[项目原始目录](https://github.com/TaleLin/lin-ui/tree/master/config/styles)下，不是从npm下载的文件
多谢大佬。嘿嘿嘿，那请问是不是把config文件下载拷贝到我项目的根目录就行了

**Comment by juzi214032** [comment]
> > 在[项目原始目录](https://github.com/TaleLin/lin-ui/tree/master/config/styles)下，不是从npm下载的文件
> > 多谢大佬。嘿嘿嘿，那请问是不是把config文件下载拷贝到我项目的根目录就行了

需要把项目clone下来，修改config后执行npm run build编译，再把dist拷贝到你的项目

**Comment by wunanda** [comment]
> > > 在[项目原始目录](https://github.com/TaleLin/lin-ui/tree/master/config/styles)下，不是从npm下载的文件
> > > 多谢大佬。嘿嘿嘿，那请问是不是把config文件下载拷贝到我项目的根目录就行了
> 
> 需要把项目克隆下来，修改config后执行npm run build编译，再把dist拷贝到你的项目

哦哦，我懂了，十分感谢
