### ISSUE TITLE
文本域自动增高不起效果的问题

### ISSUE THREAD

**Issue by NaOH123321** [TaleLin/lin-ui#723]
如图所示，在文本域中已加入了auto-height="{{true}}", 但是在模拟器上或是真机上并不能完全随着字数而自动增高，常常有两行左右的文字看不到，需用滚动条查看。经过反复测试，苹果手机出现的问题比较多。
![微信图片_20200325140428](https://user-images.githubusercontent.com/32951650/77506874-eb053b00-6ea1-11ea-87da-a061a1909632.png)

**Comment by uniquenaer** [comment]
收到反馈，会尽快解决~~

**Comment by dpp050700** [comment]
已发布新版，该问题已解决
