### ISSUE TITLE
请问支持typescript吗？

### ISSUE THREAD

**Issue by Edward66** [TaleLin/lin-ui#724]
**描述你希望的支持的新功能？**
用typescript写小程序可以在ts文件里用wx.lin掉用放法
**你期望的 API 是怎样的？**
wx.lin

**Comment by juzi214032** [comment]
请问你是在ts里面使用wx.lin失败吗，我们这边还没有尝试过这样使用

**Comment by Edward66** [comment]
嗯，是在ts里使用wx.lin失败，在编译过后的js文件里到是可以引用

**Comment by juzi214032** [comment]
暂时还无法在ts里面使用wx.lin，后期我们会出ts版本，可以关注一下

**Comment by Edward66** [comment]
嗯嗯，谢谢，辛苦了！

**Comment by jq94666** [comment]
@juzi214032 有计划什么时候推出ts版吗

**Comment by juzi214032** [comment]
@jq94666  暂无确定日期
