### ISSUE TITLE
关于自定义icon

### ISSUE THREAD

**Issue by tclcm1987** [TaleLin/lin-ui#728]
我在小程序自定义的组件中使用l-icon组件，发现如果按照教程使用自定义图标时，在组件的wxss中写入类似于下面这样
.l-icon-duihao:before {
    content: "\e63c";
}
带content属性的样式是不起作用的，只能在引入该组件的page中写入这些带content属性的样式才能启到作用，这是为什么？
是因为这些样式只能写在page的wxss中吗？

**Comment by uniquenaer** [comment]
组件内的样式默认只对组件内部样式有效，可以在page的wxss中自定义icon，是因为icon组件设置了addGlobalClass: true，是得页面可以影响icon的样式
