### ISSUE TITLE
【l-button禁用状态时+结合dialog使用会有穿透现象】-当点击button禁用按钮状态时-dialog弹框仍然会弹出

### ISSUE THREAD

**Issue by itclanCode** [TaleLin/lin-ui#730]
**LinUI版本（必填）：*^0.7.3*

**设备（必填）：*安卓9-华为*

**基础库版本（必填）：*2.10.0*

**UI问题，请附上截图**
![禁止按钮结合dialog使用会出现穿透现象](https://user-images.githubusercontent.com/25076543/77821214-5c075580-7123-11ea-99ae-47feace663b8.gif)

**重现步骤，必要时请提供代码片段链接**
`<l-button class="send-btn" bg-color="{{ btnBgColoColor }}"  size="long" shape="square" bind:tap="send" disabled="{{ isBtnDisabled }}">发布</l-button>
</view>`

**Comment by uniquenaer** [comment]
收到反馈，核实后若确认有问题会尽快修复

**Comment by 7insummer** [comment]
请问你描述的意思是按钮在禁用状态下还会触发按钮绑定的事件吗？

**Comment by juzi214032** [comment]
能否提供一个最简demo，我们这边测试暂时未发现这个问题

**Comment by itclanCode** [comment]
> 请问你描述的意思是按钮在禁用状态下还会触发按钮绑定的事件吗？

是的,是的,按钮禁用状态时,依旧会触发绑定的事件

**Comment by juzi214032** [comment]
麻烦提供一下wxml和js代码
