### ISSUE TITLE
Message在没有导航栏的刘海屏手机显示异常

### ISSUE THREAD

**Issue by shmilyQin** [TaleLin/lin-ui#732]
**LinUI版本（必填）：**
0.7.3
**设备（必填）：**
iphonex
**基础库版本（必填）：**
2.10.4
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/20322678/78030990-7d6f7800-7395-11ea-80cb-11a954a8fca0.png)

**重现步骤，必要时请提供代码片段链接**
1将页面的导航栏改为自定义."navigationStyle": "custom" 设备切换为iPhone X等有刘海屏的机型.就会出现这样的问题

**Comment by 7insummer** [comment]
感谢反馈 我们会尽快修复这个问题

**Comment by juzi214032** [comment]
问题已修复，将在下个版本更新

**Comment by shmilyQin** [comment]
请问一下什么时候更新0.7.6呢?

**Comment by juzi214032** [comment]
> 请问一下什么时候更新0.7.6呢?

已更新
