### ISSUE TITLE
Tabs组件在IOS最新版微信会出现渲染问题，官方文档页出现此bug 

### ISSUE THREAD

**Issue by NicolasDevil** [TaleLin/lin-ui#733]
**LinUI版本（必填）：最新版

**设备（必填）：IPONEXS

**基础库版本（必填）：2.10.3

详情请使用最新版（IOS微信7.0.12）打开LinUI官方小程序-->导航组件-->请查看非等宽标签/滚动标签/图标标签/图片标签栏目，切换后tabpanel内容会莫名消失 @7insummer

**Comment by uniquenaer** [comment]
收到反馈，我们会尽快看一下如何解决

**Comment by NicolasDevil** [comment]
请问是哪块出问题了，我自己应如何修改 @uniquenaer

**Comment by NicolasDevil** [comment]
你们是真的牛逼，我这issue提了1个月了竟然还在确认，一个css问题确认了一个月👍，很棒，继续保存 @uniquenaer

**Comment by juzi214032** [comment]
不好意思，这个我们很早就测试过了，只是 issue 这边忘记改状态了
我们用 iphone xr 测试没有复现这个问题，你提的问题可能是特定机型bug，因为我们这边没有对应的测试机型无法进行问题定位，实在抱歉。
您可以尝试修复一下，然后为项目提一个pr
![image](https://user-images.githubusercontent.com/38206169/80665112-26abaa00-8acb-11ea-867c-331a981c59d4.png)
![image](https://user-images.githubusercontent.com/38206169/80665119-29a69a80-8acb-11ea-9473-77e27941279f.png)

**Comment by NicolasDevil** [comment]
演示地址：[http://qiniu.wxsub.com/issue29video.mp4](url)

手机型号：IPHONE XS
