### ISSUE TITLE
样式标签名错误提示

### ISSUE THREAD

**Issue by ChasonHong** [TaleLin/lin-ui#736]
**LinUI版本（必填）：*最新版*

**设备（必填）：*所有设备*

**基础库版本（必填）：*最新基础库*
 
控制台提示组件里面样式使用了标签名：
Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./miniprogram_npm/lin-ui/action-sheet/index.wxss:1:352)

**Comment by juzi214032** [comment]
感谢反馈，下个版本将进行修复
