### ISSUE TITLE
VM6838:1 direction: column must be in the [row,colunm]

### ISSUE THREAD

**Issue by ChasonHong** [TaleLin/lin-ui#740]
**LinUI版本（必填）：*最新版*

**设备（必填）：*最新版*

**基础库版本（必填）：*最新版*

步骤条校验bug： 使用<l-steps reverse="{{true}}" direction="column" step-min-height="160" color="#00CC83" active-index="{{step}}">，后控制报column must be in the [row,colunm]，是不是源码列名字校验写错了

**Comment by aQingYun** [comment]
感谢反馈 这个是源码内的检验信息写错了 会在下个版本进行修复


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
