### ISSUE TITLE
模态框 Dialog，被小程序文本域盖住

### ISSUE THREAD

**Issue by ChasonHong** [TaleLin/lin-ui#743]
**LinUI版本（必填）：*最新生产版*

**设备（必填）：*所有设备*

**基础库版本（必填）：*最新库*

**当页面中使用组件`<l-textarea  placeholder="说说你的想法吧..."  />`后，同时又使用模态框 Dialog时，文本域文字覆盖在弹层之上**

**Comment by dpp050700** [comment]
麻烦提供一下具体的代码或者重现步骤，我这边测试并没有你说的现象。

**Comment by ChasonHong** [comment]
> 麻烦提供一下具体的代码或者重现步骤，我这边测试并没有你说的现象。
真机上测试，页面中间放一个<l-textarea placeholder="说说你的想法吧..." />，弹窗刚好在这个文本域上面时就能看到文本域内的文字穿透到了弹层之上

**Comment by ChasonHong** [comment]
@dpp050700 
真机上测试，页面中间放一个，弹窗刚好在这个文本域上面时就能看到文本域内的文字穿透到了弹层之上

**Comment by dpp050700** [comment]
您好，我们调试并没有问题 麻烦提供一下具体的版本号和代码示例 
![image](https://user-images.githubusercontent.com/24217083/78676134-9f7a7480-7918-11ea-9942-163f714f4cea.png)
@ChasonHong

**Comment by ChasonHong** [comment]
@dpp050700 
![151586314557_ pic](https://user-images.githubusercontent.com/11606876/78739759-8a88fa00-7987-11ea-8d07-51e73fbc6b94.jpg)

**Comment by MuRongXiaoDouBi** [comment]
@dpp050700 
![微信图片_20200408183622](https://user-images.githubusercontent.com/38655613/78775053-2f2b2c00-79c8-11ea-8115-5e6eead0f762.png)
测试和您的小程序版本与LinUI版本均一致，没有发现问题。
可否提供一下BUG代码供我们测试！
