### ISSUE TITLE
表单里面有l-input 输入字会超出屏幕?

### ISSUE THREAD

**Issue by shmilyQin** [TaleLin/lin-ui#744]
**LinUI版本（必填）：**
0.75
**设备（必填）：**
iphone6
**基础库版本（必填）：**
2.10.4
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/20322678/78755872-7a374600-79ac-11ea-8ce2-d6b21d17af5e.png)

**重现步骤，必要时请提供代码片段链接**
问题是官方的demo,请问怎么解决这种问题呢?只有手动计算宽度 吗?

**Comment by dpp050700** [comment]
已收到您的反馈，我们将尽快核实问题

**Comment by dpp050700** [comment]
您好，需要给 l-input 添加一个外部样式，改变它的默认宽度。
案例中的代码，我们在下个版本将会修复

**Comment by shmilyQin** [comment]
好的谢谢.
