### ISSUE TITLE
tabs 组件使用 hidden 展示时 出现 二级标题不展示(if:wx没有问题)

### ISSUE THREAD

**Issue by pink0101** [TaleLin/lin-ui#746]
**LinUI版本（必填）：**最新

**设备（必填）：**iphone 6/7/8

**基础库版本（必填）：**2.10.4

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by pink0101** [comment]
一个页面写了多个tabs组件  使用hidden控制隐藏和显示，iPhone 出现二级分类不显示

**Comment by uniquenaer** [comment]
收到反馈，问题原因不明，需要研究一下~

**Comment by juzi214032** [comment]
请问问题还存在吗，能否提供一下截图

**Comment by juzi214032** [comment]
自定义组件的显示隐藏不可使用hidden控制，这个问题官方文档没指明，但是是个事实上的bug。
所以建议使用`wx:if`或者`display:none`控制，如果实在要用`hidden`，可以尝试在自定义组件外部包一个`view`，在`view`上使用`hidden`

[参考链接](https://developers.weixin.qq.com/community/develop/doc/000cc269e28640f89b48508c05b800?highLine=%25E8%2587%25AA%25E5%25AE%259A%25E4%25B9%2589%25E7%25BB%2584%25E4%25BB%25B6%2520hidden)

**Comment by pink0101** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"桔子"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:56
收件人:&nbsp;"TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;;
抄送:&nbsp;"一心向许"<1259493451@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TaleLin/lin-ui] tabs 组件使用 hidden 展示时 出现 二级标题不展示(if:wx没有问题) (#746)





 
自定义组件的显示隐藏不可使用hidden控制，这个问题官方文档没指明，但是是个事实上的bug。
 所以建议使用wx:if或者display:none控制，如果实在要用hidden，可以尝试在自定义组件外部包一个view，在view上使用hidden
 
参考链接
