### ISSUE TITLE
album组件图片有可能会显示不出来width: 0rpx情况

### ISSUE THREAD

**Issue by junxian123** [TaleLin/lin-ui#747]
**LinUI版本（必填）：0.7.5

**设备（必填）：模拟器iPhone6

**基础库版本（必填）：2.10.3

**UI问题，请附上截图**

![1111](https://user-images.githubusercontent.com/38606245/79128971-f54a9300-7dd6-11ea-829d-96834d6ea5c1.PNG)

**重现步骤，必要时请提供代码片段链接**
`observers:{
		urls:function(urls) {
			if (this.data.urls.length > 9) {
				const e = urls.slice(0, 9);
				this.setData({
					urls: e
				}), console.warn("超过9张图片！")
			}
			this.preview()
		}
	},`

建议将attached里的代码改用监听属性方式，用attached有时可能会获取urls为空的情况

**Comment by zhc525349965** [comment]
麻烦提供下wxml调用代码。

**Comment by junxian123** [comment]
![1111](https://user-images.githubusercontent.com/38606245/79456655-772dfc80-8021-11ea-830a-873540865bb8.PNG)

**Comment by zhc525349965** [comment]
根据提供的内容，没有复现此问题。暂时关闭此issue，后续会持续关注。
