### ISSUE TITLE
form表单组件横向溢出,底部出现滚动条

### ISSUE THREAD

**Issue by liuhao645** [TaleLin/lin-ui#748]
**LinUI版本（必填）：**
0.7.5
**设备（必填）：**
iphone7
**基础库版本（必填）：**
2.10.4
**UI问题，请附上截图**
![@ASM)G0INR_{ N2U KVR}P6](https://user-images.githubusercontent.com/51433906/79288238-c6c4d900-7ef8-11ea-84b0-784f8403f308.jpg)

**重现步骤，必要时请提供代码片段链接**
使用form表单组件底部出现横向滚动条  必须在form表单外层包层view用overflow-x:  hidden;才能解决
![9L9THOQ%YS~(N8V7`K_YP%O](https://user-images.githubusercontent.com/51433906/79288345-0a1f4780-7ef9-11ea-95d3-89452c831cbb.png)

**Comment by dpp050700** [comment]
您好 通过外部样式手动改一下 l-input 组件的宽度。
