### ISSUE TITLE
npm install错误

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#753]
> gifsicle@5.0.0 postinstall D:\temp\lin-ui\node_modules\gifsicle
> node lib/install.js

  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at D:\temp\lin-ui\node_modules\bin-build\node_modules\execa\index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)

> mozjpeg@6.0.1 postinstall D:\temp\lin-ui\node_modules\mozjpeg
> node lib/install.js

  ‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ mozjpeg pre-build test failed
  i compiling from source

**Comment by juzi214032** [comment]
你的node版本是多少

**Comment by workingCar** [comment]
12.16.2

**Comment by juzi214032** [comment]
你是在cmd中执行的npm install吗？你在gitbash中执行一下npm install试试 然后截图我看看那个乱码的报错信息是什么

**Comment by workingCar** [comment]
![error](https://user-images.githubusercontent.com/35887550/79628131-ecf4ae00-8170-11ea-98b2-e365aa1e4239.png)

**Comment by juzi214032** [comment]
先临时把node切换到10.15.3可以正常install 我们这边排查一下是什么问题

**Comment by juzi214032** [comment]
我这边测试了多次只出现一次你说的问题，估计应该是网络问题，建议挂上梯子或切换网络环境多试几次。
测试node版本：10.15.3、10.20.0、12.16.2
测试结果：均可以正常install
