### ISSUE TITLE
组件中引入图标乱码，但是页面正常

### ISSUE THREAD

**Issue by 251205668** [TaleLin/lin-ui#755]
**LinUI版本（必填）：0.7.5**

**设备（必填）：开发者工具**

**基础库版本（必填）：2.10.4**

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/46418596/79633168-681c8b00-8196-11ea-8cfb-de817f645fae.png)
![image](https://user-images.githubusercontent.com/46418596/79633173-723e8980-8196-11ea-8c87-8e4536d4b780.png)

组件中

![image](https://user-images.githubusercontent.com/46418596/79633186-85515980-8196-11ea-85d4-0c50b5335920.png)
![](https://image.yangxiansheng.top/img/20200418170442.png?imagelist)

**重现步骤，必要时请提供代码片段链接**
app.wxss代码
![](https://image.yangxiansheng.top/img/20200418170612.png?imagelist)

**Comment by juzi214032** [comment]
有新建一个空项目测试一下吗，排除一下是不是你的项目引起的冲突

**Comment by 251205668** [comment]
@juzi214032 解决了 ，在自定义组件中引入了全局样式，没生效。给忘了不能直接用，可以关闭这个issues
