### ISSUE TITLE
from表单如何在底部有两个按钮都可以提交

### ISSUE THREAD

**Issue by sanjin2** [TaleLin/lin-ui#756]
![image](https://user-images.githubusercontent.com/24599702/79637367-aa06fa80-81b1-11ea-9bfa-1375f27ef4d7.png)

**Comment by juzi214032** [comment]
两种方法
1. 把两个按钮都通过submit这个slot传到组件内部
2. 给两个按钮都绑定一个点击事件，在事件函数内用`wx.lin.submitForm`手动提交
