### ISSUE TITLE
slide-view组件内缺少wxss

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#760]
**LinUI版本（必填）：*0.75*

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
slide-view组件直接引用会显示不正常，组件内缺少一些wxss，不知道 是不是就是这样设计 的。

**Comment by workingCar** [comment]
![猎豹截图20200421114028](https://user-images.githubusercontent.com/35887550/79822977-11e15f00-83c5-11ea-86cd-c662f09fec18.png)

**Comment by juzi214032** [comment]
是的，设计如此
slide-view仅提供容器功能，其样式由调用方自行传入
