### ISSUE TITLE
tabBar不显示图标

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#761]
**LinUI版本（必填）：*0.75*

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

似乎是组件js内有一些代码需要删除，点击后也不跳转tab页。

**Comment by juzi214032** [comment]
tab-bar组件之前因为小程序官方导致的问题暂时停止了维护，我们近期会再次评估下这个组件，如果问题已经修复，会对该bug进行修复，修复完成后会通知您

**Comment by juzi214032** [comment]
你好，这个问题我这边没有复现，能否提供一下你的`wxml`和`js`
![image](https://user-images.githubusercontent.com/38206169/80305639-80248800-87f0-11ea-81f2-97a8fa6bbd28.png)
