### ISSUE TITLE
segment 自定义选项卡 切换选项卡时下面还有内容部分，怎么将内容部分加进去？

### ISSUE THREAD

**Issue by Damonlanyang** [TaleLin/lin-ui#763]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**
segment 自定义选项卡 切换选项卡时下面还有内容部分，怎么将内容部分加进去？
![image](https://user-images.githubusercontent.com/23103070/79841182-a1990480-83e9-11ea-84e8-b4031b8111cb.png)

**Comment by Damonlanyang** [comment]
有点类似这个，右边的内容怎么关联到选项卡？
![image](https://user-images.githubusercontent.com/23103070/79841275-c42b1d80-83e9-11ea-9965-d035a8d1d691.png)

**Comment by juzi214032** [comment]
`segment`组件本质上是不包含内容区域的，仅仅只是一个标签。
如果你需要标签与内容联动，建议使用`tabs`组件。
如果一定要使用`segment`组件，则需要监听`linchange`事件，自行编写内容切换的逻辑，

**Comment by Damonlanyang** [comment]
> `segment`组件本质上是不包含内容区域的，仅仅只是一个标签。
> 如果你需要标签与内容联动，建议使用`tabs`组件。
> 如果一定要使用`segment`组件，则需要监听`linchange`事件，自行编写内容切换的逻辑，

我知道。但是tabs组件无法满足我自定义选项卡头的需求。
![image](https://user-images.githubusercontent.com/23103070/79842084-f5f0b400-83ea-11ea-921e-406e2d5b33ba.png)

**Comment by juzi214032** [comment]
ok，了解了。
如果给tabs提供一个标签的slot就可以满足你的需求 对吧

**Comment by Damonlanyang** [comment]
> ok，了解了。
> 如果给tabs提供一个标签的slot就可以满足你的需求 对吧

对的。

**Comment by juzi214032** [comment]
好的，我们会评估下这个需求，不出意外下个版本更新

**Comment by juzi214032** [comment]
0.8.0 版本已添加slot
