### ISSUE TITLE
mpvue+LinUI，json文件已经引入按钮组件了，按钮组件在页面显示也正常但是事件绑不上去

### ISSUE THREAD

**Issue by Damonlanyang** [TaleLin/lin-ui#764]
**LinUI版本（必填）：0.7.5

**设备（必填）：*微信小程序*

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
![image](https://user-images.githubusercontent.com/23103070/79844707-998f9380-83ee-11ea-9459-e3fb4e82e3f0.png)

![image](https://user-images.githubusercontent.com/23103070/79844765-ae6c2700-83ee-11ea-90b4-e4dafa919bee.png)

**Comment by juzi214032** [comment]
可以提供一下你的js代码吗

**Comment by Damonlanyang** [comment]
> 可以提供一下你的js代码吗

![image](https://user-images.githubusercontent.com/23103070/79845486-b5e00000-83ef-11ea-9448-48dfd9046b14.png)

**Comment by Damonlanyang** [comment]
> > 可以提供一下你的js代码吗
> 
> ![image](https://user-images.githubusercontent.com/23103070/79845486-b5e00000-83ef-11ea-9448-48dfd9046b14.png)

![image](https://user-images.githubusercontent.com/23103070/79845584-dad47300-83ef-11ea-9e54-4727b9eddb14.png)

**Comment by juzi214032** [comment]
你这个事件不是有绑定上吗？
控制台打印出了type的数据的呀

**Comment by Damonlanyang** [comment]
> 你这个事件不是有绑定上吗？
> 控制台打印出了type的数据的呀

打印出来的  是我通过@click打印出来的。组件自带的绑定事件的方法是无法绑定上的。比如我把@click去掉，如下：
![image](https://user-images.githubusercontent.com/23103070/79846701-55ea5900-83f1-11ea-9bcb-e73a41dc2e9f.png)
![image](https://user-images.githubusercontent.com/23103070/79846721-5d116700-83f1-11ea-8d9e-c682d951df74.png)

**Comment by juzi214032** [comment]
把`bind:lintap`改为`@lintap`可以吗

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/79848857-3c96dc00-83f4-11ea-806c-dcd8ea62ca8a.png)

**Comment by Damonlanyang** [comment]
> 把`bind:lintap`改为`@lintap`可以吗

嗯嗯。试了，可以。多谢。
