### ISSUE TITLE
form 表单案例样式出错

### ISSUE THREAD

**Issue by helloxtf** [TaleLin/lin-ui#770]
**LinUI版本（必填）：*0.7.5*

**设备（必填）：*微信开发者工具*

**基础库版本（必填）：*2.8.3*

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/24709101/79945947-8984bc00-84a1-11ea-9ab8-203fb0c99126.png)

**重现步骤，必要时请提供代码片段链接**
下载案例 打开里面的form 表单案例也是报错

**Comment by juzi214032** [comment]
该问题已提交pr，将在下个版本修复
