### ISSUE TITLE
如何覆盖组件内原生的样式，不是l-class方式。

### ISSUE THREAD

**Issue by Damonlanyang** [TaleLin/lin-ui#771]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**
如组件tabs，我想在我自己的css文件通过重写l-tabs这个class的方式覆盖组件内的l-tabs，怎么实现

![image](https://user-images.githubusercontent.com/23103070/80060258-b0ee8e00-8560-11ea-878e-58565be4c4f2.png)

**Comment by aQingYun** [comment]
小程序的组件是通过shadowDom实现的 可以百度一下 里面有覆盖样式的方法


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by juzi214032** [comment]
你是想问除了外部样式类还有其他什么方式修改组件默认样式吗？
如果是使用外部样式类，用`l-tabs-class`即可
