### ISSUE TITLE
表单报错

### ISSUE THREAD

**Issue by vajer** [TaleLin/lin-ui#775]
**LinUI版本（必填）：*0.7.6*

**设备（必填）：*小程序开发工具*

**基础库版本（必填）：*2.10.4*

**UI问题，请附上截图**

![image](https://user-images.githubusercontent.com/28479508/80178459-d8149080-8630-11ea-96cf-c56816498b64.png)

**重现步骤，必要时请提供代码片段链接**

官方的表单会报错

**Comment by dpp050700** [comment]
您好 我们这边测试 官方 Deom 并没有错误。麻烦检查一下是否是最新代码
