### ISSUE TITLE
组件如何添加点击效果

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#777]
**描述你希望的支持的新功能？**
正在使用linui,请问能否为组件添加点击效果，如card组件点击时，显示动效。
**你期望的 API 是怎样的？**
希望可以添加 一个外部hover-class.

**Comment by workingCar** [comment]
希望可以添加 一个外部样式hover-class

**Comment by juzi214032** [comment]
移动端一般很少使用点击态，为了保证组件的易用性，我们不提供这个接口
如果你一定要实现点击态，可以通过 js 监听事件，动态修改外部样式类实现
