### ISSUE TITLE
searchBar添加地址点击事件

### ISSUE THREAD

**Issue by whu-lisan** [TaleLin/lin-ui#778]
**描述你希望的支持的新功能？**
希望searchBar搜索栏能够添加一个地址选择事件，当点击address部分后，可以弹出一个下拉列表供用户选择不同的地址
**你期望的 API 是怎样的？**

**Comment by juzi214032** [comment]
近期会上线`IndexBar`索引组件，到时候可以结合`SearchBar`组件实现你的需求

**Comment by whu-lisan** [comment]
感谢感谢

**Comment by juzi214032** [comment]
- [x] `SearchBar`添加`lintap`事件，[Pull Request](https://github.com/TaleLin/lin-ui/pull/781)
- [ ] `IndexList`索引列表组件，[文档地址](http://doc.mini.7yue.pro/component/layout/index-list.html)

**Comment by whu-lisan** [comment]
好的，非常感谢

**Comment by juzi214032** [comment]
0.8.0 版本已添加相应事件和 IndexList 组件
