### ISSUE TITLE
【linUI】，在出一版【uniapp】的吧，用户量会大增，好多unaipp开发者的也找不到

### ISSUE THREAD

**Issue by qq1415551519** [TaleLin/lin-ui#782]
【linUI】，在出一版【uniapp】的吧，用户量会大增，好多unaipp开发者的也找不到linUI

**Comment by juzi214032** [comment]
您好，uni-app 因其特殊性质，我们短期内不会考虑。
后期我们会推出 vue 版本，欢迎持续关注。
