### ISSUE TITLE
最新0.7.6 sticky 组件 属性问题

### ISSUE THREAD

**Issue by alexosng** [TaleLin/lin-ui#783]
**LinUI版本（必填）：0.7.6**

**设备（必填）： x64 wechat devtool   **

**基础库版本（必填）：2.11.0**

重现步骤：
1.下载0.7.4源码，导入开发工具
2.打开sticky示例

期望的结果是：正常渲染 并显示

实际的结果是: 开发工具触发错误，自动断点，需要人工干预后显示

**Comment by juzi214032** [comment]
可以传一个截图看一下吗

**Comment by alexosng** [comment]
![361a45d1b140eb197592091529dcfc8](https://user-images.githubusercontent.com/2114088/80283373-97f50100-8749-11ea-8bce-19bcdd43492e.png)
![6cfeaf8f37275750616d9f27ff297f6](https://user-images.githubusercontent.com/2114088/80283374-988d9780-8749-11ea-895b-f072c51c4147.png)

**Comment by juzi214032** [comment]
断点是不会保存在源码中的，这应该是你误打了断点，你把断点取消即可
