### ISSUE TITLE
底部菜单栏,redDot和badge 样式偏离

### ISSUE THREAD

**Issue by iActing** [TaleLin/lin-ui#785]
**LinUI版本（必填）：0.76

**设备（必填）：iphone7plus

**基础库版本（必填）：**

**UI问题，请附上截图**
![3056c7b5b69a9ffee6d3c500df3f595](https://user-images.githubusercontent.com/42381722/80294946-c9e58200-87a0-11ea-8739-c5cea102aa19.jpg)

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
`CustomTabBar`组件之前由于微信方面的问题处于暂停维护状态，近期会再次评估下这个组件，确定上线会对该 Bug 进行修复，您可以贴一下相关`wxml`和`js`相关代码，方便我们后期定位问题

**Comment by juzi214032** [comment]
你好，我这边测试并没有问题，能否提供一下你的`wxml`和`js`代码

**Comment by iActing** [comment]
`<l-custom-tab-bar backgroundColor="{{backgroundColor}}" color="{{color}}" selectedColor="{{selectedColor}}"
                  fontSize="{{fontSize}}" list="{{list}}" bind:lintap="switchTab"
                  selected="{{selected}}"></l-custom-tab-bar>`

`Component({
    data: {
        selected: 0,
        backgroundColor: "#FFFFFF",
        color: "#7A7E83",
        selectedColor: "#DD5246",
        fontSize: "26",
        list: [{
            "pagePath": "/pages/home/index",
            "iconSize": "",
            "iconPath": "/uploads/20200424/043794c8ca4663bcdc17a3d47c280e41.png",
            "selectedIconPath": "/uploads/20200424/415d34cce62e80e3b95b82fb1d45ac77.png",
            "style": "",
            "redDot": "",
            "badge": "",
            "text": "首页"
        }, {
            "path": "/pages/chat/index",
            "iconSize": "",
            "iconPath": "/uploads/20200424/402dd5726975586ee38944d15056fb5b.png",
            "selectedIconPath": "/uploads/20200424/7185bb6ee418a69027fd71d441163bbd.png",
            "style": "",
            "redDot": true,
            "badge": "",
            "text": "信息"
        }, {
            "pagePath": "/pages/reserve/index",
            "iconSize": "",
            "iconPath": "/uploads/20200424/34da15fa4d1aaa031446b7a0353ac25a.png",
            "selectedIconPath": "/uploads/20200424/60fcdf53bed3920080abf2191a7b4cf0.png",
            "style": "",
            "redDot": "",
            "badge": "",
            "text": "我的"
        }]
    },
    attached() {
    },

    methods: {
        // 自定义菜单切换
        switchTab(e) {
            let url = "";
            switch (e.detail.idx) {
                case 0:
                    url = "/pages/home/index";
                    wx.switchTab({url})
                    this.setData({
                        selected: e.detail.idx
                    })
                    return;
                case 1:
                    url = "/pages/chat/index";
                    wx.switchTab({url})
                    this.setData({
                        selected: e.detail.idx
                    })
                    return;
                case 2:
                    url = "/pages/reserve/index";
                    wx.switchTab({url})
                    this.setData({
                        selected: e.detail.idx
                    })
                    return;
            }
        },
        onLoad: function (options) {
            wx.showTabBarRedDot({
                index: 2
            })


        },
    }
})`

**Comment by iActing** [comment]
wxss 

`.tab-bar {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: 48px;
    background: white;
    display: flex;
    padding-bottom: env(safe-area-inset-bottom);
}

.tab-bar-border {
    background-color: rgba(0, 0, 0, 0.33);
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 1px;
    transform: scaleY(0.5);
}

.tab-bar-item {
    flex: 1;
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}

.tab-bar-item cover-image {
    width: 27px;
    height: 27px;
}

.tab-bar-item cover-view {
    font-size: 10px;
}

`

**Comment by juzi214032** [comment]
请问您这些样式类是怎么绑定上去的，我看到您的`l-custom-tab-bar`这个节点并没有写class属性

**Comment by juzi214032** [comment]
我这边还是无法复现你这个问题，如果方便的话，你可以写个包含这个问题的demo，然后再发给我看一下

**Comment by iActing** [comment]
css 样式多余的 ,就是直接用的官方的组件, 在开发者工具中是正常显示的,但我用手机预览就变成上面截图所示那样

**Comment by juzi214032** [comment]
那您的手机看示例小程序上的正常吗

**Comment by iActing** [comment]
一样的 不正常
![Uploading B9F99FD345A4D6BB75480FC242E2CDDE.png…]()

**Comment by iActing** [comment]
![B9F99FD345A4D6BB75480FC242E2CDDE](https://user-images.githubusercontent.com/42381722/80478863-be50b180-8980-11ea-871d-29de7db8dada.png)

**Comment by juzi214032** [comment]
您的微信版本是多少呢

**Comment by iActing** [comment]
7.0.12

**Comment by juzi214032** [comment]
好的 这个问题我们需要排查一下

**Comment by juzi214032** [comment]
我们用 iphone xr 试了一下，没有复现bug，我们这边也没有iphone7plus，所以暂时无法修复这个bug。您可以尝试定位一下问题，修复后可以给我们提交pr。非常抱歉
