### ISSUE TITLE
关于l-tag  disable为true依然被选中的问题

### ISSUE THREAD

**Issue by WenLo** [TaleLin/lin-ui#793]

**Comment by juzi214032** [comment]
您好，我这边没有复现您说的这个问题，您可以看看我们的示例小程序是怎么写的，用法是否与其一致

**Comment by WenLo** [comment]
disable效果呈现了灰色，但是依然可以选中，并触发了点击事件，没有发挥disabled的作用
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"桔子"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 晚上6:36
收件人:&nbsp;"TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;;
抄送:&nbsp;"散了。"<863377861@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TaleLin/lin-ui] 关于l-tag  disable为true依然被选中的问题 (#793)





 
您好，我这边没有复现您说的这个问题，您可以看看我们的示例小程序是怎么写的，用法是否与其一致

**Comment by juzi214032** [comment]
可以提供一下您的wxml和js代码吗

**Comment by juzi214032** [comment]
还有您是在真机还是模拟器上测试的 两者效果一致吗

**Comment by juzi214032** [comment]
问题定位了，不用提供代码了，将在下个版本修复

**Comment by juzi214032** [comment]
bug 已修复，将在下个版本更新

**Comment by juzi214032** [comment]
0.8.0 版本已修复
