### ISSUE TITLE
这个组件在展开状态下，小程序js中数据绑定更新后要折叠一次，再展开，数据才能显示

### ISSUE THREAD

**Issue by tandage** [TaleLin/lin-ui#794]
**LinUI版本（必填）：**
0.7.6
**设备（必填）：**
 微信小程序开发者工具调试中
**基础库版本（必填）：**
2.11.0
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/64976499/81318266-8d7b2580-90c0-11ea-888a-995b54cac679.png)
![image](https://user-images.githubusercontent.com/64976499/81319009-a3d5b100-90c1-11ea-9b7f-74409e4b6bc6.png)
![image](https://user-images.githubusercontent.com/64976499/81319174-e13a3e80-90c1-11ea-9d6a-32a958a0c49d.png)
![Uploading image.png…]()

**重现步骤，必要时请提供代码片段链接**
这是
录的一个视频：https://share.weiyun.com/5bm1wQB

**Comment by juzi214032** [comment]
bug已解决，将在下个版本修复

**Comment by juzi214032** [comment]
0.8.0 版本已修复
