### ISSUE TITLE
状态页和搜索栏放在一起时，显示不太正常

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#796]
**LinUI版本（必填）：*0.76*

**设备（必填）：*官方ide*

**基础库版本（必填）：*2.81*
状态页组件和搜索栏组件放一起时，状态页组件全屏显示时，搜索栏内文字错误的显示出来 。
![error](https://user-images.githubusercontent.com/35887550/81378495-f9e63b00-9139-11ea-861f-4b29ae26b930.jpg)

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
			<scroll-view id="haoke" style="height:{{windowHeight-mainScrollTop}}px;" class="flex justify-center padding-top" scroll-y="{{true}}">
				<l-status-show full-screen show="{{true}}" type="network"></l-status-show>
				<view style="height:100%;width:100%;" class="padding-xs ">
					<l-search-bar shape="circle" placeholder="搜索关键字" clear="{{true}}" show-cancel="{{false}}">
						<view name="after" />
					</l-search-bar>
				</view>
			</scroll-view>

**Comment by workingCar** [comment]
代码如下：
			<scroll-view id="haoke" style="height:{{windowHeight-mainScrollTop}}px;" class="flex justify-center padding-top" scroll-y="{{true}}">
				<l-status-show full-screen show="{{true}}" type="network"></l-status-show>
				<view style="height:100%;width:100%;" class="padding-xs ">
					<l-search-bar shape="circle" placeholder="搜索关键字" clear="{{true}}" show-cancel="{{false}}">
						<view name="after" />
					</l-search-bar>
				</view>
			</scroll-view>

**Comment by workingCar** [comment]
> 			<scroll-view id="haoke" style="height:{{windowHeight-mainScrollTop}}px;" class="flex justify-center padding-top" scroll-y="{{true}}">
				<l-status-show full-screen show="{{true}}" type="network"></l-status-show>
				<view style="height:100%;width:100%;" class="padding-xs ">
					<l-search-bar shape="circle" placeholder="搜索关键字" clear="{{true}}" show-cancel="{{false}}">
						<view name="after" />
					</l-search-bar>
				</view>
			</scroll-view>

**Comment by workingCar** [comment]
`			<scroll-view id="haoke" style="height:{{windowHeight-mainScrollTop}}px;" class="flex justify-center padding-top" scroll-y="{{true}}">
				<l-status-show full-screen show="{{true}}" type="network"></l-status-show>
				<view style="height:100%;width:100%;" class="padding-xs ">
					<l-search-bar shape="circle" placeholder="搜索关键字" clear="{{true}}" show-cancel="{{false}}">
						<view name="after" />
					</l-search-bar>
				</view>
			</scroll-view>`

**Comment by juzi214032** [comment]
您的意思是搜索栏是不应该显示出来的 对吧

**Comment by workingCar** [comment]
是的，要么搜索栏完整显示，要么完全隐藏。目前的结果是，如果状态组件显示，搜索栏隐藏，但是placeholder="搜索" 属性显示。如果状态组件不显示时，搜索栏显示 是正常的。

**Comment by juzi214032** [comment]
好的 会尽快定位一下问题

**Comment by juzi214032** [comment]
建议使用 wx:if 动态控制 search-bar 的显示隐藏
因为 search-bar 内部的 input 组件是原生组件，层级高于 status-show ，所以从自定义组件的角度是无法解决的。
参考链接：[小程序原生组件](https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html)
