### ISSUE TITLE
<l-notice-bar> 问题 ，会不会引发cpu 飙升？

### ISSUE THREAD

**Issue by sunchangpu** [TaleLin/lin-ui#798]
小白一个，一脸懵逼。
两张图，一张使用了<l-notice-bar> ，一张没使用。两者都是在重新编译，稳定后截图的，cpu相差好大，是微信官方问题，还是 l-notice-bar  组件循环造成的问题？
<img width="1194" alt="1" src="https://user-images.githubusercontent.com/25578290/81490778-d39ad980-92b8-11ea-838d-72c0e95b411d.png">
<img width="1236" alt="2" src="https://user-images.githubusercontent.com/25578290/81490779-d5fd3380-92b8-11ea-8a13-f3dc495ac1d7.png">

**Comment by sunchangpu** [comment]
l-notice-bar 引用到项目里后，基本cpu跑到70%
<img width="1180" alt="WechatIMG6" src="https://user-images.githubusercontent.com/25578290/81490903-0beee780-92ba-11ea-8fb9-dad1534fc11b.png">

**Comment by juzi214032** [comment]
你好，我这边用windows测试没有出现cpu占用异常的情况，建议你使用真机测试一下，看移动端cpu占用是否异常。如果移动端无异常，那么可能是您的开发环境问题或者是微信官方bug，这两个问题我们这边都无法进行修复
![image](https://user-images.githubusercontent.com/38206169/81495509-4325be80-92e3-11ea-9c59-02c029147da0.png)
![image](https://user-images.githubusercontent.com/38206169/81495511-46b94580-92e3-11ea-8408-a2623a282ae4.png)

**Comment by zhc525349965** [comment]
你好，我这边使用mac，未复现本问题。
