### ISSUE TITLE
在弹出层能点击到 上一层的 textarea文本域  pc正常 

### ISSUE THREAD

**Issue by Ma-Yun-Peng** [TaleLin/lin-ui#799]
**LinUI版本（必填）：0.7.6

**设备（必填）：一加七pro

**基础库版本（必填）：不知道

**UI问题，请附上截图**
![F16F855D9AAF663D0985F958745AF22F](https://user-images.githubusercontent.com/56998421/81495686-a2d09980-92e4-11ea-997f-415ee3b87d02.jpg)
**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
是 当弹出层弹出，背景变灰色的时候，仍然能点击到【物品信息】那一栏吗

**Comment by juzi214032** [comment]
麻烦提供一下相应的wxml和js代码

**Comment by Ma-Yun-Peng** [comment]
> 是当弹出图层弹出，背景变灰色的时候，仍然能点击到【物品信息】那一栏吗
 不是的  是告诉我们你的要求  这句话   这句话是在白色区域的下方

**Comment by juzi214032** [comment]
请问textarea是用的微信原生的textarea还是lin-ui的textarea

**Comment by Ma-Yun-Peng** [comment]
> 请问textarea是用的微信原生的textarea还是lin-ui的textarea

lin-ui的textarea

**Comment by juzi214032** [comment]
好的，你提供一下对应的wxml和js代码吧，我复现一下场景

**Comment by juzi214032** [comment]
请问这个是还没点击就会显示【告诉我们你的要求】，还是点击那个位置后才显示【告诉我们你的要求】

**Comment by Ma-Yun-Peng** [comment]
wxml
`<view class="container">
	<l-message />
	<l-notice-bar  front-icon-name="notification" type="roll" speed="4000" show="{{true}}">请不要发布违法乱纪的信息，一经发现将进行封号处理</l-notice-bar>
	
	<view class="address-container">
		
		<view class="address-container-one">
			<image src="/image/orders/addorder_send_round_icon.png" />
			<view class="address-text-container">
				<text class="send">从哪里发货?</text>
				<text class="receive">137777777</text>
			</view>
			
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
		<view class='line'></view>
		
		<view class="address-container-two">
			<image src="/image/orders/addorder_receive_round_icon.png" />
			<view class="address-text-container">
				<text class="send">要送到哪里?</text>
				<text class="receive">137777777</text>
			</view>
			
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
	</view>
	
	<view class="goods-container">
		
		<view bindtap="showItemSelect" class="message-container">
			<image src="/image/orders/goods.png" />
			<view class="goods-text-container">
				<text class="goods-text">物品信息</text>
				<text class="goods-text-2">{{itemType}}</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		
		<view class="time-container">
			<image src="/image/orders/time.png" />
			<view class="goods-text-container">
				<text class="goods-text">取货时间</text>
				<text class="time-text-2">立即送货</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		
		<view class="price-container">
			<image src="/image/orders/price.png" />
			<view class="goods-text-container">
				<text class="goods-text">报酬金额</text>
				<text class="price-text-2">请选择</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
	</view>
	
	<view class="form-container">
		<form bindsubmit="submitOrder">
			
			<view class="remarks-container">
				<view class="msg-remarks-container">
					<image src="/image/orders/beizhu.png" />
					<text class="remarks-text">订单备注</text>
				</view>
				<view class="text-area">
					<l-textarea name="remarks" auto-height="true" border="{{false}}" maxlength="80" placeholder="告诉我们你的要求..." />
				</view>
			</view>
			
			<view class="gender-container">
				<image src="/image/orders/gender.png" />
				<view class="gender-text-container">
					<text class="gender-text">请选择跑腿者的性别</text>
					<text class="gender-text-2">{{gender}}</text>
				</view>
				<switch name="claim" bindchange="changeGender" color="#FF9038" checked="{{true}}"></switch>
			</view>
			
			<view class="button-container">

				<button style="width:700rpx" class="button" hover-class="button-hover" form-type="submit">去下单</button>

			</view>
		</form>
		
	</view>
	
	<l-popup  locked="{{true}}" show="{{itemTypeFlag}}" content-align="bottom">
		<view class="select-item-container">
			
			<view class="item-top-container">
				<view catchtap="closeItemSelect" class="item-close">取消</view>
				<view class="item-biaoti">物品类型</view>
				<view catchtap="itemConfirm" class="item-confirm">确定</view>
			</view>
			<view class="line-item"></view>
			
			<view class="select-container">
				<view class="select-block-container">
					<l-tag id="0" name="其他" plain="{{true}}" select="{{items[0]}}" bind:lintap="onSelect">其他</l-tag>
					<l-tag id="1" name="文件" plain="{{true}}" select="{{items[1]}}" bind:lintap="onSelect">文件</l-tag>
					<l-tag id="2" name="美食" plain="{{true}}" select="{{items[2]}}" bind:lintap="onSelect">美食</l-tag>
				</view>
				<view class="select-block-container">
					<l-tag id="3" name="手机" plain="{{true}}" select="{{items[3]}}" bind:lintap="onSelect">手机</l-tag>
					<l-tag id="4" name="鲜花" plain="{{true}}" select="{{items[4]}}" bind:lintap="onSelect">鲜花</l-tag>
					<l-tag id="5" name="钥匙" plain="{{true}}" select="{{items[5]}}" bind:lintap="onSelect">钥匙</l-tag>
				</view>
			</view>
		</view>
	</l-popup>
</view>`

js
`// pages/index/orders/sendOrders/sendOrders.js
Page({

    /**
     * 页面的初始数据
     */
    data: {
        gender: "男",
        itemTypeFlag: false,
        items: [true, false, false, false, false, false],
        select: "其他",//临时物品类型选项存储
        itemType: "请选择物品种类",//最终物品类型选项结果
    },

    submitOrder: function (e) {
        console.log(e.detail.value);
    },
    /**
     * 用户点击右上角分享
     */
    onShareAppMessage: function () {

    },
    /**
     * 修改跑腿者的性别
     */
    changeGender: function (e) {
        console.log(e.detail);
        if (e.detail.value) {
            this.setData({
                gender: "男"
            })
        } else {
            this.setData({
                gender: "女"
            })
        }
    },

    /**
     * 进入物品类型选项卡
     */
    showItemSelect: function () {
        this.setData({
            itemTypeFlag: true
        })
    },
    /**
     * 取消物品类型选项卡
     */
    closeItemSelect: function () {
        this.setData({
            itemTypeFlag: false,
        })
    },
    /**
     * 切换选项卡
     */
    onSelect: function (e) {
        let that = this;
        let arrays = that.data.items;
        if (e.detail.select == true) {
            that.setData({
                select: e.detail.name
            })

        } else {
            for (let i = 0; i < arrays.length; i++) {
                if (arrays[i] == true) {
                    arrays[i] = false
                } else if (e.currentTarget.id == i) {
                    arrays[i] = true
                }
            }
            that.setData({
                items: arrays,
                select: e.detail.name
            })
        }
    },
    /**
     * 物品选项卡点击确认
     */
    itemConfirm: function (e) {
        let select = this.data.select
        this.setData({
            itemType: select,
            itemTypeFlag: false
        })
    }

})`

**Comment by Ma-Yun-Peng** [comment]
> 请问这个是还没点击就会显示【告诉我们你的要求】，还是点击那个位置后才显示【告诉我们你的要求】

还没点击就有

**Comment by Ma-Yun-Peng** [comment]
wxml 代码
`<view class="container">
	<l-message />
	<l-notice-bar  front-icon-name="notification" type="roll" speed="4000" show="{{true}}">请不要发布违法乱纪的信息，一经发现将进行封号处理</l-notice-bar>
	
	<view class="address-container">
		
		<view class="address-container-one">
			<image src="/image/orders/addorder_send_round_icon.png" />
			<view class="address-text-container">
				<text class="send">从哪里发货?</text>
				<text class="receive">137777777</text>
			</view>
			
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
		<view class='line'></view>
		
		<view class="address-container-two">
			<image src="/image/orders/addorder_receive_round_icon.png" />
			<view class="address-text-container">
				<text class="send">要送到哪里?</text>
				<text class="receive">137777777</text>
			</view>
			
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
	</view>
	
	<view class="goods-container">
		
		<view bindtap="showItemSelect" class="message-container">
			<image src="/image/orders/goods.png" />
			<view class="goods-text-container">
				<text class="goods-text">物品信息</text>
				<text class="goods-text-2">{{itemType}}</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		
		<view class="time-container">
			<image src="/image/orders/time.png" />
			<view class="goods-text-container">
				<text class="goods-text">取货时间</text>
				<text class="time-text-2">立即送货</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		
		<view class="price-container">
			<image src="/image/orders/price.png" />
			<view class="goods-text-container">
				<text class="goods-text">报酬金额</text>
				<text class="price-text-2">请选择</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
	</view>
	
	<view class="form-container">
		<form bindsubmit="submitOrder">
			
			<view class="remarks-container">
				<view class="msg-remarks-container">
					<image src="/image/orders/beizhu.png" />
					<text class="remarks-text">订单备注</text>
				</view>
				<view class="text-area">
					<l-textarea name="remarks" auto-height="true" border="{{false}}" maxlength="80" placeholder="告诉我们你的要求..." />
				</view>
			</view>
			
			<view class="gender-container">
				<image src="/image/orders/gender.png" />
				<view class="gender-text-container">
					<text class="gender-text">请选择跑腿者的性别</text>
					<text class="gender-text-2">{{gender}}</text>
				</view>
				<switch name="claim" bindchange="changeGender" color="#FF9038" checked="{{true}}"></switch>
			</view>
			
			<view class="button-container">

				<button style="width:700rpx" class="button" hover-class="button-hover" form-type="submit">去下单</button>

			</view>
		</form>
		
	</view>
	
	<l-popup  locked="{{true}}" show="{{itemTypeFlag}}" content-align="bottom">
		<view class="select-item-container">
			
			<view class="item-top-container">
				<view catchtap="closeItemSelect" class="item-close">取消</view>
				<view class="item-biaoti">物品类型</view>
				<view catchtap="itemConfirm" class="item-confirm">确定</view>
			</view>
			<view class="line-item"></view>
			
			<view class="select-container">
				<view class="select-block-container">
					<l-tag id="0" name="其他" plain="{{true}}" select="{{items[0]}}" bind:lintap="onSelect">其他</l-tag>
					<l-tag id="1" name="文件" plain="{{true}}" select="{{items[1]}}" bind:lintap="onSelect">文件</l-tag>
					<l-tag id="2" name="美食" plain="{{true}}" select="{{items[2]}}" bind:lintap="onSelect">美食</l-tag>
				</view>
				<view class="select-block-container">
					<l-tag id="3" name="手机" plain="{{true}}" select="{{items[3]}}" bind:lintap="onSelect">手机</l-tag>
					<l-tag id="4" name="鲜花" plain="{{true}}" select="{{items[4]}}" bind:lintap="onSelect">鲜花</l-tag>
					<l-tag id="5" name="钥匙" plain="{{true}}" select="{{items[5]}}" bind:lintap="onSelect">钥匙</l-tag>
				</view>
			</view>
		</view>
	</l-popup>
</view>`

js代码
`// pages/index/orders/sendOrders/sendOrders.js
Page({

    /**
     * 页面的初始数据
     */
    data: {
        gender: "男",
        itemTypeFlag: false,
        items: [true, false, false, false, false, false],
        select: "其他",//临时物品类型选项存储
        itemType: "请选择物品种类",//最终物品类型选项结果
    },

    submitOrder: function (e) {
        console.log(e.detail.value);
    },
    /**
     * 用户点击右上角分享
     */
    onShareAppMessage: function () {

    },
    /**
     * 修改跑腿者的性别
     */
    changeGender: function (e) {
        console.log(e.detail);
        if (e.detail.value) {
            this.setData({
                gender: "男"
            })
        } else {
            this.setData({
                gender: "女"
            })
        }
    },

    /**
     * 进入物品类型选项卡
     */
    showItemSelect: function () {
        this.setData({
            itemTypeFlag: true
        })
    },
    /**
     * 取消物品类型选项卡
     */
    closeItemSelect: function () {
        this.setData({
            itemTypeFlag: false,
        })
    },
    /**
     * 切换选项卡
     */
    onSelect: function (e) {
        let that = this;
        let arrays = that.data.items;
        if (e.detail.select == true) {
            that.setData({
                select: e.detail.name
            })

        } else {
            for (let i = 0; i < arrays.length; i++) {
                if (arrays[i] == true) {
                    arrays[i] = false
                } else if (e.currentTarget.id == i) {
                    arrays[i] = true
                }
            }
            that.setData({
                items: arrays,
                select: e.detail.name
            })
        }
    },
    /**
     * 物品选项卡点击确认
     */
    itemConfirm: function (e) {
        let select = this.data.select
        this.setData({
            itemType: select,
            itemTypeFlag: false
        })
    }

})`

**Comment by Ma-Yun-Peng** [comment]
> 好的，你提供一下对应的wxml和js代码吧，我复现一下场景

这wxml代码贴出去 被网页解析了。。怎么办

**Comment by Ma-Yun-Peng** [comment]
```
<view class="container">
	<l-message />
	<l-notice-bar  front-icon-name="notification" type="roll" speed="4000" show="{{true}}">请不要发布违法乱纪的信息，一经发现将进行封号处理</l-notice-bar>
	<!-- 地址栏 -->
	<view class="address-container">
		<!-- 地址栏1 -->
		<view class="address-container-one">
			<image src="/image/orders/addorder_send_round_icon.png" />
			<view class="address-text-container">
				<text class="send">从哪里发货?</text>
				<text class="receive">137777777</text>
			</view>
			<!-- 标签 -->
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
		<view class='line'></view>
		<!-- 地址栏2 -->
		<view class="address-container-two">
			<image src="/image/orders/addorder_receive_round_icon.png" />
			<view class="address-text-container">
				<text class="send">要送到哪里?</text>
				<text class="receive">137777777</text>
			</view>
			<!-- 标签 -->
			<view class="label-container">
				<l-tag shape="circle" bg-color="black" type="reading">常用</l-tag>
			</view>
		</view>
	</view>
	<!-- 物品信息栏 -->
	<view class="goods-container">
		<!-- 物品种类 -->
		<view bindtap="showItemSelect" class="message-container">
			<image src="/image/orders/goods.png" />
			<view class="goods-text-container">
				<text class="goods-text">物品信息</text>
				<text class="goods-text-2">{{itemType}}</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		<!-- 时间信息 -->
		<view class="time-container">
			<image src="/image/orders/time.png" />
			<view class="goods-text-container">
				<text class="goods-text">取货时间</text>
				<text class="time-text-2">立即送货</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
		<view class="line"></view>
		<!-- 价格信息 -->
		<view class="price-container">
			<image src="/image/orders/price.png" />
			<view class="goods-text-container">
				<text class="goods-text">报酬金额</text>
				<text class="price-text-2">请选择</text>
			</view>
			<image style="margin-right:20rpx;" src="/image/orders/icon_arrow.png" />
		</view>
	</view>
	<!-- form表单 -->
	<view class="form-container">
		<form bindsubmit="submitOrder">
			<!-- 订单备注栏 -->
			<view class="remarks-container">
				<view class="msg-remarks-container">
					<image src="/image/orders/beizhu.png" />
					<text class="remarks-text">订单备注</text>
				</view>
				<view class="text-area">
					<l-textarea name="remarks" auto-height="true" border="{{false}}" maxlength="80" placeholder="告诉我们你的要求..." />
				</view>
			</view>
			<!-- 性别选择 -->
			<view class="gender-container">
				<image src="/image/orders/gender.png" />
				<view class="gender-text-container">
					<text class="gender-text">请选择跑腿者的性别</text>
					<text class="gender-text-2">{{gender}}</text>
				</view>
				<switch name="claim" bindchange="changeGender" color="#FF9038" checked="{{true}}"></switch>
			</view>
			<!-- 提交按钮 -->
			<view class="button-container">

				<button style="width:700rpx" class="button" hover-class="button-hover" form-type="submit">去下单</button>

			</view>
		</form>
		<!-- /form表单 -->
	</view>
	<!-- 物品信息选择器 -->
	<l-popup  locked="{{true}}" show="{{itemTypeFlag}}" content-align="bottom">
		<view class="select-item-container">
			<!-- 顶部操作栏 -->
			<view class="item-top-container">
				<view catchtap="closeItemSelect" class="item-close">取消</view>
				<view class="item-biaoti">物品类型</view>
				<view catchtap="itemConfirm" class="item-confirm">确定</view>
			</view>
			<view class="line-item"></view>
			<!-- 物品信息选择标签栏 -->
			<view class="select-container">
				<view class="select-block-container">
					<l-tag id="0" name="其他" plain="{{true}}" select="{{items[0]}}" bind:lintap="onSelect">其他</l-tag>
					<l-tag id="1" name="文件" plain="{{true}}" select="{{items[1]}}" bind:lintap="onSelect">文件</l-tag>
					<l-tag id="2" name="美食" plain="{{true}}" select="{{items[2]}}" bind:lintap="onSelect">美食</l-tag>
				</view>
				<view class="select-block-container">
					<l-tag id="3" name="手机" plain="{{true}}" select="{{items[3]}}" bind:lintap="onSelect">手机</l-tag>
					<l-tag id="4" name="鲜花" plain="{{true}}" select="{{items[4]}}" bind:lintap="onSelect">鲜花</l-tag>
					<l-tag id="5" name="钥匙" plain="{{true}}" select="{{items[5]}}" bind:lintap="onSelect">钥匙</l-tag>
				</view>
			</view>
		</view>
	</l-popup>
</view>
```


js
```
// pages/index/orders/sendOrders/sendOrders.js
Page({

    /**
     * 页面的初始数据
     */
    data: {
        gender: "男",
        itemTypeFlag: false,
        items: [true, false, false, false, false, false],
        select: "其他",//临时物品类型选项存储
        itemType: "请选择物品种类",//最终物品类型选项结果
    },

    submitOrder: function (e) {
        console.log(e.detail.value);
    },
    /**
     * 用户点击右上角分享
     */
    onShareAppMessage: function () {

    },
    /**
     * 修改跑腿者的性别
     */
    changeGender: function (e) {
        console.log(e.detail);
        if (e.detail.value) {
            this.setData({
                gender: "男"
            })
        } else {
            this.setData({
                gender: "女"
            })
        }
    },

    /**
     * 进入物品类型选项卡
     */
    showItemSelect: function () {
        this.setData({
            itemTypeFlag: true
        })
    },
    /**
     * 取消物品类型选项卡
     */
    closeItemSelect: function () {
        this.setData({
            itemTypeFlag: false,
        })
    },
    /**
     * 切换选项卡
     */
    onSelect: function (e) {
        let that = this;
        let arrays = that.data.items;
        if (e.detail.select == true) {
            that.setData({
                select: e.detail.name
            })

        } else {
            for (let i = 0; i < arrays.length; i++) {
                if (arrays[i] == true) {
                    arrays[i] = false
                } else if (e.currentTarget.id == i) {
                    arrays[i] = true
                }
            }
            that.setData({
                items: arrays,
                select: e.detail.name
            })
        }
    },
    /**
     * 物品选项卡点击确认
     */
    itemConfirm: function (e) {
        let select = this.data.select
        this.setData({
            itemType: select,
            itemTypeFlag: false
        })
    }

})
```

**Comment by juzi214032** [comment]
这个是微信原生组件的层级问题,textarea组件是原生组件，层级最高，无法被其他组件遮挡，建议在popup弹出时使用wx:if隐层textarea，参考 #796
