### ISSUE TITLE
优雅提交issues的方式

### ISSUE THREAD

**Issue by uniquenaer** [TaleLin/lin-ui#8]
0 提问之前
建议阅读：[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

1 issues标题：类型+内容；

类型有这两种：【Bug Report】、【Feature Request】

1.1 类型是bug时：

2 重现步骤：

3 期望的结果是什么？

4 实际的结果是什么？

5  补充说明（可选）

1.2 类型是Feature Request时：

2 描述你希望的支持的新功能？

3 你期望的 API 是怎样的？

**Comment by shmilyQin** [comment]
表单里面有l-input 输入字会超出屏幕
![image](https://user-images.githubusercontent.com/20322678/78754498-24fa3500-79aa-11ea-8248-bf5850b4e9a9.png)

**Comment by ApmI00** [comment]
[Bug Report] tabs非等宽标签，Android真机上，底部会多出一条横线，模拟器上没有问题。linUI的tabs示例上可以复现

**Comment by Bryant24s** [comment]
关于countDown倒计时组件。如下图，时间数字大小样式是可以修改的。但是，如何修改旁边文字“天-时-分-秒”大小。如何修改冒号“：”大小样式
![1625487326(1)](https://user-images.githubusercontent.com/14868600/124470892-c8fda680-ddce-11eb-827c-9f0c26a5dc07.png)
