### ISSUE TITLE
segment 组件 scroll-center.js 报错

### ISSUE THREAD

**Issue by junxian123** [TaleLin/lin-ui#801]
**LinUI版本（必填）：0.7.6

**设备（必填）：iphon6

**基础库版本（必填）：2.11.0

**UI问题，请附上截图**
![1](https://user-images.githubusercontent.com/38606245/81502700-fa392e80-9311-11ea-811e-6228115245cf.PNG)

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
请问可以提供一下相关wxml、js代码和ui截图吗，仅凭这个报错无法定位问题
