### ISSUE TITLE
真机上报错Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by BeFearless4U** [TaleLin/lin-ui#809]
**LinUI版本（必填）：0.8.0

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
![IMG_2556](https://user-images.githubusercontent.com/42951741/81799491-fee52900-9543-11ea-8ba2-1dfd3c487c33.png)

**重现步骤，必要时请提供代码片段链接**
未知原因导致编译错误,怀疑是node util导致
在真机上出现 ReferenceError: Can't find variable: regeneratorRuntime...

**Comment by MuRongXiaoDouBi** [comment]
请开启增强编译
