### ISSUE TITLE
StatusShow中的按钮会触发两次事件

### ISSUE THREAD

**Issue by Andyear** [TaleLin/lin-ui#81]
**重现步骤（可选）：**

**期望的结果是什么？**
先在StatusShow组件中触发了一次onBtn事件，又在button里触发了一次事件
**实际的结果是什么？**
只触发一次事件

**Comment by YpchenLove** [comment]
@aQingYun

**Comment by aQingYun** [comment]
已修复，感谢反馈。

**Comment by zhc525349965** [comment]
修改时间冒泡后，该问题重新复现。

**Comment by zhc525349965** [comment]
已经修复了重现的问题。

**Comment by zhc525349965** [comment]
closed as solved
