### ISSUE TITLE
【form组合使用时,l-input组件添加clear属性值为true时,清除按钮不显示】

### ISSUE THREAD

**Issue by itclanCode** [TaleLin/lin-ui#810]
**LinUI版本（必填）：*^0.7.6*

**设备（必填）：*安卓*

**基础库版本（必填）：*2.10.4*

**UI问题，请附上截图**
![Form表单清除按钮不显示](https://user-images.githubusercontent.com/25076543/81822919-47154300-9566-11ea-8efe-35db34b3c568.png)

**重现步骤，必要时请提供代码片段链接**
当使用l-form组件结合l-form-item，及l-input使用时,表单内内容不为空时,表单属性设置clear属性为true时,清除按钮不显示
`<l-form name="orderForm" data-openid="{{openid}}" bind:linsubmit="orderSubmit" l-form-btn-class="l-form-btn-class">
			<l-form-item label-width="100rpx" label="姓名:" name="orderFormUser" rules="{{orderForm.userRules}}">
				<l-input id="orderFormUser" bind:lininput="onInput" bind:linfocus="onFocus" bind:linblur="onBlur" maxlength="6" placeholder="请输入您的名字" value="{{orderForm.username}}" hide-label show-row="{{false}}" type="text" clear="{{true}}" />
			</l-form-item>
	</l-form>`

**Comment by dpp050700** [comment]
您好，清楚按钮不显示是因为 l-input 组件内部固定了 input 宽度 750rpx，导致input超出屏幕，可以使用 l-class 外部样式设置 input 组件的宽度来解决该问题
