### ISSUE TITLE
图像选择器ImagePicker返回结果跟文档所写不一致

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#811]
**LinUI版本（必填）：0.7.6

**设备（必填）：微信开发工具

**基础库版本（必填）：2.10.4

**UI问题，请附上截图**
![001](https://user-images.githubusercontent.com/3716806/81838929-69fd2280-9579-11ea-9973-0877bdb950a0.jpg)
![002](https://user-images.githubusercontent.com/3716806/81838911-61a4e780-9579-11ea-9112-9682ee7a4f1e.jpg)

`<l-image-picker count="1" urls="{}" bind:linchange="onChangeTap" />`

**重现步骤，必要时请提供代码片段链接**
无论设置参数urls是[]还是{}，控制台返回的结果e.detail都是有all+current包着，跟文档里说的Tip说明并不一致

**Comment by zhc525349965** [comment]
感谢指出，官网文档已更新，关闭此issue
