### ISSUE TITLE
tag和popup共用时，bind:lintap冲突

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#816]
**LinUI版本（必填）：0.7.6

**设备（必填）：微信开发工具

**基础库版本（必填）：2.10.4

**UI问题，请附上截图**
<img width="740" alt="截屏2020-05-15 18 59 42" src="https://user-images.githubusercontent.com/3716806/82043508-499aa880-96de-11ea-8f55-d909ef9b1e4b.png">
`<l-popup show="{{!isClose}}" content-align="bottom" bind:lintap="clickpopup" locked="{{false}}">
        <view class="demo">
            <l-tag shape="square" bind:lintap="clickone">我是tag</l-tag>
            <l-tag shape="circle" bind:lintap="clicktwo">我也是tag</l-tag>
            <button bind:tap="close">我不是tag，我要关闭弹出层</button>
        </view>
    </l-popup>`

<img width="335" alt="截屏2020-05-15 19 00 30" src="https://user-images.githubusercontent.com/3716806/82043551-5f0fd280-96de-11ea-954d-a2634944d80a.png">
`clickpopup(){
    console.log('我点击了背影')
  },
  clickone(){
    console.log('我点击了第一个tag')
  },
  clicktwo(){
    console.log('我点击了第二个tag')
  },`

**重现步骤，必要时请提供代码片段链接**
<img width="766" alt="addddd" src="https://user-images.githubusercontent.com/3716806/82043866-e2312880-96de-11ea-85e0-e9fa99e90820.png">

在popup里面用了tag组件，发现当我点击tag的时候，也同时点击了popup的背影，冲突了

**Comment by juzi214032** [comment]
在tag外面包一层view，然后在view上面写上 catchtap 试一下（只写个catchtap就行，不用给值）

**Comment by Donliang** [comment]
> 在tag外面包一层view，然后在view上面写上 catchtap 试一下（只写个catchtap就行，不用给值）

包了view后的catchtap还是会触发了popup的bind:lintap

**Comment by juzi214032** [comment]
再把tag的bindlintap改为catchlintap呢

**Comment by Donliang** [comment]
> 再把tag的bindlintap改为catchlintap呢

问题没有解决，一样是冲突，触发了popup的bind:lintap

**Comment by Donliang** [comment]
> 再把tag的bindlintap改为catchlintap呢

如果你有空的话，希望你能自己先试试看结果，减少沟通成本，我希望直接解决问题，不需要用issue来探讨让我再多次测试bug

**Comment by juzi214032** [comment]
不好意思，请您看看这个代码片段是否解决了您说的问题，采用的办法是我说的第二种
https://developers.weixin.qq.com/s/p5SlimmB7FhD

**Comment by Donliang** [comment]
> 不好意思，请您看看这个代码片段是否解决了您说的问题，采用的办法是我说的第二种
> https://developers.weixin.qq.com/s/p5SlimmB7FhD

感谢你的帮忙，catch:lintap终于解决了问题，原来还有这样的写法。。希望文档也能明示，最后耽误了你的宝贵时间，谢谢你

**Comment by Donliang** [comment]
> 不好意思，请您看看这个代码片段是否解决了您说的问题，采用的办法是我说的第二种
> https://developers.weixin.qq.com/s/p5SlimmB7FhD

我要向你表示道歉，我的语气有问题。

**Comment by juzi214032** [comment]
没关系，问题解决就好
