### ISSUE TITLE
button组件设置bg-color之后disable=true不会置灰

### ISSUE THREAD

**Issue by LeeSamFong** [TaleLin/lin-ui#817]
**LinUI版本（必填）：**
0.8.0
**设备（必填）：**
Windows版开发工具
**基础库版本（必填）：**
2.11.0
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

button在设置了bg-color之后，再设置disabled为true的情况下并不会置灰~
这是bug，还是就是设计成这样的呢？

**Comment by juzi214032** [comment]
这是个bug，我们需要讨论一下这个怎么处理，修复后会回复您
