### ISSUE TITLE
折叠面板组件的手风琴模式，不能默认展开第一个

### ISSUE THREAD

**Issue by 0feng0** [TaleLin/lin-ui#821]
**LinUI版本（必填）：**0.8

**设备（必填）：**window微信小程序

**基础库版本（必填）：**2.110

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
`<l-collapse type="accordion" expand-item-id="{{arr}}">
<l-collapse-item title="{{item.title}}" wx:for="{{arr}}" wx:key item-id="{{index}}">
{{item.text}}
  </l-collapse-item>
</l-collapse>`

js:

arr: [
      {
        title: 'aaa',
        text: '默认展开第一个'
      },
      {
        title: 'bbb',
        text: '展开第二个'
      },
      {
        title: 'ccc',
        text: '展开第三个'
      },
    ]

**Comment by juzi214032** [comment]
请提供一下您的wxml代码

**Comment by 0feng0** [comment]
> 请提供一下您的wxml代码

<l-collapse type="accordion" expand-item-id="{{arr}}">
  <l-collapse-item title="{{item.title}}" wx:for="{{arr}}" wx:key item-id="{{index}}">
    {{item.text}}
  </l-collapse-item>
</l-collapse>

**Comment by juzi214032** [comment]
麻烦可以贴一下完整代码吗，您只贴一个变量我这边没法判断是什么问题

**Comment by 0feng0** [comment]
> 麻烦可以贴一下完整代码吗，您只贴一个变量我这边没法判断是什么问题

`<l-collapse type="accordion" expand-item-id="{{arr}}">
<l-collapse-item title="{{item.title}}" wx:for="{{arr}}" wx:key item-id="{{index}}">
{{item.text}}
  </l-collapse-item>
</l-collapse>`

**Comment by juzi214032** [comment]
`expand-item-id`填写的是一个数组，这个数组是`item-id`属性指定为id，如果没有置顶，默认是索引值，如下图
![image](https://user-images.githubusercontent.com/38206169/82309631-f08c8680-99f5-11ea-9591-95aac0be41ad.png)

**Comment by 0feng0** [comment]
> `expand-item-id`填写的是一个数组，这个数组是`item-id`属性指定为id，如果没有置顶，默认是索引值，如下图
> ![image](https://user-images.githubusercontent.com/38206169/82309631-f08c8680-99f5-11ea-9591-95aac0be41ad.png)

好的，谢谢您!
