### ISSUE TITLE
布局 -> 相册 单图无法显示

### ISSUE THREAD

**Issue by JunsW** [TaleLin/lin-ui#822]
**LinUI版本（必填）：**
0.8.0

**设备（必填）：**
模拟器、iPhoneX真机

**基础库版本（必填）：**
2.8.1

**UI问题，请附上截图**
布局 -> 相册 中单图无法显示

<img width="376" alt="Screen Shot 2020-05-19 at 16 57 35" src="https://user-images.githubusercontent.com/6113815/82306606-d94b9a00-99f1-11ea-8fb8-da0e237a20ba.png">

**重现步骤，必要时请提供代码片段链接**
线上线程序和Github代码Demo中的均无法显示

**Comment by juzi214032** [comment]
感谢反馈，这个是图片链接出现了问题，我们尽快修复

**Comment by JunsW** [comment]
反馈速度好快👍
<img width="1034" alt="Screen Shot 2020-05-19 at 17 39 55" src="https://user-images.githubusercontent.com/6113815/82311047-c340d800-99f7-11ea-8701-023266fb8641.png">
似乎是单图会触发downloadFile
我把单图的链接替换成多图里的也不行

刚接触小程序开发不太了解，为啥多图不会触发域名校验单图会？
单图有额外的缓存机制？

**Comment by juzi214032** [comment]
不是的 就是单纯的图片链接问题，那个链接失效了

**Comment by juzi214032** [comment]
你控制台中的警告，把微信开发者工具中的不校验合法域名开启，就可以了

**Comment by JunsW** [comment]
好的 thx～

**Comment by AveryHandsomeBoy** [comment]
我也遇到这个问题了 辛苦了！

**Comment by juzi214032** [comment]
该问题已修复，待 Demo 更新即可看到
