### ISSUE TITLE
使用步骤条组件,设置纵向步骤条报错

### ISSUE THREAD

**Issue by 251205668** [TaleLin/lin-ui#826]
**LinUI版本（必填）：0.75**

**设备（必填）：开发者工具**

**基础库版本（必填）：*2.10.4*

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
![](https://image.yangxiansheng.top/img/20200520212415.png?imagelist)

![](https://image.yangxiansheng.top/img/20200520212358.png?imagelist)

**Comment by 7insummer** [comment]
这个错误应该是不影响使用的。但我们会修复这个问题，感谢

**Comment by 251205668** [comment]
@7insummer 好的谢谢老师

**Comment by juzi214032** [comment]
这个问题最新版已修复，请更新到最新版 0.8.1
