### ISSUE TITLE
建议增加评论列表组件

### ISSUE THREAD

**Issue by 251205668** [TaleLin/lin-ui#828]
**描述你希望的支持的新功能？**
类似这种效果的
![](https://image.yangxiansheng.top/img/20200520224446.png?imagelist)

**你期望的 API 是怎样的？**
能够动态控制单个评论面板显示多少条评论，自动隐藏未覆盖的评论

**Comment by juzi214032** [comment]
感谢建议，这个组件定制化程很高，我们需要讨论一下是否进行支持，讨论后会回复您

**Comment by juzi214032** [comment]
您好，这个组件我们经过评估后认为其通用性不大，所以暂时不进行开发。感谢您的建议，非常抱歉
