### ISSUE TITLE
custom-tab-bar isSwitchTab	属性无效，无论是 true 还是 false 都是 switchTab

### ISSUE THREAD

**Issue by hejinzhi** [TaleLin/lin-ui#835]
**LinUI版本（必填）：**
0.7.5
**设备（必填）：**
安卓 IOS
**基础库版本（必填）：**
任何版本
**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
![image](https://user-images.githubusercontent.com/18588816/82625327-6cb1e480-9c17-11ea-9dd6-05220c42e52c.png)

**Comment by juzi214032** [comment]
你好，该组件近期会进行重构，到时会对该问题进行修复

**Comment by juzi214032** [comment]
0.8.12 版本会修复此问题
