### ISSUE TITLE
segment背景色覆盖不全

### ISSUE THREAD

**Issue by AveryHandsomeBoy** [TaleLin/lin-ui#836]
**LinUI版本（必填）：**
0.8.1
**设备（必填）：**
*
**基础库版本（必填）：**
2.11.0
**UI问题，请附上截图**
![1](https://user-images.githubusercontent.com/44129388/82721562-bae6e680-9cf0-11ea-8e23-f0faf44934da.png)
**重现步骤，必要时请提供代码片段链接**
segment设置背景的时候会剩两头两个小角没有覆盖到，而且底下有一条白色的线也没覆盖到，辛苦了！

**Comment by juzi214032** [comment]
麻烦提供一下您的 wxml和wxss代码
