### ISSUE TITLE
如何响应瀑布流中各项的点击事件

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#837]
瀑布流渲染的页中，如果点击了其中的一项，如何响应这个事件。

**Comment by juzi214032** [comment]
在您自己封装的组件上使用`bind:tap`监听

**Comment by 7insummer** [comment]
瀑布流是需要自行封装组件的，可以在组件中添加对事件的响应

**Comment by workingCar** [comment]
页面能监听组件的tap事件吗?

**Comment by juzi214032** [comment]
可以的，建议看一下小程序官方文档，组件和页面通信使用`this.triggerEvent()`
