### ISSUE TITLE
card组件的报错信息

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#838]
**LinUI版本（必填）：*0.81*

**设备（必填）：*官方IDE*

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
linui组件 的官方示例小程序 中，card页面报错，但不影响使用
![1](https://user-images.githubusercontent.com/35887550/82726005-b97ae580-9d13-11ea-9573-c85da932408e.png)
。

**Comment by juzi214032** [comment]
感谢反馈，这个问题将在下个版本修复，该报错信息不影响组件运行
