### ISSUE TITLE
瀑布流组件使用的问题

### ISSUE THREAD

**Issue by workingCar** [TaleLin/lin-ui#839]
**LinUI版本（必填）：*0.81*

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
希望瀑布流渲染的组件中的事件可以被页面监听。
渲染的自封装组件littleCard的事件代码：

>     onTap(e) {
      this.triggerEvent('tapEvent', e)
    },

页面的bind:tapEvent是写在l-water-flow 组件里吗？这样写不成功啊？

>  <view class="padding">
    	<l-water-flow generic:l-water-flow-item="littleCard"  bind:tapEvent="navPage"/>
 </view>

**Comment by juzi214032** [comment]
抱歉，这个暂时只能在自定义组件中监听到tap事件，页面中暂时无法监听。页面监听点击事件的问题我们将在下个版本修复，请持续关注

**Comment by juzi214032** [comment]
请问一下您是有什么需求必须在页面中进行事件的监听呢，如果是页面跳转之类的，在组件内部监听事件也是可以实现的
