### ISSUE TITLE
吸顶容器Sticky，swiper作为"body"插槽时，header变透明的问题

### ISSUE THREAD

**Issue by abc1148738319** [TaleLin/lin-ui#842]
LinUI版本（必填）：0.7.6

设备（必填）：安卓

基础库版本（必填）：2.10.3

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
wxml:
`<l-sticky>
	<l-sticky-item>
		<view slot="header" style="background-color: darkgoldenrod;">abc</view>
		<view slot="body">
			<swiper style="background-color: burlywood;height: 2000rpx;">
				<swiper-item>123456789</swiper-item>
			</swiper>
		</view>
	</l-sticky-item>
</l-sticky>`

js:
`  onPageScroll(res) {
    wx.lin.setScrollTop(res.scrollTop)
  },`

**Comment by juzi214032** [comment]
可以提供一张截图吗

**Comment by abc1148738319** [comment]
![clipboard](https://user-images.githubusercontent.com/54339007/82733859-7b98b400-9d49-11ea-9ebd-37dfa22c6cf8.png)

**Comment by juzi214032** [comment]
使用`l-header-class`外部样式类设置`z-index`提高header层级即可
