### ISSUE TITLE
同一个页面渲染多次segment遇到问题

### ISSUE THREAD

**Issue by junxian123** [TaleLin/lin-ui#845]
**LinUI版本（必填）：0.8.0

**设备（必填）：iphone6

**基础库版本（必填）：最新

**UI问题，请附上截图**
UI图如下
图1
![image](https://user-images.githubusercontent.com/38606245/82803247-caae2880-9eb2-11ea-97cd-aaa2653b7791.png)
图2
![image](https://user-images.githubusercontent.com/38606245/82803336-eb767e00-9eb2-11ea-8434-8114de8164e2.png)
当我每次点击更多按钮也就是**图2**请选择分类的UI，我在选择分类上切换**图1**的segment
发现当切换的segment-item数量与上次的segment-item数量一致时，便会切换失败。（当我选择其他类目的时候，页面那里还是显示测试类目，测试类目跟其他类目数量是一样的）

经查看segment组件源码
if (t.length === this.data.tabList.length) return;
发现切换如果是跟上一次长度一致，会直接return

请问，如果做这种功能，有没有其他解决办法，(我现在时把这行代码注释掉了，但不想改源码)
**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
麻烦提供一下您的wxml代码和js代码

**Comment by junxian123** [comment]
`<view class="container">
	<view class="left" bindtap="onType">
		<text class="text">{{text}}</text>
		<l-icon l-class="down" name="pull-down" color="#ccc" size="24"/>
	</view>

	<view class="center">
		<l-segment 
			l-class="segment"
			l-active-class="seg-item-active"
			l-inactive-class="seg-item-inactive"
			l-line-class="seg-item-line"
			l-header-class="segment-header"
			placement="top"
			even="{{false}}"
			height="{{height}}"
			item-height="90"
			active-key="{{currentSubId}}"
			scrollable
			bind:linchange="onChange">
			<l-segment-item tab="最新" key="0"/>
			<block wx:for="{{subs}}" wx:key="id">
				<l-segment-item tab="{{item.name}}" key="{{item.id}}"/>
			</block>
		</l-segment>
	</view>
	<view class="right" bind:tap="onMore">
		<l-icon l-class="seeyou" name="mymore" color="#45526b" />
	</view>
</view>
`
上面代码对应
![image](https://user-images.githubusercontent.com/38606245/82854132-18ba3f00-9f3a-11ea-998c-7334daab9268.png)

分类组件代码
`<view class="container">
  	<view class="header">
		<text class="title">请选择分类</text>
		<view style="flex:1;"></view>
		<l-button size="mini" bg-color="#45526b" shape="square" bind:lintap="onCancel">取消</l-button>
	</view>
	<view class="main">
		<l-segment 
			l-class="segment"
			l-active-class="seg-item-active"
			l-inactive-class="seg-item-inactive"
			l-line-class="seg-item-line"
			placement="left"
			even="{{false}}"
			width="160"
			height="800"
			item-height="90"
			active-key="{{defaultRoot.id}}"
			scrollable
			bind:linchange="onChange">
			<block wx:for="{{roots}}" wx:key="id">
				<l-segment-item tab="{{item.name}}" key="{{item.id}}"/>
			</block>
    	</l-segment>

		<view class="grid-container">
			<l-grid>
				<block wx:for="{{currentSubs}}" wx:key="id">
					<l-grid-item
						slot="{{item.id}}"
						key="{{item.id}}"
						bind:linitemtap="onGridItemTap"
						data-sub="{{item}}"
						>
						<view class="grid-item">
							<image class="sub-img" src="{{item.img}}" mode="aspectFill" />
							<text class="sub-name">{{item.name}}</text>
						</view>
					</l-grid-item>
				</block>
			</l-grid>
		</view>
	</view>
</view>
Component({
    properties: {
        roots: Array,
        currentSubs: Array,
        defaultRoot:Object
    },
    observers: {},
    data: {},

    methods: {
        onGridItemTap(event) {
            const currentSub = event.currentTarget.dataset.sub
            const root = this.properties.roots.find(root => root.id === currentSub.parent_id)
            this.triggerEvent('getsub', {
                root,
                currentSub
            })
        },

        onChange(event) {
            const rootId = parseInt(event.detail.activeKey)
            this.triggerEvent('changeroot',{
                id: rootId
            })
        },

        onCancel(event) {
            this.triggerEvent('cancel')
        }
    }
})
`
上面代码对应
![image](https://user-images.githubusercontent.com/38606245/82854260-81a1b700-9f3a-11ea-8b91-94b6e27ce0d1.png)

页面引用分类组件代码
`
<l-popup show="{{showPopup}}" animation="{{false}}" transition="{{false}}" content-align="top">
    <x-category 
        roots="{{roots}}" 
        currentSubs="{{currentSubs}}" 
        defaultRoot="{{defaultRoot}}"
        bind:changeroot="onChangeRoot"
        bind:getsub="onGetSub"
        bind:cancel="onHidePopup"/>
</l-popup>
        onGetSub(event) {
		const {currentSub,root} = event.detail
		const homeSubs = this.data.categories.getSubs(root.id)
		this.setData({
			homeSubs,
			categoryId: currentSub.id,
			showPopup: false,
		})
		this.initPaging()
	},
         onChangeRoot(event) {
		const id = event.detail.id
		const currentSubs = this.data.categories.getSubs(id)
		this.setData({
			currentSubs
		})
	},`

**Comment by juzi214032** [comment]
不好意思，您的这个问题不太好理解，如果您方便的话可以录个屏吗

**Comment by junxian123** [comment]
https://myushu.top/a54923507e4d3578113aa3e52d3571fd.gif

**Comment by juzi214032** [comment]
你把
```js
if (t.length === this.data.tabList.length) return;
```
这行代码注释掉就能正常切换了吗，我这边测试了一下，这行代码注释掉也是不能正常切换的

**Comment by junxian123** [comment]
我这边是可以,,linui0.8.0,基础库2.11.0

**Comment by juzi214032** [comment]
了解了，这个问题我们将在下个版本修复，感谢反馈
