### ISSUE TITLE
吸顶组件，官网例子，没有效果

### ISSUE THREAD

**Issue by IIIIIIIIF** [TaleLin/lin-ui#846]
**LinUI版本（必填）：*0.8.1*

**设备（必填）：*开发者工具*

**基础库版本（必填）：*2.11.1*

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/29888011/82816110-22f22400-9ecd-11ea-8fa6-322aabe8acbb.png)
![Uploading image.png…]()

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
麻烦提供一下您的js代码
