### ISSUE TITLE
form验证的时候,设置type:number,没法兼容可以为空的情况

### ISSUE THREAD

**Issue by fanyao1983** [TaleLin/lin-ui#856]
**LinUI版本（必填）：0.8.0

**设备（必填）：iphone6

**基础库版本（必填）：最新

UI问题，请附上截图
UI图如下
图1

**重现步骤，必要时请提供代码片段链接**
   numberRules: [
      {
        min: 2,
        max: 8,
        message: '数值太夸张了,核对下你的赞藏和粉丝数信息',
        trigger: 'blur'
      },
      {
        required: false,
        type: 'number',
        message: '必须是纯数字,不能带中文或者标点符号',
        trigger: 'blur'
      },
    ],
有以下一个场景: 用户可以不输入,或者输入必须是数字.
但设置type:number的时候,即使设置required:false,也必须要输入数字

**Comment by juzi214032** [comment]
请提供一下wxml代码

**Comment by fanyao1983** [comment]
> 请提供一下wxml代码
form-item,粉丝数与赞藏数
	<l-form-item label="粉丝数:" name="xhs_fans" tip-type="{{tipType}}" rules="{{numberRules}}">
						<l-input l-class="l-input-container-class" id="xhs_fans" value="{{form.xhs_fans}}" hide-label show-row="{{false}}" />
					</l-form-item>
					<l-form-item label="赞藏数" name="xhs_collectslike" tip-type="{{tipType}}" rules="{{numberRules}}">
						<l-input l-class="l-input-container-class" id="xhs_collectslike" value="{{form.xhs_collectslike}}" hide-label show-row="{{false}}" />
					</l-form-item>

**Comment by fanyao1983** [comment]
<l-form-item label="粉丝数:" name="xhs_fans" tip-type="{{tipType}}" rules="{{numberRules}}">
						<l-input l-class="l-input-container-class" id="xhs_fans" value="{{form.xhs_fans}}" hide-label show-row="{{false}}" />
					</l-form-item>
					<l-form-item label="赞藏数" name="xhs_collectslike" tip-type="{{tipType}}" rules="{{numberRules}}">
						<l-input l-class="l-input-container-class" id="xhs_collectslike" value="{{form.xhs_collectslike}}" hide-label show-row="{{false}}" />
					</l-form-item>

**Comment by juzi214032** [comment]
感谢反馈，这个问题我们将在下个版本修复
