### ISSUE TITLE
form表单中使用input自定义组件右边部分无效

### ISSUE THREAD

**Issue by caiying5221** [TaleLin/lin-ui#860]
**LinUI版本（必填）：*0.8.1*

**设备（必填）：*微信小程序*

**基础库版本（必填）：*2.8.1*

**UI问题，请附上截图*
![image](https://user-images.githubusercontent.com/49259396/83499982-c60bf480-a4f0-11ea-8299-6e7b8cf8d88b.png)
*

- **重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
请提供一下wxml和wxss代码

**Comment by caiying5221** [comment]
#wxml
`<view class="container">
    
    <l-notice-bar show
                  l-class="notice-bar-class"
                  front-icon-name="soud"
                  front-icon-size="48"
                  front-icon-color="#F4516C">
        填写完基本信息即可成为尊贵的V2会员
    </l-notice-bar>
    
    <l-sticky>
        <l-sticky-item l-header-class="sticky-item-header">
            <view slot="header">
                <view class="container-text">
                    <text>基本信息</text>
                </view>
            </view>
            <view slot="body" class="userInfoForm">
                <l-form name="userInfoForm" l-form-btn-class="l-form-btn-class">
                    <l-form-item label="身高:" name="height">
                        <l-input id="height" value="{{userInfoForm.height}}" hide-label show-row="{{false}}">
                            <text slot="right">cm</text>
                        </l-input>
                    </l-form-item>
                </l-form>
            </view>
        </l-sticky-item>
    </l-sticky>
</view>
<l-toast></l-toast>`
#wxss
`page {
    background-color: #FDFDFD;
}
.sticky-item-header {
    background-color: #ffffff !important;
    z-index: 10000;
}
.notice-bar-class {
    background-color: #f3f3f3 !important;
    color: #F4516C !important;
    height: 100rpx !important;
    display: flex;
    align-items: center;
    justify-content: center;
}
.container-text {
    display: flex;
    margin-left: 20rpx;
    margin-top: 20rpx;
    font-size: 38rpx;
    height: 80rpx;
}
.userInfoForm {
    margin-top: 20rpx;
    background-color: #ffffff;
}`

**Comment by juzi214032** [comment]
这个`cm`不是已经显示出来了吗，你说的无效指的是什么呢

**Comment by caiying5221** [comment]
我的机器上没有出现cm，可能是我的机器问题。你能给我看看你的效果图

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/83510421-91536980-a4ff-11ea-988a-6d74fe522179.png)
你发的截图就是有cm的呀

**Comment by caiying5221** [comment]
那个有cm的是不在表单中，是单个的input，最下面的是在l-form和l-form-item中使用input的没有显示

**Comment by juzi214032** [comment]
你好，这个问题是由于input组件默认宽度750rpx导致的，宽度太大，`cm`被顶到屏幕外面去了。
解决方法：使用input组件的`l-class`外部样式类修改width为auto或者更小的宽度即可

**Comment by juzi214032** [comment]
这个问题我们下个版本会优化一下，让默认样式下也不会出现问题，这个版本需要您手动修改一下

**Comment by caiying5221** [comment]
好的，谢谢！非常感谢！！！

**Comment by juzi214032** [comment]
不客气
