### ISSUE TITLE
l-tabs的组件 swipeable属性设置后不能向下滑动了，固定了一个高度，去掉后就可以了

### ISSUE THREAD

**Issue by admincsw** [TaleLin/lin-ui#862]
**LinUI版本（必填）：**

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**
<l-tabs bind:linchange="changeTabs" l-class-header-line="header-line" animated="{{true}}" swipeable active-key="one" >
**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
可以详细说明一下吗，最好附上wxml代码

**Comment by admincsw** [comment]
<l-tabs bind:linchange="changeTabs" l-class-header-line="header-line" swipeable animated="{{true}}"  active-key="one" &gt;
加了swipeable 后这个商品详情就不能向上滑动了，像是固定了高度一样



       




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "桔子"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 下午2:46
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "小威哥"<1139983176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] l-tabs的组件 swipeable属性设置后不能向下滑动了，固定了一个高度，去掉后就可以了 (#862)





 
可以详细说明一下吗，最好附上wxml代码

**Comment by juzi214032** [comment]
不好意思，我没太理解您的意思。可以给一个视频或者图片吗
