### ISSUE TITLE
l-tabs 标签页下 用组件内的content-height 设置内容高度无效

### ISSUE THREAD

**Issue by TQF980522** [TaleLin/lin-ui#877]
**LinUI版本（必填）：**0.6.12

**设备（必填）：** 微信开发者工具

**基础库版本（必填）：**最新

- [ ] 

- [ ] [**UI问题，请附上截图**]())

**重现步骤，必要时请提供代码片段链接**

**Comment by juzi214032** [comment]
更新到 0.8.2 试一下
