### ISSUE TITLE
custom-tab-bar

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#88]
**重现步骤（可选）：**
引入后，只显示样式不显示list里的内容，attached（）里打印this.data.list是空数组。删除properties下定义的list属性申明内容后渲染正常。

**Comment by YpchenLove** [comment]
custom-tab-bar 这个组件现在确实有一些问题，这个会在文档里更新相关的说明。
因为要同微信的自定义tabbar一样，就必须要在data里配置list等，如果把它当成一个在任意页面都可以使用的tabbar，那么是支持通过properties传参的方式去配置list等熟悉的。
出现渲染异常的原因，应该是data里的list和properties里的list冲突了。
谢谢反馈~

**Comment by virtualChan** [comment]
> custom-tab-bar 这个组件现在确实有一些问题，这个会在文档里更新相关的说明。
> 因为要同微信的自定义tabbar一样，就必须要在data里配置list等，如果把它当成一个在任意页面都可以使用的tabbar，那么是支持通过properties传参的方式去配置list等熟悉的。
> 出现渲染异常的原因，应该是data里的list和properties里的list冲突了。
> 谢谢反馈~

这个新功能还有些BUG，不过是官方的原因，观望下先了，暂时不用了。。
