### ISSUE TITLE
fix:修复water-flow组件在数据为[]是不刷新的问题（#572）这个问题又出现了，请确认下代码是否被回归？

### ISSUE THREAD

**Issue by skygzs** [TaleLin/lin-ui#889]
**LinUI版本（必填）：**

**设备（必填）：**

**基础库版本（必填）：**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by skygzs** [comment]
@juzi214032 最新版的昨天github下载的，测试了示例也同样的问题。
![image](https://user-images.githubusercontent.com/17756459/84339137-596bb680-abd0-11ea-987a-96dba2b850cd.png)

**Comment by juzi214032** [comment]
感谢反馈，这个是我们不小心把代码回滚了，下个版本将修复
