### ISSUE TITLE
loading组件的优化建议

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#90]
**描述你希望的支持的新功能？**
loading 支持mask属性。

**你期望的 API 是怎样的？**
<l-loading show="{{true}}" mask="{{true}}" type="flash"></l-loading>
当mask为true时，自带遮罩效果

小程序原生的loading组件是有这个属性的，设置了之后自带遮罩效果。现在的ui库，我还得再包一层mask组件，不知道是不是我使用方式不对。。我觉得loading组件，这个遮罩应该是强需求而且应用场景非常广。也许可以用全屏loading模式代替，但是在某些场景下并不合适，比如我在支付页面，我点击后在支付发起的过程中我要一个loading，这时候我要防止客户点击屏幕上的任何一个元素。

**Comment by YpchenLove** [comment]
很感谢你的反馈，也很赞同你对于loading的见解与思考。
关于这些，可能是我们文档描述和指引的不够准确，我做一下解释先。
1，你的这个需求，用toast可能会更好，它和微信原生的loading差别不是特别大，而且也带了mask阻止点击事件。
2，loading本身是一个没有很高的页面层级的无状态组件。他只是一个封装好的盒子，你可以把它看成是一个类似button或者avatar的组件，它不破坏页面本身的文档流。你可以把它放在页面的任意位置，上面或者下面都可以。全屏的loading，你只要修改了背景色，也是可以完成类似的效果。
3，如果你是需要局部区域出现一个遮罩，这个可能需要你自己多敲两行代码了。
