### ISSUE TITLE
按钮disabled不生效

### ISSUE THREAD

**Issue by WenLo** [TaleLin/lin-ui#903]
**LinUI版本（必填）：*0.8.3*

**设备（必填）：*编辑器调试*

**基础库版本（必填）：**

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/32947628/84588424-d9f11800-ae59-11ea-9819-d84d71e9ad09.png)

**重现步骤，必要时请提供代码片段链接**
按钮设置了disabled，按钮颜色变化，但是依然可以点击触发

**Comment by juzi214032** [comment]
你的意思是 disable 为 false，lintap事件仍然会被触发吗。我刚才试了，没有复现你说的这个问题

**Comment by juzi214032** [comment]
我看你的代码上面也没有监听lintap，你说的触发是触发什么呢

**Comment by WenLo** [comment]
这一块用的是表单，我点击了按钮，依然触发了表单事件






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "桔子"<notifications@github.com&gt;; 
发送时间: 2020年6月14日(星期天) 下午4:21
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "散了。"<863377861@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] 按钮disabled不生效 (#903)





 
我看你的代码上面也没有监听lintap，你说的触发是触发什么呢

**Comment by juzi214032** [comment]
触发了表单的 `linsubmit` 事件吗

**Comment by WenLo** [comment]
对的。按道理是不应该去触发的，按钮已经被禁用，依然触发了。保存了接口




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "桔子"<notifications@github.com&gt;; 
发送时间: 2020年6月14日(星期天) 下午4:26
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "散了。"<863377861@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] 按钮disabled不生效 (#903)





 
触发了表单的 linsubmit 事件吗

**Comment by juzi214032** [comment]
好的，感谢反馈，这个问题稍后我们排查一下

**Comment by juzi214032** [comment]
您好，由于`button`和`form`是独立的两个组件，`form`无法获取`button`的状态，所以`button`禁用和`form`是无关的，建议在页面中维护一个flag，用这个falg把button和from的状态统一起来
