### ISSUE TITLE
l-input 文档示例代码错误

### ISSUE THREAD

**Issue by virtualChan** [TaleLin/lin-ui#91]
label-width 来设置标题部分的宽度，默认是150，单位是rpx
错误示例代码：
`<l-input label="名称" label-layout="left" label-layout="170"  />`

正确应为：
`<l-input label="名称" label-layout="left" label-width ="170"  />`

**Comment by YpchenLove** [comment]
查看了一下源码，这个地方表达的意思是没有错误的，有一个默认值，同样可以自定义，我在文档里的示例代码里写了170也是没有问题的。
不过，后来源码做了一部分的修改，现在label-width的默认值是200了，单位同样是rpx。
谢谢反馈~😊

**Comment by YpchenLove** [comment]
看错了，把label-width和label-layout搞混了，已经做了修改。感谢反馈😄
