### ISSUE TITLE
segment组件的placement属性，只有top,left时才生效，bottom,right都变为了默认top值

### ISSUE THREAD

**Issue by luochenlin** [TaleLin/lin-ui#912]
**LinUI版本（必填）：**
0.8.3
**设备（必填）：**
开发工具（iphone6/7/8），预览（安卓10）
**基础库版本（必填）：**
2.11.1
**UI问题，请附上截图**
![图片](https://user-images.githubusercontent.com/53851505/84724573-1a1bdc00-afbb-11ea-9eb0-538989336f7d.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by MuRongXiaoDouBi** [comment]
抱歉，未复现此问题，可否提供完整的代码片段，最好不要是图片，供我们测试。

**Comment by luochenlin** [comment]
<l-segment active-key="sign" placement="bottom" has-line="{{false}}" height="140" active-color="#1296db" l-icon-class="surround">
        <l-segment-item tab="签到" key="sign" icon="sign1" icon-size="48" />
        <l-segment-item tab="统计" key="statistics" icon="statistics" icon-size="48" />
    </l-segment>

这是一个page页面，wxml没有其他内容，wxss没有任何代码，设置placement="bottom"还是显示在顶部的

**Comment by luochenlin** [comment]
<l-segment&nbsp;active-key="sign"&nbsp;placement="bottom"&nbsp;has-line="{{false}}"&nbsp;height="140"&nbsp;active-color="#1296db"&nbsp;l-icon-class="surround"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<l-segment-item&nbsp;tab="签到"&nbsp;key="sign"&nbsp;icon="sign1"&nbsp;icon-size="48"&nbsp;/&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<l-segment-item&nbsp;tab="统计"&nbsp;key="statistics"&nbsp;icon="statistics"&nbsp;icon-size="48"&nbsp;/&gt;
&nbsp;&nbsp;&nbsp;&nbsp;</l-segment&gt;


这是一个page页面，wxml没有其他内容，wxss没有任何代码，设置placement="bottom"还是显示在顶部的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "木荣"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 上午10:33
收件人: "TaleLin/lin-ui"<lin-ui@noreply.github.com&gt;; 
抄送: "可かai的ヲ你"<425392085@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TaleLin/lin-ui] segment组件的placement属性，只有top,left时才生效，bottom,right都变为了默认top值 (#912)





 
抱歉，未复现此问题，可否提供完整的代码片段，最好不要是图片，供我们测试。

**Comment by MuRongXiaoDouBi** [comment]
抱歉，您提供的代码格式有问题，请在github回复代码。

**Comment by luochenlin** [comment]
`<l-segment active-key="sign" placement="bottom" has-line="{{false}}" height="140" active-color="#1296db" l-icon-class="surround" l-class="segment">
        <l-segment-item tab="签到" key="sign" icon="sign1" icon-size="48" />
        <l-segment-item tab="统计" key="statistics" icon="statistics" icon-size="48" />
    </l-segment>`

**Comment by MuRongXiaoDouBi** [comment]
您是想 `placement ` 为 `right` 时，将组件移动到最右侧吗？

**Comment by luochenlin** [comment]
对呀，难道不应该这样吗？如果用一个view包裹住segment组件，view确定宽高，也应该相对于view的位置吧

**Comment by MuRongXiaoDouBi** [comment]
目前您说的功能可暂时通过设置外部样式类 `l-class` 进行实现，代码如下：

``` wxml
<l-segment placement="right" l-class="l-class">
  ......
</l-segment>
```

```wxss
.l-class	{
  position: absolute;
  right: 0;
}
```

**Comment by juzi214032** [comment]
您好，`Segment`组件是没有`right`和`bottom`的，这个是我们的文档描述的有问题。因为`Segment`只是一个标签，没有内容区域，所以如果你想`Segment`在你的内容的右侧，你只需要再页面上进行布局，将`Segment`放置于内容右侧即可。您的截图只有一个标签，并没有内容，您如果是想要将`Segment`放置在页面底部的话，应该使用`absolute`和`fixed`对`Segment`进行定位。

**Comment by juzi214032** [comment]
你好，`placement`现在修改的是激活tab的横线位置，后期我们会对属性名进行优化

**Comment by juzi214032** [comment]
文档已补充详细描述
