### ISSUE TITLE
Popup 的外部样式类修改背景颜色失效

### ISSUE THREAD

**Issue by 1525685999** [TaleLin/lin-ui#913]
<l-popup show="{{true}}"  content-align="bottom" l-class="pop-bg"> <filter/></l-popup>
.pop-bg{
  background: blue !important;
}

**Comment by 1525685999** [comment]
<l-popup show="{{true}}"  content-align="bottom" l-class="pop-bg"> <filter/></l-popup>

**Comment by 1525685999** [comment]
l-popup show="{{true}}"  content-align="bottom" l-class="pop-bg"> <filter/></l-popup>

**Comment by 1525685999** [comment]
<         l-popup show="{{true}}"  content-align="bottom" l-class="pop-bg"> <filter/></l-popup>

**Comment by juzi214032** [comment]
您好，我这边测试是没有问题的

![image](https://user-images.githubusercontent.com/38206169/84777256-ed47e300-b013-11ea-965b-d2b99f4cda87.png)
![image](https://user-images.githubusercontent.com/38206169/84777267-f1740080-b013-11ea-8697-9a5667176f23.png)
