### ISSUE TITLE
list组件右侧箭头颜色问题

### ISSUE THREAD

**Issue by teevil** [TaleLin/lin-ui#915]
**LinUI版本（必填）：0.8.3

**设备（必填）：p20

**基础库版本（必填）：2.11.2

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

**Comment by MuRongXiaoDouBi** [comment]
请提供您的详细问题与代码

**Comment by teevil** [comment]
List组件右侧箭头颜色不对，0.7.5是正常的。
`<t-list bind:lintap="onGotoMyOrder"
                    icon="order1"
                    l-icon-class="teevil-order"
                    l-class-content="list-item"
                    title="全部订单">
            </t-list>`
0.8.3版本右侧箭头颜色是#3963bc，给view加了一个内联样式。

**Comment by MuRongXiaoDouBi** [comment]
之前的色值是不是#45526B
