### ISSUE TITLE
count-selector 组件问题

### ISSUE THREAD

**Issue by 232296834** [TaleLin/lin-ui#916]
**LinUI版本（必填）：*v0.7.6*

**设备（必填）：*所设备*

**基础库版本（必填）：*2.11.0*

**UI问题，请附上截图**
![Uploading UDDTANH6W$4B09_XL(}6SP3.png…]()
![@4 0$M))HPV6U996MG V2~S](https://user-images.githubusercontent.com/65752432/84867066-35ffaa80-b0ad-11ea-94bc-840578bf7c9a.png)
点击增加数量时候，值是3，然后更改规格时候，值然是3

**重现步骤，必要时请提供代码片段链接**

**Comment by MuRongXiaoDouBi** [comment]
您好，您应该在规格改变后手动将Counter的值清空

**Comment by 232296834** [comment]
我在
observers: {
    "min,max": function () {
      this.setData({result:1,count:1})
      this.valueRange(this.data.count, "parameter")
    }
  },
这里使用了默认值

**Comment by 232296834** [comment]
如果当前页面有多个count-selector组件  那么值都是一样的  所以

**Comment by MuRongXiaoDouBi** [comment]
请提供完整代码片段
