### ISSUE TITLE
button按钮加了disabled true禁用失效

### ISSUE THREAD

**Issue by Donliang** [TaleLin/lin-ui#920]
**LinUI版本（必填）：0.8.3

**设备（必填）：微信开发工具

**基础库版本（必填）：2.10.4

**UI问题，请附上截图**
<img width="1412" alt="WeChatd852f2efff8ba7fe3e01053de8a3f276" src="https://user-images.githubusercontent.com/3716806/85202744-3f05ab80-b33b-11ea-84d0-2253364ef4e7.png">

**重现步骤，必要时请提供代码片段链接**
`<l-button type="default" bind:tap="btn" disabled="{{true}}">default</l-button>`
button按钮加了disabled="{{true}}"，点击还是有效，麻烦修复，谢谢

**Comment by juzi214032** [comment]
请使用bindlintap，不要用bindtap
