### ISSUE TITLE
图片选择器在编辑场景下的问题

### ISSUE THREAD

**Issue by 270686992** [TaleLin/lin-ui#921]
**LinUI版本（必填）：0.8.3**

**设备（必填）：mac**

**基础库版本（必填）：2.11.0**

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
- 在文档中,图片选择器的默认值是有接收两种形式的,不知道是什么原因，我使用第一种形式 url 数组的形式接收服务器返回的图片路径时出现了以下情况,经过打印是有路径在数组中的,但报了这个错误:
```
VM1509:1 Uncaught (in promise) thirdScriptError
{"errMsg":"previewImage:fail parameter error: parameter.urls[0] should be String instead of Undefined;"}
Object
```
截图如下:
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621102804557.png)

![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621102834594.png)

![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621102857759.png)

- 而当我直接像官方示例那样在这个数组写死一个路径的时候却是可以正常使用的。
- 接着我试了第二种对象数组的使用方式,可以正常使用,如下图所示:
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621103351387.png)

![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621103444469.png)

- 希望能够指点一下第一种情况为何不能那样使用。。。

**Comment by juzi214032** [comment]
是在点开图片进行预览时报错，还是传入属性的时候就会报错呢

**Comment by juzi214032** [comment]
可以提供一下你接口返回的数据格式吗

**Comment by 270686992** [comment]
点开图片时报错,而且没点开时不能预览,下面是返回的数据格式:
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200621111721488.png)

**Comment by juzi214032** [comment]
感谢反馈，这是组件的一个bug，我们将在下个版本进行修复

**Comment by juzi214032** [comment]
您好，建议暂时先使用对象数组的方式，后期我们将对这个问题进行优化

**Comment by juzi214032** [comment]
您好，该问题目前已解决。
imagePicker 组件将新增 cells 属性用于接收对象数组，urls 属性将仅用于接收字符串数组。
此特性将在 0.8.6 版本更新，升级后请注意代码兼容性
