### ISSUE TITLE
瀑布流子项事件返回值打印了没有自己传入的数据

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-ui#923]
**LinUI版本（必填）：0.83

**设备（必填）：安卓 IOS

**基础库版本（必填）：任何版本

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
![image](https://user-images.githubusercontent.com/39727435/85225820-5c537c00-b406-11ea-906b-80d8be3eb042.png)

![image](https://user-images.githubusercontent.com/39727435/85225854-96248280-b406-11ea-914a-90ae96e9c376.png)

或者说是我自己代码漏写了啥 因为我想通过瀑布流渲染图片 点击图片想获得图片的相关信息

**Comment by juzi214032** [comment]
感谢反馈，是我们组件的问题，在周三会发布0.8.4版本修复此问题
