### ISSUE TITLE
希望相册Album组件可以减少图片数量限制最多9张

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-ui#925]
**描述你希望的支持的新功能？**
希望相册Album组件可以减少图片数量限制最多9张
**你期望的 API 是怎样的？**
因为觉得相册不一定像朋友圈的相册只有显示九张 或者来个属性控制 每个人的需求不同
我也不知道这个提议是不是好的 但我目前的需求是想相册可以超过9张显示 因为想做下拉更多的操作

**Comment by juzi214032** [comment]
感谢反馈，我们会评估下这个需求

**Comment by juzi214032** [comment]
您好，我们后期会增加一个属性控制最大显示张数，做到微博多图显示的样式。如果您还有什么建议，可以及时提出
![image](https://user-images.githubusercontent.com/38206169/85568992-bea9b800-b664-11ea-89e0-82d384f0cf53.png)

**Comment by ElanYoung** [comment]
> 您好，我们后期会增加一个属性控制最大显示张数，做到微博多图显示的样式。如果您还有什么建议，可以及时提出
> ![image](https://user-images.githubusercontent.com/38206169/85568992-bea9b800-b664-11ea-89e0-82d384f0cf53.png)

好哒！我觉得用户可以自由控制是否显示微博多图显示的样式  如果超过9张 想像微博多图那样就采用这个方式 如果想就是做个loading加载中那种效果 可以关闭这个样式 因为如果图多的话 后端肯定会做分页形式

**Comment by zhc525349965** [comment]
0.8.7已经支持，具体使用方式请查看官网文档。
[https://doc.mini.talelin.com/component/layout/album.html](url)
