### ISSUE TITLE
在Radio组件中，设置了cell属性，linchange事件的返回值中cell总是为null

### ISSUE THREAD

**Issue by luochenlin** [TaleLin/lin-ui#927]
<l-popup show="{{true}}">
    <view class="popup">
        <l-radio-group current="{{date}}" none-checked="{{false}}" bind:linchange="onRadioChange">
            <block wx:for="{{monthList}}" wx:key="index">
                <l-radio key="{{item}}" l-class="radio" cell="{{item}}">{{item}}</l-radio>
            </block>
        </l-radio-group>
    </view>
</l-popup>

**Comment by juzi214032** [comment]
请提供下你的wxml和js

**Comment by luochenlin** [comment]
``<l-popup show="{{popupShow}}">
    <view class="popup">
        <l-radio-group current="{{date}}" none-checked="{{false}}" bind:linchange="onRadioChange">
            <block wx:for="{{monthList}}" wx:key="index">
                <l-radio key="{{item}}" l-class="radio" cell="{{item}}">{{item}}</l-radio>
            </block>
        </l-radio-group>
    </view>
</l-popup>

onRadioChange(event) {
console.log(event)
}

**Comment by luochenlin** [comment]
`<l-popup show="{{popupShow}}">
    <view class="popup">
        <l-radio-group current="{{date}}" none-checked="{{false}}" bind:linchange="onRadioChange">
            <block wx:for="{{monthList}}" wx:key="index">
                <l-radio key="{{item}}" l-class="radio" cell="{{item}}">{{item}}</l-radio>
            </block>
        </l-radio-group>
    </view>
</l-popup>`
`onRadioChange(event) {console.log(event)}`

**Comment by juzi214032** [comment]
cell 必须要是一个 Object 类型，请检查一下你传入的是否是 Object

**Comment by luochenlin** [comment]
明白了
