### ISSUE TITLE
折叠面板组件Collapse 设置了expand-item-id属性没有效果

### ISSUE THREAD

**Issue by zzmkj** [TaleLin/lin-ui#935]
**LinUI版本（必填）：** 0.8.3

**设备（必填）：** win10

**基础库版本（必填）：** 2.11.2

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**

- 在页面JS文件的data对象中，定义了defaultExpand数组属性。
[![b1.png](http://ww1.sinaimg.cn/large/006KKyKcgy1ggagoykgf2j30mw0drq38.jpg)](url)

- 在页面wxml文件中使用了`l-collapse`组件，设置`expand-item-id`属性，并把`defaultExpand`数组赋值到了该属性上。`l-collapse-item`组件都设置了`item-id`属性
[![b2.png](http://ww1.sinaimg.cn/large/006KKyKcgy1ggagp7639nj321e0vpthh.jpg)](url)

- 最后返回微信开发者工具查看页面，发现并没有默认展开`l-collapse-item`组件中`item-id='1'`的一项。
[![b3.png](http://ww1.sinaimg.cn/large/006KKyKcgy1ggagpco8csj30n40lp40y.jpg)](url)

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/86114788-9ce58080-bafd-11ea-8e63-7b1d191a6b64.png)

将 `type` 设置为 `accordion` 试一下

**Comment by zzmkj** [comment]
> ![image](https://user-images.githubusercontent.com/38206169/86114788-9ce58080-bafd-11ea-8e63-7b1d191a6b64.png)
> 
> 将 `type` 设置为 `accordion` 试一下



> ![image](https://user-images.githubusercontent.com/38206169/86114788-9ce58080-bafd-11ea-8e63-7b1d191a6b64.png)
> 
> 将 `type` 设置为 `accordion` 试一下

非常感谢~已解决！将`expand-item-id`属性设置成{{[0]}}就可以了，数组里面的值指的是`l-collapse-item`顺序索引，并不是指`l-collapse-item`组件里的`item-id`。非常感谢！

**Comment by juzi214032** [comment]
不好意思，这个是个bug，`expand-item-id`本意指的就是`item-id`的值，我刚看了下代码，是判断出了错误，才出现现在的结果，所以我们下个版本会修复一下

**Comment by zzmkj** [comment]
> 不好意思，这个是个bug，`expand-item-id`本意指的就是`item-id`的值，我刚看了下代码，是判断出了错误，才出现现在的结果，所以我们下个版本会修复一下

好的，谢谢~
