### ISSUE TITLE
瀑布流组件图片mode为widthFix时，瀑布流两边会一边长一边短

### ISSUE THREAD

**Issue by xyfll7** [TaleLin/lin-ui#941]
瀑布流组件图片mode为widthFix时，瀑布流两边会一边长一边短

这是因为图片还没加载出来瀑布流已经提前去获取图片尚未加载结束时的 card高度，图片加载结束以后又会再次改变card的高度，导致某一列延长，而另外一列缩短。
粗暴的解决方式可以将传进去的数组简单拆分，分批上屏即可。。

```
  这样调用renderWaterFlow就会正常显示。
  if(!this.graphics) return
      const t = JSON.deep([...this.graphics])
      for(;;) {
        const a = t.splice(0,2) // 这里只能是2,其余的数字都不太正常。
        if(!a.length) break;
        wx.lin.renderWaterFlow(a, false ,()=>{
          console.log('渲染成功')
        })
      }
``` 
![image](https://user-images.githubusercontent.com/28172140/86997856-b2376a80-c1e1-11ea-9a54-77fba6f383bf.png)

**Comment by juzi214032** [comment]
您好，可以提供一下相关的代码以及你所用的图片链接吗，我这边简单测了一下暂时没有发现这个问题

**Comment by xyfll7** [comment]
只需要将虚拟节点中的 image标签设置属性为： mode="widthFix" lazy-load
采用不同宽高比的图片加载进去就会一边长一边短。这个很正常。

**Comment by juzi214032** [comment]
您好，这个问题我已经复现了。感谢您提供的解决思路，但您的这种解决方案好像只是相当于做了一个延时操作，让`boundingClientRect`在图片加载完后才获取高度，是这样吗

**Comment by xyfll7** [comment]
> _您好_，_这个问题我已经复现了。感谢您提供的解决思路_，_但您的这种解决方案好像只是相当于做了一个延时操作_，让`boundingClientRect`_在图片加载完后才获取高度_，_是这样吗_

我的本意是使用`setTimeout`回调方式等待前2张图片完全被渲染完成，再延时调用`boundingClientRect`再渲染2张，但是实践结果发现，并不需要`setTimeout`直接for `boundingClientRect`即可。
说明只要给图片传入src，无论是否已经显示图片`boundingClientRect`都可以拿到正确的card高度值。

**Comment by xyfll7** [comment]
还有一个问题，这明显是一个无限长列表，card数量一旦多起来，会有明显的性能问题。
可以给每个card内部放一个 ` this.createIntersectionObserver().relativeToViewport({}).observe(`#card${_id}`, (res) => {})`
当这个card离开交叉口范围就自动隐藏（同时必须保留card自身高度，否则会出现塌陷）。这样就可以解决性能问题了。

但是这个代码似乎需要用户自己添加到虚拟节点内部，如果能封装进 虚拟节点的父组件，多用户隐藏，就再好不过了。

**Comment by objcxiaobai** [comment]
我也遇到这种情况.

**Comment by ElanYoung** [comment]
请问1.0版本会修复此问题吗
