### ISSUE TITLE
价格price组件 可不可以加一个功能

### ISSUE THREAD

**Issue by eaglemens** [TaleLin/lin-ui#943]
可以设置价格小数点后面部分的价格字体大小和加粗  
![微信图片_20200711133611](https://user-images.githubusercontent.com/19241562/87217427-7fc17500-c37b-11ea-868b-048c28f433df.png)
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by juzi214032** [comment]
感谢反馈，我们会为小数点后面的部分增加外部样式类
