### ISSUE TITLE
瀑布流组件图片mode为widthFix时，瀑布流两边会一边长一边短

### ISSUE THREAD

**Issue by xyfll7** [TaleLin/lin-ui#945]
这是因为图片还没加载出来瀑布流已经提前去获取图片尚未加载结束时的 card高度，图片加载结束以后又会再次改变card的高度，导致某一列延长，而另外一列缩短。
粗暴的解决方式可以将传进去的数组简单拆分用setTimeout()分批上屏。。或者使用flix布局。
![image](https://user-images.githubusercontent.com/28172140/86991762-78ab3300-c1d2-11ea-9d38-431d15c60404.png)

**Comment by juzi214032** [comment]
参考 issue #941
