### ISSUE TITLE
骨架屏 Skeleton组件 外部样式背景好像有问题

### ISSUE THREAD

**Issue by eaglemens** [TaleLin/lin-ui#946]
**LinUI版本（必填）：**0.8.4

**设备（必填）：**微信开发者工具

**UI问题，请附上截图**
![微信图片_20200712093001](https://user-images.githubusercontent.com/19241562/87236948-527bd200-c422-11ea-9d13-9af7790b0526.png)
![微信图片_20200712093006](https://user-images.githubusercontent.com/19241562/87236951-5a3b7680-c422-11ea-967a-5fe42e5bd5f4.png)

![微信图片_20200712090156](https://user-images.githubusercontent.com/19241562/87236897-4fccad00-c421-11ea-9c7e-664a95d7b88c.png)

骨架屏设置外部样式类背景色发现有问题  占不满我们设定的尺寸宽度  
（然后去掉外部样式背景色  本身的背景也是占不满设定的尺寸 ）

**Comment by juzi214032** [comment]
感谢反馈，我核查一下

**Comment by juzi214032** [comment]
您好，我看了下骨架屏的源码，应该是不会有您这个问题的。您这个问题初步判断应该是由您小程序页面样式的问题引起的，方便的话提供一个代码片段供我排查一下

**Comment by eaglemens** [comment]
我的骨架屏是用在瀑布流组件里面的  看下这个代码片段   https://developers.weixin.qq.com/s/P5GYbMmB79ix

**Comment by eaglemens** [comment]
> 您好，我看了下骨架屏的源码，应该是不会有您这个问题的。您这个问题初步判断应该是由您小程序页面样式的问题引起的，方便的话提供一个代码片段供我排查一下

你好   我的骨架屏是用在瀑布流组件里面的 看下这个代码片段https://developers.weixin.qq.com/s/P5GYbMmB79ix
![微信图片_20200712143028](https://user-images.githubusercontent.com/19241562/87240440-41e05180-c44c-11ea-9e84-2dc589c51b7b.png)

**Comment by juzi214032** [comment]
您好这是因为骨架屏的 avatar 默认给了一个 margin-right，在 css 中重新设置 margin-right 即可
```css
.avatar{
  background: #ff0036;
  margin-right: 0 !important;
}
```
