### ISSUE TITLE
Cannot read property 'validatorData' of undefined

### ISSUE THREAD

**Issue by fanyao1983** [TaleLin/lin-ui#948]
**LinUI版本（必填）：0.84

**设备（必填）：苹果6plus+小程序调试

**基础库版本（必填）：0.84

**UI问题，请附上截图**
有注意到之前有人有同样的错误,看见issue已经修复,在下载最后版本后,还是遇到同样的问题,第一次检测ok,返回页面再进入就出现如下的提示错误
![微信截图_20200712162618](https://user-images.githubusercontent.com/40686735/87242144-a3a8b780-c45c-11ea-99f4-fe27bedcfe4e.png)
![微信截图_20200712162631](https://user-images.githubusercontent.com/40686735/87242150-ab685c00-c45c-11ea-9fff-aea4eac0b7f2.png)

`var app = getApp()

Page({

  /**
   * 页面的初始数据
   */
  data: {
    pageloading:false,
    form: {
      address: '',
      zfb_account: '',
      zfb_name: '',
      name: '',
      phone: '',
    },
    zfbRules: [{
        required: true,
        message: '必须输入支付宝账号,否则没法打款给你,务必确认账号正确',
        trigger: 'blur'
      },
      // {
      //   pattern: '/^(?:1[3-9]\d{9}|[a-zA-Z\d._-]*\@[a-zA-Z\d.-]{1,10}\.[a-zA-Z\d]{1,20})$/',
      //   message: '小姐姐你的支付宝不符合要求,请检查下啊',
      //   trigger: 'blur'
      // }
    ],
    nameRules: [{
      required: true,
      message: '姓名不能为空',
      trigger: 'blur'
    }, ],
    phoneRules: [{
        required: true,
        message: '电话不能为空',
        trigger: 'blur'
      },
      {
        type: 'number',
        message: '必须是纯数字,不能带中文或者标点符号',
        trigger: 'blur',
      }
    ],
    address_detailsRules: [{
      required: true,
      message: '不能为空',
      trigger: 'blur'
    }],
    tipType: 'text',
    isSubmitValidate: 1,
    alignType: 'start'
  },

  change(e) {
    let items = this.data.items;
    items.forEach(item => {
      if (item.name == e.detail.key) {
        item.checked = e.detail.checked;
      }
    });
    this.setData({
      items: items
    });
  },

  change2(e) {
    let items = this.data.items2;
    items.forEach(item => {
      if (item.name == e.detail.key) {
        item.checked = e.detail.checked;
      }
    });
    this.setData({
      items2: items
    });
  },

  changeTipType(e) {
    this.setData({
      tipType: e.currentTarget.dataset.type
    });
    wx.lin.resetForm('ruleForm')
  },

  changeSubmitValidate(e) {
    const {
      currentKey
    } = {
      ...e.detail
    };
    this.setData({
      isSubmitValidate: currentKey
    });
  },

  changeAlignType(e) {
    this.setData({
      alignType: e.currentTarget.dataset.type
    });
  },
  getUserInfo: function (e) {
    if (e) {
      console.log(e)
      if (e.detail.errMsg == "getUserInfo:ok") {
        app.globalData.userInfo = e.detail.userInfo
        console.log('userinfo e >>>', e)
      }
    }
  },
  submit(data) {
    console.log("提交表单了")
    ///获取用户的uid,判断是否登录
    //判断是否登录了
    if (!app.globalData.userInfo || !app.globalData.openid) {
      // this.onShowPopupTap()
      this.getUserInfo()

    } else {
      // 获取微信openid,并联合发布到后台

      console.log(data.detail.values)
      if (data.detail.isValidate) {
        var projectUrl = app.globalData.bankAccount
        // var data =JSON.stringify(data.detail.values)
        this.postSocialData(projectUrl, data.detail.values)
      }else{
        wx.lin.showToast({
          title: '检查一下填写项目,有漏填或者出错的地方呢',
          icon: 'error',
          duration:'4000'
        })
      }

    }

    // console.log(JSON.stringify(data.detail))

  },
  postSocialData: function (url, postdata) {
    var that = this;
    wx.request({
      url: url + app.globalData.openid,
      method: 'POST', // OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT
      header: {
        "Content-Type": "application/json"
      },
      data: postdata,
      success: function (res) {

        if (res.data.errmsg == "ok") {
          res.data.status == 1 ? "提交成功" : "提交失败,请重新提交或联系管理员"
          // 提交成功后清空表单状态
          if (res.data.status == 1) {
            // that.setData({
            //   form: ''
            // })
            wx.lin.showToast({
              title: '创建成功~',
              icon: 'success',
              duration:'3000'
            })
          }
        } else {
          //出现问题了
          wx.lin.showToast({
            title: '提交出错,请重新提交.反复出错联系程序员小gg',
            icon: 'error',
            duration:'4000'
          })
        }
      },
      fail: function (error) {
        // fail
        console.log(error)
        wx.lin.showToast({
          title: '提交出错,请重新提交.反复出错联系程序员小gg',
          icon: 'error',
          duration:'4000'
        })
      }
    })
  },
  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function () {
    var that = this;
    that.setData({
      pageloading: true
    })
    ///从后台拉一次账号数据
    var openid = wx.getStorageSync('openid')
    var url = app.globalData.get_bankacount + openid
    this.getBank_accountData(url)
    wx.lin.initValidateForm(this)
  },
  getBank_accountData: function (url) {
    var that = this;

    wx.request({
      url: url,
      method: 'GET', // OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT
      header: {
        "Content-Type": "json"
      },
      success: function (res) {
        console.log(res.data.errmsg)
        if (res.data.errmsg == "ok") {
          that.setData({
            form: res.data.form
          })
          console.log("设置成功")
          that.setData({
            pageloading: false
          })
          wx.lin.showToast({
            title: '你已经提交过了,如不修改,无须重复提交~',
            icon: 'success',
            duration:'4000'
          })
        }
      },
      fail: function (error) {
        // fail
        console.log(error)
        that.setData({
          pageloading: false
        })
        wx.lin.showToast({
          title: '从服务器加载数据失败,重新进或联系程序员gg解决',
          icon: 'error',
          duration:'5000'
        })
      }
    })
  },
 
})`

**Comment by juzi214032** [comment]
这个问题已经修复了，但是还没有发版，会在15号之前发布一个版本进行修复

**Comment by fanyao1983** [comment]
thank you


| |
樊耀
|
|
13951762324@163.com
|
签名由网易邮箱大师定制
On 7/12/2020 16:33，桔子<notifications@github.com> wrote：

这个问题已经修复了，但是还没有发版，会在15号之前发布一个版本进行修复

**Comment by juzi214032** [comment]
issue 标注已修复但没有关闭的就是 修复代码已经合并到develop分支，但还没有发布新版本的意思
