### ISSUE TITLE
l-countdown倒计时组件切换后台会停止计时，再切换回来对组件所有的操作都无效

### ISSUE THREAD

**Issue by Lin1018** [TaleLin/lin-ui#949]
l-countdown倒计时组件切换后台，会停止计时，而且再切换回来计时器停止了，并且组件所有的操作都无效，尝试过在onShow给这个组件弄个wx:if隐藏再显示，才能再对这个组件做设置处理

**Comment by juzi214032** [comment]
请问切后台什么意思，是将小程序挂在后台运行吗

**Comment by Lin1018** [comment]
是的，开发者工具上是有个切后台菜单，真机上右上角有个小圆圈

**Comment by juzi214032** [comment]
您好，我这边使用 `小米 8 屏幕指纹板`和 Windows 平台开发工具测试均未复现这个问题，请问你那边是什么机型，方便发个录屏吗
