### ISSUE TITLE
可否考虑新增一个轮播图组件？原生的无法更改指示点样式

### ISSUE THREAD

**Issue by TXxyin** [TaleLin/lin-ui#951]
例如：扁平长方形的指示点、有大小区别的指示点

**Comment by fishwithwater** [comment]
原生的应该可以改的，之前看一个小程序ui的css库有写过
[示例wxml](https://github.com/weilanwl/ColorUI/blob/cec4e9f600efca3ab0582a92e6592302e9473308/demo/pages/component/swiper/swiper.wxml#L13)   [示例wxss](https://github.com/weilanwl/ColorUI/blob/cec4e9f600efca3ab0582a92e6592302e9473308/demo/colorui/main.wxss#L2548)

**Comment by juzi214032** [comment]
@fishwithwater  感谢提供解决方案

**Comment by TXxyin** [comment]
@fishwithwater 非常感谢！已成功修改！
