### ISSUE TITLE
[Bug Report]Tabs非等宽标签，底部会多出一条横线

### ISSUE THREAD

**Issue by ApmI00** [TaleLin/lin-ui#952]
**LinUI版本（必填）：0.8.2

**设备（必填）：Android手机，红米Note 3，一加6，红米k30

**基础库版本（必填）：2.11.1

![image](https://user-images.githubusercontent.com/7700710/87381095-82fc7100-c5c6-11ea-8ef3-f5a10fcbfe06.png)

**Comment by ApmI00** [comment]
查了一下，是scrollable之后，scroll-view的滚动条，目前使用外部控制，可以去除。不过，在iphone和模拟器上，这个bug没有。
::-webkit-scrollbar {
    width: 0;
    height: 0;
    color: transparent;
    display: none;
}

**Comment by juzi214032** [comment]
这是微信小程序实现的问题，下个版本我们会在组件内部隐藏这个滚动条

**Comment by juzi214032** [comment]
我测试了一下，这个不能从组件内部隐藏。从组件内部隐藏了会导致整个小程序都不显示滚动条。
如果需要隐藏该滚动条，建议用户自行在页面中隐藏

**Comment by ApmI00** [comment]
主要是iOS和模拟器并不会显示这个滚动条，而到了Android真机上，居然就有了。

**Comment by juzi214032** [comment]
对的，微信小程序在iso和android中是有一定差异的
