### ISSUE TITLE
按照文档使用wx.lin，报错提示函数找不到

### ISSUE THREAD

**Issue by mybichu** [TaleLin/lin-ui#961]
**LinUI版本（必填）：**
085
**设备（必填）：**
微信开发者工具模拟器
**基础库版本（必填）：**
2.8.1
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/20676047/87856771-d61e4d00-c953-11ea-9cf6-0cb43919334c.png)

**重现步骤，必要时请提供代码片段链接**

按照文档上在wxml中：
```
<l-water-flow` generic:l-water-flow-item="moment" />
```
在json文件中：
```
"l-water-folw" : "/lin-ui/water-flow/index"
```

,

但是调用渲染API `wx.lin.renderWaterFlow(moment)`的时候，提示该方法not found了。

**Comment by juzi214032** [comment]
您好，我这边没有复现这个问题，请检查一下项目中的lin-ui源码是否完整，尝试重新复制下。如还是无法解决，请提供一个代码片段

**Comment by mybichu** [comment]
> 您好，我这边没有复现这个问题，请检查一下项目中的lin-ui源码是否完整，尝试重新复制下。如还是无法解决，请提供一个代码片段

项目中的lin-ui就是复制的项目中dist目录下的组件。
项目结构如下：
![image](https://user-images.githubusercontent.com/20676047/87857340-9c037a00-c958-11ea-866b-cde84afc5173.png)
其中
index.js：
```
import { moment } from "./data";
//index.js
const app = getApp()

Page({
  onLoad: function() {
    wx.lin.renderWaterFlow(moment);
    ...
  },

})
```

index.wxml:
```
<!-- 瀑布流feeds -->
<l-water-flow generic:l-water-flow-item="moment" />
```

**Comment by mybichu** [comment]
嗯嗯，是我这边的失误，搞错了一个路径，谢谢解答！

**Comment by oliwang** [comment]
> 嗯嗯，是我这边的失误，搞错了一个路径，谢谢解答！

@mybichu 
你好，我想问一下你是怎么解决的呢？我也遇到了一样的问题，但是我看了一下路径好像没写错呀。

<img width="1092" alt="Screen Shot 2020-09-07 at 11 15 13 PM" src="https://user-images.githubusercontent.com/5282363/92401438-38c7e400-f160-11ea-9de0-dd2bafc5fb26.png">

我就是按照这个repo example里的water-flow写的

**Comment by oliwang** [comment]
我研究了一下发现好像是因为还没加载好，先sleep了一下就可以加载了。这样正常吗？

**Comment by mybichu** [comment]
> 我研究了一下发现好像是因为还没加载好，先sleep了一下就可以加载了。这样正常吗？

我当时好像是因为json文件里面的，引入waterFlow的时候，绝对路径和相对路径的问题，你可以试一下修改那个路径。
至于加载这个，我也没有遇到，可以艾特一下开发者。

**Comment by oliwang** [comment]
好像是用了wx:if的问题，开成visible就可以了
