### ISSUE TITLE
相册组件是否可以指定一行显示多少张图

### ISSUE THREAD

**Issue by qq940993208** [TaleLin/lin-ui#962]
**描述你希望的支持的新功能？**
相册组件是否可以指定一行显示多少张图
**你期望的 API 是怎样的？**
相册组件默认在5-6张图的时候是两行三列
但是在部分场景下
不论多少张图 都只需要两列来展示
当然最好是可以每一行指定显示多少列~
^_^~

**Comment by juzi214032** [comment]
感谢建议，我们评估之后回复您

**Comment by zhc525349965** [comment]
感谢反馈，我们正在讨论该组件的重构，会充分考虑您的建议。

**Comment by zhc525349965** [comment]
0.8.7已经支持，具体使用方式请查看官网文档。
[https://doc.mini.talelin.com/component/layout/album.html](url)
