### ISSUE TITLE
Tabs 能否在标签栏 添加 (显示/隐藏)固定 按钮/图标

### ISSUE THREAD

**Issue by zhyphil** [TaleLin/lin-ui#964]
**描述你希望的支持的新功能？**
Tabs 的标签栏 最右边 提供一个 固定的按钮位置,或者是 图标, 左部分标签栏可以滑动,但是不移动 最右边这个 按钮/图标, 用以添加新标签页/ 其他业务
**你期望的 API 是怎样的？**
提供参数设置, action-btn/action-icon之类的,设置的时候显示此 按钮/图标, 点击后呼叫设置的方法

谢谢

**Comment by juzi214032** [comment]
可以提供一个图片吗

**Comment by zhyphil** [comment]
> 可以提供一个图片吗

https://6f72-orders-w9orx-1302086253.tcb.qcloud.la/Screenshot%202020-07-20%20at%204.53.37%20PM.png?sign=daf83a7ad9dd87d308622abdfcb3c8d2&t=1595257015

这个链接能打开吗?

**Comment by zhyphil** [comment]
或者这个google drive 的链接
https://drive.google.com/file/d/1E8mENSaJia5nMTT7zwYXcGzwSus401jv/view?usp=sharing

**Comment by juzi214032** [comment]
好的，感谢反馈，我们评估后回复您

**Comment by juzi214032** [comment]
您好，经过我们的评估，我们认为这个需求在移动端是否场景较少，所以决定暂不支持，非常抱歉

**Comment by zhyphil** [comment]
好,谢谢告知
