### ISSUE TITLE
签名组件

### ISSUE THREAD

**Issue by qq940993208** [TaleLin/lin-ui#966]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**
办理电信业务的时候
客户能在画板上签名
最后生成一张图
效果图如下链接

[https://ttfou.com/images/2020/07/21/6b6c5fec3a96a439414c1ddbe3a350e5.png](url)

**Comment by juzi214032** [comment]
感谢反馈，我们评估后回复您

**Comment by juzi214032** [comment]
您好，经过我们团队的评估，因为这个组件的使用场景太少，所以暂不决定支持，非常抱歉
