### ISSUE TITLE
l-list 组件icon的右边距样式不起作用

### ISSUE THREAD

**Issue by christan-duplicate** [TaleLin/lin-ui#968]
**LinUI版本（必填）：**
v0.8.5

**设备（必填）：**
微信pc，微信开发者工具

**基础库版本（必填）：**

**UI问题，请附上截图**
l-list 组件icon的右边距样式不起作用
![image](https://user-images.githubusercontent.com/769138/88142249-c179d780-cc27-11ea-828f-1527a6d44430.png)
![image](https://user-images.githubusercontent.com/769138/88142352-f128df80-cc27-11ea-8746-5fa3b932f1d2.png)
![image](https://user-images.githubusercontent.com/769138/88142462-1cabca00-cc28-11ea-8a91-2c43444ee57a.png)

**重现步骤，必要时请提供代码片段链接**

**Comment by christan-duplicate** [comment]
![image](https://user-images.githubusercontent.com/769138/88142910-e458bb80-cc28-11ea-98b7-69e2ee098c31.png)

**Comment by MuRongXiaoDouBi** [comment]
`list` 组件有提供对 `icon` 样式修改的外部样式类 `l-icon-class` ，请使用此外部样式类修改样式

**Comment by MuRongXiaoDouBi** [comment]
外部样式类属性一定要加 `!important` ，不然样式权重没有组件内部高

**Comment by christan-duplicate** [comment]
![image](https://user-images.githubusercontent.com/769138/88146079-fa1caf80-cc2d-11ea-9f24-f462f7069b6a.png)
这后面的空格，也会导致样式无效，删除后面的空格就好了

**Comment by christan-duplicate** [comment]
> `list` 组件有提供对 `icon` 样式修改的外部样式类 `l-icon-class` ，请使用此外部样式类修改样式

我面边距样式的截图是你个list组件自带的样式，不是我写的

**Comment by MuRongXiaoDouBi** [comment]
已定位问题，正在修复

**Comment by MuRongXiaoDouBi** [comment]
> ![image](https://user-images.githubusercontent.com/769138/88146079-fa1caf80-cc2d-11ea-9f24-f462f7069b6a.png)
> 这后面的空格，也会导致样式无效，删除后面的空格就好了

这个是您自己的外部样式类输入多出的空格吗

**Comment by MuRongXiaoDouBi** [comment]
> > ![image](https://user-images.githubusercontent.com/769138/88146079-fa1caf80-cc2d-11ea-9f24-f462f7069b6a.png)
> > 这后面的空格，也会导致样式无效，删除后面的空格就好了
> 
> 这个是您自己的外部样式类输入多出的空格吗

我这里查看并没有空格 
<img width="419" alt="WX20200722-154554@2x" src="https://user-images.githubusercontent.com/38655613/88149295-74e7c980-cc32-11ea-97c1-a8c0718a4c55.png">

**Comment by christan-duplicate** [comment]
> > > ![image](https://user-images.githubusercontent.com/769138/88146079-fa1caf80-cc2d-11ea-9f24-f462f7069b6a.png)
> > > 这后面的空格，也会导致样式无效，删除后面的空格就好了
> > 
> > 
> > 这个是您自己的外部样式类输入多出的空格吗
> 
> 我这里查看并没有空格
> <img alt="WX20200722-154554@2x" width="419" src="https://user-images.githubusercontent.com/38655613/88149295-74e7c980-cc32-11ea-97c1-a8c0718a4c55.png">

是你们的组件生成的，
![image](https://user-images.githubusercontent.com/769138/88153827-8502a780-cc38-11ea-8aff-889fee7b1126.png)
比如引用时不传这两个属性，就会有两个空格在后面

**Comment by MuRongXiaoDouBi** [comment]
> > > > ![image](https://user-images.githubusercontent.com/769138/88146079-fa1caf80-cc2d-11ea-9f24-f462f7069b6a.png)
> > > > 这后面的空格，也会导致样式无效，删除后面的空格就好了
> > > 
> > > 
> > > 这个是您自己的外部样式类输入多出的空格吗
> > 
> > 
> > 我这里查看并没有空格
> > <img alt="WX20200722-154554@2x" width="419" src="https://user-images.githubusercontent.com/38655613/88149295-74e7c980-cc32-11ea-97c1-a8c0718a4c55.png">
> 
> 是你们的组件生成的，
> ![image](https://user-images.githubusercontent.com/769138/88153827-8502a780-cc38-11ea-8aff-889fee7b1126.png)
> 比如引用时不传这两个属性，就会有两个空格在后面

测试并未发现空格现象，可否提供一下复现代码

**Comment by christan-duplicate** [comment]
我用的工具是微信开发者日常构建版1.04.2007212

**Comment by MuRongXiaoDouBi** [comment]
> 我用的工具是微信开发者日常构建版1.04.2007212

基础库是哪个版本呢

**Comment by christan-duplicate** [comment]
基础库是什么啊

**Comment by MuRongXiaoDouBi** [comment]
> 基础库是什么啊

<img width="394" alt="WX20200722-200921@2x" src="https://user-images.githubusercontent.com/38655613/88174680-429c9300-cc57-11ea-8b3f-317838f25f4b.png">

**Comment by christan-duplicate** [comment]
基础库：2.12.0

**Comment by MuRongXiaoDouBi** [comment]
> 基础库：2.12.0

测试发现空格不会导致样式类失效，可能是那个样式类本来就没有属性

**Comment by christan-duplicate** [comment]
好的，多谢啦
