### ISSUE TITLE
我有一个关于配置整合方面的问题需要咨询各位老师

### ISSUE THREAD

**Issue by tclcm1987** [TaleLin/lin-ui#971]
我在想如果我们在定义多个小程序自定义component中同时用到了lin-ui的基础组件如l-button和l-list，这样为了避免基础组件的重复引入，是不是应该在app.json中把我们需要用到的如l-button和l-list一次性全部引入了，这样就一劳永逸了？这样做是不是更合理？

**Comment by dpp050700** [comment]
对的
