### ISSUE TITLE
l-countdown样式不起作用bug

### ISSUE THREAD

**Issue by christan-duplicate** [TaleLin/lin-ui#972]
**LinUI版本（必填）：**
v0.8.5
**设备（必填）：**
微信pc，微信开发者工具
**基础库版本（必填）：**
2.12.0
**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/769138/88369025-bbb7f980-cdc1-11ea-9677-f63c7032ee96.png)
![image](https://user-images.githubusercontent.com/769138/88369187-12253800-cdc2-11ea-8bd8-89ad49421249.png)

**重现步骤，必要时请提供代码片段链接**
指定 l-time-class 样式一样不能够覆盖掉 l-countdown-time 中的样式，因为这里面的顺序有问题，像默认样式 l-countdown-time 应该放在第一位，而不是最后。

**Comment by juzi214032** [comment]
class 中的样式声明顺序不影响实际显示效果，请在外部样式类中使用`!important`提升样式优先级

**Comment by christan-duplicate** [comment]
![image](https://user-images.githubusercontent.com/769138/88369821-6bda3200-cdc3-11ea-8d0b-0c213995ba4c.png)

**Comment by juzi214032** [comment]
请贴一下您的 wxss 代码

**Comment by christan-duplicate** [comment]
<l-countdown wx:else l-class="countdown-con" l-time-class="countdown-text" time-type="second" time="{{ countdownTime }}"  format="{%s}秒" status="{{ countdownStatus }}" bind:linend="countdownEnd"/>

.wrapper .countdown-con {
    font-size: 24rpx;
    color: #C0C0C0;
}

.wrapper .countdown-con .countdown-text {
    width: 10rpx !important;
    background: transparent;
    color: #C0C0C0;
}

**Comment by christan-duplicate** [comment]
看我的截图，如果能起作用的话，60 秒 中间是不会再有空隙的。

**Comment by juzi214032** [comment]
我看您的css中使用了后代选择器，但是您给的html没有显示出具有此后代关系

**Comment by juzi214032** [comment]
请尝试单独定义：
```css
.countdown-text {
    width: 10rpx !important;
    background: transparent;
    color: #C0C0C0;
}
```

**Comment by christan-duplicate** [comment]
我贴出的代码省了父级节点了，其实是有的，我也试过你这样的，一样覆盖不了!

**Comment by christan-duplicate** [comment]
去掉前面的后，连背景都去不掉了。

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/88371661-0f791180-cdc7-11ea-8b4e-8063b7651fc6.png)
![image](https://user-images.githubusercontent.com/38206169/88371673-130c9880-cdc7-11ea-9a11-55df950fa906.png)
我这边测试了，并无您说的问题，请您先检查下您的业务代码，如仍有问题，可以提交一个代码片段供我们排查

**Comment by christan-duplicate** [comment]
找到问题了，其实是起作用的，只是微信开发者调试器显示有问题，谢谢啦。

**Comment by juzi214032** [comment]
不客气
