### ISSUE TITLE
Segment 能否传输自定义的值

### ISSUE THREAD

**Issue by zhyphil** [TaleLin/lin-ui#973]
**描述你希望的支持的新功能？**

现在在bind:linchange里面只能拿到{activeKey:当前激活选项卡的key,currentIndex:当前激活选项卡的索引} 两个值,能不能添加任意入口用以设置自定义值,比如我现在想要 给一个 id,方便做搜索, 在l-segment里面加入 data-id="{{id}}" 是不能获取到这个id 值的.

**你期望的 API 是怎样的？**
给segement添加任意自定义值的入口,或者 直接可以 拿到  data-*="{{value}}" 的设置, 在event.currentTarget.dataset.*中获取

谢谢

**Comment by juzi214032** [comment]
感谢反馈，我们会增加此特性的支持

**Comment by juzi214032** [comment]
您好，请问一下您的这个需求用现有的 currentIndex无法实现吗，你在页面维护一个数组，通过这个 currentIndex 索引从数组中取值

**Comment by zhyphil** [comment]
你好,我现在是通过key传递的id值,但是如果要传其他值的话,感觉这个写法语义上不搭配.

https://doc.mini.talelin.com/component/nav/segment.html

在doc里面没有看到哪一个属性对应传参给currentIndex

也许技术上这样是可以传递参数,但是感觉也只能是临时的吧.

**Comment by juzi214032** [comment]
目前已增加data-cell传值方式，将在下一个版本更新

**Comment by zhyphil** [comment]
好的!谢谢
