### ISSUE TITLE
表单验证页  第一次没有问题 返回首页第二次再跳转到表单页面 输入内容 就会报错  不知道什么原因

### ISSUE THREAD

**Issue by eaglemens** [TaleLin/lin-ui#975]
*
![image](https://user-images.githubusercontent.com/19241562/88766501-b6382600-d1aa-11ea-80ca-d8e7ba4b50c8.png)

代码片段：https://developers.weixin.qq.com/s/yLz96cml7lj6

**Comment by juzi214032** [comment]
请更新最新版
