### ISSUE TITLE
l-list组件icon大小设置无效，外部样式类也无法覆盖

### ISSUE THREAD

**Issue by laichengs** [TaleLin/lin-ui#977]
**LinUI版本（必填）：*0.8.4*

**设备（必填）：*微信开发者工具*

**基础库版本（必填）：*2.12.0*

**UI问题，请附上截图*
![image](https://user-images.githubusercontent.com/32843416/88783030-e2f73800-d1c0-11ea-9036-66e961e59472.png)
*

**重现步骤，必要时请提供代码片段链接*
查阅源码发现，l-list组件的index.wxml里，对l-icon组件没有设置上对应的值，由于是内联样式，所以外部样式类就算加入了important也无法覆盖。
解决办法：在l-list的index.wxml里的l-icon组件上加上 size="{{iconSize}}"即可
*

**Comment by juzi214032** [comment]
感谢反馈，当前 iconSize 设计的是设置列表左侧icon的大小，右侧箭头暂时无法设置大小

**Comment by laichengs** [comment]
默认的大小是40rpx，相对其它icon的组件来讲有些大了，就算无法调整，都用28rpx不更好吗？

**Comment by juzi214032** [comment]
请问您说的是list右侧的箭头吗，这个箭头默认给的是26rpx，不知您看的40rpx是指的哪里
![image](https://user-images.githubusercontent.com/38206169/88868393-a5d38a00-d242-11ea-959c-233b118b2129.png)

**Comment by laichengs** [comment]
不好意思，这个是我之前去掉了l-icon组件的默认size，导致组件的l-icon样式生效了所以变为了40rpx，但是这个list的右边默认箭头大小还是被l-icon组件的size默认值28rpx所覆盖，因为是内联样式，所以你们自定义的26rpx的样式同样也没有生效，算是一个小小的问题吧，浪费你们时间了抱歉
![image](https://user-images.githubusercontent.com/32843416/88870083-082e8980-d247-11ea-8645-d2162d429e7a.png)

**Comment by juzi214032** [comment]
size未生效这个问题已在0.8.5版本中修复，建议您更新至0.8.5版本尝试

**Comment by juzi214032** [comment]
下个版本将会为 List 组件 添加 `l-link-icon-class` 外部样式类用于修改右侧箭头图标的样式
