### ISSUE TITLE
同一页面多个l-popul存在时，popul关闭时会出现闪屏现象

### ISSUE THREAD

**Issue by laichengs** [TaleLin/lin-ui#978]
**LinUI版本（必填）：*0.8.5*

**设备（必填）：*iphoneX*

**基础库版本（必填）：*2.12.0*

**UI问题，请附上截图*同一页面多个l-popul存在时，关闭时会出现闪屏现象，附视频[地址](https://minicdn.meijinguanjia.com/sample.mp4)*

**重现步骤，必要时请提供代码片段链接**

**现象：**同一页面正常引用三个l-popul组件，通过事件设置开关属性，短时间频繁点击时即出现上述问题。
**解决办法：**定位lin-ui源码src/popul/index.js 版本库0.8.5, 115行代码处有300毫秒定时器，调整为10或者更小数值即可解决此问题，此问题虽不易复现，但在企业级开发中还是会影响到用户体验，其它低端机器暂无法测试。

**Comment by juzi214032** [comment]
可以麻烦您提供一个代码片段吗

**Comment by juzi214032** [comment]
感谢反馈，问题已复现，不用提供代码片段了

**Comment by juzi214032** [comment]
该问题已解决，将在下个版本修复

**Comment by juzi214032** [comment]
感谢您提供的解决方案，但 setTimeout 时间不是这个问题的根源，我这边是在 css animation 属性中添加了 forwards，如果感兴趣的话您可以看一下源码
