### ISSUE TITLE
l-button的size设置为long时，loading状态下icon与字体之间无间距

### ISSUE THREAD

**Issue by laichengs** [TaleLin/lin-ui#980]
**LinUI版本（必填）：*0.8.5*

**设备（必填）：*微信开发者工具*

**基础库版本（必填）：*2.12.0*

**UI问题，请附上截图**
![image](https://user-images.githubusercontent.com/32843416/88870608-5ee89300-d248-11ea-83cb-8a6f3c5b9e4e.png)

**重现步骤，必要时请提供代码片段链接**
`						<l-button type="error"  width="200" height="80" loading="{{true}}" bind>今日订单</l-button>
						<l-button type="warning" width="200" height="80" size="long" loading="{{true}}" >我要选单</l-button>`

**Comment by juzi214032** [comment]
感谢反馈，问题已复现，正在修复中

**Comment by juzi214032** [comment]
您好，该问题已修复，目前已为 size 为 long 的按钮图标添加了默认 24rpx 的右边距
将在下个版本更新
