### ISSUE TITLE
list组件通过NPM安装和源码dist目录拷贝引入后两者样式表现不一致

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-ui#988]
**LinUI版本（必填）：**
0.8.5

**设备（必填）：**
开发者工具

**基础库版本（必填）：**
2.12.0
**UI问题，请附上截图**
list组件配置icon属性，通过npm安装的lin-ui，icon和title会有间距，通过克隆源码后拷贝dist目录的方式，icon和title不会有间距

* NPM方式：
![image](https://user-images.githubusercontent.com/49727104/88909420-a80f0600-d28d-11ea-8538-442ba533804c.png)

* 拷贝dist目录方式：
![image](https://user-images.githubusercontent.com/49727104/88909510-caa11f00-d28d-11ea-9719-73d971494a82.png)

拷贝dist目录的方式，icon缺少一个样式：

![image](https://user-images.githubusercontent.com/49727104/88909726-0f2cba80-d28e-11ea-92ff-e5846d04d251.png)

**重现步骤，必要时请提供代码片段链接**

通过npm安装linui和通过克隆源码dist目录，使用list组件并配置icon属性：

wxml代码片段：
```html
<view style="width:100%">
  <l-list icon="share" title="分享"></l-list>
</view>
```

**Comment by dpp050700** [comment]
收到反馈，我们先核对下该问题

**Comment by juzi214032** [comment]
请问你copy的是哪个分支的dist npm安装是和master分支保持一致的

**Comment by ChenJinchuang** [comment]
> 请问你copy的是哪个分支的dist npm安装是和master分支保持一致的

master分支。 wxml处的代码不变，我通过调整引入组件的路径（npm构建目录和dist）目录即可复现问题，可以尝试下。

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/88915074-37b8b280-d296-11ea-8a40-fb5d7bfc8379.png)
我看了仓库master分支，list是存在该样式的
