### ISSUE TITLE
list 组件lintap事件 点击list中的标签时，事件会触发两次。官方demo也有此问题

### ISSUE THREAD

**Issue by juzihai** [TaleLin/lin-ui#989]
**LinUI版本（必填）：**0.8.5

**设备（必填）：**安卓

**基础库版本（必填）：**2.10.3

**UI问题，请附上截图**

**重现步骤，必要时请提供代码片段链接**
** wxml**
<l-list title="购物车" icon="cart" tag-content="购物车" bind:lintap="clickListItem" data-key="cart" />

** js **
  clickListItem(e){
    console.log("点击了",e.currentTarget.dataset.key)
  },

**Comment by juzi214032** [comment]
感谢反馈，这是一个已知bug，我们会尽快修复，您暂时可以通过`event.detail`的不同对两次事件做一下区分
给您带来的不便非常抱歉

**Comment by juzi214032** [comment]
关联 issue #687

**Comment by juzi214032** [comment]
该问题已解决，将在下个版本更新

**Comment by juzi214032** [comment]
0.8.7 版本已解决该问题
