### ISSUE TITLE
price 组件无法显示价格

### ISSUE THREAD

**Issue by kmyhy** [TaleLin/lin-ui#991]
使用文档中的示例代码，无论那一段都无法显示价格数，只能显示货币符号。

所用版本 0.6.4，操作系统版本：Mac 10.5.1  微信开发者工具版本 1.03.2007151

**Comment by juzi214032** [comment]
请升级最新版本`0.8.6`尝试一下

**Comment by kmyhy** [comment]
0.8.6 的问题更大，整个页面都无法显示。

**Comment by kmyhy** [comment]
Uncaught TypeError: wx.getMenuButtonBoundingClientRect is not a function
    at DeviceUtil.getTitleBarHeight (device-util.js? [sm]:1)
    at index.js? [sm]:1
    at require (VM722 WAService.js:19)
    at <anonymous>:209:7
    at doWhenAllScriptLoaded (appservice?t=1596285355330:5558)
    at appservice?t=1596285355330:4994
    at HTMLScriptElement.t.onload (<anonymous>:1:21960)

Page is not constructed because it is not found.

**Comment by juzi214032** [comment]
请把基础库版本调至最新

**Comment by kmyhy** [comment]
将小程序的“调试基础库”更新至2.12.0，问题解决
