### ISSUE TITLE
数量选择器组件，是否可以支持键盘输入事件？

### ISSUE THREAD

**Issue by 0feng0** [TaleLin/lin-ui#992]
**描述你希望的支持的新功能？**
希望数量选择器组件可以支持键盘输入事件，这样可以方便获取数量，对是否超出限值，更好做出其他操作
**你期望的 API 是怎样的？**

**Comment by juzi214032** [comment]
已新增 linchange 事件，在值改变时触发
该特性将在下个版本更新
