### ISSUE TITLE
input可以设置disabled时的样式吗

### ISSUE THREAD

**Issue by yumendexihai** [TaleLin/lin-ui#995]
**描述你希望的支持的新功能？**
radio有l-disabled-class,但input没有。。

**Comment by juzi214032** [comment]
因为 input 组件的 disable 是基于小程序原生 input 实现。
请尝试使用外部样式类`l-input-class`修改`disabled`样式
```css
l-input-class[disabled]{
    ...
}
```

**Comment by yumendexihai** [comment]
谢谢解答
